SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE FUNCTION [dbo].[LOAN_FN_GET_COLLATERAL_LOANS](@collateral_id int, @just_linked bit)
RETURNS TABLE 
AS
RETURN 
(
	SELECT L.* FROM dbo.LOAN_COLLATERALS C
	INNER JOIN dbo.LOAN_VW_LOANS L ON C.LOAN_ID = L.LOAN_ID
	WHERE C.COLLATERAL_ID = @collateral_id AND @just_linked = 0

	UNION

	SELECT L.* FROM LOAN_COLLATERALS_LINK lnk
	INNER JOIN dbo.LOAN_VW_LOANS L ON lnk.LOAN_ID = L.LOAN_ID
	WHERE lnk.COLLATERAL_ID = @collateral_id
)
GO
