SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[bank_open_date] ()
RETURNS smalldatetime AS
BEGIN
  RETURN (SELECT VALS FROM dbo.INI_DT (NOLOCK) WHERE IDS = 'OPEN_BANK_DATE')
END
GO
