SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[acc_get_bal_acc] (@acc_id int)  
RETURNS TBAL_ACC AS  
BEGIN 
  RETURN (SELECT BAL_ACC_ALT FROM dbo.ACCOUNTS (NOLOCK) WHERE ACC_ID = @acc_id)
END
GO
