SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[depo_fn_get_executed_ops](@start_date smalldatetime, 
	@end_date smalldatetime = NULL, @eng_version bit = 0, @op_types varchar(255) = NULL)
RETURNS
	@depo_data TABLE (
	DEPO_ID int NOT NULL,
	OP_ID int NULL,
	BRANCH_ID int NULL,
	DEPT_NO int NULL,
	[STATE] tinyint NULL,
	PROD_CODE varchar(15) NULL,
	CLIENT_DESCRIP varchar(100) NULL,
	AGREEMENT_NO varchar(100) NULL,
	DEPO_ISO TISO NULL,
	DEPO_AMOUNT money NULL,
	[START_DATE] smalldatetime NULL,
	END_DATE smalldatetime NULL,
	OP_DATE smalldatetime NULL,
	OP_TYPE smallint NULL,
	OP_DESCRIP varchar(150) NULL, 
	OP_ISO CHAR(3) NULL,
	OP_AMOUNT money NULL, 
	OP_DOC_REC_ID int NULL,
	EXECUTED bit NULL, 
	OWNER_U_NAME varchar(20) NULL, 
	AUTH_OWNER_U_NAME varchar(20) NULL)

AS
BEGIN
	IF @end_date IS NULL	
		SET @end_date = dbo.get_max_smalldatetime()	

	INSERT INTO @depo_data (DEPO_ID, OP_ID, BRANCH_ID, DEPT_NO, [STATE], PROD_CODE, CLIENT_DESCRIP, AGREEMENT_NO, 
					DEPO_ISO, DEPO_AMOUNT, [START_DATE],  END_DATE, OP_DATE, OP_TYPE, OP_DESCRIP, OP_ISO, 
					OP_AMOUNT, OP_DOC_REC_ID, EXECUTED, OWNER_U_NAME, AUTH_OWNER_U_NAME )
	(SELECT D.DEPO_ID, NULL AS OP_ID, D.BRANCH_ID, D.DEPT_NO, D.STATE, D.PROD_CODE, D.CLIENT_DESCRIP, D.AGREEMENT_NO,
			D.ISO AS DEPO_ISO, D.AMOUNT AS DEPO_AMOUNT, D.START_DATE, D.END_DATE, NULL AS OP_DATE, NULL AS OP_TYPE, NULL AS OP_DESCRIP, NULL AS OP_ISO,
			NULL AS OP_AMOUNT, NULL AS OP_DOC_REC_ID, NULL AS EXECUTED, NULL AS OWNER_U_NAME, NULL AS AUTH_OWNER_U_NAME
		FROM dbo.DEPO_VW_DEPO_LIST D (NOLOCK)
		INNER JOIN dbo.DEPO_OP O (NOLOCK) ON D.DEPO_ID = O.DEPO_ID
		INNER JOIN dbo.DEPO_OP_TYPES T (NOLOCK) ON O.OP_TYPE = T.TYPE_ID
	WHERE
		((ISNULL(@op_types, '')='') OR (EXISTS (SELECT * FROM dbo.fn_split_list_int(@op_types, default) WHERE ID = O.OP_TYPE))) AND 
		((@start_date is NULL) OR (O.OP_DATE >= @start_date)) AND ((@end_date is NULL) OR (O.OP_DATE <= @end_date))

	UNION 

	SELECT D.DEPO_ID, O.OP_ID, NULL AS BRANCH_ID, NULL AS DEPT_NO, NULL AS [STATE], NULL AS PROD_CODE, NULL AS CLIENT_DESCRIP, NULL AS AGREEMENT_NO, 
			NULL AS DEPO_ISO, D.AMOUNT AS DEPO_AMOUNT, NULL AS [START_DATE], NULL AS END_DATE,
			O.OP_DATE, O.OP_TYPE,
			CASE WHEN @eng_version = 0 THEN T.DESCRIP ELSE T.DESCRIP_LAT END AS OP_DESCRIP,
			D.ISO AS OP_ISO, O.AMOUNT AS OP_AMOUNT, O.DOC_REC_ID AS OP_DOC_REC_ID,
			O.OP_STATE AS EXECUTED, 
			RTRIM(U.USER_NAME) + '@' + DP_U.ALIAS AS OWNER_U_NAME,
			CASE WHEN US.USER_NAME IS NULL THEN US.USER_NAME ELSE RTRIM(US.USER_NAME) + '@' + DP_US.ALIAS END AS AUTH_OWNER_U_NAME
		FROM dbo.DEPO_VW_DEPO_LIST D (NOLOCK)
		INNER JOIN dbo.DEPO_OP O (NOLOCK) ON D.DEPO_ID = O.DEPO_ID
		INNER JOIN dbo.DEPO_OP_TYPES T (NOLOCK) ON O.OP_TYPE = T.TYPE_ID
		INNER JOIN dbo.USERS U (NOLOCK) ON O.OWNER = U.USER_ID
		INNER JOIN dbo.DEPTS DP_U (NOLOCK) ON DP_U.DEPT_NO = U.DEPT_NO
		LEFT JOIN dbo.USERS US (NOLOCK) ON O.AUTH_OWNER = US.USER_ID
		LEFT JOIN dbo.DEPTS DP_US (NOLOCK) ON DP_US.DEPT_NO = US.DEPT_NO

	WHERE
		((ISNULL(@op_types, '')='') OR (EXISTS (SELECT * FROM dbo.fn_split_list_int(@op_types, default) WHERE ID=O.OP_TYPE))) AND 
		((@start_date is NULL) OR (O.OP_DATE >= @start_date)) AND ((@end_date is NULL) OR (O.OP_DATE <= @end_date)) 
	)  ORDER BY D.DEPO_ID, OP_ID

RETURN
END
GO
