SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[show_depo_rights2]
 (@group_id int) 
RETURNS TABLE
AS 
	RETURN
	SELECT AST.SET_ID, ASS.DESCRIP AS SET_NAME, AST.RIGHT_NAME, CONVERT(bit, 1) AS HAS_RIGHT
	FROM dbo.DEPO_SET_RIGHTS2 AST (NOLOCK)
		INNER JOIN dbo.DEPO_SETS2 ASS (NOLOCK) ON ASS.SET_ID = AST.SET_ID
	WHERE AST.GROUP_ID = @group_id

	UNION ALL

	SELECT ASS.SET_ID, ASS.DESCRIP AS SET_NAME, ASRN.RIGHT_NAME, CONVERT(bit, 0) AS HAS_RIGHT
	FROM dbo.DEPO_SETS2 ASS (NOLOCK)
		CROSS JOIN dbo.DEPO_SET_RIGHT_NAMES2 ASRN (NOLOCK)
	WHERE NOT EXISTS(SELECT * FROM dbo.DEPO_SET_RIGHTS2 A2 (NOLOCK) WHERE A2.GROUP_ID = @group_id AND A2.SET_ID = ASS.SET_ID AND A2.RIGHT_NAME = ASRN.RIGHT_NAME)
GO
