SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[depo_get_depo_full_data]
(
	@depo_id int, 
	@op_id int = NULL
)
RETURNS 
@depo_data TABLE 
(
	[OP_ID] int NULL,
	[DEPO_ID] int NOT NULL,
	[ROW_VERSION] [int] NOT NULL,
	[BRANCH_ID] [int] NOT NULL,
	[DEPT_NO] [int] NOT NULL,
	[STATE] [tinyint] NOT NULL,
	[ALARM_STATE] [tinyint] NOT NULL ,
	[CLIENT_NO] [int] NOT NULL,
	[TRUST_DEPOSIT] [bit] NULL,
	[TRUST_CLIENT_NO] [int] NULL,
	[TRUST_EXTRA_INFO] [varchar](255) NULL,
	[PROD_ID] [int] NOT NULL,
	[AGREEMENT_NO] [varchar](100) NOT NULL,
	[DEPO_TYPE] [tinyint] NOT NULL,
	[DEPO_ACC_SUBTYPE] [int] NOT NULL,
	[DEPO_ACCOUNT_STATE] [tinyint] NOT NULL,
	[ISO] [dbo].[TISO] NOT NULL,
	[AGREEMENT_AMOUNT] [money] NULL,
	[AMOUNT] [money] NOT NULL,
	[DATE_TYPE] [tinyint] NOT NULL,
	[PERIOD] [int] NULL,
	[START_DATE] [smalldatetime] NOT NULL,
	[END_DATE] [smalldatetime] NULL,
	[ANNULMENT_DATE] [smalldatetime] NULL,
	[INTRATE] [money] NOT NULL,
	[REAL_INTRATE] [dbo].[TRATE] NOT NULL,
	[PERC_FLAGS] [int] NOT NULL,
	[DAYS_IN_YEAR] [smallint] NOT NULL,
	[PROD_ACCRUE_MIN] [money] NULL,
	[PROD_ACCRUE_MAX] [money] NULL,
	[PROD_SPEND_MIN] [money] NULL,
	[PROD_SPEND_MAX] [money] NULL,
	[FORMULA] [varchar](255) NOT NULL,
	[INTRATE_SCHEMA] [int] NOT NULL,
	[ACCRUE_TYPE] [tinyint] NOT NULL,
	[RECALCULATE_TYPE] [tinyint] NOT NULL,
	[REALIZE_SCHEMA] [int] NOT NULL,
	[REALIZE_TYPE] [tinyint] NOT NULL,
	[REALIZE_COUNT] [smallint] NULL,
	[REALIZE_COUNT_TYPE] [tinyint] NULL,
	[DEPO_REALIZE_SCHEMA] [tinyint] NOT NULL,
	[DEPO_REALIZE_SCHEMA_AMOUNT] [money] NULL,
	[CONVERTIBLE] [bit] NOT NULL,
	[PROLONGABLE] [bit] NOT NULL,
	[PROLONGATION_COUNT] [int] NULL,
	[RENEWABLE] [bit] NOT NULL,
	[RENEW_CAPITALIZED] [bit] NOT NULL,
	[RENEW_MAX] [int] NULL,
	[RENEW_COUNT] [int] NULL,
	[RENEW_LAST_PROD_ID] [int] NULL,
	[LAST_RENEW_DATE] [smalldatetime] NULL,
	[SHAREABLE] [bit] NOT NULL,
	[SHARED_CONTROL_CLIENT_NO] [int] NULL,
	[SHARED_CONTROL] [bit] NOT NULL,
	[REVISION_SCHEMA] [int] NOT NULL,
	[REVISION_TYPE] [tinyint] NOT NULL,
	[REVISION_COUNT] [smallint] NULL,
	[REVISION_COUNT_TYPE] [tinyint] NULL,
	[REVISION_GRACE_ITEMS] [int] NULL,
	[REVISION_GRACE_DATE_TYPE] [tinyint] NULL,
	[ANNULMENTED] [bit] NOT NULL,
	[ANNULMENT_REALIZE] [bit] NOT NULL,
	[ANNULMENT_SCHEMA] [int] NULL,
	[ANNULMENT_SCHEMA_ADVANCE] [int] NULL,
	[INTEREST_REALIZE_ADV] [bit] NOT NULL,
	[INTEREST_REALIZE_ADV_AMOUNT] [money] NULL,
	[CHILD_DEPOSIT] [bit] NOT NULL,
	[CHILD_CONTROL_OWNER] [bit] NOT NULL,
	[CHILD_CONTROL_CLIENT_NO_1] [int] NULL,
	[CHILD_CONTROL_CLIENT_NO_2] [int] NULL,
	[ACCUMULATIVE] [bit] NOT NULL,
	[ACCUMULATE_PRODUCT] [bit] NOT NULL,
	[ACCUMULATE_MIN] [money] NULL,
	[ACCUMULATE_MAX] [money] NULL,
	[ACCUMULATE_AMOUNT] [money] NULL,
	[ACCUMULATE_MAX_AMOUNT_LIMIT] [money] NULL,
	[ACCUMULATE_MAX_AMOUNT] [money] NULL,
	[ACCUMULATE_SCHEMA_INTRATE] [tinyint] NULL,
	[SPEND] [bit] NOT NULL,
	[SPEND_INTRATE] [money] NULL,
	[SPEND_AMOUNT] [money] NULL,
	[SPEND_AMOUNT_INTRATE] [money] NULL,
	[SPEND_CONST_AMOUNT] [money] NULL,
	[DEPO_REALIZE_TYPE] [tinyint] NOT NULL,
	[CREDITCARD_BALANCE_CHECK] [bit] NOT NULL,
	[INTEREST_REALIZE_TYPE] [tinyint] NOT NULL ,
	[DEPO_FILL_ACC_ID] [int] NULL,
	[DEPO_ACC_ID] [int] NOT NULL,
	[LOSS_ACC_ID] [int] NOT NULL,
	[ACCRUAL_ACC_ID] [int] NOT NULL,
	[DEPO_REALIZE_ACC_ID] [int] NULL,
	[INTEREST_REALIZE_ACC_ID] [int] NULL,
	[INTEREST_REALIZE_ADV_ACC_ID] [int] NULL,
	[RESPONSIBLE_USER_ID] [int] NOT NULL,
	[DEPO_NOTE] [varchar](255) NULL,
	[ALARM_NOTE] [varchar](255) NULL,
	[DEPOSIT_DEFAULT] [bit] NOT NULL
)
AS
BEGIN
	DECLARE @op_id2 int

	IF @op_id IS NULL
	BEGIN
		INSERT INTO @depo_data
		SELECT -1, D.* FROM DEPO_DEPOSITS D
		WHERE DEPO_ID = @depo_id 
	END
	ELSE
	IF @op_id = 0
	BEGIN
		IF EXISTS(SELECT OP_ID FROM dbo.DEPO_DEPOSITS_HISTORY (NOLOCK) WHERE DEPO_ID = @depo_id)
		BEGIN
			SELECT @op_id = MIN(OP_ID) FROM dbo.DEPO_DEPOSITS_HISTORY
			WHERE DEPO_ID = @depo_id

			INSERT INTO @depo_data
			SELECT * FROM dbo.DEPO_DEPOSITS_HISTORY (NOLOCK)
			WHERE OP_ID = @op_id
		END
		ELSE
		BEGIN
			INSERT INTO @depo_data
			SELECT -1, D.* FROM DEPO_DEPOSITS D
			WHERE DEPO_ID = @depo_id 
		END
	END
	ELSE
	BEGIN
		IF EXISTS(SELECT OP_ID FROM dbo.DEPO_DEPOSITS_HISTORY WHERE DEPO_ID = @depo_id AND OP_ID > @op_id)
		BEGIN		
			INSERT INTO @depo_data
			SELECT TOP 1 * FROM dbo.DEPO_DEPOSITS_HISTORY (NOLOCK)
			WHERE DEPO_ID = @depo_id AND OP_ID > @op_id
			
		END
		ELSE
		BEGIN
			INSERT INTO @depo_data
			SELECT -1, D.* FROM DEPO_DEPOSITS D
			WHERE DEPO_ID = @depo_id 
		END
	END

	RETURN 
END
GO
