SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[depo_common_branch_id]()
RETURNS int AS
BEGIN
  RETURN (SELECT VALS FROM dbo.INI_INT (NOLOCK) WHERE IDS = 'DEPO_COMMON_BRANCH')
END
GO
