SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[fn_group_rights] (@group_id int, @all bit = 0) 
  RETURNS TABLE AS

RETURN

SELECT A.* FROM
(
	SELECT T.CATEGORY, T.DESCRIP AS TASK_NAME, TR.DESCRIP AS TASK_RIGHT_NAME, 
	  CONVERT(bit,
		CASE WHEN
		  CONVERT(tinyint,(SELECT SUBSTRING(G.ACCESS_STRING, TR.TASK_ID-1,2) FROM dbo.GROUPS G WHERE GROUP_ID = @group_id)) & 
		 (CASE TASK_RIGHT_ID WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 4 WHEN 4 THEN 8 WHEN 5 THEN 16 WHEN 6 THEN 32 WHEN 7 THEN 64 WHEN 8 THEN 128 END) <> 0 THEN 1 ELSE 0 END) AS HAS_RIGHT
	FROM dbo.TASK_RIGHTS TR (NOLOCK)
	  INNER JOIN dbo.TASKS T(NOLOCK) ON T.TASK_ID = TR.TASK_ID
) A
WHERE @all = 1 OR A.HAS_RIGHT = 1
GO
