SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[bank_head_branch_id] ()
RETURNS int AS
BEGIN
  RETURN (SELECT VALS FROM dbo.INI_INT (NOLOCK) WHERE IDS = 'HEAD_BRANCH_DEPT_NO')
END


--DROP PROCEDURE dbo.NBG_PLATS_FOR_SEND
GO
