SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[depo_show_depo_by_op_id] (@op_id int)
RETURNS TABLE
AS

RETURN
SELECT DX.DEPO_ID, DX.BRANCH_ID, DX.DEPT_NO, DX.CLIENT_NO, DX.DEPO_NO, 
	DX.DEPO_TYPE_ID, DX.PROD_ID, P.PROD_NO, DX.START_DATE AS REG_DT, DX.START_DATE, 
	DX.ACC_ID, A.ACCOUNT, DX.ISO, DX.PROLONGATION,
	DATEDIFF(day, DX.START_DATE, D.END_DATE) AS PERIOD, convert(bit, 0) AS CONVERTED_DEPOSIT, convert(bit, 0) AS REALIZE_ADVANCE, NULL AS REALIZE_ADV_ACC_ID,
	D.*
FROM dbo.DEPOS DX 
	INNER JOIN dbo.DEPO_OPS O ON O.DEPO_ID = DX.DEPO_ID
	INNER JOIN dbo.DEPO_DATA D ON D.OP_ID = O.OP_ID
	INNER JOIN dbo.ACCOUNTS A ON A.ACC_ID = DX.ACC_ID
	LEFT OUTER JOIN dbo.DEPO_PRODUCTS P ON P.PROD_ID = DX.PROD_ID
WHERE O.OP_ID = @op_id
GO
