SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[loan_open_date] ()
RETURNS smalldatetime AS
BEGIN
  RETURN (SELECT VALS FROM dbo.INI_DT (NOLOCK) WHERE IDS = 'OPEN_LOAN_DATE')
END
GO
