SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Autogenerated by dbo.SYS_CREATE_VAL_RATES_VIEW
CREATE FUNCTION [dbo].[get_equ] (@amount money, @ccy TISO, @date smalldatetime)
RETURNS money AS
BEGIN
  DECLARE @equ money

  IF @amount = $0.0000 OR @ccy = 'GEL'
    SET @equ = @amount
  ELSE
  BEGIN
	SET @equ = NULL

    SELECT TOP 1 @equ = (@amount * A.AMOUNT) / A.ITEMS
    FROM  dbo.VAL_RATES_0000 A (NOLOCK)
    WHERE A.ISO = @ccy AND A.DT <= @date
	ORDER BY A.DT DESC

	IF @equ IS NULL
		SELECT TOP 1 @equ = (@amount * A.AMOUNT) / A.ITEMS
		FROM  dbo.VAL_RATES_2017 A (NOLOCK)
		WHERE A.ISO = @ccy AND A.DT <= @date
		ORDER BY A.DT DESC

	IF @equ IS NULL
		SELECT TOP 1 @equ = (@amount * A.AMOUNT) / A.ITEMS
		FROM  dbo.VAL_RATES_OLD A (NOLOCK)
		WHERE A.ISO = @ccy AND A.DT <= @date
		ORDER BY A.DT DESC
  END

  RETURN ROUND(@equ, 4)
END
GO
