SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[DX_FN_GET_DEPOSIT_ISO](@oid int)
RETURNS TISO
AS
BEGIN
  DECLARE
    @iso TISO
  SELECT @iso=DX.ISO
  FROM
    dbo.DX_DEPOSITS DX INNER JOIN
    dbo.DX_DEPOSIT_OPS O ON O.DID=DX.DID
  WHERE O.OID=@oid

  RETURN @iso
END
GO
