SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[depo_get_last_data] (@did int)
RETURNS TABLE
AS

RETURN  (
	SELECT D.* 
	FROM dbo.DEPO_DATA D (NOLOCK)
		INNER JOIN dbo.DEPOS L (NOLOCK) ON D.OP_ID = L.OP_ID
	WHERE L.DEPO_ID = @did)
GO
