SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FNX_GET_CROSS_RATE_TBL](@doc_rec_id int, @doc_type tinyint)
RETURNS 
  @T TABLE (
    ISO1 char(3) NOT NULL,
    ISO2 char(3) NOT NULL, 
    ITEMS int NOT NULL,
    AMOUNT_BUY money NOT NULL,
    AMOUNT_SELL money NOT NULL)
AS
BEGIN

DECLARE
	@iso1 TISO,
	@iso2 TISO, 
	@doc_add_time smalldatetime

SELECT @iso1 = ISO 
FROM dbo.OPS_0000 (NOLOCK) 
WHERE REC_ID = @doc_rec_id AND PARENT_REC_ID = -1

SELECT @iso2 = D.ISO 
FROM dbo.OPS_0000 D (NOLOCK) 
WHERE D.REC_ID = (SELECT MIN(REC_ID) FROM dbo.OPS_0000 (NOLOCK) WHERE REC_ID > @doc_rec_id AND PARENT_REC_ID = @doc_rec_id)

SELECT @doc_add_time = D.TIME_OF_CHANGE
FROM dbo.DOC_CHANGES D (NOLOCK)
WHERE D.DOC_REC_ID = @doc_rec_id AND D.REC_ID = (SELECT MIN(D1.REC_ID) FROM dbo.DOC_CHANGES D1 (NOLOCK) WHERE D1.DOC_REC_ID = D.DOC_REC_ID)  


IF @doc_type < 100 -- Memorial order
BEGIN
  INSERT INTO @T(ISO1, ISO2, ITEMS, AMOUNT_BUY, AMOUNT_SELL)
  SELECT T.ISO1, T.ISO2, T.ITEMS, T.AMOUNT_BUY, T.AMOUNT_SELL
  FROM dbo.CROSS_RATES_ARC T (NOLOCK)
  WHERE ((T.ISO1 = @iso1 AND T.ISO2 = @iso2) OR (T.ISO1 = @iso2 AND T.ISO2 = @iso1)) AND 
    (T.DT_TM = (SELECT MIN(T1.DT_TM) FROM dbo.CROSS_RATES_ARC T1 (NOLOCK) WHERE T1.ISO1 = T.ISO1 AND T1.ISO2 = T.ISO2 AND T1.DT_TM > @doc_add_time))

  IF NOT EXISTS (SELECT * FROM @T)
  BEGIN
    INSERT INTO @T(ISO1, ISO2, ITEMS, AMOUNT_BUY, AMOUNT_SELL)
    SELECT T.ISO1, T.ISO2, T.ITEMS, T.AMOUNT_BUY, T.AMOUNT_SELL
    FROM dbo.CROSS_RATES T (NOLOCK)
    WHERE (T.ISO1 = @iso1 AND T.ISO2 = @iso2) OR (T.ISO1 = @iso2 AND T.ISO2 = @iso1)
  END
END
ELSE
BEGIN
  INSERT INTO @T(ISO1, ISO2, ITEMS, AMOUNT_BUY, AMOUNT_SELL)
  SELECT T.ISO1, T.ISO2, T.ITEMS, T.AMOUNT_BUY, T.AMOUNT_SELL
  FROM dbo.CROSS_RATES_KAS_ARC T (NOLOCK)
  WHERE ((T.ISO1 = @iso1 AND T.ISO2 = @iso2) OR (T.ISO1 = @iso2 AND T.ISO2 = @iso1)) AND 
    (T.DT_TM = (SELECT MIN(T1.DT_TM) FROM dbo.CROSS_RATES_ARC T1 (NOLOCK) WHERE T1.ISO1 = T.ISO1 AND T1.ISO2 = T.ISO2 AND T1.DT_TM > @doc_add_time))

  IF NOT EXISTS (SELECT * FROM @T)
  BEGIN
    INSERT INTO @T(ISO1, ISO2, ITEMS, AMOUNT_BUY, AMOUNT_SELL)
    SELECT T.ISO1, T.ISO2, T.ITEMS, T.AMOUNT_BUY, T.AMOUNT_SELL
    FROM dbo.CROSS_RATES_KAS T (NOLOCK)
    WHERE (T.ISO1 = @iso1 AND T.ISO2 = @iso2) OR (T.ISO1 = @iso2 AND T.ISO2 = @iso1)
  END
END

RETURN
END
GO
