SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[CHANGE_TEXT_]( @TMP_STR VARCHAR(100), @TMP_SUB_STR VARCHAR(100))
RETURNS VARCHAR(100)
AS
BEGIN

IF CHARINDEX(@TMP_SUB_STR, @TMP_STR) = 0
   RETURN @TMP_STR

RETURN SUBSTRING(@TMP_STR, CHARINDEX(@TMP_SUB_STR, @TMP_STR) + LEN(@TMP_SUB_STR), 999)

END



GO
