SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[user_dept_no] (@user_id int)
RETURNS int AS
BEGIN
  RETURN (SELECT DEPT_NO FROM dbo.USERS (NOLOCK) WHERE [USER_ID] = @user_id)
END
GO
