SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[LOAN_FN_GET_COLLATERALS](@loan_id int, @credit_line_id int)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		*, CONVERT(bit, 0) AS IS_LINKED 
	FROM dbo.LOAN_VW_LOAN_COLLATERALS 
	WHERE LOAN_ID = @loan_id OR CREDIT_LINE_ID = @credit_line_id

		UNION ALL

	SELECT 
		*, CONVERT(bit, 1) AS IS_LINKED 
	FROM dbo.LOAN_VW_LOAN_COLLATERALS 
	WHERE COLLATERAL_ID IN (SELECT COLLATERAL_ID FROM dbo.LOAN_COLLATERALS_LINK WHERE LOAN_ID = @loan_id)

		UNION ALL

	SELECT 
		*, CONVERT(bit, 1) AS IS_LINKED 
	FROM dbo.LOAN_VW_LOAN_COLLATERALS 
	WHERE COLLATERAL_ID IN (SELECT COLLATERAL_ID FROM dbo.LOAN_CREDIT_LINE_COLLATERALS_LINK WHERE CREDIT_LINE_ID = @credit_line_id)
)
GO
