SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[acc_get_bank_code_bic] (@acc_id int)  
RETURNS CHAR(11) AS  
BEGIN 
  RETURN (SELECT BIC FROM dbo.DEPTS (NOLOCK) WHERE DEPT_NO = (SELECT DEPT_NO FROM dbo.ACCOUNTS (NOLOCK) WHERE ACC_ID = @acc_id))
END
GO
