SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[acc_get_account] (@acc_id int)  
RETURNS TACCOUNT AS  
BEGIN 
  RETURN (SELECT ACCOUNT FROM dbo.ACCOUNTS (NOLOCK) WHERE ACC_ID = @acc_id)
END
GO
