SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[acc_get_bank_code] (@acc_id int)  
RETURNS TGEOBANKCODE AS  
BEGIN 
  RETURN (SELECT CODE9 FROM dbo.DEPTS (NOLOCK) WHERE DEPT_NO = (SELECT DEPT_NO FROM dbo.ACCOUNTS (NOLOCK) WHERE ACC_ID = @acc_id))
END
GO
