SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[cli_get_cli_type] (@client_id int) 
RETURNS tinyint
AS
BEGIN
  RETURN (SELECT CLIENT_TYPE FROM dbo.CLIENTS (NOLOCK) WHERE CLIENT_NO = @client_id)
END
GO
