SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[acc_get_name_lat] (@acc_id int)  
RETURNS varchar(100) AS  
BEGIN 
  RETURN (SELECT DESCRIP_LAT FROM dbo.ACCOUNTS (NOLOCK) WHERE ACC_ID = @acc_id)
END
GO
