SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--აბაშიძე
CREATE FUNCTION [dbo].[loan_get_loan_data](@loan_id int, @date smalldatetime)
RETURNS
	@loan_data TABLE (
	LOAN_ID int NOT NULL PRIMARY KEY,
	ROW_VERSION int NOT NULL,
	BRANCH_ID int NOT NULL,
	DEPT_NO int NOT NULL,
	AUTHORIZE_LEVEL tinyint NOT NULL,
	STATE tinyint NOT NULL,
	CLIENT_NO int NOT NULL,
	CREDIT_LINE_ID int NULL,
	PRODUCT_ID int NOT NULL,
	AGREEMENT_NO varchar(100) NOT NULL,
	REG_DATE smalldatetime NOT NULL,
	LOAN_TYPE int NOT NULL,
	DISBURSE_TYPE int NOT NULL,
	ENSURE_TYPE int NOT NULL,
	INSTALLMENT bit NOT NULL,
	EVENT_INSTALLMENT bit NULL,
	RESTRUCTURED int NOT NULL,
	PROLONGED int NOT NULL,
	ISO TISO NOT NULL,
	AMOUNT money NOT NULL,
	DISBURSE_AMOUNT money NOT NULL,
	START_DATE smalldatetime NOT NULL,
	PERIOD int NOT NULL,
	END_DATE smalldatetime NOT NULL,
	INTRATE money NOT NULL,
	PENALTY_INTRATE TPERCENT NOT NULL,
	PREPAYMENT_INTRATE TPERCENT NOT NULL,
	PREPAYMENT_STEP int NOT NULL,
	NOTUSED_INTRATE TPERCENT NOT NULL,
	ADMIN_INTRATE TPERCENT NOT NULL,
	ADMIN_FEE money NOT NULL,
	RISK_TYPE int NOT NULL,
	RISK_PERC_RATE_1 money NOT NULL,
	RISK_PERC_RATE_2 money NOT NULL,
	RISK_PERC_RATE_3 money NOT NULL,
	RISK_PERC_RATE_4 money NOT NULL,
	RISK_PERC_RATE_5 money NOT NULL,
	WRITEOFF_DATE smalldatetime NULL,
	CALLOFF_DATE smalldatetime NULL,
	INTEREST_FLAGS int NOT NULL,
	PENALTY_FLAGS int NOT NULL,
	PREPAYMENT_FLAGS int NOT NULL,
	PAYMENT_INTERVAL_TYPE int NOT NULL,
	SCHEDULE_TYPE int NOT NULL,
	PAYMENT_DAY tinyint NOT NULL,
	RESERVE_MAX_CATEGORY bit NOT NULL,
	INSTALLMENT_PERCENT money NULL,
	GRACE_STEPS tinyint NULL,
	GRACE_TYPE bit NULL,
	BASIS int NOT NULL,
	RESPONSIBLE_USER_ID int NOT NULL,
	CORESPONSIBLE_USER_ID int NOT NULL,
	PURPOSE_TYPE int NOT NULL,
	BAL_ACC TBAL_ACC NOT NULL,
	GROUP_ID int NULL,
	RAITING varchar(3) NULL)
     
AS
BEGIN
	DECLARE
		@op_id int

	SELECT @op_id = MIN(OP_ID)
	FROM dbo.LOAN_VW_LOANS_HISTORY (NOLOCK)
	WHERE LOAN_ID = @loan_id AND OP_DATE > @date

	IF @op_id IS NOT NULL
		INSERT INTO @loan_data(LOAN_ID, ROW_VERSION, BRANCH_ID, DEPT_NO, AUTHORIZE_LEVEL, STATE, CLIENT_NO,
			CREDIT_LINE_ID, PRODUCT_ID, AGREEMENT_NO, REG_DATE, LOAN_TYPE, DISBURSE_TYPE, ENSURE_TYPE,
			INSTALLMENT, EVENT_INSTALLMENT, RESTRUCTURED, PROLONGED, ISO, AMOUNT, DISBURSE_AMOUNT, START_DATE, PERIOD, END_DATE,
			INTRATE, PENALTY_INTRATE, PREPAYMENT_INTRATE, PREPAYMENT_STEP, NOTUSED_INTRATE, ADMIN_INTRATE, ADMIN_FEE,
			RISK_TYPE, RISK_PERC_RATE_1, RISK_PERC_RATE_2, RISK_PERC_RATE_3, RISK_PERC_RATE_4, RISK_PERC_RATE_5, 
			WRITEOFF_DATE, INTEREST_FLAGS, PENALTY_FLAGS, PREPAYMENT_FLAGS, PAYMENT_INTERVAL_TYPE, SCHEDULE_TYPE, PAYMENT_DAY,
			RESERVE_MAX_CATEGORY, INSTALLMENT_PERCENT, GRACE_STEPS, GRACE_TYPE, BASIS, RESPONSIBLE_USER_ID, CORESPONSIBLE_USER_ID, 
			PURPOSE_TYPE, BAL_ACC, GROUP_ID, RAITING) 
		(SELECT LOAN_ID, ROW_VERSION, BRANCH_ID, DEPT_NO, AUTHORIZE_LEVEL, STATE, CLIENT_NO,
			CREDIT_LINE_ID, PRODUCT_ID, AGREEMENT_NO, REG_DATE, LOAN_TYPE, DISBURSE_TYPE, ENSURE_TYPE,
			INSTALLMENT, EVENT_INSTALLMENT, RESTRUCTURED, PROLONGED, ISO, AMOUNT, DISBURSE_AMOUNT, START_DATE, PERIOD, END_DATE,
			INTRATE, PENALTY_INTRATE, PREPAYMENT_INTRATE, PREPAYMENT_STEP, NOTUSED_INTRATE, ADMIN_INTRATE, ADMIN_FEE,
			RISK_TYPE, RISK_PERC_RATE_1, RISK_PERC_RATE_2, RISK_PERC_RATE_3, RISK_PERC_RATE_4, RISK_PERC_RATE_5, 
			WRITEOFF_DATE, INTEREST_FLAGS, PENALTY_FLAGS, PREPAYMENT_FLAGS, PAYMENT_INTERVAL_TYPE, SCHEDULE_TYPE, PAYMENT_DAY,
			RESERVE_MAX_CATEGORY, INSTALLMENT_PERCENT, GRACE_STEPS, GRACE_TYPE, BASIS, RESPONSIBLE_USER_ID, CORESPONSIBLE_USER_ID, 
			PURPOSE_TYPE, BAL_ACC, GROUP_ID, dbo.LOAN_FN_GET_CLIENT_RATING_HISTORY(CLIENT_NO, @date) AS RAITING
		FROM dbo.LOAN_VW_LOANS_HISTORY
		WHERE OP_ID = @op_id)
	ELSE
		INSERT INTO @loan_data(LOAN_ID, ROW_VERSION, BRANCH_ID, DEPT_NO, AUTHORIZE_LEVEL, STATE, CLIENT_NO,
			CREDIT_LINE_ID, PRODUCT_ID, AGREEMENT_NO, REG_DATE, LOAN_TYPE, DISBURSE_TYPE, ENSURE_TYPE,
			INSTALLMENT, EVENT_INSTALLMENT, RESTRUCTURED, PROLONGED, ISO, AMOUNT, DISBURSE_AMOUNT, START_DATE, PERIOD, END_DATE,
			INTRATE, PENALTY_INTRATE, PREPAYMENT_INTRATE, PREPAYMENT_STEP, NOTUSED_INTRATE, ADMIN_INTRATE, ADMIN_FEE,
			RISK_TYPE, RISK_PERC_RATE_1, RISK_PERC_RATE_2, RISK_PERC_RATE_3, RISK_PERC_RATE_4, RISK_PERC_RATE_5, 
			WRITEOFF_DATE, INTEREST_FLAGS, PENALTY_FLAGS, PREPAYMENT_FLAGS, PAYMENT_INTERVAL_TYPE, SCHEDULE_TYPE, PAYMENT_DAY,
			RESERVE_MAX_CATEGORY, INSTALLMENT_PERCENT, GRACE_STEPS, GRACE_TYPE, BASIS, RESPONSIBLE_USER_ID, CORESPONSIBLE_USER_ID, 
			PURPOSE_TYPE, BAL_ACC, GROUP_ID, RAITING) 
		(SELECT L.LOAN_ID, L.ROW_VERSION, L.BRANCH_ID, L.DEPT_NO, L.AUTHORIZE_LEVEL, L.STATE, L.CLIENT_NO,
			L.CREDIT_LINE_ID, L.PRODUCT_ID, L.AGREEMENT_NO, L.REG_DATE, L.LOAN_TYPE, L.DISBURSE_TYPE, L.ENSURE_TYPE,
			L.INSTALLMENT, L.EVENT_INSTALLMENT, L.RESTRUCTURED, L.PROLONGED, L.ISO, L.AMOUNT, L.DISBURSE_AMOUNT, L.START_DATE, L.PERIOD, L.END_DATE,
			L.INTRATE, L.PENALTY_INTRATE, L.PREPAYMENT_INTRATE, L.PREPAYMENT_STEP, L.NOTUSED_INTRATE, L.ADMIN_INTRATE, L.ADMIN_FEE,
			L.RISK_TYPE, L.RISK_PERC_RATE_1, L.RISK_PERC_RATE_2, L.RISK_PERC_RATE_3, L.RISK_PERC_RATE_4, L.RISK_PERC_RATE_5,
			L.WRITEOFF_DATE, L.INTEREST_FLAGS, L.PENALTY_FLAGS, L.PREPAYMENT_FLAGS, L.PAYMENT_INTERVAL_TYPE, L.SCHEDULE_TYPE, L.PAYMENT_DAY,
			L.RESERVE_MAX_CATEGORY, L.INSTALLMENT_PERCENT, L.GRACE_STEPS, L.GRACE_TYPE, L.BASIS, L.RESPONSIBLE_USER_ID, L.CORESPONSIBLE_USER_ID,
			L.PURPOSE_TYPE, L.BAL_ACC, L.GROUP_ID, CE.RAITING AS RAITING
		FROM dbo.LOANS L
			LEFT JOIN dbo.CLIENT_EXTENSIONS CE ON L.CLIENT_NO = CE.CLIENT_NO
		WHERE LOAN_ID = @loan_id)
RETURN
END
GO
