SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[acc_get_ccy] (@acc_id int)  
RETURNS TISO AS  
BEGIN 
  RETURN (SELECT ISO FROM dbo.ACCOUNTS (NOLOCK) WHERE ACC_ID = @acc_id)
END
GO
