SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[LOAN_FN_FIND_LOAN_SCHEDULE] (@loan_id int, @date smalldatetime)
RETURNS
	@LOAN_SCHEDULE TABLE (
		SCHEDULE_DATE smalldatetime,
		PRINCIPAL money,
		INTEREST money,
		INSURANCE money,
		SERVICE_FEE money,
		DEFERED_INTEREST money, 
		DEFERED_OVERDUE_INTEREST money,
		DEFERED_PENALTY money,
		DEFERED_FINE money)
AS
BEGIN
DECLARE 
	@op_id int

SELECT TOP 1 @op_id = OP_ID FROM LOAN_OPS
WHERE LOAN_ID = @loan_id AND UPDATE_SCHEDULE = 1 AND OP_DATE >= @date 
ORDER BY OP_DATE


IF @op_id IS NULL
	INSERT INTO @LOAN_SCHEDULE (SCHEDULE_DATE, PRINCIPAL, INTEREST, INSURANCE, SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE)
	SELECT SCHEDULE_DATE, PRINCIPAL, INTEREST, INSURANCE, SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE FROM dbo.LOAN_SCHEDULE (NOLOCK) WHERE LOAN_ID = @loan_id
ELSE
	INSERT INTO @LOAN_SCHEDULE (SCHEDULE_DATE, PRINCIPAL, INTEREST, INSURANCE, SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE)
	SELECT SCHEDULE_DATE, PRINCIPAL, INTEREST, INSURANCE, SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE FROM dbo.LOAN_SCHEDULE_HISTORY (NOLOCK) WHERE LOAN_ID = @loan_id AND OP_ID = @op_id

RETURN
END
GO
