SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[client_show_statement] (
  @client_id int,
  @start_date smalldatetime,
  @end_date smalldatetime,
  @shadow_level smallint = -1
)
RETURNS @statement TABLE (REC_ID int, DOC_TYPE smallint, DT smalldatetime NOT NULL, DEBIT decimal(15,0) NULL, CREDIT decimal(15,0) NULL, ISO char(3), DESCRIP varchar(150), EXTRA_INFO varchar(150),
							DOC_NUM int, OP_CODE varchar(5), REC_STATE tinyint, PARENT_REC_ID int, ACCOUNT_EXTRA decimal(15,0) NULL, DOC_DATE_IN_DOC smalldatetime NULL,
							IS_ARC bit, DBO money, DBO_EQU money, CRO money, CRO_EQU money, REC_TYPE tinyint, DEBIT_ID int, CREDIT_ID int)

AS 
BEGIN
	DECLARE
		@dt_open smalldatetime,
		@rec_state smallint

	SET @dt_open = dbo.bank_open_date()

	IF @end_date < @dt_open 
		SET @shadow_level = -1

	IF @shadow_level <= 0
	  SET @rec_state = 0
	ELSE
	IF @shadow_level = 1
	  SET @rec_state = 10
	ELSE
	IF @shadow_level >= 2
	  SET @rec_state = 20

	IF @start_date > @dt_open
		SET @start_date = @dt_open

	DECLARE @tbl TABLE (REC_ID int, DOC_TYPE smallint, DT smalldatetime NOT NULL, DEBIT_ID int, CREDIT_ID int,
			DOC_NUM int, OP_CODE varchar(5), DESCRIP varchar(150), REC_STATE tinyint, PARENT_REC_ID int, ACCOUNT_EXTRA decimal(15,0) NULL, DOC_DATE_IN_DOC smalldatetime NULL,
			IS_ARC bit, DBO money, DBO_EQU money, CRO money, CRO_EQU money)

	INSERT INTO @tbl (REC_ID, DOC_TYPE, DT,	DEBIT_ID, CREDIT_ID, DOC_NUM, OP_CODE, DESCRIP, REC_STATE, PARENT_REC_ID, ACCOUNT_EXTRA, DOC_DATE_IN_DOC, IS_ARC, DBO, DBO_EQU, CRO, CRO_EQU/*, SALDO, SALDO_EQU*/)
	SELECT S.REC_ID, D.DOC_TYPE, S.DT,
		D.DEBIT_ID, D.CREDIT_ID,
		D.DOC_NUM, D.OP_CODE, D.DESCRIP, D.REC_STATE, D.PARENT_REC_ID, D.ACCOUNT_EXTRA, D.DOC_DATE_IN_DOC,
		CASE WHEN S.DT >= @dt_open THEN 0 ELSE 1 END AS IS_ARC,
		CASE A.ACC_ID WHEN D.DEBIT_ID THEN D.AMOUNT ELSE NULL END as DBO,
		CASE A.ACC_ID WHEN D.DEBIT_ID THEN D.AMOUNT_EQU ELSE NULL END as DBO_EQU,
		CASE A.ACC_ID WHEN D.CREDIT_ID THEN D.AMOUNT ELSE NULL END as CRO,
		CASE A.ACC_ID WHEN D.CREDIT_ID THEN D.AMOUNT_EQU ELSE NULL END as CRO_EQU
	FROM dbo.OPS_HELPER_FULL S(NOLOCK) 
		INNER JOIN dbo.ACCOUNTS A(NOLOCK) ON A.ACC_ID = S.ACC_ID		INNER JOIN dbo.OPS_FULL D(NOLOCK) ON D.REC_ID = S.REC_ID AND (D.DOC_DATE BETWEEN @start_date AND @end_date) AND D.REC_STATE >= @rec_state 	WHERE A.CLIENT_NO = @client_id AND S.DT BETWEEN @start_date AND @end_date
	ORDER BY S.DT, S.REC_ID

	INSERT INTO @statement
	SELECT T.REC_ID, T.DOC_TYPE, T.DT, A.ACCOUNT, B.ACCOUNT, A.ISO, T.DESCRIP, 
		CASE 
			WHEN T.DOC_TYPE BETWEEN 100 AND 109 AND T.DBO > $0 THEN 
				CASE WHEN T.IS_ARC = 0 THEN
					(SELECT RECEIVER_ACC_NAME FROM dbo.DOC_DETAILS_PLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				ELSE
					(SELECT RECEIVER_ACC_NAME FROM dbo.DOC_DETAILS_ARC_PLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				END
			WHEN T.DOC_TYPE BETWEEN 100 AND 109 AND T.CRO > $0 THEN 
				CASE WHEN T.IS_ARC = 0 THEN
					(SELECT SENDER_ACC_NAME FROM dbo.DOC_DETAILS_PLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				ELSE
					(SELECT SENDER_ACC_NAME FROM dbo.DOC_DETAILS_ARC_PLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				END
			WHEN T.DOC_TYPE BETWEEN 110 AND 119 AND T.DBO > $0 THEN 
				CASE WHEN T.IS_ARC = 0 THEN
					(SELECT RECEIVER_ACC_NAME FROM dbo.DOC_DETAILS_VALPLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				ELSE
					(SELECT RECEIVER_ACC_NAME FROM dbo.DOC_DETAILS_ARC_VALPLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				END
			WHEN T.DOC_TYPE BETWEEN 110 AND 119 AND T.CRO > $0 THEN 
				CASE WHEN T.IS_ARC = 0 THEN
					(SELECT SENDER_ACC_NAME FROM dbo.DOC_DETAILS_VALPLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				ELSE
					(SELECT SENDER_ACC_NAME FROM dbo.DOC_DETAILS_ARC_VALPLAT DD WHERE DD.DOC_REC_ID = T.REC_ID)
				END
			WHEN T.DOC_TYPE BETWEEN 120 AND 159 THEN 
				CASE WHEN T.IS_ARC = 0 THEN
					(SELECT LTRIM(ISNULL(FIRST_NAME,'') + ' ' + ISNULL(LAST_NAME,'')) FROM dbo.DOC_DETAILS_PASSPORTS DD WHERE DD.DOC_REC_ID = T.REC_ID)
				ELSE
					(SELECT LTRIM(ISNULL(FIRST_NAME,'') + ' ' + ISNULL(LAST_NAME,'')) FROM dbo.DOC_DETAILS_ARC_PASSPORTS DD WHERE DD.DOC_REC_ID = T.REC_ID)
				END
			ELSE
				NULL
		END AS EXTRA_INFO,
		T.DOC_NUM, T.OP_CODE, T.REC_STATE, T.PARENT_REC_ID, T.ACCOUNT_EXTRA, T.DOC_DATE_IN_DOC, T.IS_ARC,
		T.DBO, T.DBO_EQU, T.CRO, T.CRO_EQU,
		0, T.DEBIT_ID, T.CREDIT_ID
	FROM @tbl T
		LEFT JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = T.DEBIT_ID
		LEFT JOIN dbo.ACCOUNTS B (NOLOCK) ON B.ACC_ID = T.CREDIT_ID

  RETURN
END
GO
