SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[LOAN_FN_GET_COLLATERAL_CREDIT_LINES](@collateral_id int, @just_linked bit)
RETURNS TABLE 
AS
RETURN 
(
	SELECT CL.* FROM dbo.LOAN_COLLATERALS C
	INNER JOIN dbo.LOAN_VW_CREDIT_LINES CL ON C.CREDIT_LINE_ID = CL.CREDIT_LINE_ID
	WHERE C.COLLATERAL_ID = @collateral_id AND @just_linked = 0

	UNION

	SELECT CL.* FROM LOAN_CREDIT_LINE_COLLATERALS_LINK lnk
	INNER JOIN dbo.LOAN_VW_CREDIT_LINES CL ON lnk.CREDIT_LINE_ID = CL.CREDIT_LINE_ID
	WHERE lnk.COLLATERAL_ID = @collateral_id
)
GO
