SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[BALANCES_WIDE] ASSELECT * FROM dbo.BAL_2009 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2010 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2011 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2012 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2013 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2014 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2015 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2016 (NOLOCK)  UNION ALLSELECT * FROM dbo.BAL_2017 (NOLOCK)
GO
