SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[LOAN_VW_LOAN_REPS_original]
AS
SELECT
	L.LOAN_ID, L.ROW_VERSION, L.BRANCH_ID, L.DEPT_NO, L.AUTHORIZE_LEVEL, L.STATE,
	DP.ALIAS AS BRANCH_ALIAS, DP.ALIAS + ': ' + DP.DESCRIP AS BRANCH_NAME, L.AGREEMENT_NO,
	RTRIM(U.USER_NAME) + '@' + DP.ALIAS AS U_USER_NAME,
	RTRIM(U2.USER_NAME) + '@' + DP.ALIAS AS U_CO_USER_NAME,
	L.GROUP_ID, LG.CODE AS LG_CODE,	
	L.CLIENT_NO, C.DESCRIP AS CLIENT_DESCRIP, C.DESCRIP_LAT AS CLIENT_DESCRIP_LAT,
	L.START_DATE, L.PROLONGED, L.END_DATE,
	L.ISO, L.AMOUNT,
	L.PRODUCT_ID, P.CODE AS PRODUCT_CODE, 
	C.PHONE2 AS C_MOBILE_PHONE,
	L.REG_DATE, 
	L.DISBURSE_AMOUNT, L.PERIOD, 
	C.IS_RESIDENT, C.IS_INSIDER, C.IS_EMPLOYEE, C.IS_IN_BLACK_LIST, L.CREDIT_LINE_ID, L.LOAN_TYPE,
	L.DISBURSE_TYPE, L.ENSURE_TYPE, L.INSTALLMENT, L.EVENT_INSTALLMENT, L.RESTRUCTURED, 
	L.INTRATE, L.PENALTY_INTRATE, L.PREPAYMENT_INTRATE,
	L.PREPAYMENT_STEP, L.NOTUSED_INTRATE, L.ADMIN_INTRATE, L.ADMIN_FEE,
	L.RISK_TYPE, L.RISK_PERC_RATE_1, L.RISK_PERC_RATE_2, L.RISK_PERC_RATE_3, L.RISK_PERC_RATE_4, L.RISK_PERC_RATE_5,
	L.WRITEOFF_DATE, L.CALLOFF_DATE, L.INTEREST_FLAGS,
	L.PENALTY_FLAGS, L.PREPAYMENT_FLAGS, L.PAYMENT_INTERVAL_TYPE,
	LPI.DESCRIP AS LPI_DESCRIP,
	LPI.DESCRIP_LAT AS LPI_DESCRIP_LAT,
	LPI.INTERVAL AS LPI_INTERVAL, L.SCHEDULE_TYPE,
	L.PAYMENT_DAY, L.RESERVE_MAX_CATEGORY,
	L.INSTALLMENT_PERCENT, L.GRACE_STEPS, L.GRACE_TYPE,
	L.BASIS, L.RESPONSIBLE_USER_ID, L.CORESPONSIBLE_USER_ID, L.PURPOSE_TYPE, L.BAL_ACC,
	LS.DESCRIP AS LS_DESCRIP, 
	LS.DESCRIP_LAT AS LS_DESCRIP_LAT,
	CT.CLIENT_TYPE, CT.DESCRIP AS CT_DESCRIP,
	/*CE.RAITING, */CE.SEGMENTATION_NUM,
	LRT.DESCRIP AS LRT_DESCRIP,
	L.CLIENT_ACCOUNT,
	L.SERVICE_FEE, L.SERVICE_FEE_RATE, L.INSURANCE_RATE,
	L.GUARANTEE
FROM dbo.LOANS L (NOLOCK)
	INNER JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = L.DEPT_NO
	INNER JOIN dbo.LOAN_PRODUCTS P (NOLOCK) ON P.PRODUCT_ID = L.PRODUCT_ID
	INNER JOIN dbo.LOAN_PAYMENT_INTERVALS LPI (NOLOCK) ON LPI.TYPE_ID = L.PAYMENT_INTERVAL_TYPE
	INNER JOIN dbo.LOAN_STATES LS (NOLOCK) ON LS.STATE = L.STATE
	INNER JOIN dbo.USERS U (NOLOCK) ON U.USER_ID = L.RESPONSIBLE_USER_ID
	INNER JOIN dbo.USERS U2 (NOLOCK) ON U2.USER_ID = L.CORESPONSIBLE_USER_ID
	INNER JOIN dbo.CLIENTS C (NOLOCK) ON C.CLIENT_NO = L.CLIENT_NO
	INNER JOIN dbo.CLIENT_TYPES CT (NOLOCK) ON CT.CLIENT_TYPE = C.CLIENT_TYPE
	INNER JOIN dbo.LOAN_RISK_TYPES LRT ON LRT.TYPE_ID = L.RISK_TYPE
	LEFT OUTER JOIN dbo.CLIENT_EXTENSIONS CE ON CE.CLIENT_NO = C.CLIENT_NO
	LEFT OUTER JOIN dbo.LOAN_GROUPS LG (NOLOCK) ON  LG.GROUP_ID = L.GROUP_ID
GO
