SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[depo_realize_accounts]
AS
	SELECT A.*
	FROM dbo.ACCOUNTS A
	WHERE (A.REC_STATE NOT IN (2,128)) AND (A.ACC_TYPE IN (100, 200)) AND
		((A.ACC_TYPE <> 100) OR ((A.ACC_TYPE = 100) AND (A.CLIENT_NO IS NOT NULL))) 
GO
