SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ACC_SHADOWS] AS
SELECT DISTINCT A.ACC_ID, A.ACCOUNT, A.ISO, S.DT, A.REC_STATE, A.IS_CONTROL, A.IS_INCASSO, A.SALDO, A.SALDO_AVAILABLE, A.LAST_OP_DATE, DP.ALIAS AS BRANCH_ALIAS, DP.ALIAS + ': ' + DP.DESCRIP AS BRANCH_NAME
FROM dbo.ACC_VIEW A(NOLOCK) 
	LEFT JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = A.DEPT_NO
	INNER JOIN dbo.OPS_HELPER_0000 S(NOLOCK) ON S.ACC_ID=A.ACC_ID INNER JOIN dbo.OPS_0000 D(NOLOCK) ON D.REC_ID=S.REC_ID
GO
