SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_DEPO_PRODUCT_INTRATE_SCHEMA]
AS
	SELECT S.[SCHEMA_ID], S.DESCRIP, S.DATE_TYPE, D.ISO, D.ITEMS, D.INTRATE
	FROM dbo.DEPO_PRODUCT_INTRATE_SCHEMA S (NOLOCK)  
		INNER JOIN dbo.DEPO_PRODUCT_INTRATE_SCHEMA_DETAILS D (NOLOCK) ON S.[SCHEMA_ID] = D.[SCHEMA_ID]
GO
