SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[SO_PROCESS_VIEW]
AS
SELECT  s.TASK_ID, s.DATE, 0 AS [VERSION], s.STATE  AS PROCESS_STATE, s.FAIL_COUNTER, s.FAULT_CODE, s.FAULT_MESSAGE, NULL AS SUSPENDED_BY_BANK,
		t.AGREEMENT_NO, t.STATE AS TASK_STATE, t.DEBT_ACTION, t.REG_DATE, 
		t.RESPONSIBLE_USER_ID, t.START_DATE, t.END_DATE, t.PRIORITY AS TASK_PRIORITY,
		t.CLIENT_NO, t.HOLIDAY_SHIFTING, t.RETRY_COUNT_PER_PAY, t.MAX_FAILURE_COUNT,
		t.DESCRIP AS TASK_DESCRIP, t.DESCRIP_LAT AS TASK_DESCRIP_LAT,
		p.ID AS PRODUCT_ID, p.DESCRIP AS PRODUCT_DESCRIP, p.DESCRIP_LAT AS PRODUCT_DESCRIP_LAT,
		p.PRODUCT_OWNER, p.CHARGE_TYPE, p.EXECUTION_TIME, p.PRIORITY AS PRODUCT_PRIORITY, s.DOC_REC_ID
FROM dbo.SO_SCHEDULES s
	INNER JOIN dbo.SO_TASKS t ON t.ID = s.TASK_ID
	INNER JOIN dbo.SO_PRODUCTS p ON p.ID = t.PRODUCT_ID
UNION ALL
SELECT	s.TASK_ID, s.DATE, s.VERSION, s.STATE  AS PROCESS_STATE, s.FAIL_COUNTER, s.FAULT_CODE, s.FAULT_MESSAGE, s.SUSPENDED_BY_BANK,
		t.AGREEMENT_NO, t.STATE AS TASK_STATE, t.DEBT_ACTION, t.REG_DATE, 
		t.RESPONSIBLE_USER_ID, t.START_DATE, t.END_DATE, t.PRIORITY AS TASK_PRIORITY,
		t.CLIENT_NO, t.HOLIDAY_SHIFTING, t.RETRY_COUNT_PER_PAY, t.MAX_FAILURE_COUNT,
		t.DESCRIP AS TASK_DESCRIP, t.DESCRIP_LAT AS TASK_DESCRIP_LAT,
		p.ID AS PRODUCT_ID, p.DESCRIP AS PRODUCT_DESCRIP, p.DESCRIP_LAT AS PRODUCT_DESCRIP_LAT,
		p.PRODUCT_OWNER, p.CHARGE_TYPE, p.EXECUTION_TIME, p.PRIORITY AS PRODUCT_PRIORITY, NULL AS DOC_REC_ID
FROM dbo.SO_SCHEDULE_ANULLS s
	INNER JOIN dbo.SO_TASKS t ON t.ID = s.TASK_ID
	INNER JOIN dbo.SO_PRODUCTS p ON p.ID = t.PRODUCT_ID
GO
