SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_DATA_CHANGE_DEPO_REALIZE_ACCOUNT]
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_DATA.value('(row/@OLD_DEPO_REALIZE_ACC_ID)[1]', 'int') AS OLD_DEPO_REALIZE_ACC_ID,
		OP_DATA.value('(row/@NEW_DEPO_REALIZE_ACC_ID)[1]', 'int') AS NEW_DEPO_REALIZE_ACC_ID,
		OP_DATA.value('(row/@CHANGE_INTEREST_REALIZE_ACC)[1]', 'bit') AS CHANGE_INTEREST_REALIZE_ACC
	FROM dbo.DEPO_OP
	WHERE OP_TYPE = dbo.depo_fn_const_op_change_depo_realize_account()
GO
