SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[PENDING_PAYMENTS_VIEW]
AS
SELECT	A.DOC_REC_ID, A.IS_ONLINE, A.PROVIDER_ID, A.SERVICE_ALIAS, A.DOC_TYPE, A.OWNER, A.DEPT_NO, A.CHANNEL_ID, A.REC_STATE, 
		A.SORT_ORDER, A.DT_TM, A.AMOUNT, A.ID_IN_PROVIDER, A.ID2_IN_PROVIDER, A.CARD_ID, A.CARD_TYPE, A.INFO, A.RESPONSE, A.REF_NUM, 
        A.INSERT_TIME, A.PAUSED, A.LOCK_FLAG, A.WAITING_FLAG, A.DELETE_FLAG, 
        CASE WHEN A.IS_ONLINE = 0 THEN 'ÀÒÀÐÉÒÃÀÐÉÒÉ ÊÀÅÛÉÒÉ' ELSE 'ÐÉÒÃÀÐÉÒÉ ÊÀÅÛÉÒÉ' END AS IS_ONLINE_NAME, B.PROVIDER_NAME, 
        C.SERVICE_NAME, D.USER_NAME, dbo.get_pending_acc(A.DOC_REC_ID, A.DOC_TYPE, 0) AS SENDER_ACC, 
        dbo.get_pending_acc_name(A.DOC_REC_ID, A.DOC_TYPE, 0) AS SENDER_ACC_NAME
FROM	dbo.PENDING_PAYMENTS (NOLOCK) AS A INNER JOIN
        dbo.PAYMENT_PROVIDERS (NOLOCK) AS B ON B.PROVIDER_ID = A.PROVIDER_ID INNER JOIN
        dbo.PAYMENT_PROVIDER_SERVICES (NOLOCK) AS C ON C.PROVIDER_ID = A.PROVIDER_ID AND C.SERVICE_ALIAS = A.SERVICE_ALIAS INNER JOIN
        dbo.USERS (NOLOCK) AS D ON D.USER_ID = A.OWNER INNER JOIN
        dbo.DEPTS (NOLOCK) AS E ON E.DEPT_NO = A.DEPT_NO

GO
