SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_DATA_CHANGE_SHAREABLE]
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_DATA.value('(row/@SHAREABLE)[1]', 'bit') AS SHAREABLE,
		OP_DATA.value('(row/@SHARED_CONTROL_CLIENT_NO)[1]', 'int') AS SHARED_CONTROL_CLIENT_NO,
		OP_DATA.value('(row/@SHARED_CONTROL)[1]', 'bit') AS SHARED_CONTROL
	FROM dbo.DEPO_OP
	WHERE OP_TYPE = dbo.depo_fn_const_op_shareable_change()
GO
