SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[depo_realize_accounts_saving_private]
AS
SELECT A.*
FROM dbo.ACCOUNTS A (NOLOCK)
WHERE (A.REC_STATE NOT IN (2,128)) AND (A.ACC_TYPE = 2)
GO
