SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_SWIFT_STATEMENTS_LIST]
AS
SELECT     S.REC_ID, S.UID, S.STATE, S.STATEMENT_NO, S.CLIENT_NO, C.DESCRIP AS CLIENT_DESCRIP, A.ISO, S.ACC_ID, A.ACCOUNT, 
                      A.DESCRIP AS ACC_DESCRIP, S.CREATE_DT, S.START_DATE, S.END_DATE, S.STATEMENT_COMMITTED, S.OWNER, convert(text, Null) AS SWIFT_TEXT
FROM         dbo.SWIFT_STATEMENTS_LIST AS S WITH (NOLOCK) INNER JOIN
                      dbo.ACCOUNTS AS A WITH (NOLOCK) ON A.ACC_ID = S.ACC_ID INNER JOIN
                      dbo.CLIENTS AS C WITH (NOLOCK) ON C.CLIENT_NO = S.CLIENT_NO

GO
