SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DOCS_ARC_PLAT] AS
 
SELECT D.*, DD.*
FROM dbo.DOCS_ARC_ALL D
	INNER JOIN dbo.DOC_DETAILS_ARC_PLAT DD(NOLOCK) ON DD.DOC_REC_ID = D.REC_ID
WHERE D.DOC_TYPE BETWEEN 100 AND 109
GO
