SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
	
CREATE VIEW [dbo].[V_DEPO_PRODUCTS]
AS

SELECT P.PROD_ID, P.PROD_NO, P.DESCRIP, P.REG_DATE, P.ACTIVE, P.CLIENT_TYPE, P.DEPO_TYPE_ID, T.DESCRIP AS TDESCRIP, 
	T.DESCRIP_LAT AS TDESCRIP_LAT, P.CONVERTED_DEPOSIT, P.MOVE_METHOD, M.METHOD_DESCRIP AS MOVE_METHOD_DESCRIP, P.PERC_METHOD, 
	P1.METHOD_DESCRIP AS PERC_METHOD_DESCRIP, P.PERC_CORRECT, P.ACRUAL_ACCOUNT, P.DISB_ACCOUNT, P.DEPOSIT_ACCOUNT, P.REALIZE_ADVANCE, P.REALIZE_ADV_ACCOUNT,
	P.PERC_FLAGS, P.DAYS_IN_YEAR, P.MAX_DAYS, P.NO_CLIENT_ACCOUNT, P.PROLONGATION, P.ANNULMENT_METHOD, A.METHOD_DESCRIP AS ANNULMENT_METHOD_DESCRIP, P.DEPO_ACC_SUBTYPE
FROM dbo.DEPO_PRODUCTS AS P WITH (NOLOCK) 
	INNER JOIN dbo.DEPO_MOVE_METHODS AS M (NOLOCK) ON P.MOVE_METHOD = M.METHOD_ID
	INNER JOIN dbo.DEPO_PERC_METHODS AS P1 (NOLOCK) ON P.PERC_METHOD = P1.METHOD_ID
	INNER JOIN dbo.DEPO_TYPES AS T (NOLOCK) ON P.DEPO_TYPE_ID = T.DEPO_TYPE_ID
	LEFT OUTER JOIN dbo.DEPO_ANNULMENT_METHODS AS A (NOLOCK) ON P.ANNULMENT_METHOD = A.METHOD_ID
GO
