SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[BCC_BRANCH_ACC_VIEW] 
AS

SELECT A.*, BC.BC_CLIENT_ID
FROM dbo.ACCOUNTS A (NOLOCK)
	INNER JOIN dbo.BC_CLIENTS BC (NOLOCK) ON A.BRANCH_ID = BC.BRANCH_ID
GO
