SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[LOAN_VW_LOAN_OP_OVERDUE]
AS
SELECT
		OP_ID,
		LOAN_ID,
		ISNULL(OP_DATA.value('(row/@OVERDUE_PERCENT)[1]', 'money'), $0.00) AS OVERDUE_PERCENT,
		ISNULL(OP_DATA.value('(row/@OVERDUE_PRINCIPAL)[1]', 'money'), $0.00) AS OVERDUE_PRINCIPAL,
		ISNULL(OP_DATA.value('(row/@OVERDUE_INSURANCE)[1]', 'money'), $0.00) AS OVERDUE_INSURANCE,
		ISNULL(OP_DATA.value('(row/@OVERDUE_SERVICE_FEE)[1]', 'money'), $0.00) AS OVERDUE_SERVICE_FEE,
		ISNULL(OP_DATA.value('(row/@OVERDUE_DEFERED_INTEREST)[1]', 'money'), $0.00) AS OVERDUE_DEFERED_INTEREST
	FROM dbo.LOAN_OPS
	WHERE OP_TYPE = dbo.loan_const_op_overdue()
GO
