SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_BAL_ACCS]
AS
SELECT B.BAL_ACC, P1.DESCRIP AS BAL_ACC_DESCRIP, P1.DESCRIP_LAT AS BAL_ACC_DESCRIP_LAT,
	T.TYPE_ID, T.CODE AS TYPE_CODE, T.DESCRIP AS TYPE_DESCRIP, T.DESCRIP_LAT AS TYPE_DESCRIP_LAT,
	B.ACCOUNT_BAL_ACC, P2.DESCRIP AS ACCOUNT_BAL_ACC_DESCRIP, P2.DESCRIP_LAT AS ACCOUNT_BAL_ACC_DESCRIP_LAT
FROM dbo.LOAN_BAL_ACCS B (NOLOCK) 
	INNER JOIN dbo.LOAN_ACCOUNT_TYPES T (NOLOCK) ON B.TYPE_ID = T.TYPE_ID
	INNER JOIN dbo.PLANLIST_ALT P1 (NOLOCK) ON P1.BAL_ACC = B.BAL_ACC
	INNER JOIN dbo.PLANLIST_ALT P2 (NOLOCK) ON P2.BAL_ACC = B.ACCOUNT_BAL_ACC

GO
