SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[depo_realize_accounts_saving_non_private]
AS
SELECT A.*
FROM dbo.ACCOUNTS A (NOLOCK)
      INNER JOIN dbo.CLIENTS C (NOLOCK) ON A.CLIENT_NO = C.CLIENT_NO
WHERE (A.REC_STATE NOT IN (2,128)) AND (A.ACC_TYPE = 100) AND (C.CLIENT_TYPE <> 1)
GO
