SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_OP_WRITEOFF_DETAILS]
AS
SELECT
		OP_ID,
		LOAN_ID,
		ISNULL(OP_DETAILS.value('(row/@OVERDUE_PERCENT_PENALTY)[1]', 'money'), $0.00) AS OVERDUE_PERCENT_PENALTY,
		ISNULL(OP_DETAILS.value('(row/@OVERDUE_PRINCIPAL_PENALTY)[1]', 'money'), $0.00) AS OVERDUE_PRINCIPAL_PENALTY,
		ISNULL(OP_DETAILS.value('(row/@OVERDUE_PERCENT)[1]', 'money'), $0.00) AS OVERDUE_PERCENT,
		ISNULL(OP_DETAILS.value('(row/@LATE_PERCENT)[1]', 'money'), $0.00) AS LATE_PERCENT,
		ISNULL(OP_DETAILS.value('(row/@OVERDUE_PRINCIPAL)[1]', 'money'), $0.00) AS OVERDUE_PRINCIPAL,
		ISNULL(OP_DETAILS.value('(row/@LATE_PRINCIPAL)[1]', 'money'), $0.00) AS LATE_PRINCIPAL,
		ISNULL(OP_DETAILS.value('(row/@OVERDUE_PRINCIPAL_INTEREST)[1]', 'money'), $0.00) AS OVERDUE_PRINCIPAL_INTEREST,
		ISNULL(OP_DETAILS.value('(row/@INTEREST)[1]', 'money'), $0.00) AS INTEREST,
		ISNULL(OP_DETAILS.value('(row/@NU_INTEREST)[1]', 'money'), $0.00) AS NU_INTEREST,
		ISNULL(OP_DETAILS.value('(row/@PRINCIPAL)[1]', 'money'), $0.00) AS PRINCIPAL
	FROM dbo.LOAN_OPS
	WHERE OP_TYPE = dbo.loan_const_op_writeoff()
GO
