SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[VW_USER_SESSIONS]
AS
	SELECT S.*, A.NAME AS [APP_NAME], U.USER_FULL_NAME FROM dbo.USER_SESSIONS S (NOLOCK)
		INNER JOIN dbo.APPLICATIONS A (NOLOCK) ON S.APP_URI = A.URI
		INNER JOIN dbo.USERS U (NOLOCK) ON S.[USER_ID] = U.[USER_ID]
GO
