SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_ACC_DATA_ACTIVE]
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_ACC_DATA.value('(row/@INTEREST_REALIZE_ADV_TAX_AMOUNT)[1]', 'money') AS INTEREST_REALIZE_ADV_TAX_AMOUNT,
		OP_ACC_DATA.value('(row/@INTEREST_REALIZE_ADV_TAX_AMOUNT_EQU)[1]', 'money') AS INTEREST_REALIZE_ADV_TAX_AMOUNT_EQU
	FROM dbo.DEPO_OP
	WHERE OP_TYPE = dbo.depo_fn_const_op_active()
GO
