SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[LOAN_VW_COLLATERAL_DETAILS_DEPOSIT]
AS
	SELECT 
		COLLATERAL_ID,
		COLLATERAL_DETAILS.value('(row/@ACC_ID)[1]', 'int') AS ACC_ID
	FROM dbo.LOAN_COLLATERALS
	WHERE COLLATERAL_TYPE = 2
GO
