SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_OP_RESTRUCTURE_PARAMS]
AS
	SELECT
		OP_ID,
		LOAN_ID,
		ISNULL(OP_DATA.value('(row/@PURPOSE_TYPE)[1]', 'int'), 0) AS PURPOSE_TYPE,
		ISNULL(OP_DATA.value('(row/@GROUP_ID)[1]', 'int'), 0) AS GROUP_ID,
		ISNULL(OP_DATA.value('(row/@CORESPONSIBLE_USER_ID)[1]', 'int'), 0) AS CORESPONSIBLE_USER_ID,
		ISNULL(OP_DATA.value('(row/@PREPAYMENT_STEP)[1]', 'int'), 0) AS PREPAYMENT_STEP,
		ISNULL(OP_DATA.value('(row/@INTEREST_FLAGS)[1]', 'int'), 0) AS INTEREST_FLAGS,
		ISNULL(OP_DATA.value('(row/@PENALTY_FLAGS)[1]', 'int'), 0) AS PENALTY_FLAGS,
		ISNULL(OP_DATA.value('(row/@PREPAYMENT_FLAGS)[1]', 'int'), 0) AS PREPAYMENT_FLAGS,
		ISNULL(OP_DATA.value('(row/@RESERVE_MAX_CATEGORY)[1]', 'bit'), 0) AS RESERVE_MAX_CATEGORY,

		ISNULL(OP_DATA.value('(row/@OLD_PURPOSE_TYPE)[1]', 'int'), 0) AS OLD_PURPOSE_TYPE,
		ISNULL(OP_DATA.value('(row/@OLD_GROUP_ID)[1]', 'int'), 0) AS OLD_GROUP_ID,
		ISNULL(OP_DATA.value('(row/@OLD_CORESPONSIBLE_USER_ID)[1]', 'int'), 0) AS OLD_CORESPONSIBLE_USER_ID,
		ISNULL(OP_DATA.value('(row/@OLD_PREPAYMENT_STEP)[1]', 'int'), 0) AS OLD_PREPAYMENT_STEP,
		ISNULL(OP_DATA.value('(row/@OLD_INTEREST_FLAGS)[1]', 'int'), 0) AS OLD_INTEREST_FLAGS,
		ISNULL(OP_DATA.value('(row/@OLD_PENALTY_FLAGS)[1]', 'int'), 0) AS OLD_PENALTY_FLAGS,
		ISNULL(OP_DATA.value('(row/@OLD_PREPAYMENT_FLAGS)[1]', 'int'), 0) AS OLD_PREPAYMENT_FLAGS,
		ISNULL(OP_DATA.value('(row/@OLD_RESERVE_MAX_CATEGORY)[1]', 'bit'), 0) AS OLD_RESERVE_MAX_CATEGORY
	FROM dbo.LOAN_OPS
	WHERE OP_TYPE = dbo.loan_const_op_restructure_params()
GO
