SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DOCS_KASCHE] AS

SELECT D.*, 
	ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,'') AS CLIENT_NAME, P.PERSONAL_ID
FROM dbo.DOCS_ALL D
	LEFT JOIN dbo.DOC_DETAILS_PASSPORTS P ON P.DOC_REC_ID = D.REC_ID
WHERE D.DOC_TYPE BETWEEN 140 AND 149
GO
