SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_INSTALLMENT_CLIENT_OBJECTS]
AS
SELECT I.REC_ID, C.CLIENT_NO, C.DESCRIP AS CLIENT_DESCRIP, 
     C.DESCRIP_LAT AS CLIENT_DESCRIP_LAT, I.DESCRIP, 
     I.DESCRIP_LAT, I.ADDRESS, I.ADDRESS_LAT, I.IS_ACTIVE
FROM dbo.LOAN_INSTALLMENT_CLIENT_OBJECTS AS I INNER JOIN
     dbo.CLIENTS AS C ON I.CLIENT_NO = C.CLIENT_NO
GO
