SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[CURRENT_RATES_KAS] AS

SELECT CR.ISO1 AS ISO, CR.ITEMS, CR.AMOUNT_BUY, CR.AMOUNT_SELL 
FROM dbo.CROSS_RATES_KAS CR (NOLOCK)
WHERE ISO2 = 'GEL'
GO
