SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[LOAN_VW_CREDIT_LINES]
AS
	SELECT lcl.*, C.DESCRIP AS C_DESCRIP, C.DESCRIP_LAT AS C_DESCRIP_LAT, ISNULL(B.DISBURSED_AMOUNT, $0.00) AS DISBURSED_AMOUNT,
			ISNULL(B.PRINCIPAL_AMOUNT, $0.00) AS PRINCIPAL_AMOUNT, ISNULL(B.NU_PRINCIPAL_AMOUNT, $0.00) AS NU_PRINCIPAL_AMOUNT
	FROM dbo.LOAN_CREDIT_LINES lcl
	LEFT JOIN 
		(
			SELECT 
				l.CREDIT_LINE_ID, 
				SUM(dbo.get_cross_amount(l.AMOUNT, l.ISO, cl.ISO, GETDATE())) AS DISBURSED_AMOUNT,
				SUM(dbo.get_cross_amount(ISNULL(ld.PRINCIPAL, $0.00) + ISNULL(ld.OVERDUE_PRINCIPAL, $0.00) + ISNULL(ld.WRITEOFF_PRINCIPAL, $0.00), l.ISO, cl.ISO, GETDATE())) AS PRINCIPAL_AMOUNT,
				SUM(dbo.get_cross_amount(ISNULL(ld.NU_PRINCIPAL, $0.00), l.ISO, cl.ISO, GETDATE())) AS NU_PRINCIPAL_AMOUNT
			FROM dbo.LOANS l 
				INNER JOIN dbo.LOAN_DETAILS ld ON l.LOAN_ID = ld.LOAN_ID
				INNER JOIN dbo.LOAN_CREDIT_LINES cl ON cl.CREDIT_LINE_ID = l.CREDIT_LINE_ID
			WHERE l.CREDIT_LINE_ID IS NOT NULL AND l.STATE BETWEEN 20 AND 254
			GROUP BY l.CREDIT_LINE_ID
		) B ON lcl.CREDIT_LINE_ID = B.CREDIT_LINE_ID
	INNER JOIN dbo.CLIENTS C ON C.CLIENT_NO = lcl.CLIENT_NO
GO
