SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_OP_WRITEDOFF_FORGIVE]
AS
SELECT
		OP_ID,
		LOAN_ID,
		OP_DATA.value('(row/@WRITEOFF_PRINCIPAL)[1]', 'money') AS WRITEOFF_PRINCIPAL,
		OP_DATA.value('(row/@WRITEOFF_PRINCIPAL_ORG)[1]', 'money') AS WRITEOFF_PRINCIPAL_ORG,
		OP_DATA.value('(row/@WRITEOFF_PERCENT)[1]', 'money') AS WRITEOFF_PERCENT,
		OP_DATA.value('(row/@WRITEOFF_PERCENT_ORG)[1]', 'money') AS WRITEOFF_PERCENT_ORG,
		OP_DATA.value('(row/@WRITEOFF_PENALTY)[1]', 'money') AS WRITEOFF_PENALTY,
		OP_DATA.value('(row/@WRITEOFF_PENALTY_ORG)[1]', 'money') AS WRITEOFF_PENALTY_ORG,
		OP_DATA.value('(row/@WRITEOFF_PRINCIPAL_PENALTY)[1]', 'money') AS WRITEOFF_PRINCIPAL_PENALTY,
		OP_DATA.value('(row/@WRITEOFF_PRINCIPAL_PENALTY_ORG)[1]', 'money') AS WRITEOFF_PRINCIPAL_PENALTY_ORG,
		OP_DATA.value('(row/@WRITEOFF_PERCENT_PENALTY)[1]', 'money') AS WRITEOFF_PERCENT_PENALTY,
		OP_DATA.value('(row/@WRITEOFF_PERCENT_PENALTY_ORG)[1]', 'money') AS WRITEOFF_PERCENT_PENALTY_ORG,
		OP_DATA.value('(row/@SUM_NEW)[1]', 'money') AS SUM_NEW,
		OP_DATA.value('(row/@SUM_ORG)[1]', 'money') AS SUM_ORG
	FROM dbo.LOAN_OPS
	WHERE OP_TYPE = dbo.loan_const_op_writedoff_forgive()
GO
