SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_DEPOS]
AS

SELECT DX.DEPO_ID, DX.BRANCH_ID, DX.DEPT_NO, DX.CLIENT_NO, DX.DEPO_NO, 
	DX.DEPO_TYPE_ID, DX.PROD_ID, P.PROD_NO, DX.START_DATE AS REG_DT, DX.START_DATE, 
	DX.ACC_ID, A.ACCOUNT, DX.ISO, DX.PROLONGATION, DX.CONVERTED_DEPOSIT, DX.REALIZE_ADVANCE, DX.REALIZE_ADV_ACC_ID, 
	DATEDIFF(day, DX.START_DATE, D.END_DATE) AS PERIOD,
	D.OP_ID, D.REC_STATE, D.AMOUNT, D.INT_RATE, D.ACCUMULATE, D.INC_AMOUNT, D.MAX_AMOUNT, 
	D.OFFICER_ID, D.COMMENTS, D.END_DATE, D.MOVE_COUNT, D.MOVE_COUNT_TYPE, D.CALC_TYPE, D.FORMULA,
	D.CLIENT_ACCOUNT, D.PERC_CLIENT_ACCOUNT, D.PERC_BANK_ACCOUNT, D.DAYS_IN_YEAR, D.CALC_AMOUNT,
	D.TOTAL_CALC_AMOUNT, D.TOTAL_PAYED_AMOUNT, D.LAST_CALC_DATE, D.LAST_MOVE_DATE, D.PERC_FLAGS,
	D.PERC_TYPE, D.TAX_RATE, D.START_DATE_TYPE, D.START_DATE_DAYS, D.DATE_TYPE, A1.ACCOUNT AS CLIENT_ACCOUNT_B
FROM dbo.DEPO_DATA D
	INNER JOIN dbo.DEPOS DX ON D.OP_ID = DX.OP_ID
	INNER JOIN dbo.ACCOUNTS A ON A.ACC_ID = DX.ACC_ID
	LEFT OUTER JOIN dbo.ACCOUNTS A1 ON A1.ACC_ID = D.CLIENT_ACCOUNT
	LEFT OUTER JOIN dbo.DEPO_PRODUCTS P ON P.PROD_ID = DX.PROD_ID
	LEFT OUTER JOIN dbo.ACCOUNTS A2 ON A2.ACC_ID = DX.REALIZE_ADV_ACC_ID
	LEFT OUTER JOIN dbo.ACCOUNTS A3 ON A3.ACC_ID = D.PERC_CLIENT_ACCOUNT
	LEFT OUTER JOIN dbo.ACCOUNTS A4 ON A4.ACC_ID = D.PERC_BANK_ACCOUNT
GO
