SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_COLLATERAL_DETAILS_EQUIP]
AS
	SELECT 
		COLLATERAL_ID,
		COLLATERAL_DETAILS.value('(row/@ITEM_ID)[1]', 'int') AS ITEM_ID
	FROM dbo.LOAN_COLLATERALS
	WHERE COLLATERAL_TYPE = 4 
GO
