SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[VW_USER_LOG]
AS
	SELECT L.*, A.NAME AS [APP_NAME] FROM dbo.USER_LOG L 
		INNER JOIN dbo.APPLICATIONS A (NOLOCK) ON L.APP_URI = A.URI
GO
