SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DOCS_ARC]
AS
 
SELECT D.*, AD.ACCOUNT AS DEBIT, AC.ACCOUNT AS CREDIT
FROM dbo.OPS_ARC D (NOLOCK)
 INNER JOIN dbo.ACCOUNTS AD (NOLOCK) ON AD.ACC_ID = D.DEBIT_ID
 INNER JOIN dbo.ACCOUNTS AC (NOLOCK) ON AC.ACC_ID = D.CREDIT_ID
GO
