SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VAL_RATES_OLD] ASSELECT * FROM dbo.VAL_RATES_2009 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2010 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2011 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2012 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2013 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2014 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2015 (NOLOCK)  UNION ALLSELECT * FROM dbo.VAL_RATES_2016 (NOLOCK)
GO
