SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_OP_PENALTY_FORGIVE]
AS
	SELECT
		OP_ID,
		LOAN_ID,
		ISNULL(OP_DATA.value('(row/@OVERDUE_PRINCIPAL_PENALTY)[1]', 'money'), $0.00) AS OVERDUE_PRINCIPAL_PENALTY,
		ISNULL(OP_DATA.value('(row/@OVERDUE_PERCENT_PENALTY)[1]', 'money'), $0.00) AS OVERDUE_PERCENT_PENALTY,
		ISNULL(OP_DATA.value('(row/@CALLOFF_PRINCIPAL_PENALTY)[1]', 'money'), $0.00) AS CALLOFF_PRINCIPAL_PENALTY,
		ISNULL(OP_DATA.value('(row/@CALLOFF_PERCENT_PENALTY)[1]', 'money'), $0.00) AS CALLOFF_PERCENT_PENALTY,
		ISNULL(OP_DATA.value('(row/@WRITEOFF_PRINCIPAL_PENALTY)[1]', 'money'), $0.00) AS WRITEOFF_PRINCIPAL_PENALTY,
		ISNULL(OP_DATA.value('(row/@WRITEOFF_PERCENT_PENALTY)[1]', 'money'), $0.00) AS WRITEOFF_PERCENT_PENALTY,
		ISNULL(OP_DATA.value('(row/@PENALTY_SUM)[1]', 'money'), $0.00) AS PENALTY_SUM,
		ISNULL(OP_DATA.value('(row/@OLD_OV_PRINC_PENALTY)[1]', 'money'), $0.00) AS OLD_OV_PRINC_PENALTY,
		ISNULL(OP_DATA.value('(row/@OLD_OV_PERC_PENALTY)[1]', 'money'), $0.00) AS OLD_OV_PERC_PENALTY,
		ISNULL(OP_DATA.value('(row/@OLD_CL_PRINC_PENALTY)[1]', 'money'), $0.00) AS OLD_CL_PRINC_PENALTY,
		ISNULL(OP_DATA.value('(row/@OLD_CL_PERC_PENALTY)[1]', 'money'), $0.00) AS OLD_CL_PERC_PENALTY,
		ISNULL(OP_DATA.value('(row/@OLD_WR_PRINC_PENALTY)[1]', 'money'), $0.00) AS OLD_WR_PRINC_PENALTY,
		ISNULL(OP_DATA.value('(row/@OLD_WR_PERC_PENALTY)[1]', 'money'), $0.00) AS OLD_WR_PERC_PENALTY,
		ISNULL(OP_DATA.value('(row/@OLD_PENALTY_SUM)[1]', 'money'), $0.00) AS OLD_PENALTY_SUM,
		ISNULL(OP_DATA.value('(row/@STATE)[1]', 'int'), dbo.loan_const_state_current()) AS [STATE]
	FROM dbo.LOAN_OPS
	WHERE OP_TYPE = dbo.loan_const_op_penalty_forgive()
GO
