SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[LOAN_VW_LOANS_HISTORY]
AS
SELECT L.OP_ID, O.OP_DATE, L.LOAN_ID, L.ROW_VERSION, L.BRANCH_ID, L.DEPT_NO, L.AUTHORIZE_LEVEL, L.STATE, L.CLIENT_NO,
	L.CREDIT_LINE_ID, L.PRODUCT_ID, L.AGREEMENT_NO, L.REG_DATE, L.LOAN_TYPE, L.DISBURSE_TYPE, L.ENSURE_TYPE,
	L.INSTALLMENT, L.EVENT_INSTALLMENT, L.RESTRUCTURED, L.PROLONGED, L.ISO, L.AMOUNT, L.DISBURSE_AMOUNT, L.START_DATE, L.PERIOD, L.END_DATE,
    L.INTRATE, L.PENALTY_INTRATE, L.PREPAYMENT_INTRATE, L.PREPAYMENT_STEP, L.NOTUSED_INTRATE, L.ADMIN_INTRATE, L.ADMIN_FEE,
	L.RISK_TYPE, L.RISK_PERC_RATE_1, L.RISK_PERC_RATE_2, L.RISK_PERC_RATE_3, L.RISK_PERC_RATE_4, L.RISK_PERC_RATE_5, 
	L.WRITEOFF_DATE, L.INTEREST_FLAGS, L.PENALTY_FLAGS, L.PREPAYMENT_FLAGS, L.PAYMENT_INTERVAL_TYPE, L.SCHEDULE_TYPE, L.PAYMENT_DAY,
	L.RESERVE_MAX_CATEGORY, L.INSTALLMENT_PERCENT, L.GRACE_STEPS, L.GRACE_TYPE, L.BASIS, L.RESPONSIBLE_USER_ID, L.CORESPONSIBLE_USER_ID, L.PURPOSE_TYPE, L.BAL_ACC, L.GROUP_ID, L.MAIN_COLLATERAL_LIST, L.CLIENT_ACCOUNT
FROM dbo.LOANS_HISTORY L (NOLOCK)
	INNER JOIN dbo.LOAN_OPS O (NOLOCK) ON O.OP_ID = L.OP_ID

GO
