SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DOCS_ARC_CONV]
AS
SELECT CASE WHEN D.PARENT_REC_ID > 0 THEN D.PARENT_REC_ID ELSE D.REC_ID END AS OP_NUM,
	D.REC_ID, D.PARENT_REC_ID, D.UID, D.DOC_DATE, D.AMOUNT, D.ISO, D.FLAGS, D.RELATION_ID,
	B.AMOUNT AS AMOUNT1, B.ISO AS ISO1, C.AMOUNT AS AMOUNT2,
	D.DOC_TYPE, D.DOC_NUM, D.OP_CODE, AD.ACCOUNT AS DEBIT, D.DEBIT_ID, AC.ACCOUNT AS CREDIT, B.CREDIT_ID, D.REC_STATE, D.BNK_CLI_ID, D.DESCRIP, D.OWNER, D.ACCOUNT_EXTRA, D.PROD_ID, D.FOREIGN_ID, D.CHANNEL_ID, D.DEPT_NO, D.IS_SUSPICIOUS,
	V.RATE_ITEMS, V.RATE_AMOUNT, V.RATE_REVERSE, V.RATE_FLAGS, V.LAT_DESCRIP, V.TARIFF_KIND, V.CLIENT_NO, V.RATE_CLIENT_NO,
CONVERT (bit, CASE WHEN V.RATE_FLAGS & 8 <> 0 THEN 1 ELSE 0 END) AS RATE_CHANGED 
FROM dbo.OPS_ARC D (NOLOCK)
	INNER JOIN dbo.OPS_ARC B(NOLOCK) ON B.PARENT_REC_ID = D.REC_ID AND B.DOC_TYPE = 14 AND B.DOC_DATE = D.DOC_DATE 
	LEFT JOIN dbo.OPS_ARC C(NOLOCK) ON C.PARENT_REC_ID = D.REC_ID AND C.DOC_TYPE = 16 AND C.DOC_DATE = D.DOC_DATE
	INNER JOIN dbo.ACCOUNTS AD (NOLOCK) ON AD.ACC_ID = D.DEBIT_ID
	INNER JOIN dbo.ACCOUNTS AC (NOLOCK) ON AC.ACC_ID = B.CREDIT_ID
	INNER JOIN dbo.DOC_DETAILS_ARC_CONV V(NOLOCK) ON V.DOC_REC_ID = D.REC_ID
WHERE D.DOC_TYPE = 20
GO
