SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_DATA_WITHDRAW]
AS
	SELECT
		OP_ID,
		DEPO_ID,		
		OP_DATA.value('(row/@DEPO_REALIZE_ACC_ID)[1]', 'int') AS DEPO_REALIZE_ACC_ID,
		OP_DATA.value('(row/@PREV_AMOUNT)[1]', 'money') AS PREV_AMOUNT,
		OP_DATA.value('(row/@MAX_SPEND_AMOUNT)[1]', 'money') AS MAX_SPEND_AMOUNT,
		OP_DATA.value('(row/@CHANGE_SPEND_CONST_AMOUNT)[1]', 'bit') AS CHANGE_SPEND_CONST_AMOUNT,
		OP_DATA.value('(row/@PREV_SPEND_CONST_AMOUNT)[1]', 'money') AS PREV_SPEND_CONST_AMOUNT,
		OP_DATA.value('(row/@CHANGE_FORMULA)[1]', 'bit') AS CHANGE_FORMULA,
		OP_DATA.value('(row/@PREV_FORMULA)[1]', 'varchar(255)') AS PREV_FORMULA

	FROM dbo.DEPO_OP
	WHERE OP_TYPE = dbo.depo_fn_const_op_withdraw()
GO
