SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[depo_unauthorized_docs]
AS
SELECT O.*
FROM dbo.DEPO_DEPOSITS D (NOLOCK)
	INNER JOIN dbo.OPS_HELPER_0000 H (NOLOCK) ON (H.ACC_ID = D.DEPO_ACC_ID)
	INNER JOIN dbo.DOCS_ALL O (NOLOCK) ON (O.REC_ID = H.REC_ID)
	LEFT OUTER JOIN dbo.DEPO_OP DO (NOLOCK) ON (DO.DEPO_ID = D.DEPO_ID) AND ((H.REC_ID = DO.DOC_REC_ID) OR (O.PARENT_REC_ID = DO.DOC_REC_ID))
WHERE (O.DOC_TYPE <> 16) AND (D.STATE > 40) AND (D.STATE < 240) AND (O.REC_STATE < 20) AND (DO.OP_ID IS NULL)
GO
