SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_DEPO_PRODUCT_ANNULMENT_SCHEMA]
AS
	SELECT S.[SCHEMA_ID], S.DESCRIP, S.DATE_TYPE, S.START_POINT, D.ITEMS, D.ISO, D.INTRATE
	FROM dbo.DEPO_PRODUCT_ANNULMENT_SCHEMA S (NOLOCK)  
		INNER JOIN dbo.DEPO_PRODUCT_ANNULMENT_SCHEMA_DETAILS D (NOLOCK) ON S.[SCHEMA_ID] = D.[SCHEMA_ID]
GO
