SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_PRODUCTS]
AS
SELECT p.*, lt.DESCRIP AS LT_DESCRIP, lt.DESCRIP_LAT AS LT_DESCRIP_LAT, lrt.DESCRIP AS LRT_DESCRIP, lrt.DESCRIP_LAT AS LRT_DESCRIP_LAT
	
FROM dbo.LOAN_PRODUCTS p 
	INNER JOIN dbo.LOAN_TYPES lt ON p.LOAN_TYPE_ID=lt.TYPE_ID
    INNER JOIN dbo.LOAN_RISK_TYPES lrt ON p.RISK_TYPE=lrt.TYPE_ID
GO
