SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[BC_LOGIN_ACC_VIEW] 
AS

SELECT DISTINCT A.*, BL.FLAGS AS LOGIN_FLAGS, BLA.FLAGS AS LOGIN_ACC_FLAGS, BL.BC_LOGIN_ID
FROM dbo.BC_CLIENT_ACC_VIEW A (NOLOCK)
  INNER JOIN dbo.BC_LOGINS BL(NOLOCK) ON BL.BC_CLIENT_ID = A.BC_CLIENT_ID
  INNER JOIN dbo.BC_LOGIN_ACC BLA(NOLOCK) ON BLA.BC_LOGIN_ID = BL.BC_LOGIN_ID AND BLA.ACC_ID  = A.ACC_ID
GO
