SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[C_CLIENTS] 
AS
SELECT C.* , CT.DESCRIP + ' ' + ISNULL(CST.DESCRIP, '') AS CLIENT_TYPE_DESCRIP, 
	PT.DESCRIP AS PASSPORT_TYPE_NAME,
	CA1.ATTRIB_VALUE AS ADDRESS_FACT, 
	DP.ALIAS AS BRANCH_ALIAS, DP.ALIAS + ': ' + DP.DESCRIP AS BRANCH_NAME
FROM dbo.CLIENTS C (NOLOCK)
	INNER JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = C.DEPT_NO
	INNER JOIN dbo.CLIENT_TYPES CT (NOLOCK) ON CT.CLIENT_TYPE = C.CLIENT_TYPE
	LEFT JOIN dbo.CLIENT_SUBTYPES CST (NOLOCK) ON CST.CLIENT_TYPE = C.CLIENT_TYPE AND CST.CLIENT_SUBTYPE = C.CLIENT_SUBTYPE
	LEFT JOIN dbo.PASSPORT_TYPES PT (NOLOCK) ON PT.PASSPORT_TYPE_ID = C.PASSPORT_TYPE_ID
	LEFT JOIN dbo.CLIENT_ATTRIBUTES CA1 (NOLOCK) ON CA1.CLIENT_NO = C.CLIENT_NO AND CA1.ATTRIB_CODE = '$ADDRESS_FACT'
GO
