SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_DEPO_ANNULMENT_METHODS]
AS

SELECT M.METHOD_ID, M.METHOD_DESCRIP, M.START_DATE_TYPE, M.START_DATE_DAYS, M.DATE_TYPE, D.DAYS, D.ISO, D.PERC
FROM dbo.DEPO_ANNULMENT_METHODS M (NOLOCK)
	INNER JOIN dbo.DEPO_ANNULMENT_METHOD_DETAILS D (NOLOCK) ON M.METHOD_ID = D.METHOD_ID
GO
