SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_PURPOSE_MONITORING]
AS
SELECT
	L.REC_ID, L.LOAN_ID, L.MONITORING_DATE, L.USER_ID, RTRIM(U.USER_NAME) + '@' + D.ALIAS AS U_USER_NAME,	
	L.MONITORING_PROGRESS, L.MONITORING_SUBJECT, L.MONITORING_MEMO
FROM dbo.LOAN_PURPOSE_MONITORING L (NOLOCK)
	INNER JOIN dbo.USERS U (NOLOCK) ON U.USER_ID = L.USER_ID
	INNER JOIN dbo.DEPTS D (NOLOCK) ON D.DEPT_NO = U.DEPT_NO
GO
