SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_INTEREST_ACCRUAL_LIST]
AS
SELECT V.LOAN_ID, CONVERT(bit, 0) AS CALCED, CONVERT(bit, NULL) AS ACCRUE, V.AGREEMENT_NO, V.CLIENT_DESCRIP, V.CLIENT_DESCRIP_LAT, V.ISO,
	dbo.LOAN_FN_GET_MAX_INTEREST_ACCRUE_DATE(V.LOAN_ID) AS MAX_ACCRUE_DATE,
	B.INTEREST_DATE, 
	B.INTEREST_BALANCE, CONVERT(money, NULL) AS INTEREST_BALANCE_,
	B.OVERDUE_INTEREST_DATE, 
	B.OVERDUE_INTEREST_BALANCE,
	B.OVERDUE_INTEREST30_DATE, 
	B.OVERDUE_INTEREST30_BALANCE, CONVERT(money, NULL) AS OVERDUE_INTEREST30_BALANCE_,
	B.PENALTY_DATE, 
	B.PENALTY_BALANCE, CONVERT(money, NULL) AS PENALTY_BALANCE_,
	B.WRITEOFF_DATE, 
	B.WRITEOFF_BALANCE, CONVERT(money, NULL) AS WRITEOFF_BALANCE_,
	CONVERT(smallint, NULL) AS WHAT_ACT,
	CONVERT(money, NULL) AS INTEREST_ACCRUE
FROM dbo.LOAN_VW_LOANS V (NOLOCK)
	INNER JOIN dbo.LOAN_ACCOUNT_BALANCE B (NOLOCK) ON B.LOAN_ID = V.LOAN_ID

GO
