SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_COMMITTEE]
AS
	SELECT * 
	FROM dbo.LOAN_VW_LOANS 
	WHERE (STATE IN (0, 10) AND AUTHORIZE_LEVEL IN (10, 20)) OR
		(STATE IN (10, 20) AND AUTHORIZE_LEVEL = 20)

GO
