SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_INCASSO]
AS 

SELECT A.*, C.DESCRIP AS CLIENT_NAME, CASE WHEN ISNULL(C.TAX_INSP_CODE, '') <> '' THEN C.TAX_INSP_CODE ELSE C.PERSONAL_ID END AS TAX_CODE_OR_PID,
	CASE WHEN A.BALANCE > $0.00 THEN
		(SELECT SUM(dbo.acc_get_incasso_usable_amount(IA.ACC_ID) - CASE WHEN IA.AMOUNT < $0.00 THEN IA.AMOUNT ELSE $0.00 END) FROM dbo.INCASSO_ACCOUNTS IA WHERE IA.INCASSO_ID = A.REC_ID)
	ELSE
		NULL
	END AS USABLE_AMOUNT
FROM dbo.INCASSO A
	INNER JOIN dbo.CLIENTS C ON A.CLIENT_NO = C.CLIENT_NO
GO
