SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_LOAN_OP_PENALTY_STOP]
AS
	SELECT
		OP_ID,
		LOAN_ID,
		OP_DATA.value('(row/@OLD_PENALTY_FLAGS)[1]', 'int') AS OLD_PENALTY_FLAGS,
		OP_DATA.value('(row/@NEW_PENALTY_FLAGS)[1]', 'int') AS NEW_PENALTY_FLAGS
	FROM dbo.LOAN_OPS
	WHERE OP_TYPE = dbo.loan_const_op_penalty_stop()
GO
