SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_DATA_ALLOW_PROLONGATION]
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_DATA.value('(row/@PREV_PROLONGABLE)[1]', 'bit') AS PREV_PROLONGABLE,
		OP_DATA.value('(row/@PREV_PROLONGATION_COUNT)[1]', 'int') AS PREV_PROLONGATION_COUNT,
		OP_DATA.value('(row/@PROLONGABLE)[1]', 'bit') AS PROLONGABLE,
		OP_DATA.value('(row/@PROLONGATION_COUNT)[1]', 'int') AS PROLONGATION_COUNT
	FROM dbo.DEPO_OP
	WHERE OP_TYPE = dbo.depo_fn_const_op_allow_prolongation()
GO
