SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_DATA_COMMON]
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_DATA.value('(row/@ARCHIVE_DEPOSIT)[1]', 'bit') AS ARCHIVE_DEPOSIT,
		OP_DATA.value('(row/@ACCRUE_DEPOSIT)[1]', 'bit') AS ACCRUE_DEPOSIT
	FROM dbo.DEPO_OP
GO
