SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE  VIEW [dbo].[BC_CLIENT_ACC_VIEW] 
AS

SELECT A.ACC_ID, A.DEPT_NO, A.ACCOUNT, A.ISO, A.BAL_ACC_ALT, A.ACT_PAS, A.REC_STATE, A.DESCRIP, A.DESCRIP_LAT, A.ACC_TYPE,  A.ACC_SUBTYPE,  A.FLAGS AS ACC_FLAGS, A.CLIENT_NO, B.BC_CLIENT_ID
FROM dbo.ACCOUNTS A (NOLOCK)
  INNER JOIN dbo.BC_CLIENT_CLIENTS B (NOLOCK) ON B.CLIENT_NO = A.CLIENT_NO
WHERE A.FLAGS & 4 = 0 /* not hidden */
GO
