SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_COMMON_ACCOUNT_TEMPLATES]
AS
	SELECT A.ACC_TYPE_ID, A.PARENT_ACC_TYPE_ID, B.CODE, P.CODE AS PARENT_CODE, B.DESCRIP, B.DESCRIP_LAT, A.TEMPLATE
	FROM dbo.LOAN_COMMON_ACCOUNT_TEMPLATES A (NOLOCK)
	LEFT OUTER JOIN	dbo.LOAN_ACCOUNT_TYPES P (NOLOCK) ON P.TYPE_ID=A.PARENT_ACC_TYPE_ID
	INNER JOIN dbo.LOAN_ACCOUNT_TYPES B (NOLOCK) ON A.ACC_TYPE_ID=B.TYPE_ID
GO
