SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[SALDOS] ASSELECT * FROM dbo.SALDOS_2009 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2010 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2011 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2012 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2013 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2014 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2015 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2016 (NOLOCK)  UNION ALLSELECT * FROM dbo.SALDOS_2017 (NOLOCK)
GO
