SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[BRANCHES_BAL_ALT]
AS

SELECT D.DEPT_NO, D.DATABASE_ID, D.DESCRIP + 
	ISNULL (' (' + CONVERT(varchar(20), (SELECT MAX(B.DT) FROM dbo.BALANCES B (NOLOCK) WHERE B.BRANCH_ID = D.DEPT_NO AND B.DT > GETDATE() - 30), 103) + ')', '') AS DESCRIP
FROM dbo.DEPTS D (NOLOCK)
WHERE IS_DEPT = 0 
GO
