SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[SO_TASK_DEBIT_ACCOUNTS_VIEW]
AS
	SELECT t.TASK_ID, t.ACC_ID, t.PRIORITY, t.AMOUNT, t.IS_PERCENT, t.EQU_ISO, a.ACCOUNT, a.DESCRIP, a.ISO, t.IS_MASTER_ACC, t.IS_HELPER_ACC
	FROM dbo.SO_TASK_DEBIT_ACCOUNTS (NOLOCK) t
		INNER JOIN dbo.ACCOUNTS (NOLOCK) a ON t.ACC_ID = a.ACC_ID
GO
