SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[OPS_FULL] ASSELECT * FROM dbo.OPS_0000  UNION ALLSELECT * FROM dbo.OPS_2009 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2010 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2011 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2012 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2013 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2014 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2015 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2016 (NOLOCK)  UNION ALLSELECT * FROM dbo.OPS_2017 (NOLOCK)
GO
