SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_CREDIT_LINE_COBORROWERS]
AS
	SELECT 
		A.*, B.DESCRIP, B.DESCRIP_LAT
	FROM dbo.LOAN_CREDIT_LINE_COBORROWERS A
	INNER JOIN dbo.CLIENTS B ON A.CLIENT_NO = B.CLIENT_NO
GO
