SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOAN_VW_RISK_ACCRUAL_LIST]
AS
SELECT V.LOAN_ID, CONVERT(bit, 0) AS CALCED, CONVERT(bit, NULL) AS ACCRUE, V.AGREEMENT_NO, V.CLIENT_DESCRIP, V.CLIENT_DESCRIP_LAT, V.ISO, B.RISK_CATEGORY_DATE, 
	B.RISK_CATEGORY_BALANCE, CONVERT(money, NULL) AS RISK_CATEGORY_BALANCE_,
	B.RISK_CATEGORY_1_BALANCE, CONVERT(money, NULL) AS RISK_CATEGORY_1_BALANCE_,
	B.RISK_CATEGORY_2_BALANCE, CONVERT(money, NULL) AS RISK_CATEGORY_2_BALANCE_,
	B.RISK_CATEGORY_3_BALANCE, CONVERT(money, NULL) AS RISK_CATEGORY_3_BALANCE_,
	B.RISK_CATEGORY_4_BALANCE, CONVERT(money, NULL) AS RISK_CATEGORY_4_BALANCE_,
	B.RISK_CATEGORY_5_BALANCE, CONVERT(money, NULL) AS RISK_CATEGORY_5_BALANCE_,
	CONVERT(smallint, NULL) AS WHAT_ACT,
	CONVERT(money, NULL) AS RISK_ACCRUE
FROM dbo.LOAN_VW_LOANS V (NOLOCK)
	INNER JOIN dbo.LOAN_ACCOUNT_BALANCE B ON B.LOAN_ID = V.LOAN_ID
GO
