SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[DEPO_VW_DEPO_LIST]
AS
	SELECT DP.ALIAS AS BRANCH_ALIAS, DP.ALIAS + ': ' + DP.DESCRIP AS BRANCH_NAME,
		D.CLIENT_NO, C.DESCRIP AS CLIENT_DESCRIP, C.CLIENT_TYPE, D.DEPO_ID, D.ROW_VERSION, D.BRANCH_ID, D.DEPT_NO, D.STATE, D.ALARM_STATE, D.PROD_ID, P.CODE AS PROD_CODE,
		D.AGREEMENT_NO, D.DEPO_TYPE, D.DEPO_ACC_SUBTYPE, D.DEPO_ACCOUNT_STATE, DC.ACCOUNT, D.ISO, D.AGREEMENT_AMOUNT, D.AMOUNT, D.DATE_TYPE, D.PERIOD, D.START_DATE, D.END_DATE,
		CASE WHEN D.END_DATE IS NULL THEN NULL ELSE DATEDIFF(DAY, D.START_DATE, D.END_DATE) END AS DAY_PERIOD,
		D.ANNULMENT_DATE, D.INTRATE, D.REAL_INTRATE, D.PERC_FLAGS, D.DAYS_IN_YEAR, D.PROD_ACCRUE_MIN, D.PROD_ACCRUE_MAX, D.PROD_SPEND_MIN, D.PROD_SPEND_MAX, D.FORMULA,
		D.TRUST_DEPOSIT, D.TRUST_CLIENT_NO, D.TRUST_EXTRA_INFO,	D.INTRATE_SCHEMA, D.ACCRUE_TYPE, D.RECALCULATE_TYPE, D.REALIZE_SCHEMA, D.REALIZE_TYPE, D.REALIZE_COUNT,
		D.REALIZE_COUNT_TYPE, D.DEPO_REALIZE_SCHEMA, D.DEPO_REALIZE_SCHEMA_AMOUNT, D.CONVERTIBLE, D.PROLONGABLE, D.PROLONGATION_COUNT, D.RENEWABLE, D.RENEW_CAPITALIZED,
		D.RENEW_MAX, D.RENEW_COUNT, D.RENEW_LAST_PROD_ID, D.LAST_RENEW_DATE, D.SHAREABLE, D.SHARED_CONTROL_CLIENT_NO, D.SHARED_CONTROL, D.REVISION_SCHEMA, D.REVISION_TYPE,
		D.REVISION_COUNT, D.REVISION_COUNT_TYPE, D.REVISION_GRACE_ITEMS, D.REVISION_GRACE_DATE_TYPE, D.ANNULMENTED, D.ANNULMENT_REALIZE, D.ANNULMENT_SCHEMA, D.ANNULMENT_SCHEMA_ADVANCE,
		D.INTEREST_REALIZE_ADV,	D.INTEREST_REALIZE_ADV_AMOUNT, D.CHILD_DEPOSIT, D.CHILD_CONTROL_OWNER, D.CHILD_CONTROL_CLIENT_NO_1, D.CHILD_CONTROL_CLIENT_NO_2, D.ACCUMULATIVE,
		D.ACCUMULATE_PRODUCT, D.ACCUMULATE_MIN, D.ACCUMULATE_MAX, D.ACCUMULATE_AMOUNT, D.ACCUMULATE_MAX_AMOUNT_LIMIT, D.ACCUMULATE_MAX_AMOUNT, D.ACCUMULATE_SCHEMA_INTRATE, D.SPEND,
		D.SPEND_INTRATE, D.SPEND_AMOUNT, D.SPEND_AMOUNT_INTRATE, D.SPEND_CONST_AMOUNT, D.DEPO_REALIZE_TYPE, D.CREDITCARD_BALANCE_CHECK, D.INTEREST_REALIZE_TYPE, D.DEPO_FILL_ACC_ID,
		D.DEPO_ACC_ID, D.LOSS_ACC_ID, D.ACCRUAL_ACC_ID, D.DEPO_REALIZE_ACC_ID, D.INTEREST_REALIZE_ACC_ID, D.INTEREST_REALIZE_ADV_ACC_ID, D.RESPONSIBLE_USER_ID, D.DEPO_NOTE, D.ALARM_NOTE,
		D.DEPOSIT_DEFAULT, RTRIM(U.USER_NAME) + '@' + DP_U.ALIAS AS RESPONSIBLE_USER
	FROM dbo.DEPO_DEPOSITS D (NOLOCK)
		LEFT JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = D.DEPT_NO
		INNER JOIN dbo.DEPO_PRODUCT P (NOLOCK) ON D.PROD_ID = P.PROD_ID		
		INNER JOIN dbo.CLIENTS C (NOLOCK) ON D.CLIENT_NO = C.CLIENT_NO
		INNER JOIN dbo.ACCOUNTS DC (NOLOCK) ON D.DEPO_ACC_ID = DC.ACC_ID
		INNER JOIN dbo.USERS U ON D.RESPONSIBLE_USER_ID = U.[USER_ID]
		INNER JOIN dbo.DEPTS DP_U (NOLOCK) ON DP_U.DEPT_NO = U.DEPT_NO

GO
