SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[C_NON_CLIENTS] 
AS

SELECT C.*, PT.DESCRIP AS PASSPORT_TYPE_NAME
FROM dbo.OTHER_CLIENT_INFO C (NOLOCK)
	LEFT JOIN dbo.PASSPORT_TYPES PT (NOLOCK) ON PT.PASSPORT_TYPE_ID = C.PASSPORT_TYPE_ID
GO
