SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DOCS_ARC_KASCHE]
AS
 
SELECT D.*, 
	ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,'') AS CLIENT_NAME
FROM dbo.DOCS_ARC_ALL D (NOLOCK)
	LEFT OUTER JOIN dbo.DOC_DETAILS_ARC_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_ID
WHERE D.DOC_TYPE BETWEEN 140 AND 149
GO
