SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DEPO_VW_OP_DATA_CHANGE_INTEREST_REALIZE_ACCOUNT]
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_DATA.value('(row/@OLD_INTEREST_REALIZE_ACC_ID)[1]', 'int') AS OLD_INTEREST_REALIZE_ACC_ID,
		OP_DATA.value('(row/@NEW_INTEREST_REALIZE_ACC_ID)[1]', 'int') AS NEW_INTEREST_REALIZE_ACC_ID
	FROM dbo.DEPO_OP
	WHERE OP_TYPE = dbo.depo_fn_const_op_change_interest_realize_account()
GO
