SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[SO_PROCESS_CHANGES_VIEW]
AS
SELECT C.TASK_ID, C.DATE, NULL AS [VERSION], C.USER_ID, C.FIELD, C.OLD_VALUE, C.NEW_VALUE, C.OLD_DISPLAY_VALUE, C.NEW_DISPLAY_VALUE, C.TIME_OF_CHANGE
FROM dbo.SO_SCHEDULES S 
	INNER JOIN dbo.SO_SCHEDULE_CHANGES C ON C.TASK_ID = S.TASK_ID AND C.DATE = S.DATE

UNION ALL	
	
SELECT C.*
FROM dbo.SO_SCHEDULE_ANULLS S 
	INNER JOIN dbo.SO_SCHEDULE_ANULL_CHANGES C ON C.TASK_ID = S.TASK_ID AND C.DATE = S.DATE AND C.VERSION = S.VERSION
GO
