SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [impexp].[V_DOCS_IN_SWIFT_ARC] AS
SELECT D.*, 
	A.DESCRIP_LAT AS ACCOUNT_NAME,
	A.ACC_TYPE, AT.DESCRIP + ' ' + ISNULL(AST.DESCRIP,'') AS ACC_DESCRIP,
	C.DESCRIP_LAT AS CLIENT_NAME, A.CLIENT_NO,
	DP.ALIAS AS BRANCH_ALIAS,
	PS.STATE AS PORTION_STATE,
	CB.BIC AS FINALYZE_BIC, AF.ACCOUNT AS FINALYZE_ACCOUNT,
	ISNULL(I.PORTION_ALIAS, D.PORTION) AS PORTION_ALIAS
FROM impexp.DOCS_IN_SWIFT_ARC D
	LEFT JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = D.ACC_ID
	LEFT JOIN dbo.ACCOUNTS AF (NOLOCK) ON AF.ACC_ID = D.FINALYZE_ACC_ID
	LEFT JOIN dbo.CLIENTS C (NOLOCK) ON C.CLIENT_NO = A.CLIENT_NO
	LEFT JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = A.DEPT_NO
	LEFT JOIN dbo.ACC_TYPES AT (NOLOCK) ON AT.ACC_TYPE = A.ACC_TYPE
	LEFT JOIN dbo.ACC_SUBTYPES AST (NOLOCK) ON AST.ACC_TYPE = A.ACC_TYPE AND AST.ACC_SUBTYPE = A.ACC_SUBTYPE
	INNER JOIN impexp.PORTIONS_IN_SWIFT_ARC PS ON PS.PORTION_DATE = D.PORTION_DATE AND PS.PORTION = D.PORTION
	LEFT OUTER JOIN dbo.CORRESPONDENT_BANKS CB (NOLOCK) ON CB.REC_ID = D.FINALYZE_BANK_ID
	LEFT JOIN impexp.PORTIONS_IN_SWIFT_INFO I ON I.PORTION = D.PORTION
GO
