SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE  VIEW [impexp].[V_STATEMENT_CLIENTS_INSTITUTIONS]
AS
SELECT V.CLIENT_NO, V.CLIENT_CODE, V.BRANCH_ALIAS, V.BRANCH_NAME, V.DESCRIP_LAT, I.RECEIVER_INSTITUTION, I.RECEIVER_INSTITUTION_NAME, I.IS_ACTIVE
FROM impexp.V_STATEMENT_CLIENTS V (NOLOCK) 
	INNER JOIN impexp.STATEMENT_CLIENTS_INSTITUTIONS I (NOLOCK) ON V.CLIENT_NO = I.CLIENT_NO
GO
