SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE  VIEW [impexp].[V_PORTIONS_OUT_NBG] AS

SELECT P.*, PS.NAME_GEO AS STATE_NAME_GEO, PS.NAME_LAT AS STATE_NAME_LAT
FROM impexp.PORTIONS_OUT_NBG P
	INNER JOIN impexp.PORTION_STATES PS ON PS.STATE = P.STATE

GO
