SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [impexp].[V_STATEMENT_CLIENTS2]
AS
SELECT DISTINCT C.*
FROM dbo.CLIENTS C (NOLOCK)
	INNER JOIN impexp.STATEMENT_CLIENTS S (NOLOCK) ON C.CLIENT_NO = S.CLIENT_NO
	LEFT OUTER JOIN impexp.STATEMENT_CLIENTS_INSTITUTIONS I (NOLOCK) ON I.CLIENT_NO = S.CLIENT_NO AND I.IS_ACTIVE = 1
WHERE I.CLIENT_NO IS NOT NULL
GO
