SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [impexp].[V_DOCS_OUT_SWIFT]
AS
SELECT A.DOC_REC_ID, A.UID, A.DOC_DATE, A.PORTION_DATE, A.PORTION, ISNULL(B.PORTION_ALIAS, A.PORTION) AS PORTION_ALIAS, A.OLD_FLAGS, 
	A.ISO, A.AMOUNT, A.AMOUNT_EQU, A.DOC_CREDIT_ID, A.REF_NUM, A.DESCRIP, 
	A.SENDER_BANK_CODE, A.SENDER_BANK_NAME, A.SENDER_ACC, A.SENDER_ACC_NAME, A.SENDER_ADDRESS_LAT, 
	A.RECEIVER_BANK_CODE, A.RECEIVER_BANK_NAME, A.RECEIVER_ACC, A.RECEIVER_ACC_NAME, A.RECEIVER_ADDRESS_LAT,
	A.INTERMED_BANK_CODE, A.INTERMED_BANK_NAME, A.INTERMED_BANK_CODE2, A.INTERMED_BANK_NAME2, A.CORRESPONDENT_BANK_ID, CR.BIC AS CORR_BIC, CR.ISO AS CORR_ISO, CR.DESCRIP AS CORR_DESCRIP, CR.NOSTRO_ACCOUNT AS CORR_NOSTRO_ACCOUNT, CR.LORO_ACCOUNT AS CORR_LORO_ACCOUNT,
	A.EXTRA_INFO, A.EXTRA_INFO_DESCRIP, A.DET_OF_CHARG, 
	A.CLOSE_TIME, A.EXPORT_TIME, A.FINISH_TIME, 
	A.FINALYZE_DATE, A.FINALYZE_BANK_ID, FN.BIC AS FIN_BIC, FN.ISO AS FIN_ISO, FN.DESCRIP AS FIN_DESCRIP, FN.NOSTRO_ACCOUNT AS FIN_NOSTRO_ACCOUNT, FN.LORO_ACCOUNT AS FIN_LORO_ACCOUNT,
	A.FINALYZE_ACC_ID, A.FINALYZE_AMOUNT, A.FINALYZE_ISO, A.FINALYZE_DOC_REC_ID, 
	A.SWIFT_FILENAME, A.STATE, A.SWIFT_FLAGS_1, A.SWIFT_FLAGS_2, A.OP_CODE
FROM impexp.DOCS_OUT_SWIFT A
	LEFT JOIN impexp.PORTIONS_OUT_SWIFT_INFO B ON B.PORTION = A.PORTION
	LEFT OUTER JOIN dbo.CORRESPONDENT_BANKS CR ON CR.REC_ID = A.CORRESPONDENT_BANK_ID
	LEFT OUTER JOIN dbo.CORRESPONDENT_BANKS FN ON FN.REC_ID = A.FINALYZE_BANK_ID
GO
