SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE  VIEW [impexp].[V_PORTIONS_IN_NBG] AS
SELECT P.*, PS.NAME_GEO AS STATE_NAME_GEO, PS.NAME_LAT AS STATE_NAME_LAT
FROM impexp.PORTIONS_IN_NBG P
	INNER JOIN impexp.PORTION_STATES PS ON PS.STATE = P.STATE

GO
