SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [impexp].[V_STATEMENT_CLIENTS]
AS
SELECT S.CLIENT_NO, S.CLIENT_CODE, DP.ALIAS AS BRANCH_ALIAS, DP.ALIAS + ': ' + DP.DESCRIP AS BRANCH_NAME,
	C.DESCRIP, C.DESCRIP_LAT
FROM impexp.STATEMENT_CLIENTS S (NOLOCK) 
	INNER JOIN	dbo.CLIENTS C (NOLOCK) ON C.CLIENT_NO = S.CLIENT_NO
	INNER JOIN dbo.DEPTS DP (NOLOCK) ON DP.DEPT_NO = C.DEPT_NO
GO
