SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [impexp].[V_STATEMENTS]
AS
SELECT S.REC_ID, S.UID, S.STATE, S.CREATE_DT, S.CLIENT_NO, C.DESCRIP AS CLIENT_DESCRIP, A.ISO, S.ACC_ID, A.ACCOUNT, 
	A.DESCRIP AS ACC_DESCRIP, S.START_DATE, S.END_DATE, S.SWIFT_START_DATE, S.OWNER
FROM impexp.STATEMENTS S (NOLOCK) 
	INNER JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = S.ACC_ID 
	INNER JOIN dbo.CLIENTS C (NOLOCK) ON C.CLIENT_NO = S.CLIENT_NO
GO
