SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [impexp].[V_SWIFT_BAD_DOCS]
AS
SELECT D.*
FROM dbo.DOCS_ALL D (NOLOCK)
	INNER JOIN dbo.DOC_DETAILS_VALPLAT DD(NOLOCK) ON D.REC_ID = DD.DOC_REC_ID
	INNER JOIN dbo.ACCOUNTS A(NOLOCK) ON A.ACC_ID = D.CREDIT_ID
	LEFT OUTER JOIN dbo.INI_INT CR_ACC (NOLOCK) ON CR_ACC.IDS = 'CORR_ACC_VA' AND A.ACCOUNT = CONVERT(Decimal(15,0), CR_ACC.VALS)
	LEFT OUTER JOIN dbo.INI_INT CR_ACC2 (NOLOCK) ON CR_ACC2.IDS = 'CORR_ACC_VA2' AND A.ACCOUNT = CONVERT(Decimal(15,0), CR_ACC2.VALS)
WHERE A.BRANCH_ID = dbo.bank_head_branch_id() AND A.ISO = D.ISO AND (CR_ACC.VALS IS NOT NULL OR CR_ACC2.VALS IS NOT NULL) AND
	D.DOC_TYPE NOT IN (112,116)
GO
