SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [impexp].[V_NBG_BAD_DOCS]
AS
SELECT D.*
FROM dbo.DOCS_ALL D (NOLOCK)
	INNER JOIN dbo.DOC_DETAILS_PLAT DD(NOLOCK) ON D.REC_ID = DD.DOC_REC_ID
	INNER JOIN dbo.ACCOUNTS A(NOLOCK) ON A.ACC_ID = D.CREDIT_ID
	LEFT OUTER JOIN dbo.INI_INT CR_ACC (NOLOCK) ON CR_ACC.IDS = 'CORR_ACC_NA' AND A.ACCOUNT = CONVERT(Decimal(15,0), CR_ACC.VALS)
WHERE D.DOC_TYPE NOT IN (102,106) AND CR_ACC.VALS IS NOT NULL
GO
