SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [ivp].[DEPO_VW_OP_DATA_62]
WITH SCHEMABINDING
AS
	SELECT
		OP_ID,
		DEPO_ID,
		OP_DATA
	FROM dbo.DEPO_OP
	WHERE OP_TYPE = 62 /*dbo.depo_fn_const_op_mark2default_change_intrate_schema()*/
GO
CREATE UNIQUE CLUSTERED INDEX [IPV_IDX_DEPO_VW_OP_DATA_62] ON [ivp].[DEPO_VW_OP_DATA_62] ([OP_ID]) ON [PRIMARY]
GO
