SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_RESTORE_OPS_LOAN_DETAILS]
	@op_id int
AS
SET NOCOUNT ON
DECLARE
	@e int, 
	@r int
												
UPDATE dbo.LOAN_DETAILS
SET
	CALC_DATE							 	= V.CALC_DATE						 
	,PREV_STEP							 	= V.PREV_STEP							 
	,NU_PRINCIPAL						 	= V.NU_PRINCIPAL						 
	,NU_INTEREST						 	= V.NU_INTEREST						 	
	,NU_INTEREST_DAILY					 	= V.NU_INTEREST_DAILY					 
	,NU_INTEREST_FRACTION				 	= V.NU_INTEREST_FRACTION				 
	,PRINCIPAL							 	= V.PRINCIPAL							 
	,INTEREST							 	= V.INTEREST							 
	,INTEREST_DAILY						 	= V.INTEREST_DAILY						 
	,INTEREST_FRACTION					 	= V.INTEREST_FRACTION					 
	,LATE_DATE							 	= V.LATE_DATE							 
	,LATE_PRINCIPAL						 	= V.LATE_PRINCIPAL						 
	,LATE_PERCENT						 	= V.LATE_PERCENT						 
	,OVERDUE_DATE						 	= V.OVERDUE_DATE						 
	,OVERDUE_PRINCIPAL					 	= V.OVERDUE_PRINCIPAL					 
	,OVERDUE_PRINCIPAL_INTEREST			 	= V.OVERDUE_PRINCIPAL_INTEREST			 
	,OVERDUE_PRINCIPAL_INTEREST_DAILY	 	= V.OVERDUE_PRINCIPAL_INTEREST_DAILY	 
	,OVERDUE_PRINCIPAL_INTEREST_FRACTION 	= V.OVERDUE_PRINCIPAL_INTEREST_FRACTION 
	,OVERDUE_PRINCIPAL_PENALTY			 	= V.OVERDUE_PRINCIPAL_PENALTY			 
	,OVERDUE_PRINCIPAL_PENALTY_DAILY	 	= V.OVERDUE_PRINCIPAL_PENALTY_DAILY	 	
	,OVERDUE_PRINCIPAL_PENALTY_FRACTION	 	= V.OVERDUE_PRINCIPAL_PENALTY_FRACTION	 
	,OVERDUE_PERCENT					 	= V.OVERDUE_PERCENT					 	
	,OVERDUE_PERCENT_PENALTY			 	= V.OVERDUE_PERCENT_PENALTY			 	
	,OVERDUE_PERCENT_PENALTY_DAILY		 	= V.OVERDUE_PERCENT_PENALTY_DAILY		 
	,OVERDUE_PERCENT_PENALTY_FRACTION	 	= V.OVERDUE_PERCENT_PENALTY_FRACTION	 
	,CALLOFF_PRINCIPAL					 	= V.CALLOFF_PRINCIPAL					 
	,CALLOFF_PRINCIPAL_INTEREST			 	= V.CALLOFF_PRINCIPAL_INTEREST			 
	,CALLOFF_PRINCIPAL_INTEREST_DAILY	 	= V.CALLOFF_PRINCIPAL_INTEREST_DAILY	 
	,CALLOFF_PRINCIPAL_INTEREST_FRACTION 	= V.CALLOFF_PRINCIPAL_INTEREST_FRACTION 
	,CALLOFF_PRINCIPAL_PENALTY			 	= V.CALLOFF_PRINCIPAL_PENALTY			 
	,CALLOFF_PRINCIPAL_PENALTY_DAILY	 	= V.CALLOFF_PRINCIPAL_PENALTY_DAILY	 	
	,CALLOFF_PRINCIPAL_PENALTY_FRACTION	 	= V.CALLOFF_PRINCIPAL_PENALTY_FRACTION	 
	,CALLOFF_PERCENT					 	= V.CALLOFF_PERCENT					 	
	,CALLOFF_PERCENT_PENALTY			 	= V.CALLOFF_PERCENT_PENALTY			 	
	,CALLOFF_PERCENT_PENALTY_DAILY		 	= V.CALLOFF_PERCENT_PENALTY_DAILY		 
	,CALLOFF_PERCENT_PENALTY_FRACTION	 	= V.CALLOFF_PERCENT_PENALTY_FRACTION	 
	,CALLOFF_PENALTY					 	= V.CALLOFF_PENALTY					 	
	,WRITEOFF_PRINCIPAL					 	= V.WRITEOFF_PRINCIPAL					 
	,WRITEOFF_PRINCIPAL_PENALTY			 	= V.WRITEOFF_PRINCIPAL_PENALTY			 
	,WRITEOFF_PRINCIPAL_PENALTY_DAILY	 	= V.WRITEOFF_PRINCIPAL_PENALTY_DAILY	 
	,WRITEOFF_PRINCIPAL_PENALTY_FRACTION 	= V.WRITEOFF_PRINCIPAL_PENALTY_FRACTION 
	,WRITEOFF_PERCENT					 	= V.WRITEOFF_PERCENT					 
	,WRITEOFF_PERCENT_PENALTY			 	= V.WRITEOFF_PERCENT_PENALTY			 
	,WRITEOFF_PERCENT_PENALTY_DAILY		 	= V.WRITEOFF_PERCENT_PENALTY_DAILY		 
	,WRITEOFF_PERCENT_PENALTY_FRACTION	 	= V.WRITEOFF_PERCENT_PENALTY_FRACTION	 
	,WRITEOFF_PENALTY					 	= V.WRITEOFF_PENALTY					 
	,IMMEDIATE_PENALTY					 	= V.IMMEDIATE_PENALTY					 
	,FINE								 	= V.FINE
	,MAX_CATEGORY_LEVEL					 	= V.MAX_CATEGORY_LEVEL					 
	,CATEGORY_1							 	= V.CATEGORY_1							 
	,CATEGORY_2							 	= V.CATEGORY_2							 
	,CATEGORY_3							 	= V.CATEGORY_3							 
	,CATEGORY_4							 	= V.CATEGORY_4							 
	,CATEGORY_5							 	= V.CATEGORY_5							 
	,CATEGORY_6							 	= V.CATEGORY_6
	,OVERDUE_INSURANCE						= V.OVERDUE_INSURANCE
	,OVERDUE_SERVICE_FEE					= V.OVERDUE_SERVICE_FEE
	,DEFERABLE_INTEREST						= V.DEFERABLE_INTEREST
	,DEFERABLE_OVERDUE_INTEREST				= V.DEFERABLE_OVERDUE_INTEREST
	,DEFERABLE_PENALTY						= V.DEFERABLE_PENALTY
	,DEFERABLE_FINE							= V.DEFERABLE_FINE
	,REMAINING_FEE							= V.REMAINING_FEE
FROM dbo.LOAN_DETAILS D (ROWLOCK)
	INNER JOIN dbo.LOAN_VW_OP_LOAN_DETAILS V ON D.LOAN_ID = V.LOAN_ID
WHERE V.OP_ID = @op_id

SELECT @r = @@ROWCOUNT, @e = @@ERROR
IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
IF @r = 0 BEGIN RAISERROR('ÛÄÝÃÏÌÀ ßÉÍÀ ÃÙÉÓ ÃÀÒÉÝáÅÄÁÉÓ ÀÙÃÂÄÍÉÓ ÃÒÏÓ !',16,1) RETURN(1) END

RETURN(0)

GO
