SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[LOAN_SP_CREDIT_LINE_SHOW_COMMITTEE_NOTES]
	@user_id int,
	@authorize bit,
	@eng_version bit
AS
SELECT V.CREDIT_LINE_ID, V.REC_ID, V.DATE_TIME, V.OWNER, V.OP_TYPE, U.USER_NAME,CASE WHEN @eng_version = 1 THEN V.OP_DESCRIP_LAT ELSE V.OP_DESCRIP END AS OP_DESCRIP, V.NOTE
FROM dbo.LOAN_CREDIT_LINES C
	INNER JOIN dbo.LOAN_VW_CREDIT_LINE_NOTES V ON V.CREDIT_LINE_ID = C.CREDIT_LINE_ID
	INNER JOIN dbo.USERS U ON V.OWNER = U.USER_ID
WHERE
	(@authorize = 1) AND (STATE IN (0, 20))
GO
