SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[client_banking_products_update] (@client_id int, @product_id int, @value bit)
AS

SET NOCOUNT ON;

IF @value = 1 
BEGIN
	IF NOT EXISTS(SELECT * FROM dbo.CLIENT_BANKING_PRODUCTS (NOLOCK) WHERE CLIENT_NO = @client_id AND BANKING_PRODUCT_ID = @product_id)
		INSERT INTO dbo.CLIENT_BANKING_PRODUCTS (CLIENT_NO, BANKING_PRODUCT_ID)
		VALUES (@client_id, @product_id)
END
ELSE
BEGIN
	IF EXISTS(SELECT * FROM dbo.CLIENT_BANKING_PRODUCTS (NOLOCK) WHERE CLIENT_NO = @client_id AND BANKING_PRODUCT_ID = @product_id)
		DELETE FROM dbo.CLIENT_BANKING_PRODUCTS
		WHERE CLIENT_NO = @client_id AND BANKING_PRODUCT_ID = @product_id
END
GO
