SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[BCC_CHECK_DAY_RETURNS] 
	@rec_id integer OUTPUT,
	@dt smalldatetime OUTPUT
AS

SELECT @dt = MIN(DT)
FROM dbo.DAY_RETURNS (NOLOCK)
WHERE REC_ID > @rec_id

SELECT @rec_id = MAX(REC_ID)
FROM dbo.DAY_RETURNS (NOLOCK)
GO
