SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SYS_ENABLE_CONSTRAINTS] @TableName nvarchar(255) AS SET NOCOUNT ON

 EXEC ('ALTER TABLE ' + @TableName + ' ENABLE TRIGGER ALL')  EXEC ('ALTER TABLE ' + @TableName + ' CHECK CONSTRAINT ALL')
GO
