SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[EXPORT_BALANCE_ALT]
  @dt1 smalldatetime, 
  @dt2 smalldatetime
AS

SET NOCOUNT ON
DECLARE @branch_id int

EXEC dbo.GET_SETTING_INT 'BRANCH_NUM', @branch_id OUTPUT

SELECT *
FROM dbo.BALANCES_WIDE (NOLOCK)
WHERE BRANCH_ID = @branch_id AND DT BETWEEN @dt1 AND @dt2
GO
