SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[BCBR_EXP_DEPTS]
AS

SET NOCOUNT ON

SELECT DEPT_NO,BRANCH_ID,IS_DEPT,ALIAS,DATABASE_ID,CODE9,BIC,DESCRIP,DESCRIP_LAT,ADDRESS,PHONE,FAX,HEAD,MAIN_ACC,WORK_TYPE,SIGN1,SIGN2
FROM dbo.DEPTS (NOLOCK)
GO
