SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LOAN_SP_DELETE_LOAN]
	@loan_id int
AS
	IF (SELECT STATE FROM dbo.LOANS WHERE LOAN_ID = @loan_id) > 0
	BEGIN
		RAISERROR ('ÃÀÀÅÔÏÒÉÆÉÒÄÁÖËÉ ÓÄÓáÉÓ ßÀÛËÀ ÛÄÖÞËÄÁÄËÉÀ !', 16, 1)
		RETURN (1)
	END

	DELETE FROM dbo.LOAN_COLLATERALS_LINK 
	WHERE LOAN_ID = @loan_id

	DELETE dbo.LOAN_COLLATERALS
	FROM dbo.LOAN_COLLATERALS A
		LEFT OUTER JOIN	dbo.LOAN_COLLATERALS_LINK B ON B.COLLATERAL_ID = A.COLLATERAL_ID
		LEFT OUTER JOIN	dbo.LOAN_CREDIT_LINE_COLLATERALS_LINK C ON C.COLLATERAL_ID = A.COLLATERAL_ID
	WHERE A.LOAN_ID IS NULL AND A.CREDIT_LINE_ID IS NULL AND B.LOAN_ID IS NULL AND C.CREDIT_LINE_ID IS NULL
	
	DELETE dbo.LOAN_COLLATERALS
	FROM dbo.LOAN_COLLATERALS A
		LEFT OUTER JOIN	dbo.LOAN_COLLATERALS_LINK B ON B.COLLATERAL_ID = A.COLLATERAL_ID
		LEFT OUTER JOIN	dbo.LOAN_CREDIT_LINE_COLLATERALS_LINK C ON C.COLLATERAL_ID = A.COLLATERAL_ID
	WHERE A.LOAN_ID = @loan_id AND B.LOAN_ID IS NULL AND C.CREDIT_LINE_ID IS NULL

	UPDATE dbo.LOAN_COLLATERALS 
	SET LOAN_ID = NULL
	WHERE LOAN_ID = @loan_id 

	DELETE FROM dbo.LOANS
	WHERE LOAN_ID = @loan_id
RETURN


GO
