SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[SWIFT_GET_BRANCH_FOR_ACCOUNT]
  @account TINTACCOUNT = null
AS

DECLARE 
  @bank_code TINTBANKCODE

  EXEC dbo.GET_SETTING_STR 'OUR_BANK_CODE_INT', @bank_code OUTPUT

  SELECT @bank_code AS BANK_CODE

GO
