SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE PROCEDURE [dbo].[_GET_OPERATION_RELATE]
  @rec_id int,
  @rel_type tinyint = 0
AS

SET NOCOUNT ON
DECLARE @T TABLE (REC_ID int PRIMARY KEY, PARENT_REC_ID int)

DECLARE @parent_rec_id int

INSERT INTO @T(REC_ID, PARENT_REC_ID) VALUES(@rec_id, -2)

INSERT INTO @T(REC_ID, PARENT_REC_ID)
SELECT REC_ID, PARENT_REC_ID
FROM dbo.OPS_0000 (NOLOCK)
WHERE RELATION_ID = @rec_id

DECLARE cr CURSOR FOR
SELECT REC_ID
FROM @T WHERE PARENT_REC_ID = -1
OPEN cr

FETCH NEXT FROM cr INTO @parent_rec_id

WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO @T(REC_ID, PARENT_REC_ID)
	SELECT REC_ID, PARENT_REC_ID
	FROM dbo.OPS_0000 (NOLOCK)
	WHERE PARENT_REC_ID = @parent_rec_id  

	FETCH NEXT FROM cr INTO @parent_rec_id
END

CLOSE cr
DEALLOCATE cr

IF @rel_type = 0
	SELECT T.PARENT_REC_ID, D.REC_ID, D.OP_CODE, D.DEBIT, D.CREDIT, D.ISO, D.AMOUNT, D.DESCRIP, D.DOC_DATE, D.DOC_TYPE
	FROM dbo.DOCS D (NOLOCK)
		INNER JOIN @T T ON D.REC_ID=T.REC_ID
	WHERE T.PARENT_REC_ID <= 0
	ORDER BY D.REC_ID
ELSE
	SELECT T.PARENT_REC_ID, D.REC_ID, D.OP_CODE, D.DEBIT, D.CREDIT, D.ISO, D.AMOUNT, D.DESCRIP, D.DOC_DATE, D.DOC_TYPE
	FROM dbo.DOCS D (NOLOCK)
		INNER JOIN @T T ON D.REC_ID=T.REC_ID
	WHERE T.PARENT_REC_ID > 0
	ORDER BY D.REC_ID
GO
