SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[LOAN_SP_GET_OLD_SCHEDULES]
	@loan_id int
AS
SET NOCOUNT ON

DECLARE @tbl TABLE(LOAN_ID int NOT NULL,
OP_ID int NOT NULL,
SCHEDULE_DATE smalldatetime NOT NULL,
INTEREST_DATE smalldatetime NULL,
AMOUNT money NULL,
PRINCIPAL money NULL,
INTEREST money NULL,
NU_INTEREST money NULL,
BALANCE money NULL,
PAY_INTEREST bit NULL,
INSURANCE money NULL,
SERVICE_FEE money NULL,
DEFERED_INTEREST money NULL,
DEFERED_OVERDUE_INTEREST money NULL,
DEFERED_PENALTY money NULL,
DEFERED_FINE money NULL
PRIMARY KEY (LOAN_ID, OP_ID, SCHEDULE_DATE)
)
	

DECLARE
	@op_id int,
	@amount money,
	@principal money,
	@interest money,
	@nu_interest money,
	@insurance money,
	@service_fee money,
	@defered_interest money,
	@defered_overdue_interest money,
	@defered_penalty money,
	@defered_fine money


DECLARE cr CURSOR LOCAL FORWARD_ONLY FAST_FORWARD READ_ONLY
FOR SELECT DISTINCT OP_ID
FROM dbo.LOAN_SCHEDULE_HISTORY
WHERE LOAN_ID = @loan_id AND ORIGINAL_AMOUNT IS NOT NULL

OPEN cr

FETCH NEXT FROM cr INTO @op_id

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @amount = $0.00
	SET @principal = $0.00
	SET @interest = $0.00
	SET @nu_interest = $0.00

	INSERT INTO @tbl(LOAN_ID, OP_ID, SCHEDULE_DATE, INTEREST_DATE, AMOUNT, PRINCIPAL, INTEREST, NU_INTEREST, BALANCE, PAY_INTEREST, INSURANCE, SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE)
	SELECT LOAN_ID, OP_ID, SCHEDULE_DATE, INTEREST_DATE, ORIGINAL_AMOUNT, ORIGINAL_PRINCIPAL, ORIGINAL_INTEREST, ORIGINAL_NU_INTEREST, ORIGINAL_BALANCE, PAY_INTEREST, ORIGINAL_INSURANCE, ORIGINAL_SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE
	FROM dbo.LOAN_SCHEDULE_HISTORY
	WHERE LOAN_ID = @loan_id AND OP_ID = @op_id AND ORIGINAL_AMOUNT IS NOT NULL

	SELECT 
		@amount = SUM(ISNULL(AMOUNT, $0.00)), 
		@principal = SUM(ISNULL(PRINCIPAL, $0.00)), 
		@interest = SUM(ISNULL(INTEREST, $0.00)), 
		@nu_interest = SUM(ISNULL(NU_INTEREST, $0.00)), 
		@insurance = SUM(ISNULL(INSURANCE, $0.00)), 
		@service_fee = SUM(ISNULL(SERVICE_FEE, $0.00)),
		@defered_interest = SUM(ISNULL(DEFERED_INTEREST, $0.00)),
		@defered_overdue_interest = SUM(ISNULL(DEFERED_OVERDUE_INTEREST, $0.00)),
		@defered_penalty = SUM(ISNULL(DEFERED_PENALTY, $0.00)),
		@defered_fine = SUM(ISNULL(DEFERED_FINE, $0.00)) 
	FROM @tbl
	WHERE LOAN_ID = @loan_id AND OP_ID = @op_id
	
	INSERT INTO @tbl(LOAN_ID, OP_ID, SCHEDULE_DATE, AMOUNT, PRINCIPAL, INTEREST, NU_INTEREST, INSURANCE, SERVICE_FEE, DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE)
	VALUES(@loan_id, @op_id, dbo.get_max_smalldatetime(), @amount, @principal, @interest, @nu_interest, @insurance, @service_fee, @defered_interest, @defered_overdue_interest, @defered_penalty, @defered_fine)

	FETCH NEXT FROM cr INTO @op_id
END

CLOSE cr
DEALLOCATE cr

SELECT * FROM @tbl
RETURN 0
GO
