SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE  PROCEDURE [dbo].[_STARTUP] AS

SET DATEFORMAT 'mdy'

IF NOT EXISTS (SELECT * FROM dbo.INI_INT WHERE IDS = 'SERVER_STATE')
  INSERT INTO dbo.INI_INT (IDS,VALS) VALUES('SERVER_STATE',0)

IF NOT EXISTS (SELECT * FROM dbo.INI_DT WHERE IDS = 'OPEN_BANK_DATE')
  INSERT INTO dbo.INI_DT (IDS,VALS) VALUES('OPEN_BANK_DATE','01/01/2000')

SELECT VALS FROM dbo.INI_STR WHERE IDS = 'DBVER'
GO
