SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[LOAN_SP_GET_OPS_DOCS]
	@doc_rec_id int
AS
	SELECT D.OP_NUM, D.OP_CODE, D.DEBIT, D.CREDIT, D.ISO, D.AMOUNT, D.DESCRIP 
	FROM dbo.DOCS_ALL D (NOLOCK)
	WHERE (D.OP_NUM=@doc_rec_id)
	ORDER BY D.REC_ID
GO
