SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PLASTIC_CARD_FOR_SEND]
	@client_type int
AS
SELECT P.*,
	CT.RISK_LEVEL,
	CT.CARD_CHIP,
	CT.DESIGN_ID,
	C.CLIENT_REG_DATE,
	C.IS_RESIDENT,
	C.IS_JURIDICAL,
	C.IS_INSIDER,
	C.PHONE1,
	C.PHONE2,
	dbo.cli_get_cli_attribute(C.CLIENT_NO, '$FAX') AS FAX,
	dbo.cli_get_cli_attribute(C.CLIENT_NO, '$EMAIL') AS E_MAIL,
	C.BIRTH_DATE,
	C.FIRST_NAME_LAT,
	C.LAST_NAME_LAT,
	C.REC_STATE,
	C.FATHERS_NAME_LAT,
	C.MALE_FEMALE,
	C.COMPLETED,
	C.PERSONAL_ID,
	C.PASSPORT_TYPE_ID,
	C.PASSPORT_ISSUE_DT,
	dbo.convert_geo_to_acadnusx(C.PASSPORT) AS PASSPORT,
	dbo.convert_geo_to_acadnusx(SUBSTRING(C.PASSPORT, 0, PATINDEX('%[0-9]%', C.PASSPORT))) AS PASSPORT_SERIAL,
	SUBSTRING(C.PASSPORT, PATINDEX('%[0-9]%', C.PASSPORT), LEN(C.PASSPORT)) AS PASSPORT_NUMBER,
	dbo.convert_geo_to_acadnusx(C.PASSPORT_REG_ORGAN) AS PASSPORT_REG_ORGAN,
	C.TAX_INSP_CODE,
	C.MARITAL_STATUS,
	dbo.plastic_card_accounts_count(P.REC_ID) AS ACCOUNTS_COUNT,
	ISNULL(CITY_LAT, ISNULL((SELECT TOP 1 CITY_LAT FROM dbo.CITIES WHERE COUNTRY = C.COUNTRY AND CITY = C.CITY), 'Tbilisi')) AS CITY_LAT
FROM  dbo.PLASTIC_CARDS_FOR_SEND P
	INNER JOIN dbo.CLIENTS AS C ON P.CLIENT_NO = C.CLIENT_NO
	INNER JOIN dbo.CCARD_TYPES AS CT ON CT.REC_ID = P.CARD_TYPE
WHERE C.COMPLETED = 1
	AND C.IS_JURIDICAL = @client_type
GO
