SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[depo_sp_get_product]
	@depo_id int
AS
	SET NOCOUNT ON;

	SELECT P.* 
	FROM dbo.DEPO_DEPOSITS D (NOLOCK)
		INNER JOIN dbo.DEPO_PRODUCT P (NOLOCK) ON D.PROD_ID=P.PROD_ID
	WHERE DEPO_ID = @depo_id

	RETURN 0

GO
