SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE PROCEDURE [dbo].[_GET_OPERATION_ARC]
  @rec_id int
AS

SET NOCOUNT ON

SELECT REC_ID, OP_CODE, DEBIT, CREDIT, ISO, AMOUNT, DESCRIP, DOC_DATE, DOC_TYPE 
FROM dbo.DOCS_ARC (NOLOCK)
WHERE REC_ID = @rec_id OR PARENT_REC_ID = @rec_id
ORDER BY REC_ID
GO
