SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[BCC_EXP_VAL_CODES] (@for_branch bit = 0)
AS

SET NOCOUNT ON

SELECT ISO,DESCRIP,DIGITS,IS_DISABLED,DESCRIP_LAT
FROM dbo.VAL_CODES (NOLOCK)
WHERE (@for_branch <> 0) OR (IS_DISABLED = 0)
GO
