SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAVE_OLD_LOGS] AS

	DECLARE @dt smalldatetime
	SET @dt = dbo.bank_open_date()

	INSERT INTO dbo.B2000_LOG_ARC
	SELECT * FROM dbo.B2000_LOG
	WHERE DATE_AND_TIME < DATEADD(mm, 1, @dt)

	DELETE FROM dbo.B2000_LOG
	WHERE DATE_AND_TIME < DATEADD(mm, 1, @dt)
GO
