SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DX_SPX_GET_DEPOSIT_OPS_DOCS_LIST]
  @docs_rec_id int
AS
SET NOCOUNT ON
SELECT D.OP_NUM, D.OP_CODE, D.DEBIT, D.CREDIT, D.ISO, D.AMOUNT, D.DESCRIP 
FROM DOCS_ALL D (NOLOCK)
WHERE (D.OP_NUM=@docs_rec_id)
ORDER BY D.REC_ID


GO
