SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE  PROCEDURE [dbo].[LOAN_SP_GET_COLLATERAL_ACCOUNTS]
	@collateral_id		int,
	@credit_line_id		int			= NULL,
	@eng_version		bit			= 0,
	@collateral_iso		TISO		= NULL,
	@client_no			int			= NULL, 
	@collateral_type	int			= NULL
AS
SET NOCOUNT ON


IF (@collateral_iso IS NULL) OR (@client_no IS NULL)
	SELECT @credit_line_id = CREDIT_LINE_ID, @client_no = CLIENT_NO, @collateral_iso = ISO FROM dbo.LOAN_COLLATERALS (NOLOCK) WHERE COLLATERAL_ID = @collateral_id

IF @credit_line_id IS NULL
	SELECT @collateral_id AS COLLATERAL_ID, T.TYPE_ID, 
		CASE WHEN @eng_version = 0 THEN T.CODE ELSE T.CODE_LAT END AS CODE,
		CASE WHEN @eng_version = 0 THEN T.DESCRIP ELSE T.DESCRIP_LAT END AS DESCRIP,
		@client_no AS CLIENT_NO,
		AT.BAL_ACC,
		@collateral_iso AS COLLATERAL_ISO,
	A.ACC_ID, CASE WHEN @eng_version = 0 THEN ACC.DESCRIP ELSE ACC.DESCRIP_LAT END AS ACCOUNT_DESCRIP
	FROM dbo.LOAN_COLLATERAL_TYPES T (NOLOCK)
		LEFT OUTER JOIN	dbo.LOAN_COLLATERAL_ACCOUNT_TEMPLATES AT (NOLOCK) ON AT.COLLATERAL_TYPE = T.TYPE_ID
		LEFT OUTER JOIN	dbo.LOAN_COLLATERAL_ACCOUNTS_2 A (NOLOCK) ON (A.COLLATERAL_ID = @collateral_id) AND (A.COLLATERAL_TYPE = T.TYPE_ID)
		LEFT OUTER JOIN	dbo.ACCOUNTS ACC (NOLOCK) ON A.ACC_ID = ACC.ACC_ID
	WHERE ((@collateral_type IS NULL) OR ((@collateral_type IS NOT NULL) AND (T.TYPE_ID = @collateral_type)))
	ORDER BY T.TYPE_ID
ELSE
	SELECT @collateral_id AS COLLATERAL_ID, T.TYPE_ID, 
		CASE WHEN @eng_version = 0 THEN T.CODE ELSE T.CODE_LAT END AS CODE,
		CASE WHEN @eng_version = 0 THEN T.DESCRIP ELSE T.DESCRIP_LAT END AS DESCRIP,
		@client_no AS CLIENT_NO,
		AT.BAL_ACC,
		@collateral_iso AS COLLATERAL_ISO,
	A.ACC_ID, CASE WHEN @eng_version = 0 THEN ACC.DESCRIP ELSE ACC.DESCRIP_LAT END AS ACCOUNT_DESCRIP
	FROM dbo.LOAN_COLLATERAL_TYPES T (NOLOCK)
		LEFT OUTER JOIN	dbo.LOAN_CREDIT_LINE_ACCOUNT_TEMPLATES AT (NOLOCK) ON AT.COLLATERAL_TYPE = T.TYPE_ID
		LEFT OUTER JOIN	dbo.LOAN_COLLATERAL_ACCOUNTS_2 A (NOLOCK) ON (A.COLLATERAL_ID = @collateral_id) AND (A.COLLATERAL_TYPE = T.TYPE_ID)
		LEFT OUTER JOIN	dbo.ACCOUNTS ACC (NOLOCK) ON A.ACC_ID = ACC.ACC_ID
	WHERE ((@collateral_type IS NULL) OR ((@collateral_type IS NOT NULL) AND (T.TYPE_ID = @collateral_type)))
	ORDER BY T.TYPE_ID



GO
