SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BCC_EXP_BC_DOCS_3000]
  @bc_client_id int,
  @bc_login_id int,
  @step tinyint,
  @is_arc bit,
  @dt smalldatetime = 0,
  @lat bit = 0
AS
SET NOCOUNT ON

IF @step = 0
BEGIN
  IF @is_arc = 0
  BEGIN
    DECLARE @flags int
    SELECT @flags = FLAGS FROM BC_LOGINS WHERE BC_LOGIN_ID = @bc_login_id
    SET @flags = ISNULL(@flags,0)

    INSERT #REC_IDS (REC_ID)
    SELECT DISTINCT S.REC_ID 
    FROM dbo.SHADOWS S 
       INNER JOIN dbo.DOCS D (NOLOCK) ON D.REC_ID = S.REC_ID
       INNER JOIN dbo.BC_LOGIN_ACC A ON A.ACCOUNT=S.ACCOUNT AND A.ISO=S.ISO 
    WHERE (D.DOC_TYPE > 0) AND ((@flags & 1024 = 0) OR (D.REC_STATE >= 10) OR (NOT D.DOC_TYPE IN (103,104,113,114))) AND /* can see red zach */ A.BC_LOGIN_ID = @bc_login_id
  END
  ELSE
  BEGIN
    INSERT #REC_IDS (REC_ID)
    SELECT DISTINCT D.REC_ID 
    FROM dbo.STATEMENT D 
       INNER JOIN dbo.BC_LOGIN_ACC A ON D.ACCOUNT=A.ACCOUNT AND D.ISO=A.ISO 
    WHERE (@dt=0 OR D.DT>=@dt) AND A.BC_LOGIN_ID = @bc_login_id
  END
END

ELSE

IF @step = 1
BEGIN
  IF @is_arc = 0
  BEGIN
    SELECT D.OP_NUM, D.REC_ID, D.UID, D.DOC_DATE, D.DOC_DATE_IN_DOC, D.ISO, D.AMOUNT, D.AMOUNT_EQU, D.DOC_NUM, D.OP_CODE, D.DEBIT, D.CREDIT, D.REC_STATE, D.BNK_CLI_ID, D.DESCRIP, D.PARENT_REC_ID, D.OWNER, D.DOC_TYPE, D.ACCOUNT_EXTRA,
           CASE @lat WHEN 0 THEN A1.DESCRIP ELSE A1.DESCRIP_LAT END AS DEBIT_NAME,  
           CASE @lat WHEN 0 THEN A2.DESCRIP ELSE A2.DESCRIP_LAT END AS CREDIT_NAME 
    FROM #REC_IDS T 
      INNER JOIN dbo.DOCS_ALL D ON D.REC_ID=T.REC_ID
      INNER JOIN dbo.ACCOUNTS A1 ON D.DEBIT=A1.ACCOUNT AND D.ISO=A1.ISO
      INNER JOIN dbo.ACCOUNTS A2 ON D.CREDIT=A2.ACCOUNT AND D.ISO=A2.ISO
  END
  ELSE
  BEGIN
    SELECT D.OP_NUM, D.REC_ID, D.UID, D.DOC_DATE, D.DOC_DATE_IN_DOC, D.ISO, D.AMOUNT, D.AMOUNT_EQU, D.DOC_NUM, D.OP_CODE, D.DEBIT, D.CREDIT, D.REC_STATE, D.BNK_CLI_ID, D.DESCRIP, D.PARENT_REC_ID, D.OWNER, D.DOC_TYPE, D.ACCOUNT_EXTRA,
           CASE @lat WHEN 0 THEN A1.DESCRIP ELSE A1.DESCRIP_LAT END AS DEBIT_NAME,  
           CASE @lat WHEN 0 THEN A2.DESCRIP ELSE A2.DESCRIP_LAT END AS CREDIT_NAME 
    FROM #REC_IDS T 
      INNER JOIN dbo.DOCS_ARC_ALL D ON D.REC_ID=T.REC_ID
      INNER JOIN dbo.ACCOUNTS A1 ON D.DEBIT=A1.ACCOUNT AND D.ISO=A1.ISO
      INNER JOIN dbo.ACCOUNTS A2 ON D.CREDIT=A2.ACCOUNT AND D.ISO=A2.ISO
	WHERE D.DOC_TYPE > 0
  END
END

ELSE

IF @step = 2
BEGIN
  IF @is_arc = 0 
       SELECT DD.REC_ID,CONVERT(int, dbo.get_real_bank_code (DD.SENDER_BANK_CODE)) AS SENDER_BANK_CODE,DD.SENDER_ACC,DD.SENDER_TAX_CODE,CONVERT(int, dbo.get_real_bank_code (DD.RECEIVER_BANK_CODE)) AS RECEIVER_BANK_CODE,DD.RECEIVER_ACC,DD.RECEIVER_TAX_CODE,DD.SENDER_BANK_NAME,DD.RECEIVER_BANK_NAME,DD.SENDER_ACC_NAME,DD.RECEIVER_ACC_NAME,DD.POR REC_DATE,DD.SAXAZKOD,DD.EXTRA_INFO,DD.REF_NUM 
       FROM dbo.DOC_DETAILS_PLAT DD INNER JOIN #REC_IDS D ON DD.REC_ID=D.REC_ID
  ELSE SELECT DD.REC_ID,CONVERT(int, dbo.get_real_bank_code (DD.SENDER_BANK_CODE)) AS SENDER_BANK_CODE,DD.SENDER_ACC,DD.SENDER_TAX_CODE,CONVERT(int, dbo.get_real_bank_code (DD.RECEIVER_BANK_CODE)) AS RECEIVER_BANK_CODE,DD.RECEIVER_ACC,DD.RECEIVER_TAX_CODE,DD.SENDER_BANK_NAME,DD.RECEIVER_BANK_NAME,DD.SENDER_ACC_NAME,DD.RECEIVER_ACC_NAME,DD.POR REC_DATE,DD.SAXAZKOD,DD.EXTRA_INFO,DD.REF_NUM  
       FROM dbo.DOC_DETAILS_ARC_PLAT DD INNER JOIN #REC_IDS D ON DD.REC_ID=D.REC_ID
END

ELSE

IF @step = 3
BEGIN
  IF @is_arc = 0 
       SELECT DD.REC_ID,dbo.get_real_bank_code (DD.SENDER_BANK_CODE) AS SENDER_BANK_CODE,DD.SENDER_ACC,dbo.get_real_bank_code (DD.RECEIVER_BANK_CODE) AS RECEIVER_BANK_CODE,DD.RECEIVER_ACC,DD.SENDER_BANK_NAME,DD.RECEIVER_BANK_NAME,DD.SENDER_ACC_NAME,DD.RECEIVER_ACC_NAME,DD.INTERMED_BANK_CODE,DD.INTERMED_BANK_NAME,DD.RECEIVER_INFO,DD.SENDER_TAX_CODE,DD.RECEIVER_TAX_CODE,DD.FIRST_NAME,DD.LAST_NAME,DD.FATHERS_NAME,DD.BIRTH_DATE,DD.BIRTH_PLACE,DD.ADDRESS_JUR,DD.ADDRESS_FACT,DD.COUNTRY,DD.PASSPORT_TYPE_ID,DD.PASSPORT,DD.PERSONAL_ID,DD.SWIFT_TEXT,DD.REF_NUM,DD.COR_BANK_CODE,DD.COR_BANK_NAME,DD.ADDRESS_LAT 
       FROM dbo.DOC_DETAILS_VALPLAT DD INNER JOIN #REC_IDS D ON DD.REC_ID=D.REC_ID
  ELSE SELECT DD.REC_ID,dbo.get_real_bank_code (DD.SENDER_BANK_CODE) AS SENDER_BANK_CODE,DD.SENDER_ACC,dbo.get_real_bank_code (DD.RECEIVER_BANK_CODE) AS RECEIVER_BANK_CODE,DD.RECEIVER_ACC,DD.SENDER_BANK_NAME,DD.RECEIVER_BANK_NAME,DD.SENDER_ACC_NAME,DD.RECEIVER_ACC_NAME,DD.INTERMED_BANK_CODE,DD.INTERMED_BANK_NAME,DD.RECEIVER_INFO,DD.SENDER_TAX_CODE,DD.RECEIVER_TAX_CODE,DD.FIRST_NAME,DD.LAST_NAME,DD.FATHERS_NAME,DD.BIRTH_DATE,DD.BIRTH_PLACE,DD.ADDRESS_JUR,DD.ADDRESS_FACT,DD.COUNTRY,DD.PASSPORT_TYPE_ID,DD.PASSPORT,DD.PERSONAL_ID,DD.SWIFT_TEXT,DD.REF_NUM,DD.COR_BANK_CODE,DD.COR_BANK_NAME,DD.ADDRESS_LAT 
       FROM dbo.DOC_DETAILS_ARC_VALPLAT DD INNER JOIN #REC_IDS D ON DD.REC_ID=D.REC_ID
END

ELSE

IF @step = 4
BEGIN
  IF @is_arc = 0 
       SELECT DD.* FROM dbo.DOC_DETAILS_KAS DD INNER JOIN #REC_IDS D ON DD.REC_ID=D.REC_ID
  ELSE SELECT DD.* FROM dbo.DOC_DETAILS_ARC_KAS DD INNER JOIN #REC_IDS D ON DD.REC_ID=D.REC_ID
END

ELSE

DROP TABLE #REC_IDS
GO
