SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_LOAN_CLONE_SCHEDULE]
  @loan_id int
AS

DECLARE
	@r int,
	@e int 


	UPDATE LOAN_SCHEDULE 
	SET 
		ORIGINAL_AMOUNT = AMOUNT,
		ORIGINAL_PRINCIPAL = PRINCIPAL,
		ORIGINAL_INTEREST = INTEREST,
		ORIGINAL_NU_INTEREST = NU_INTEREST,
		ORIGINAL_BALANCE = BALANCE,
		ORIGINAL_INSURANCE = INSURANCE,
		ORIGINAL_SERVICE_FEE = SERVICE_FEE,
		ORIGINAL_DEFERED_INTEREST = DEFERED_INTEREST,
		ORIGINAL_DEFERED_OVERDUE_INTEREST = DEFERED_OVERDUE_INTEREST,
		ORIGINAL_DEFERED_PENALTY = DEFERED_PENALTY,
		ORIGINAL_DEFERED_FINE = DEFERED_FINE
	WHERE LOAN_ID = @loan_id

	SELECT @r = @@ROWCOUNT, @e = @@ERROR
	IF @e <> 0 RETURN(1) 
	IF @r = 0 RETURN(1) 
		
	RETURN(0)
GO
