SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[LOAN_SP_UPDATE_ACCOUNT_BALANCE_INTERNAL]
	@loan_id int,
	@type_id int,
	@doc_date smalldatetime,
	@amount money
AS
	UPDATE dbo.LOAN_ACCOUNT_BALANCE
	SET
		ACC_0301_DATE = CASE ABS(@type_id) WHEN 10 THEN @doc_date ELSE ACC_0301_DATE END,
		ACC_0301_BALANCE = CASE ABS(@type_id) WHEN 10 THEN ISNULL(ACC_0301_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE ACC_0301_BALANCE END,
		PRINCIPAL_BALANCE = CASE ABS(@type_id)
			WHEN 30 THEN ISNULL(PRINCIPAL_BALANCE, $0.00) + (SIGN(@type_id) * @amount)
			WHEN 40 THEN ISNULL(PRINCIPAL_BALANCE, $0.00) + (SIGN(@type_id) * -@amount)
			WHEN 50 THEN ISNULL(PRINCIPAL_BALANCE, $0.00) + (SIGN(@type_id) * -@amount)
			ELSE PRINCIPAL_BALANCE END,
		OVERDUE_PRINCIPAL_BALANCE = CASE ABS(@type_id)
			WHEN 40 THEN ISNULL(OVERDUE_PRINCIPAL_BALANCE, $0.00) + (SIGN(@type_id) * @amount)
			WHEN 51 THEN ISNULL(OVERDUE_PRINCIPAL_BALANCE, $0.00) + (SIGN(@type_id) * -@amount)	
			ELSE OVERDUE_PRINCIPAL_BALANCE END,

		--WRITEOFF_PRINCIPAL_BALANCE = CASE WHEN ABS(@type_id) IN (50, 51) THEN ISNULL(WRITEOFF_PRINCIPAL_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE WRITEOFF_PRINCIPAL_BALANCE END,

		INTEREST_DATE = CASE ABS(@type_id) WHEN 1030 THEN @doc_date ELSE INTEREST_DATE END,
		INTEREST_BALANCE = CASE ABS(@type_id) WHEN 1030 THEN ISNULL(INTEREST_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE INTEREST_BALANCE END,
		
		OVERDUE_INTEREST_DATE = CASE ABS(@type_id) WHEN 1160 THEN @doc_date ELSE OVERDUE_INTEREST_DATE END,
		OVERDUE_INTEREST_BALANCE = CASE ABS(@type_id) WHEN 1160 THEN ISNULL(OVERDUE_INTEREST_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE OVERDUE_INTEREST_BALANCE END,

		OVERDUE_INTEREST30_DATE = CASE ABS(@type_id) WHEN 2060 THEN @doc_date ELSE OVERDUE_INTEREST30_DATE END,
		OVERDUE_INTEREST30_BALANCE = CASE ABS(@type_id) WHEN 2060 THEN ISNULL(OVERDUE_INTEREST30_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE OVERDUE_INTEREST30_BALANCE END,

		PENALTY_DATE = CASE ABS(@type_id) WHEN 2000 THEN @doc_date ELSE PENALTY_DATE END,
		PENALTY_BALANCE = CASE ABS(@type_id) WHEN 2000 THEN ISNULL(PENALTY_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE PENALTY_BALANCE END,

		--WRITEOFF_DATE  = CASE ABS(@type_id) WHEN 70 THEN @doc_date ELSE WRITEOFF_DATE END,
		--WRITEOFF_BALANCE = CASE ABS(@type_id) WHEN 70 THEN ISNULL(WRITEOFF_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE WRITEOFF_BALANCE END,


		ADMIN_FEE_DATE = CASE ABS(@type_id) WHEN 1000 THEN @doc_date ELSE ADMIN_FEE_DATE END,
		ADMIN_FEE_BALANCE = CASE ABS(@type_id) WHEN 1000 THEN ISNULL(ADMIN_FEE_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE ADMIN_FEE_BALANCE END,

		RISK_CATEGORY_DATE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050)  THEN @doc_date ELSE RISK_CATEGORY_DATE END,
		RISK_CATEGORY_BALANCE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050) THEN CASE WHEN ABS(@type_id) = 8000 THEN ISNULL(RISK_CATEGORY_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE NULL END ELSE RISK_CATEGORY_BALANCE END,
		RISK_CATEGORY_1_BALANCE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050) THEN CASE WHEN ABS(@type_id) = 8010 THEN ISNULL(RISK_CATEGORY_1_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE CASE WHEN ABS(@type_id) = 8000 THEN NULL ELSE RISK_CATEGORY_1_BALANCE END END ELSE RISK_CATEGORY_1_BALANCE END,
		RISK_CATEGORY_2_BALANCE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050) THEN CASE WHEN ABS(@type_id) = 8020 THEN ISNULL(RISK_CATEGORY_2_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE CASE WHEN ABS(@type_id) = 8000 THEN NULL ELSE RISK_CATEGORY_2_BALANCE END  END ELSE RISK_CATEGORY_2_BALANCE END,
		RISK_CATEGORY_3_BALANCE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050) THEN CASE WHEN ABS(@type_id) = 8030 THEN ISNULL(RISK_CATEGORY_3_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE CASE WHEN ABS(@type_id) = 8000 THEN NULL ELSE RISK_CATEGORY_3_BALANCE END  END ELSE RISK_CATEGORY_3_BALANCE END,
		RISK_CATEGORY_4_BALANCE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050) THEN CASE WHEN ABS(@type_id) = 8040 THEN ISNULL(RISK_CATEGORY_4_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE CASE WHEN ABS(@type_id) = 8000 THEN NULL ELSE RISK_CATEGORY_4_BALANCE END  END ELSE RISK_CATEGORY_4_BALANCE END,
		RISK_CATEGORY_5_BALANCE = CASE WHEN ABS(@type_id) IN (8000, 8010, 8020, 8030, 8040, 8050) THEN CASE WHEN ABS(@type_id) = 8050 THEN ISNULL(RISK_CATEGORY_5_BALANCE, $0.00) + (SIGN(@type_id) * @amount) ELSE CASE WHEN ABS(@type_id) = 8000 THEN NULL ELSE RISK_CATEGORY_5_BALANCE END  END ELSE RISK_CATEGORY_5_BALANCE END
	WHERE LOAN_ID = @loan_id
	
	IF @@ERROR<>0 OR @@ROWCOUNT <> 1 RETURN 1
RETURN 0

GO
