SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_DISABLE_ALL_CONSTRAINTS] AS SET NOCOUNT ON DECLARE  @TableName nvarchar(255)

DECLARE Cur CURSOR FOR SELECT [name] FROM sysobjects WHERE type='U' and [name] = upper([name]) OPEN Cur

FETCH NEXT FROM Cur INTO @TableName

WHILE @@FETCH_STATUS = 0
BEGIN

  EXEC SYS_DISABLE_CONSTRAINTS @TableName
--  EXEC ('ALTER TABLE ' + @TableName + ' DISABLE TRIGGER ALL')
--  EXEC ('ALTER TABLE ' + @TableName + ' NOCHECK CONSTRAINT ALL')
  FETCH NEXT FROM Cur INTO @TableName
END

CLOSE Cur
DEALLOCATE Cur

GO
