SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[DELETE_RESERVED_ACCOUNTS] (@user_id int = 0) AS

set nocount on

DELETE FROM RESERVED_ACCOUNTS
WHERE [USER_ID] = @user_id OR DATEDIFF(mi,DT_TM,GETDATE()) > 10

SELECT 0

GO
