SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_GET_LOAN_SCHEDULE_WITH_SUM]
  @loan_id int
AS
	SET NOCOUNT ON

DECLARE
	@loan_disbursed int

	SELECT @loan_disbursed = COUNT(*) FROM dbo.LOAN_OPS WHERE LOAN_ID = @loan_id AND OP_TYPE = dbo.loan_const_op_disburse() AND OP_STATE = 255

	IF @loan_disbursed > 0 AND EXISTS (SELECT * FROM dbo.LOAN_SCHEDULE WHERE LOAN_ID = @loan_id AND ORIGINAL_AMOUNT IS NOT NULL)
	BEGIN
		(SELECT 
			convert(int, SCHEDULE_DATE) AS REC_ID, LOAN_ID, convert(varchar(20), SCHEDULE_DATE, 103) AS SCHEDULE_DATE, INTEREST_DATE,
			ORIGINAL_AMOUNT AS AMOUNT,
			ORIGINAL_PRINCIPAL AS PRINCIPAL, 
			ORIGINAL_INTEREST AS INTEREST, 
			ORIGINAL_NU_INTEREST AS NU_INTEREST, 
			ORIGINAL_BALANCE AS BALANCE, 
			PAY_INTEREST,
			ORIGINAL_INSURANCE AS INSURANCE,
			ORIGINAL_SERVICE_FEE AS SERVICE_FEE,
			ORIGINAL_DEFERED_INTEREST AS DEFERED_INTEREST,
			ORIGINAL_DEFERED_OVERDUE_INTEREST AS DEFERED_OVERDUE_INTEREST,
			ORIGINAL_DEFERED_PENALTY AS DEFERED_PENALTY,
			ORIGINAL_DEFERED_FINE AS DEFERED_FINE
		FROM dbo.LOAN_SCHEDULE
		WHERE LOAN_ID = @loan_id AND ORIGINAL_AMOUNT IS NOT NULL
		UNION
		SELECT 
			0x0FFFFFFF AS REC_ID, NULL AS LOAN_ID, 'ãÀÌÉ:' AS SCHEDULE_DATE, NULL AS INTEREST_DATE,
			SUM(ORIGINAL_AMOUNT) AS AMOUNT,
			SUM(ORIGINAL_PRINCIPAL) AS PRINCIPAL, 
			SUM(ORIGINAL_INTEREST) AS INTEREST, 
			SUM(ORIGINAL_NU_INTEREST) AS NU_INTEREST, 
			NULL AS BALANCE, 
			0 AS PAY_INTEREST,
			SUM(ORIGINAL_INSURANCE) AS INSURANCE,
			SUM(ORIGINAL_SERVICE_FEE) AS SERVICE_FEE,
			SUM(ORIGINAL_DEFERED_INTEREST) AS DEFERED_INTEREST,
			SUM(ORIGINAL_DEFERED_OVERDUE_INTEREST) AS DEFERED_OVERDUE_INTEREST,
			SUM(ORIGINAL_DEFERED_PENALTY) AS DEFERED_PENALTY,
			SUM(ORIGINAL_DEFERED_FINE) AS DEFERED_FINE
		FROM dbo.LOAN_SCHEDULE
		WHERE LOAN_ID = @loan_id AND ORIGINAL_AMOUNT IS NOT NULL)
		ORDER BY 1
	END
	ELSE
	BEGIN
		SELECT 
			CONVERT(int, SCHEDULE_DATE) AS REC_ID, LOAN_ID, CONVERT(varchar(20), SCHEDULE_DATE, 103) AS SCHEDULE_DATE, INTEREST_DATE,
			AMOUNT, PRINCIPAL, INTEREST, NU_INTEREST, BALANCE, PAY_INTEREST, INSURANCE, SERVICE_FEE,
			DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE
		FROM dbo.LOAN_SCHEDULE
		WHERE LOAN_ID = @loan_id
		UNION
		SELECT 
			0x0FFFFFFF AS REC_ID, NULL AS LOAN_ID, 'ãÀÌÉ:' AS SCHEDULE_DATE, NULL AS INTEREST_DATE,
			SUM(AMOUNT) AS AMOUNT, SUM(PRINCIPAL) AS PRINCIPAL, SUM(INTEREST) AS INTEREST, SUM(NU_INTEREST) AS NU_INTEREST, NULL AS BALANCE, 0 AS PAY_INTEREST, SUM(INSURANCE) AS INSURANCE, SUM(SERVICE_FEE) AS SERVICE_FEE,
			SUM(DEFERED_INTEREST), SUM(DEFERED_OVERDUE_INTEREST), SUM(DEFERED_PENALTY), SUM(DEFERED_FINE)
		FROM dbo.LOAN_SCHEDULE
		WHERE LOAN_ID = @loan_id
		ORDER BY 1
	END
GO
