SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE  PROCEDURE [dbo].[LOAN_SP_GET_LOAN_ACCOUNTS]
	@loan_id			int,
	@eng_version		bit			= 0,
	@loan_iso			TISO		= NULL,
	@loan_bal_acc		TBAL_ACC	= NULL,
	@client_no			int			= NULL, 
	@account_type		int			= NULL,
	@product_id			int			= NULL,	
	@is_guarantee		int			= 0
AS

SET NOCOUNT ON

DECLARE
	@acc_show_flag int

IF @is_guarantee = 0
	SET @acc_show_flag = 1
ELSE SET @acc_show_flag = 2

IF (@loan_iso IS NULL) OR (@loan_bal_acc IS NULL) OR (@client_no IS NULL) OR (@product_id IS NULL)
	SELECT @client_no = CLIENT_NO, @loan_iso = ISO, @loan_bal_acc = BAL_ACC, @product_id = PRODUCT_ID FROM dbo.LOANS (NOLOCK) WHERE LOAN_ID = @loan_id

SELECT @loan_id AS LOAN_ID, T.TYPE_ID, T.CODE, CASE WHEN @eng_version = 0 THEN T.DESCRIP ELSE T.DESCRIP_LAT END AS DESCRIP, @client_no AS CLIENT_NO,
	CASE WHEN T.TYPE_ID IN (20, 30, 40, 50) THEN CONVERT(bit,  1) ELSE CONVERT(bit,  0) END AS CLIENT_NO_STRONG,
	CASE WHEN P.ACT_PAS IS NULL THEN CASE WHEN T.TYPE_ID = 20 THEN CONVERT(bit,  1) ELSE CONVERT(bit, NULL) END WHEN P.ACT_PAS=3 THEN CONVERT(bit, 0) ELSE CONVERT(bit, 1) END AS IS_BAL,
	CASE WHEN T.TYPE_ID IN (30, 35) THEN @loan_bal_acc ELSE CASE WHEN T.TYPE_ID = 20 THEN B1.ACCOUNT_BAL_ACC WHEN T.TYPE_ID BETWEEN 10001 AND 10010 THEN (SELECT BAL_ACC FROM dbo.LOAN_COLLATERAL_ACCOUNT_TEMPLATES (NOLOCK) WHERE COLLATERAL_TYPE = T.TYPE_ID - 10000) ELSE CASE WHEN BP.ACCOUNT_BAL_ACC IS NOT NULL THEN BP.ACCOUNT_BAL_ACC ELSE B.ACCOUNT_BAL_ACC END END END AS BAL_ACC_ALT,
	CASE WHEN T.TYPE_ID IN (8000, 8010, 8020, 8030, 8040, 8050, 9000, 9010, 9020, 9030, 9040, 9050, 170) THEN 'GEL' ELSE @loan_iso END AS LOAN_ISO,
A.ACC_ID, ACC.ISO AS ISO, ACC.ACCOUNT, CASE WHEN @eng_version = 0 THEN ACC.DESCRIP ELSE ACC.DESCRIP_LAT END AS ACCOUNT_DESCRIP
FROM dbo.LOAN_ACCOUNT_TYPES T (NOLOCK) 
	LEFT OUTER JOIN	dbo.LOAN_BAL_ACCS B (NOLOCK) ON B.BAL_ACC = @loan_bal_acc AND B.TYPE_ID = T.TYPE_ID 
	LEFT OUTER JOIN	dbo.LOAN_PRODUCT_BAL_ACCS BP (NOLOCK) ON BP.BAL_ACC = @loan_bal_acc AND BP.PRODUCT_ID = @product_id AND BP.TYPE_ID = T.TYPE_ID 
	LEFT OUTER JOIN	dbo.LOAN_CLIENT_BAL_ACCS B1 (NOLOCK) ON B1.BAL_ACC = @loan_bal_acc 
	LEFT OUTER JOIN	dbo.LOAN_ACCOUNTS A (NOLOCK) ON (A.LOAN_ID = @loan_id) AND (A.ACCOUNT_TYPE = T.TYPE_ID) 
	LEFT OUTER JOIN	dbo.ACCOUNTS ACC (NOLOCK) ON A.ACC_ID = ACC.ACC_ID
	LEFT OUTER JOIN	dbo.PLANLIST_ALT P (NOLOCK) ON P.BAL_ACC = CASE WHEN T.TYPE_ID IN (30, 35) THEN @loan_bal_acc ELSE CASE WHEN T.TYPE_ID = 20 THEN CONVERT(decimal(6,2), NULL) ELSE B.ACCOUNT_BAL_ACC END END
WHERE (T.ACC_SHOW_FLAG & @acc_show_flag = @acc_show_flag) AND (((@account_type IS NULL) OR ((@account_type IS NOT NULL) AND (T.TYPE_ID = @account_type))))
ORDER BY T.TYPE_ID
GO
