SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[bonus_show]
	@client_no int
AS

SET NOCOUNT ON;
	
SELECT BP.DESCRIP AS PRODUCT_DESCRIP, B.DESCRIP, C.*, B.BONUS_PRODUCT_ID,
	U.USER_FULL_NAME AS [ADDED_BY_DESCRIP], U2.USER_FULL_NAME AS [EXECUTED_BY_DESCRIP]
FROM dbo.CLIENT_BONUSES C (NOLOCK) 
	INNER JOIN dbo.BONUSES B (NOLOCK) ON B.REC_ID = C.BONUS_ID
	INNER JOIN dbo.BONUS_PRODUCTS BP (NOLOCK) ON BP.REC_ID = B.BONUS_PRODUCT_ID
	INNER JOIN dbo.USERS U (NOLOCK) ON U.[USER_ID] = C.ADDED_BY
	LEFT JOIN dbo.USERS U2 (NOLOCK) ON U2.[USER_ID] = C.EXECUTED_BY
WHERE C.CLIENT_NO = @client_no
GO
