SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE  PROCEDURE [dbo].[smart_card_remove]
	@client_id int,
	@user_id int
AS

SET NOCOUNT ON;

BEGIN TRAN

UPDATE dbo.CLIENTS
SET SMART_CARD_NO = NULL
WHERE CLIENT_NO = @client_id
IF @@ERROR <> 0 BEGIN IF @@TRANCOUNT > 0 ROLLBACK; RETURN 1; END 

INSERT INTO dbo.CLI_CHANGES (CLIENT_NO, [USER_ID], DESCRIP)
VALUES (@client_id, @user_id, 'ÓÌÀÒÔ ÁÀÒÀÈÉÓ ÂÀÖØÌÄÁÀ')
IF @@ERROR <> 0 BEGIN IF @@TRANCOUNT > 0 ROLLBACK; RETURN 1; END 

COMMIT
GO
