SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[GET_REPORT_KASSYM]
  @start_date smalldatetime,
  @end_date smalldatetime,
  @iso TISO,
  @equ bit
AS

SET NOCOUNT ON

IF @iso = 'GEL' SET @equ = 0
ELSE
IF @iso = '%%%' SET @equ = 1

SELECT
  D.OP_CODE,
  CASE WHEN (D.DOC_TYPE BETWEEN 120 AND 129) OR (D.DOC_TYPE BETWEEN 150 AND 159) THEN 0 ELSE 1 END AS KAS_TYPE,
  CASE WHEN @equ = 1 THEN D.AMOUNT_EQU ELSE D.AMOUNT END AS AMOUNT
INTO #TT
FROM dbo.OPS_ARC D (NOLOCK)
	INNER JOIN dbo.ACCOUNTS A1 (NOLOCK) ON A1.ACC_ID = D.DEBIT_ID
	INNER JOIN dbo.ACCOUNTS A2 (NOLOCK) ON A2.ACC_ID = D.CREDIT_ID
WHERE (D.DOC_TYPE BETWEEN 120 AND 159) AND
      (D.DOC_DATE >= @start_date) AND (D.DOC_DATE <= @end_date) AND
      ((@iso = '%%%' AND D.ISO <> 'GEL') OR (D.ISO = @iso)) AND
		(A1.BAL_ACC_ALT < 1018 OR A1.BAL_ACC_ALT >= 1019) AND
		(A2.BAL_ACC_ALT < 1018 OR A2.BAL_ACC_ALT >= 1019)

INSERT INTO #TT
SELECT
  D.OP_CODE,
  CASE WHEN (D.DOC_TYPE BETWEEN 120 AND 129) OR (D.DOC_TYPE BETWEEN 150 AND 159) THEN 0 ELSE 1 END AS KAS_TYPE,
  CASE WHEN @equ = 1 THEN D.AMOUNT_EQU ELSE D.AMOUNT END AS AMOUNT
FROM dbo.DOCS D (NOLOCK)
	INNER JOIN dbo.ACCOUNTS A1 (NOLOCK) ON A1.ACC_ID = D.DEBIT_ID
	INNER JOIN dbo.ACCOUNTS A2 (NOLOCK) ON A2.ACC_ID = D.CREDIT_ID
WHERE (D.DOC_TYPE BETWEEN 120 AND 159) AND
      (D.DOC_DATE >= @start_date) AND (D.DOC_DATE <= @end_date) AND
      ((@iso = '%%%' AND D.ISO <> 'GEL') OR (D.ISO = @iso)) AND
		(A1.BAL_ACC_ALT < 1018 OR A1.BAL_ACC_ALT >= 1019) AND
		(A2.BAL_ACC_ALT < 1018 OR A2.BAL_ACC_ALT >= 1019)


SELECT OP_CODE,KAS_TYPE,SUM(AMOUNT) AS AMOUNT
INTO #TTT
FROM #TT D
GROUP BY OP_CODE,KAS_TYPE
DROP TABLE #TT

SELECT T.OP_CODE, T.AMOUNT, K.DESCRIP, T.KAS_TYPE
FROM #TTT T
	LEFT OUTER JOIN dbo.KASSYM K ON (T.OP_CODE = K.SYMBOL)

DROP TABLE #TTT
GO
