SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_DELETE_AUTO_DOCS] @dt smalldatetime
AS

SET NOCOUNT ON;

DELETE FROM dbo.OPS_0000
WHERE DOC_TYPE = 97 AND OP_CODE IN ('*CLR*','*CVR*') AND PROD_ID = 0 AND FLAGS = 1 AND DOC_NUM IN (1,2)
GO
