SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BCC_EXP_BR_DOCS]
	@dept_no int,
	@step tinyint
AS

SET NOCOUNT ON

IF @step = 0
BEGIN
	DECLARE @flags int
	SELECT @flags = FLAGS FROM dbo.BC_CLIENTS (NOLOCK) WHERE BRANCH_ID = @dept_no
	SET @flags = ISNULL(@flags,0)

	INSERT dbo.BC_REC_IDS (SP_ID, REC_ID)
	SELECT DISTINCT @@SPID, S.REC_ID 
	FROM dbo.OPS_HELPER_0000 S (NOLOCK)
		INNER JOIN dbo.OPS_0000 D(NOLOCK) ON D.REC_ID = S.REC_ID
		INNER JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = S.ACC_ID
	WHERE A.BRANCH_ID = @dept_no AND ((@flags & 1024 = 0) OR (D.REC_STATE >= 10) OR (NOT D.DOC_TYPE IN (103,104,113,114))) /* can see red zach */
END

ELSE

IF @step = 1
BEGIN
	SELECT D.* 
	FROM dbo.BC_REC_IDS T (NOLOCK)
		INNER JOIN dbo.DOCS D (NOLOCK) ON D.REC_ID=T.REC_ID 
	WHERE T.SP_ID = @@SPID
END

ELSE

IF @step = 2
BEGIN
	SELECT DD.* 
	FROM dbo.DOC_DETAILS_PLAT DD (NOLOCK)
		INNER JOIN dbo.BC_REC_IDS D (NOLOCK) ON DD.DOC_REC_ID=D.REC_ID 
	WHERE D.SP_ID = @@SPID
END

ELSE

IF @step = 3
BEGIN
	SELECT DD.* 
	FROM dbo.DOC_DETAILS_VALPLAT DD (NOLOCK)
		INNER JOIN dbo.BC_REC_IDS D (NOLOCK) ON DD.DOC_REC_ID=D.REC_ID 
	WHERE D.SP_ID = @@SPID
END

/*ELSE

IF @step = 4
BEGIN
	SELECT TOP 0 DD.* 
	FROM dbo.BC_TEMPLATE_DOC_DETAILS_KAS DD(NOLOCK) 
END*/

ELSE

DELETE 
FROM dbo.BC_REC_IDS
WHERE SP_ID = @@SPID
GO
