SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[LOAN_SP_DELETE_OPS]
  @op_id int,
  @user_id int
AS
SET NOCOUNT ON
DECLARE
	@e int, @r int

DECLARE @T TABLE(OP_ID int NOT NULL PRIMARY KEY)

INSERT INTO @T(OP_ID)
SELECT OP_ID FROM dbo.LOAN_OPS
WHERE OP_ID=@op_id OR ISNULL(PARENT_OP_ID, 0) = @op_id

SET @r = 0
DECLARE cr CURSOR FORWARD_ONLY FOR
SELECT OP_ID FROM @T
ORDER BY OP_ID DESC
OPEN cr
FETCH NEXT FROM cr INTO @op_id
WHILE @@FETCH_STATUS = 0
BEGIN
	EXEC @r = dbo.LOAN_SP_DEL_EXEC_OP
		  @op_id = @op_id,
		  @user_id = @user_id
	IF @r <> 0 OR @@ERROR <> 0
		GOTO _ret

	DELETE FROM dbo.LOAN_OPS WHERE OP_ID=@op_id
	IF @@ERROR <> 0 BEGIN ROLLBACK RAISERROR ('ÛÄÝÃÏÌÀ 1 .',16,1) RETURN END
	IF @@ROWCOUNT <> 0 BEGIN ROLLBACK RAISERROR('RECORD NOT FOUND 1',16,1) RETURN END

	FETCH NEXT FROM cr INTO @op_id
END
_ret:
CLOSE cr
DEALLOCATE cr
RETURN @r

GO
