SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[LOAN_SP_GET_LOAN_SCHEDULE]
  @loan_id int
AS
SET NOCOUNT ON

DECLARE
	@loan_disbursed int

	SELECT @loan_disbursed = COUNT(*) FROM dbo.LOAN_OPS WHERE LOAN_ID = @loan_id AND OP_TYPE = dbo.loan_const_op_disburse() AND OP_STATE = 255

	IF @loan_disbursed > 0 AND EXISTS (SELECT * FROM dbo.LOAN_SCHEDULE WHERE LOAN_ID = @loan_id AND ORIGINAL_AMOUNT IS NOT NULL)
	BEGIN
		SELECT 
			LOAN_ID, SCHEDULE_DATE, INTEREST_DATE,
			ORIGINAL_AMOUNT AS AMOUNT,
			ORIGINAL_PRINCIPAL AS PRINCIPAL, 
			ORIGINAL_INTEREST AS INTEREST, 
			ORIGINAL_NU_INTEREST AS NU_INTEREST, 
			ORIGINAL_BALANCE AS BALANCE, 
			PAY_INTEREST,
			ORIGINAL_INSURANCE AS INSURANCE,
			ORIGINAL_SERVICE_FEE AS SERVICE_FEE,
			ORIGINAL_DEFERED_INTEREST AS DEFERED_INTEREST,
			ORIGINAL_DEFERED_OVERDUE_INTEREST AS DEFERED_OVERDUE_INTEREST,
			ORIGINAL_DEFERED_PENALTY AS DEFERED_PENALTY,
			ORIGINAL_DEFERED_FINE AS DEFERED_FINE
		FROM dbo.LOAN_SCHEDULE
		WHERE LOAN_ID = @loan_id AND ORIGINAL_AMOUNT IS NOT NULL
	END
	ELSE
	BEGIN
		SELECT 
			LOAN_ID, SCHEDULE_DATE, INTEREST_DATE,
			AMOUNT, PRINCIPAL, INTEREST, NU_INTEREST, BALANCE, PAY_INTEREST, INSURANCE, SERVICE_FEE,
			DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE
		FROM dbo.LOAN_SCHEDULE
		WHERE LOAN_ID = @loan_id
	END
GO
