SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_RETURN_LOAN_DETAILS]
	@loan_id int,
	@date smalldatetime -- თარიღი რომელიც უნდა გაიხსნას სესხისთვის
AS

DECLARE
	@e int, 
	@r int,
	@calc_date_to_return smalldatetime

											
	UPDATE LOAN_DETAILS
	SET
		CALC_DATE							= B.CALC_DATE,
		PREV_STEP							= B.PREV_STEP,
		NU_PRINCIPAL						= B.NU_PRINCIPAL,
		NU_INTEREST						 	= B.NU_INTEREST,
		NU_INTEREST_DAILY					= B.NU_INTEREST_DAILY,
		NU_INTEREST_FRACTION				= B.NU_INTEREST_FRACTION,
		PRINCIPAL							= B.PRINCIPAL,
		INTEREST							= B.INTEREST,
		INTEREST_DAILY						= B.INTEREST_DAILY,
		INTEREST_FRACTION					= B.INTEREST_FRACTION,
		LATE_DATE							= B.LATE_DATE,
		LATE_PRINCIPAL						= B.LATE_PRINCIPAL,
		LATE_PERCENT						= B.LATE_PERCENT,
		OVERDUE_DATE						= B.OVERDUE_DATE,
		OVERDUE_PRINCIPAL					= B.OVERDUE_PRINCIPAL,
		OVERDUE_PRINCIPAL_INTEREST			= B.OVERDUE_PRINCIPAL_INTEREST,
		OVERDUE_PRINCIPAL_INTEREST_DAILY	= B.OVERDUE_PRINCIPAL_INTEREST_DAILY,
		OVERDUE_PRINCIPAL_INTEREST_FRACTION = B.OVERDUE_PRINCIPAL_INTEREST_FRACTION,
		OVERDUE_PRINCIPAL_PENALTY			= B.OVERDUE_PRINCIPAL_PENALTY,
		OVERDUE_PRINCIPAL_PENALTY_DAILY	 	= B.OVERDUE_PRINCIPAL_PENALTY_DAILY,
		OVERDUE_PRINCIPAL_PENALTY_FRACTION	= B.OVERDUE_PRINCIPAL_PENALTY_FRACTION,
		OVERDUE_PERCENT					 	= B.OVERDUE_PERCENT,
		OVERDUE_PERCENT_PENALTY			 	= B.OVERDUE_PERCENT_PENALTY,
		OVERDUE_PERCENT_PENALTY_DAILY		= B.OVERDUE_PERCENT_PENALTY_DAILY,
		OVERDUE_PERCENT_PENALTY_FRACTION	= B.OVERDUE_PERCENT_PENALTY_FRACTION,
		CALLOFF_PRINCIPAL					= B.CALLOFF_PRINCIPAL,
		CALLOFF_PRINCIPAL_INTEREST			= B.CALLOFF_PRINCIPAL_INTEREST,
		CALLOFF_PRINCIPAL_INTEREST_DAILY	= B.CALLOFF_PRINCIPAL_INTEREST_DAILY,
		CALLOFF_PRINCIPAL_INTEREST_FRACTION = B.CALLOFF_PRINCIPAL_INTEREST_FRACTION,
		CALLOFF_PRINCIPAL_PENALTY			= B.CALLOFF_PRINCIPAL_PENALTY,
		CALLOFF_PRINCIPAL_PENALTY_DAILY	 	= B.CALLOFF_PRINCIPAL_PENALTY_DAILY,
		CALLOFF_PRINCIPAL_PENALTY_FRACTION	= B.CALLOFF_PRINCIPAL_PENALTY_FRACTION,
		CALLOFF_PERCENT					 	= B.CALLOFF_PERCENT,
		CALLOFF_PERCENT_PENALTY			 	= B.CALLOFF_PERCENT_PENALTY,
		CALLOFF_PERCENT_PENALTY_DAILY		= B.CALLOFF_PERCENT_PENALTY_DAILY,
		CALLOFF_PERCENT_PENALTY_FRACTION	= B.CALLOFF_PERCENT_PENALTY_FRACTION,
		CALLOFF_PENALTY					 	= B.CALLOFF_PENALTY,
		WRITEOFF_PRINCIPAL					= B.WRITEOFF_PRINCIPAL,
		WRITEOFF_PRINCIPAL_PENALTY			= B.WRITEOFF_PRINCIPAL_PENALTY,
		WRITEOFF_PRINCIPAL_PENALTY_DAILY	= B.WRITEOFF_PRINCIPAL_PENALTY_DAILY,
		WRITEOFF_PRINCIPAL_PENALTY_FRACTION	= B.WRITEOFF_PRINCIPAL_PENALTY_FRACTION,
		WRITEOFF_PERCENT					= B.WRITEOFF_PERCENT,
		WRITEOFF_PERCENT_PENALTY			= B.WRITEOFF_PERCENT_PENALTY,
		WRITEOFF_PERCENT_PENALTY_DAILY		= B.WRITEOFF_PERCENT_PENALTY_DAILY,
		WRITEOFF_PERCENT_PENALTY_FRACTION	= B.WRITEOFF_PERCENT_PENALTY_FRACTION,
		WRITEOFF_PENALTY					= B.WRITEOFF_PENALTY,
		IMMEDIATE_PENALTY					= B.IMMEDIATE_PENALTY,
		FINE								= B.FINE,
		MAX_CATEGORY_LEVEL					= B.MAX_CATEGORY_LEVEL,
		CATEGORY_1							= B.CATEGORY_1,
		CATEGORY_2							= B.CATEGORY_2,
		CATEGORY_3							= B.CATEGORY_3,
		CATEGORY_4							= B.CATEGORY_4,
		CATEGORY_5							= B.CATEGORY_5,
		CATEGORY_6							= B.CATEGORY_6,
		OVERDUE_INSURANCE					= B.OVERDUE_INSURANCE,
		OVERDUE_SERVICE_FEE					= B.OVERDUE_SERVICE_FEE,
		DEFERABLE_INTEREST					= B.DEFERABLE_INTEREST,
		DEFERABLE_OVERDUE_INTEREST			= B.DEFERABLE_OVERDUE_INTEREST,
		DEFERABLE_PENALTY					= B.DEFERABLE_PENALTY,
		DEFERABLE_FINE						= B.DEFERABLE_FINE,
		REMAINING_FEE						= B.REMAINING_FEE
	FROM dbo.LOAN_DETAILS A
		INNER JOIN dbo.LOAN_DETAILS_HISTORY B ON A.LOAN_ID = B.LOAN_ID 
	WHERE B.LOAN_ID = @loan_id AND B.CALC_DATE = @date

	SELECT @r = @@ROWCOUNT, @e = @@ERROR
	IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
	--IF @r = 0 BEGIN RAISERROR('ÛÄÝÃÏÌÀ ßÉÍÀ ÃÙÉÓ ÃÀÒÉÝáÅÄÁÉÓ ÀÙÃÂÄÍÉÓ ÃÒÏÓ !',16,1) RETURN(1) END

	IF @r <> 0 
	BEGIN
		DELETE FROM dbo.LOAN_DETAILS_HISTORY
		WHERE LOAN_ID = @loan_id AND CALC_DATE = @date
	
		SELECT @r = @@ROWCOUNT, @e = @@ERROR
		IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
		IF @r = 0 BEGIN RAISERROR('ÛÄÝÃÏÌÀ ßÉÍÀ ÃÙÉÓ ÃÀÒÉÝáÅÄÁÉÓ ÀÙÃÂÄÍÉÓ ÃÒÏÓ !',16,1) RETURN(1) END
	END

	RETURN(0)
GO
