SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[show_aml_credit_ops] 
	@client_no int,
	@dt1 smalldatetime,
	@dt2 smalldatetime
AS

DECLARE @tbl TABLE (DOC_TYPE int NOT NULL PRIMARY KEY)

INSERT INTO @tbl 
SELECT 	CASE 
		WHEN O.DOC_TYPE BETWEEN 100 AND 109 THEN 100
		WHEN O.DOC_TYPE BETWEEN 110 AND 119 THEN 110
		WHEN O.DOC_TYPE BETWEEN 120 AND 129 THEN 120
		WHEN O.DOC_TYPE BETWEEN 130 AND 149 THEN 130
	END

FROM dbo.OPS_0000 O (NOLOCK)
	INNER JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = O.CREDIT_ID
	LEFT JOIN dbo.ACCOUNTS A2 (NOLOCK) ON A2.ACC_ID = O.DEBIT_ID
WHERE A.CLIENT_NO = @client_no AND O.DOC_DATE BETWEEN @dt1 AND @dt2 AND O.DOC_TYPE BETWEEN 100 AND 149 AND (A.CLIENT_NO <> ISNULL(A2.CLIENT_NO, 0)) 
GROUP BY 
	CASE 
		WHEN O.DOC_TYPE BETWEEN 100 AND 109 THEN 100
		WHEN O.DOC_TYPE BETWEEN 110 AND 119 THEN 110
		WHEN O.DOC_TYPE BETWEEN 120 AND 129 THEN 120
		WHEN O.DOC_TYPE BETWEEN 130 AND 149 THEN 130
	END
HAVING SUM(O.AMOUNT_EQU) > 30000

SELECT O.*
FROM dbo.DOCS_ALL O (NOLOCK)
	INNER JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = O.CREDIT_ID
	LEFT JOIN dbo.ACCOUNTS A2 (NOLOCK) ON A2.ACC_ID = O.DEBIT_ID
	INNER JOIN @tbl T ON T.DOC_TYPE = 
		CASE 
			WHEN O.DOC_TYPE BETWEEN 100 AND 109 THEN 100
			WHEN O.DOC_TYPE BETWEEN 110 AND 119 THEN 110
			WHEN O.DOC_TYPE BETWEEN 120 AND 129 THEN 120
			WHEN O.DOC_TYPE BETWEEN 130 AND 149 THEN 130
		END
WHERE A.CLIENT_NO = @client_no AND O.DOC_DATE BETWEEN @dt1 AND @dt2 AND O.DOC_TYPE BETWEEN 100 AND 149 AND (A.CLIENT_NO <> ISNULL(A2.CLIENT_NO, 0)) 
ORDER BY T.DOC_TYPE, O.REC_ID
GO
