SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[loan_rep_portfolio] (
	@user_id int,
	@right_name varchar(100) = 'ÍÀáÅÀ',
	@field_list varchar(1000) = NULL,
	@view_name sysname = 'dbo.LOAN_VW_LOAN_REPS',
	@where_sql1 varchar(1000) = NULL,
	@where_sql2 varchar(1000) = NULL,
	@where_sql3 varchar(1000) = NULL,
	@join_sql varchar(1000) = NULL,
	@date smalldatetime,
	@distinct bit = 0)
AS
SET NOCOUNT ON;

CREATE TABLE #tbl (LOAN_ID INT PRIMARY KEY)

IF @date <> dbo.loan_open_date()
BEGIN
	SET @where_sql1 = REPLACE(@where_sql1, 'L.STATE', 'dbo.LOAN_FN_GET_STATE_IN_PERIOD(L.LOAN_ID, ' + CONVERT(varchar(20), CONVERT(money, @date)) + ')')
	SET @where_sql2 = REPLACE(@where_sql2, 'L.STATE', 'dbo.LOAN_FN_GET_STATE_IN_PERIOD(L.LOAN_ID, ' + CONVERT(varchar(20), CONVERT(money, @date)) + ')')
	SET @where_sql3 = REPLACE(@where_sql3, 'L.STATE', 'dbo.LOAN_FN_GET_STATE_IN_PERIOD(L.LOAN_ID, ' + CONVERT(varchar(20), CONVERT(money, @date)) + ')')
END

INSERT INTO #tbl
EXEC [dbo].[loan_show_loans]
	@user_id = @user_id,
	@right_name = @right_name,
	@field_list = 'L.LOAN_ID',
	@view_name = 'dbo.LOANS',
	@where_sql1 = @where_sql1,
	@where_sql2 = @where_sql2,
	@where_sql3 = @where_sql3,
	@join_sql = @join_sql,
	@distinct = @distinct

CREATE TABLE #tbl1 (LOAN_ID INT NOT NULL PRIMARY KEY, 
					DESCRIP varchar(100) NOT NULL, 
					DESCRIP_LAT varchar(100) NULL, 
					AMOUNT money NOT NULL,
					MAIN_COLLATERAL_LIST varchar(200) NULL,
					NU_PRINCIPAL money NULL,
					INTEREST money NULL,
					PRINCIPAL money NULL,
					OVERDUE_DAYS int NULL,
					OVERDUE_PRINCIPAL money NULL, 
					OVERDUE_PRINCIPAL_INTEREST money NULL,
                    OVERDUE_PRINCIPAL_PENALTY money NULL, 
					OVERDUE_PERCENT money NULL,
					PENALTY money NULL,
					OVERDUE_PERCENT_PENALTY	money NULL,
					WHOLE_PRINCIPAL money NULL,
					INTEREST_PLUS_PENALTY money NULL,
					ALL_DEBT money NULL,
					REMAINING_FEE money NULL,
					CATEGORY_1 money NULL, 
					CATEGORY_2 money NULL, 
					CATEGORY_3 money NULL, 
					CATEGORY_4 money NULL, 
					CATEGORY_5 money NULL,
					BENNEFICIAR varchar(400) NULL,
					CERTIFIED_AMOUNT money NULL,
					CERTIFIER varchar(400) NULL)

DECLARE cc CURSOR LOCAL FAST_FORWARD
FOR
SELECT LOAN_ID
FROM #tbl

DECLARE @loan_id int
OPEN cc
FETCH NEXT FROM cc INTO @loan_id

WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO #tbl1
		(LOAN_ID, DESCRIP, DESCRIP_LAT, AMOUNT, MAIN_COLLATERAL_LIST, NU_PRINCIPAL, INTEREST, PRINCIPAL, OVERDUE_DAYS,
		 OVERDUE_PRINCIPAL, OVERDUE_PRINCIPAL_INTEREST, OVERDUE_PRINCIPAL_PENALTY, OVERDUE_PERCENT, PENALTY, OVERDUE_PERCENT_PENALTY,
		 WHOLE_PRINCIPAL, INTEREST_PLUS_PENALTY, ALL_DEBT, REMAINING_FEE,
		 CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, CATEGORY_5, BENNEFICIAR, CERTIFIED_AMOUNT, CERTIFIER)
	SELECT LCD.LOAN_ID, LCD.DESCRIP, LCD.DESCRIP_LAT, LCD.AMOUNT, LCD.MAIN_COLLATERAL_LIST,
		   LDD.NU_PRINCIPAL, LDD.INTEREST + LDD.NU_INTEREST, LDD.PRINCIPAL, LDD.OVERDUE_DAYS,
		   LDD.OVERDUE_PRINCIPAL, LDD.OVERDUE_PRINCIPAL_INTEREST, LDD.OVERDUE_PRINCIPAL_PENALTY, 
		   LDD.OVERDUE_PERCENT, LDD.OVERDUE_PRINCIPAL_PENALTY + LDD.OVERDUE_PERCENT_PENALTY, LDD.OVERDUE_PERCENT_PENALTY,
		   LDD.PRINCIPAL + LDD.OVERDUE_PRINCIPAL, LDD.INTEREST + LDD.NU_INTEREST + LDD.OVERDUE_PRINCIPAL_PENALTY + LDD.OVERDUE_PERCENT_PENALTY,
		   LDD.PRINCIPAL + LDD.LATE_PRINCIPAL + LDD.OVERDUE_PRINCIPAL + LDD.NU_INTEREST + LDD.INTEREST + LDD.OVERDUE_PRINCIPAL_INTEREST +
		   LDD.LATE_PERCENT + LDD.OVERDUE_PERCENT + LDD.OVERDUE_PRINCIPAL_PENALTY + LDD.OVERDUE_PERCENT_PENALTY, LDD.REMAINING_FEE,
		   LDD.CATEGORY_1, LDD.CATEGORY_2, LDD.CATEGORY_3, LDD.CATEGORY_4, LDD.CATEGORY_5, A1.ATTRIB_VALUE, A2.ATTRIB_VALUE, A3.ATTRIB_VALUE
	FROM dbo.loan_get_loan_collateral_data(@loan_id, @date) LCD
		INNER JOIN dbo.loan_get_loan_detail_data(@loan_id, @date) LDD ON LDD.LOAN_ID = LCD.LOAN_ID
		LEFT JOIN dbo.LOAN_ATTRIBUTES A1 ON LCD.LOAN_ID = A1.LOAN_ID AND A1.ATTRIB_CODE = 'BNFCR'
		LEFT JOIN dbo.LOAN_ATTRIBUTES A2 ON LCD.LOAN_ID = A2.LOAN_ID AND A2.ATTRIB_CODE = 'CAMNT'
		LEFT JOIN dbo.LOAN_ATTRIBUTES A3 ON LCD.LOAN_ID = A3.LOAN_ID AND A3.ATTRIB_CODE = 'CBANK'

	FETCH NEXT FROM cc INTO @loan_id
END
CLOSE cc
DEALLOCATE cc

--- ÞÉÒÉÈÀÃÉ ÌÏÍÀÝÄÌÄÁÉÓ ßÀÌÏÙÄÁÀ ---

DECLARE @sql nvarchar(4000)

IF @field_list IS NULL OR @field_list = '*'
	SET @field_list = 'L.*'

SET @sql = N'
	DECLARE @loan_open_date smalldatetime
	SET @loan_open_date = dbo.loan_open_date()
'

SET @sql = @sql + N'
SELECT ' + @field_list + N', dbo.LOAN_FN_LOAN_FIRST_PROLONG_DATE (L.LOAN_ID) AS FIRST_PROLONG_DATE, dbo.LOAN_FN_LOAN_SECOND_PROLONG_DATE (L.LOAN_ID) AS SECOND_PROLONG_DATE,
							 R.OVERDUE_PRINCIPAL_INTEREST, R.OVERDUE_PRINCIPAL_PENALTY,
							 R.OVERDUE_PERCENT_PENALTY, 
							 R.DESCRIP AS COLLATERAL_DESCRIP, R.DESCRIP_LAT AS COLLATERAL_DESCRIP_LAT, R.AMOUNT AS COLLATERAL_AMOUNT, R.MAIN_COLLATERAL_LIST, 
							 R.NU_PRINCIPAL, dbo.get_equ(R.NU_PRINCIPAL, L.ISO, @date) AS NU_PRINCIPAL_EQU,
							 R.INTEREST, dbo.get_equ(R.INTEREST, L.ISO, @date) AS INTEREST_EQU,
							 R.PRINCIPAL, dbo.get_equ(R.PRINCIPAL,L.ISO, @date) AS PRINCIPAL_EQU,
							 R.OVERDUE_PERCENT, dbo.get_equ(R.OVERDUE_PERCENT, L.ISO, @date) AS OVERDUE_PERCENT_EQU,
							 R.PENALTY, dbo.get_equ(R.PENALTY, L.ISO, @date) AS PENALTY_EQU,
							 R.OVERDUE_PRINCIPAL, dbo.get_equ(R.OVERDUE_PRINCIPAL, L.ISO, @date) AS OVERDUE_PRINCIPAL_EQU,
							 R.OVERDUE_DAYS,
						   	 R.WHOLE_PRINCIPAL, dbo.get_equ(R.WHOLE_PRINCIPAL, L.ISO, @date) AS WHOLE_PRINCIPAL_EQU,
							 R.INTEREST_PLUS_PENALTY, dbo.get_equ(R.INTEREST_PLUS_PENALTY, L.ISO, @date) AS INTEREST_PLUS_PENALTY_EQU,
							 R.ALL_DEBT, dbo.get_equ(R.ALL_DEBT, L.ISO, @date) AS ALL_DEBT_EQU,
							 dbo.get_equ(L.AMOUNT, L.ISO, @date) AS LOAN_AMOUNT_EQU,
							 R.REMAINING_FEE, dbo.get_equ(R.REMAINING_FEE, L.ISO, @date) AS REMAINING_FEE_EQU,
							 dbo.LOAN_FN_GET_CLIENT_RATING_HISTORY(L.CLIENT_NO, @date) AS RAITING,

							 ROUND(dbo.get_equ(R.CATEGORY_1, L.ISO, @date) * L.RISK_PERC_RATE_1/100, 2, 1) AS RISK_CATEGORY_1_BALANCE,
							 ROUND(dbo.get_equ(R.CATEGORY_2, L.ISO, @date) * L.RISK_PERC_RATE_2/100, 2, 1) AS RISK_CATEGORY_2_BALANCE,
							 ROUND(dbo.get_equ(R.CATEGORY_3, L.ISO, @date) * L.RISK_PERC_RATE_3/100, 2, 1) AS RISK_CATEGORY_3_BALANCE,
							 ROUND(dbo.get_equ(R.CATEGORY_4, L.ISO, @date) * L.RISK_PERC_RATE_4/100, 2, 1) AS RISK_CATEGORY_4_BALANCE,
							 ROUND(dbo.get_equ(R.CATEGORY_5, L.ISO, @date) * L.RISK_PERC_RATE_5/100, 2, 1) AS RISK_CATEGORY_5_BALANCE,
							 R.BENNEFICIAR, CERTIFIED_AMOUNT, CERTIFIER
FROM ' + @view_name + N' L
	INNER JOIN #tbl1 R ON R.LOAN_ID = L.LOAN_ID	
'

--PRINT @sql

EXEC sp_executesql @sql, N'@date smalldatetime', @date
DROP TABLE #tbl
DROP TABLE #tbl1
GO
