SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[BCC_GET_SETTING_INT]
  @param_name varchar(20),
  @val TACCOUNT OUTPUT
AS

SET NOCOUNT ON

SELECT @val = VALS 
FROM dbo.INI_INT (NOLOCK)
WHERE IDS = @param_name
IF @@ROWCOUNT=0
  SET @val = 0
GO
