SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_DISABLE_CONSTRAINTS] @TableName nvarchar(255) AS SET NOCOUNT ON

 EXEC ('ALTER TABLE ' + @TableName + ' DISABLE TRIGGER ALL')  EXEC ('ALTER TABLE ' + @TableName + ' NOCHECK CONSTRAINT ALL')
GO
