SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[GET_OTHER_ACC_NAME]
  @bank_code  	TINTBANKCODE,
  @account  	TINTACCOUNT,
  @iso		TISO,
  @acc_name	varchar(100) OUTPUT
AS

SET NOCOUNT ON

SELECT @acc_name  = DESCRIP
FROM   OTHER_ACCOUNTS (NOLOCK)
WHERE  BANK_CODE = @bank_code AND ACCOUNT = @account

IF @@ROWCOUNT = 0 RETURN (1)
RETURN (0)


GO
