SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Cannot merge following tables
-- CLIENTS_FACSIMILE
-- CLIENTS_FACSIMILE_ARC
-- CLIENTS_ARC
-- CLI_CHANGES
-- CLIENTS_BLOB
-- CLIENT_NOTES
-- CLIENT_EXTENSIONS (SGBR)
-- CLIENT_EXTENSIONS2 (TBC)
-- BC_CLIENTS...


CREATE PROCEDURE [dbo].[merge_2clients] (@client_no int, @client_no2 int)
AS

SET NOCOUNT ON;

BEGIN TRAN

DECLARE @tbl_i TABLE (I int)
DECLARE @tbl_s TABLE (S varchar(max))

-- CLIENT_ATTRIBUTES
INSERT INTO dbo.CLIENT_ATTRIBUTES
OUTPUT inserted.ATTRIB_CODE INTO @tbl_s
SELECT @client_no, ATTRIB_CODE, ATTRIB_VALUE
FROM dbo.CLIENT_ATTRIBUTES A
WHERE A.CLIENT_NO = @client_no2 AND NOT EXISTS(SELECT * FROM dbo.CLIENT_ATTRIBUTES B WHERE B.CLIENT_NO = @client_no AND B.ATTRIB_CODE = A.ATTRIB_CODE)

DELETE A
FROM dbo.CLIENT_ATTRIBUTES A
	INNER JOIN @tbl_s B ON B.S = A.ATTRIB_CODE
WHERE A.CLIENT_NO = @client_no2
DELETE FROM @tbl_s 

-- CLIENTS_USR
INSERT INTO dbo.CLIENTS_USR ([USER_ID], [CLIENT_NO])
SELECT A.[USER_ID], @client_no
FROM dbo.CLIENTS_USR A
WHERE A.CLIENT_NO = @client_no2 AND NOT EXISTS(SELECT * FROM dbo.CLIENTS_USR B WHERE B.CLIENT_NO = @client_no AND B.[USER_ID] = A.[USER_ID])

-- CLIENTS_CLASSIF 
INSERT INTO dbo.CLIENTS_CLASSIF (CLIENT_ID, [ID])
OUTPUT inserted.ID INTO @tbl_s
SELECT @client_no, [ID]
FROM dbo.CLIENTS_CLASSIF A
WHERE A.CLIENT_ID = @client_no2 AND NOT EXISTS(SELECT * FROM dbo.CLIENTS_CLASSIF B WHERE B.CLIENT_ID = @client_no AND B.[ID] = A.[ID])

DELETE A
FROM dbo.CLIENTS_CLASSIF A
	INNER JOIN @tbl_s B ON B.S = A.ID
WHERE A.CLIENT_ID = @client_no2
DELETE FROM @tbl_s 

-- CLIENT_ATTACHMENTS
INSERT INTO dbo.CLIENT_ATTACHMENTS
OUTPUT inserted.[FILE_NAME] INTO @tbl_s
SELECT @client_no, [FILE_NAME], IS_FOLDER, FILE_DATA
FROM dbo.CLIENT_ATTACHMENTS A
WHERE A.CLIENT_NO = @client_no2 AND NOT EXISTS(SELECT * FROM dbo.CLIENT_ATTACHMENTS B WHERE B.CLIENT_NO = @client_no AND B.[FILE_NAME] = A.[FILE_NAME])

DELETE A
FROM dbo.CLIENT_ATTACHMENTS A
	INNER JOIN @tbl_s B ON B.S = A.[FILE_NAME]
WHERE A.CLIENT_NO = @client_no2
DELETE FROM @tbl_s 

-- CLIENT_RELATIONS
INSERT INTO dbo.CLIENT_RELATIONS
SELECT @client_no, REL_CLIENT_NO, CLIENT_RELATION_TYPE_ID, INT_VALUE, STR_VALUE, MONEY_VALUE
FROM dbo.CLIENT_RELATIONS A
WHERE A.CLIENT_NO = @client_no2 AND NOT EXISTS(SELECT * FROM dbo.CLIENT_RELATIONS B WHERE B.CLIENT_NO = @client_no AND B.REL_CLIENT_NO = A.REL_CLIENT_NO AND B.CLIENT_RELATION_TYPE_ID = A.CLIENT_RELATION_TYPE_ID)

INSERT INTO dbo.CLIENT_RELATIONS
SELECT CLIENT_NO, @client_no, CLIENT_RELATION_TYPE_ID, INT_VALUE, STR_VALUE, MONEY_VALUE
FROM dbo.CLIENT_RELATIONS A
WHERE A.REL_CLIENT_NO = @client_no2 AND NOT EXISTS(SELECT * FROM dbo.CLIENT_RELATIONS B WHERE B.REL_CLIENT_NO = @client_no2 AND B.CLIENT_NO = A.CLIENT_NO AND B.CLIENT_RELATION_TYPE_ID = A.CLIENT_RELATION_TYPE_ID)

DELETE FROM dbo.CLIENT_RELATIONS
WHERE CLIENT_NO = @client_no2 OR REL_CLIENT_NO = @client_no2 

--

-- ACCOUNTS
UPDATE dbo.ACCOUNTS
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

UPDATE dbo.ACCOUNTS_ARC
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

-- USERS
UPDATE dbo.USERS
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

-- INCASSO
UPDATE dbo.INCASSO
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

UPDATE dbo.INCASSO_ARC
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

-- DOC_DETAILS_CONV
UPDATE dbo.DOC_DETAILS_CONV
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

UPDATE dbo.DOC_DETAILS_CONV
SET RATE_CLIENT_NO = @client_no
WHERE RATE_CLIENT_NO = @client_no2

UPDATE dbo.DOC_DETAILS_ARC_CONV
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

UPDATE dbo.DOC_DETAILS_ARC_CONV
SET RATE_CLIENT_NO = @client_no
WHERE RATE_CLIENT_NO = @client_no2

-- PLASTIC_CARDS
UPDATE dbo.PLASTIC_CARDS
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

UPDATE dbo.PLASTIC_CARDS_FOR_SEND
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2



-- CALL_CENTER_CODES
--Zura
UPDATE dbo.CALL_CENTER_CODES
SET [STATUS] = 2
WHERE CLIENT_NO = @client_no2
--Zura

UPDATE dbo.CALL_CENTER_CODES
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

--Zura
UPDATE dbo.CLIENTS 
SET CLIENT_TYPE_BANK = CLIENT_TYPE_BANK | 32 
WHERE CLIENT_NO = @client_no2

UPDATE dbo.ACCOUNTS 
SET FLAGS = FLAGS | 16, 
	CODE_PHRASE = NULL 
WHERE CLIENT_NO = @client_no2
--Zura

-- SWIFT_STATEMENTS_LIST
UPDATE dbo.SWIFT_STATEMENTS_LIST
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

-- SWIFT_CLIENT_REG
UPDATE dbo.SWIFT_CLIENT_REG
SET CLIENT_NO = @client_no
WHERE CLIENT_NO = @client_no2

COMMIT
GO
