SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[call_center_loans2007_details]
	@client_no int,
	@loan_id int,
	@user_id int
AS
	DECLARE @T TABLE(
		REC_ID int NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		DESCRIP varchar(150) NOT NULL,
		[VALUE] varchar(150) NOT NULL,
		ROW_COLOR int NOT NULL DEFAULT(0xFFFFFF)
	)
	
	INSERT INTO @T(DESCRIP, [VALUE], ROW_COLOR)
	VALUES('DESCRIP', 'VALUE', 0xFFFFFF)

	SELECT * FROM @T
GO
