SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_CREATE_VAL_RATES_VIEW]
AS

DECLARE 
	@sql nvarchar(2000),
	@year int,
	@y int

SET @sql = N'IF OBJECT_ID(''VAL_RATES'')<>0 DROP VIEW dbo.VAL_RATES'
EXEC sp_executesql @sql

SET @sql = N'CREATE VIEW dbo.VAL_RATES AS

SELECT * FROM dbo.VAL_RATES_0000 (NOLOCK)
  UNION ALL' + CHAR(13)

SET @year = YEAR(dbo.bank_first_date ())
IF @year < 2000
	SET @year = 2000

DECLARE @dt smalldatetime
  
SET @dt = dbo.bank_open_date() - 1

SET @y = @year
WHILE @y <= YEAR(@dt)
BEGIN
  SET @sql = @sql + N'SELECT * FROM dbo.VAL_RATES_' + CONVERT(nvarchar(4), @y) + ' (NOLOCK)' + CHAR(13)
  IF @y <> YEAR(@dt)
    SET @sql = @sql + N'  UNION ALL' + CHAR(13)
  SET @y = @y + 1
END

EXEC sp_executesql @sql

--

SET @dt = @dt + 1

SET @sql = N'IF OBJECT_ID(''VAL_RATES_OLD'')<>0 DROP VIEW dbo.VAL_RATES_OLD'
EXEC sp_executesql @sql

SET @sql = N'CREATE VIEW dbo.VAL_RATES_OLD AS' + CHAR(13)

DECLARE @open_year int

IF @year = YEAR(@dt)
	SET @sql = @sql + N'SELECT TOP 0 * FROM dbo.VAL_RATES_0000 (NOLOCK)' + CHAR(13)
ELSE
BEGIN
	SET @y = @year
	WHILE @y <= YEAR(@dt) - 1
	BEGIN
	  SET @sql = @sql + N'SELECT * FROM dbo.VAL_RATES_' + CONVERT(nvarchar(4), @y) + ' (NOLOCK)' + CHAR(13)
	  IF @y <> YEAR(@dt) - 1
		SET @sql = @sql + N'  UNION ALL' + CHAR(13)
	  SET @y = @y + 1
	END
END

EXEC sp_executesql @sql

--

SET @sql = N'
-- Autogenerated by dbo.SYS_CREATE_VAL_RATES_VIEW
ALTER FUNCTION dbo.get_equ (@amount money, @ccy TISO, @date smalldatetime)
RETURNS money AS
BEGIN
  DECLARE @equ money

  IF @amount = $0.0000 OR @ccy = ''GEL''
    SET @equ = @amount
  ELSE
  BEGIN
	SET @equ = NULL

    SELECT TOP 1 @equ = (@amount * A.AMOUNT) / A.ITEMS
    FROM  dbo.VAL_RATES_0000 A (NOLOCK)
    WHERE A.ISO = @ccy AND A.DT <= @date
	ORDER BY A.DT DESC

	IF @equ IS NULL
		SELECT TOP 1 @equ = (@amount * A.AMOUNT) / A.ITEMS
		FROM  dbo.VAL_RATES_' + CONVERT(nvarchar(4), YEAR(@dt)) + ' A (NOLOCK)
		WHERE A.ISO = @ccy AND A.DT <= @date
		ORDER BY A.DT DESC

	IF @equ IS NULL
		SELECT TOP 1 @equ = (@amount * A.AMOUNT) / A.ITEMS
		FROM  dbo.VAL_RATES_OLD A (NOLOCK)
		WHERE A.ISO = @ccy AND A.DT <= @date
		ORDER BY A.DT DESC
  END

  RETURN ROUND(@equ, 4)
END'

EXEC sp_executesql @sql
GO
