SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_MOVE_ALL_DOCS_TO_ARC]
  @dt smalldatetime
AS

SET NOCOUNT ON

DECLARE 
	@year int,
	@sql nvarchar(4000),
	@e int,
	@r int

SET @year = YEAR(@dt)

SET @sql = N'
DECLARE @tbl TABLE (REC_ID int NOT NULL PRIMARY KEY CLUSTERED)

INSERT INTO @tbl (REC_ID) SELECT REC_ID FROM dbo.OPS_0000 WITH (XLOCK) WHERE DOC_DATE = @dt

INSERT INTO dbo.' + dbo.sys_get_arc_table_name('OPS',@year) + N'
SELECT DD.*
FROM dbo.OPS_0000 DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERRORIF @e<>0 RETURN

INSERT INTO dbo.DOC_DETAILS_ARC_PLAT 
SELECT DD.* 
FROM dbo.DOC_DETAILS_PLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURNDELETE FROM dbo.DOC_DETAILS_PLAT
FROM dbo.DOC_DETAILS_PLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURNINSERT INTO dbo.DOC_DETAILS_ARC_VALPLAT 
SELECT DD.* 
FROM dbo.DOC_DETAILS_VALPLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.DOC_DETAILS_VALPLAT
FROM dbo.DOC_DETAILS_VALPLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN

INSERT INTO dbo.DOC_DETAILS_ARC_CONV
SELECT DD.* 
FROM dbo.DOC_DETAILS_CONV DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_IDSET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.DOC_DETAILS_CONV
FROM dbo.DOC_DETAILS_CONV DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_DETAILS_ARC_PASSPORTS
SELECT DD.* 
FROM dbo.DOC_DETAILS_PASSPORTS DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_IDSET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.DOC_DETAILS_PASSPORTS
FROM dbo.DOC_DETAILS_PASSPORTS DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_DETAILS_ARC_PERC
SELECT DD.* 
FROM dbo.DOC_DETAILS_PERC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_IDSET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.DOC_DETAILS_PERC
FROM dbo.DOC_DETAILS_PERC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_ATTRIBUTES_ARC
SELECT DD.* 
FROM dbo.DOC_ATTRIBUTES DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_IDSET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.DOC_ATTRIBUTES
FROM dbo.DOC_ATTRIBUTES DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_CHANGES_ARC
SELECT DD.* 
FROM dbo.DOC_CHANGES DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.DOC_CHANGES
FROM dbo.DOC_CHANGES DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN

DELETE FROM dbo.OPS_0000
FROM dbo.OPS_0000 DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERRORIF @e<>0 RETURNINSERT INTO dbo.' + dbo.sys_get_arc_table_name('VAL_RATES',@year) + N'
SELECT *
FROM dbo.VAL_RATES_0000 WITH (XLOCK)
WHERE DT = @dt
SET @e=@@ERROR
IF @e<>0 RETURN
DELETE FROM dbo.VAL_RATES_0000
FROM dbo.VAL_RATES_0000 WITH (XLOCK)
WHERE DT = @dt
SET @e=@@ERROR'
EXEC @r = sp_executesql @sql, N'@dt smalldatetime, @e int OUTPUT', @dt, @e OUTPUT
IF @@ERROR <> 0 OR @r <> 0 OR @e <> 0 RETURN (99)

RETURN (0)
GO
