SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[depo_sp_show_depo_transactions]
	@depo_id int,
	@only_accruals bit = 0
AS

DECLARE @T TABLE(DEPO_ACC_ID int NOT NULL PRIMARY KEY)

INSERT INTO @T
SELECT DISTINCT D.DEPO_ACC_ID
FROM
(SELECT DEPO_ACC_ID
FROM dbo.DEPO_DEPOSITS_HISTORY (NOLOCK)
WHERE (DEPO_ID = @depo_id)
UNION
SELECT DEPO_ACC_ID
FROM dbo.DEPO_DEPOSITS (NOLOCK)
WHERE (DEPO_ID = @depo_id)) D

DECLARE
	@start_date smalldatetime

SELECT @start_date = [START_DATE]
FROM dbo.DEPO_DEPOSITS (NOLOCK)
WHERE DEPO_ID = @depo_id

IF @only_accruals = 0
BEGIN
	SELECT DA.* 
	FROM dbo.DOCS_ARC_ALL DA (NOLOCK)
		INNER JOIN @T T ON DA.ACCOUNT_EXTRA = T.DEPO_ACC_ID
	WHERE DA.DOC_DATE >= @start_date
	UNION
	SELECT DA.* 
	FROM dbo.OPS_HELPER_ARC OH (NOLOCK)
		INNER JOIN @T T ON OH.ACC_ID = T.DEPO_ACC_ID
		INNER JOIN dbo.DOCS_ARC_ALL DA (NOLOCK) ON (DA.DOC_DATE = OH.DT) AND (DA.REC_ID = OH.REC_ID)
	WHERE OH.DT >= @start_date
	UNION
	SELECT DA.* 
	FROM dbo.DOCS_ALL DA (NOLOCK)
		INNER JOIN @T T ON DA.ACCOUNT_EXTRA = T.DEPO_ACC_ID
	UNION
	SELECT DA.* 
	FROM dbo.OPS_HELPER OH (NOLOCK)
		INNER JOIN @T T ON OH.ACC_ID = T.DEPO_ACC_ID
		INNER JOIN dbo.DOCS_ALL DA (NOLOCK) ON (DA.DOC_DATE = OH.DT) AND (DA.REC_ID = OH.REC_ID)
END	
ELSE
BEGIN
	SELECT DA.* 
	FROM dbo.DOCS_ARC_ALL DA (NOLOCK)
		INNER JOIN @T T ON DA.ACCOUNT_EXTRA = T.DEPO_ACC_ID
	WHERE (DA.DOC_DATE >= @start_date) AND  (DA.DOC_TYPE = 30)
	UNION ALL
	SELECT DA.* 
	FROM dbo.DOCS_ALL DA (NOLOCK)
		INNER JOIN @T T ON DA.ACCOUNT_EXTRA = T.DEPO_ACC_ID
	WHERE DA.DOC_TYPE = 30
END

GO
