SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[depo_sp_get_deposit_intrate]
	@prod_id int,
	@iso char(3),
	@period int,
	@intrate money = NULL OUTPUT,
	@show_result bit = 1
AS
BEGIN

DECLARE
	@interest_correction money
	
SELECT @interest_correction = INTEREST_CORRECTION
FROM dbo.DEPO_PRODUCT (NOLOCK)
WHERE PROD_ID = @prod_id

IF @show_result = 0
BEGIN
	WITH intrates([SCHEMA_ID], ISO, ITEMS) AS
	(
		SELECT S.[SCHEMA_ID], S.ISO, MAX(S.ITEMS) AS ITEMS
		FROM dbo.DEPO_PRODUCT_INTRATE_SCHEMA_DETAILS S (NOLOCK)
			INNER JOIN dbo.DEPO_PRODUCT P (NOLOCK) ON P.INTRATE_SCHEMA = S.[SCHEMA_ID]
		WHERE P.PROD_ID = @prod_id AND S.ISO = @iso AND ((@period IS NULL) OR (S.ITEMS <= @period))
		GROUP BY [SCHEMA_ID], ISO
	)
	SELECT @intrate = S.INTRATE + ISNULL(@interest_correction, $0.00)
	FROM dbo.DEPO_PRODUCT_INTRATE_SCHEMA_DETAILS  S (NOLOCK)
		INNER JOIN intrates I ON S.[SCHEMA_ID] = I.[SCHEMA_ID] AND S.ISO =  I.ISO AND S.ITEMS = I.ITEMS
END
ELSE
BEGIN
	WITH intrates([SCHEMA_ID], ISO, ITEMS) AS
	(
		SELECT S.[SCHEMA_ID], S.ISO, MAX(S.ITEMS) AS ITEMS
		FROM dbo.DEPO_PRODUCT_INTRATE_SCHEMA_DETAILS S (NOLOCK)
			INNER JOIN dbo.DEPO_PRODUCT P (NOLOCK) ON P.INTRATE_SCHEMA = S.[SCHEMA_ID]
		WHERE P.PROD_ID = @prod_id AND S.ISO = @iso AND ((@period IS NULL) OR (S.ITEMS <= @period))
		GROUP BY [SCHEMA_ID], ISO
	)
	SELECT S.INTRATE + ISNULL(@interest_correction, $0.00) AS INTRATE
	FROM dbo.DEPO_PRODUCT_INTRATE_SCHEMA_DETAILS  S (NOLOCK)
		INNER JOIN intrates I ON S.[SCHEMA_ID] = I.[SCHEMA_ID] AND S.ISO =  I.ISO AND S.ITEMS = I.ITEMS
END		

	RETURN 0
END

GO
