SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_CREATE_NEW_YEAR]
AS

SET NOCOUNT ON;

DECLARE
  @date smalldatetime,
  @r int

SET @date = dbo.bank_open_date ()

DECLARE @msg nvarchar(255)
SET @msg =  'CLOSING YEAR: ' + CONVERT(varchar(4),YEAR(@date))
PRINT @msg

IF DAY(@date + 1) <> 2 OR MONTH(@date + 1) <> 1
BEGIN
  SET @msg = CONVERT(varchar(20), @date, 103)
  RAISERROR ('<ERR>Cannot close year. %s is not JAN 01</ERR>', 16, 1, @msg)
  RETURN(-1009)
END

DECLARE @year int
SET @year = YEAR(@date)

UPDATE dbo.INI_DT
SET VALS = VALS + 1
WHERE IDS = 'OPEN_BANK_DATE'

EXEC dbo.SYS_CREATE_OPS_TABLE @year, 0
EXEC dbo.SYS_CREATE_OPS_VIEW 1, 0
EXEC dbo.SYS_CREATE_OPS_VIEW 0, 1
EXEC dbo.SYS_CREATE_OPS_VIEW 0, 0

EXEC dbo.SYS_CREATE_BAL_TABLE @year, 0
EXEC dbo.SYS_CREATE_BAL_VIEW 0
EXEC dbo.SYS_CREATE_BAL_VIEW 1
EXEC dbo.SYS_CREATE_BAL_VIEW 2

EXEC dbo.SYS_CREATE_SALDOS_TABLE @year, 0
EXEC dbo.SYS_CREATE_SALDOS_VIEW 

EXEC dbo.SYS_CREATE_OPS_HELPER_TABLE @year, 0
EXEC dbo.SYS_CREATE_OPS_HELPER_VIEW 1, 0
EXEC dbo.SYS_CREATE_OPS_HELPER_VIEW 0, 1
EXEC dbo.SYS_CREATE_OPS_HELPER_VIEW 0, 0

EXEC dbo.SYS_CREATE_VAL_RATES_TABLE @year, 0
EXEC dbo.SYS_CREATE_VAL_RATES_VIEW

UPDATE dbo.INI_DT
SET VALS = VALS - 1
WHERE IDS = 'OPEN_BANK_DATE'
GO
