SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BCC_EXP_BIC_CODES]
AS

SET NOCOUNT ON

DECLARE @bic varchar(11)
EXEC dbo.GET_SETTING_STR 'OUR_BANK_CODE_INT', @bic OUTPUT

SET @bic = SUBSTRING(@bic, 1, 8) + '%'
SELECT BIC, DESCRIP, REC_STATE
FROM dbo.BIC_CODES
WHERE BIC LIKE @bic
GO
