SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[depo_sp_show_depo_ops]
	@depo_id int = Null,
	@op_type int = Null,
	@op_id int = Null,
	@eng_version bit = 0 
AS

SET NOCOUNT ON;

	DECLARE
		@last_op_id int

	SELECT TOP 1 @last_op_id = OP_ID 
	FROM dbo.DEPO_OP (NOLOCK) 
	WHERE DEPO_ID = @depo_id
	ORDER BY OP_ID DESC

	SELECT O.OP_ID, O.DEPO_ID, O.OP_DATE, O.OP_TYPE, O.OP_STATE,
		CASE WHEN @eng_version = 0 THEN T.DESCRIP ELSE T.DESCRIP_LAT END AS OP_DESCRIP,
		O.AMOUNT, O.ISO, T.SELF_EXEC, @last_op_id AS LAST_OP_ID, O.BY_PROCESSING,
		O.DOC_REC_ID, O.ACCRUE_DOC_REC_ID, O.OP_NOTE, O.ALARM_NOTE, 
		O.OWNER, RTRIM(U.USER_NAME) + '@' + DP_U.ALIAS AS U_OWNER_NAME,
		O.AUTH_OWNER, CASE WHEN US.USER_NAME IS NULL THEN US.USER_NAME ELSE RTRIM(US.USER_NAME) + '@' + DP_US.ALIAS END AS US_AUTH_OWNER_NAME
 	FROM dbo.DEPO_OP O (NOLOCK)
		INNER JOIN dbo.DEPO_OP_TYPES T (NOLOCK) ON T.TYPE_ID = O.OP_TYPE
		INNER JOIN dbo.DEPO_DEPOSITS D (NOLOCK) ON O.DEPO_ID = D.DEPO_ID
        INNER JOIN dbo.USERS U (NOLOCK) ON O.OWNER = U.USER_ID
		INNER JOIN dbo.DEPTS DP_U (NOLOCK) ON DP_U.DEPT_NO = U.DEPT_NO
        LEFT JOIN dbo.USERS US (NOLOCK) ON O.AUTH_OWNER = US.USER_ID
		LEFT JOIN dbo.DEPTS DP_US (NOLOCK) ON DP_US.DEPT_NO = US.DEPT_NO
	WHERE O.DEPO_ID = @depo_id AND ( @op_type IS NULL OR @op_type = T.GROUP_ID) AND ( @op_id IS NULL OR O.OP_ID <= @op_id )
	ORDER BY O.OP_ID

RETURN(0)

GO
