SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[BCC_EXP_BC_DOCS_ARC]
  @bc_client_id int,
  @bc_login_id int,
  @step tinyint,
  @dt smalldatetime = 0,
  @lat bit = 0
AS
 
SET NOCOUNT ON
 
IF @step = 0
BEGIN
 DECLARE @accs TABLE (ACC_ID int PRIMARY KEY)
 INSERT INTO @accs
 SELECT B.ACC_ID
 FROM dbo.ACCOUNTS B (NOLOCK)
  INNER JOIN dbo.BC_LOGIN_ACC A (NOLOCK) ON A.ACC_ID = B.ACC_ID
 WHERE A.BC_LOGIN_ID = @bc_login_id
 
 INSERT dbo.BC_REC_IDS (SP_ID,REC_ID)
 SELECT DISTINCT @@SPID, S.REC_ID 
 FROM dbo.OPS_HELPER_ARC S (NOLOCK)
    INNER JOIN @accs A ON S.ACC_ID = A.ACC_ID
 WHERE @dt = 0 OR S.DT >= @dt
END
 
ELSE
 
IF @step = 1
BEGIN
	SELECT CASE WHEN D.PARENT_REC_ID > 0 THEN D.PARENT_REC_ID ELSE D.REC_ID END AS OP_NUM, 
		D.REC_ID, D.DOC_DATE, D.DOC_DATE_IN_DOC, D.ISO, D.AMOUNT, D.AMOUNT_EQU, D.DOC_NUM, D.OP_CODE, 
		A1.ACCOUNT AS DEBIT, A2.ACCOUNT AS CREDIT, CASE WHEN D.REC_STATE >= 20 THEN 20 WHEN D.REC_STATE >= 10 THEN 10 ELSE 0 END AS REC_STATE, D.BNK_CLI_ID, D.DESCRIP, D.PARENT_REC_ID, D.OWNER, D.DOC_TYPE, D.ACCOUNT_EXTRA,
		CASE @lat WHEN 0 THEN A1.DESCRIP ELSE A1.DESCRIP_LAT END AS DEBIT_NAME,  
		CASE @lat WHEN 0 THEN A2.DESCRIP ELSE A2.DESCRIP_LAT END AS CREDIT_NAME,
		D.DEBIT_ID,
		D.CREDIT_ID
	FROM dbo.BC_REC_IDS T (NOLOCK)
		INNER JOIN dbo.OPS_ARC D (NOLOCK) ON D.REC_ID=T.REC_ID
		INNER JOIN dbo.ACCOUNTS A1 (NOLOCK) ON A1.ACC_ID = D.DEBIT_ID
		INNER JOIN dbo.ACCOUNTS A2 (NOLOCK) ON A2.ACC_ID = D.CREDIT_ID
	WHERE T.SP_ID = @@SPID
END
 
ELSE
 
IF @step = 2
BEGIN
	SELECT DD.DOC_REC_ID AS REC_ID,CONVERT(int, dbo.get_real_bank_code (DD.SENDER_BANK_CODE)) AS SENDER_BANK_CODE,
		DD.SENDER_ACC,DD.SENDER_TAX_CODE,CONVERT(int, dbo.get_real_bank_code (DD.RECEIVER_BANK_CODE)) AS RECEIVER_BANK_CODE,
		DD.RECEIVER_ACC,DD.RECEIVER_TAX_CODE,DD.SENDER_BANK_NAME,DD.RECEIVER_BANK_NAME,
		DD.SENDER_ACC_NAME + 
			CASE WHEN O.DOC_TYPE = 104 THEN 
				'' 
			ELSE 
				CASE WHEN C.IS_RESIDENT = 0 THEN 
					CASE WHEN C.IS_JURIDICAL = 1 THEN '' ELSE ISNULL(', ' + C.PASSPORT, '') END + ISNULL(', ' + CC.DESCRIP, '') 
				ELSE 
					ISNULL(', ' + DD.SENDER_TAX_CODE, '') 
				END 
			END AS SENDER_ACC_NAME,
		DD.RECEIVER_ACC_NAME,DD.POR,DD.REC_DATE,DD.SAXAZKOD,DD.EXTRA_INFO,DD.REF_NUM,DD.TAX_PAYER_NAME,DD.TAX_PAYER_TAX_CODE
	FROM dbo.DOC_DETAILS_ARC_PLAT DD(NOLOCK) 
		INNER JOIN dbo.BC_REC_IDS D (NOLOCK) ON DD.DOC_REC_ID = D.REC_ID
		INNER JOIN dbo.OPS_ARC O (NOLOCK) ON O.REC_ID = D.REC_ID
		INNER JOIN dbo.ACCOUNTS A (NOLOCK) ON A.ACC_ID = O.DEBIT_ID
		LEFT JOIN dbo.CLIENTS C (NOLOCK) ON C.CLIENT_NO = A.CLIENT_NO
		LEFT JOIN dbo.COUNTRIES CC (NOLOCK) ON CC.COUNTRY = C.PASSPORT_COUNTRY
	WHERE D.SP_ID = @@SPID
END
 
ELSE
 
IF @step = 3
BEGIN
	SELECT DD.DOC_REC_ID AS REC_ID,dbo.get_real_bank_code (DD.SENDER_BANK_CODE) AS SENDER_BANK_CODE,
		DD.SENDER_ACC,dbo.get_real_bank_code (DD.RECEIVER_BANK_CODE) AS RECEIVER_BANK_CODE,DD.RECEIVER_ACC,DD.SENDER_BANK_NAME,
		DD.RECEIVER_BANK_NAME,DD.SENDER_ACC_NAME,DD.RECEIVER_ACC_NAME,DD.INTERMED_BANK_CODE,DD.INTERMED_BANK_NAME,
		DD.SENDER_TAX_CODE,DD.RECEIVER_TAX_CODE,DD.SWIFT_TEXT,DD.REF_NUM,DD.COR_BANK_CODE,DD.COR_BANK_NAME,
		DD.EXTRA_INFO AS RECEIVER_INFO, P.*
	FROM dbo.DOC_DETAILS_ARC_VALPLAT DD(NOLOCK) 
		INNER JOIN dbo.BC_REC_IDS D (NOLOCK) ON DD.DOC_REC_ID = D.REC_ID
		INNER JOIN dbo.DOC_DETAILS_ARC_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_ID
	WHERE D.SP_ID = @@SPID
END
 
ELSE
 
IF @step = 4
BEGIN
	SELECT DOC_REC_ID AS REC_ID, 
		ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,'') AS CLIENT_NAME,
		T.DESCRIP + CASE WHEN PASSPORT IS NULL THEN '' ELSE ', ÐÀÓÐ# ' + PASSPORT END + CASE WHEN PERSONAL_ID IS NULL THEN '' ELSE ', ÐÉÒ# ' + PERSONAL_ID END AS DOCUMENT,
		P.* , O.CHK_SERIE
	FROM dbo.DOC_DETAILS_ARC_PASSPORTS P (NOLOCK)
		INNER JOIN dbo.PASSPORT_TYPES T (NOLOCK) ON T.PASSPORT_TYPE_ID = P.PASSPORT_TYPE_ID
		INNER JOIN dbo.BC_REC_IDS D (NOLOCK) ON P.DOC_REC_ID = D.REC_ID
		INNER JOIN dbo.OPS_ARC O (NOLOCK) ON O.REC_ID = D.REC_ID
	WHERE D.SP_ID = @@SPID
END
 
ELSE
 
DELETE 
FROM dbo.BC_REC_IDS
WHERE SP_ID = @@SPID
GO
