SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[depo_sp_sync_flag_clear]
AS
BEGIN
	UPDATE dbo.INI_INT WITH (ROWLOCK)
	SET VALS = 0
	WHERE IDS = 'DEPO_SYNCHRONIZING'
	IF @@ERROR <> 0 OR @@ROWCOUNT <> 1 RETURN (1);
	
	RETURN 0;
END;	
GO
