SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_BACKUP_LOAN_DATA]
	@op_id int,
	@loan_id int = NULL
AS
SET NOCOUNT ON

DECLARE
	@r int,
	@e int
	
IF @loan_id IS NULL
BEGIN
	SELECT @loan_id = LOAN_ID
	FROM dbo.LOAN_OPS (NOLOCK)
	WHERE OP_ID = @op_id

	SELECT @r = @@ROWCOUNT, @e = @@ERROR
	IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
	IF @r <> 1 BEGIN RAISERROR('RECORD NOT FOUND',16,1) RETURN(1) END
END


INSERT INTO dbo.LOANS_HISTORY(LOAN_ID,OP_ID,ROW_VERSION,BRANCH_ID,DEPT_NO,AUTHORIZE_LEVEL,STATE,CLIENT_NO,CREDIT_LINE_ID,PRODUCT_ID,AGREEMENT_NO,REG_DATE,LOAN_TYPE,DISBURSE_TYPE,ENSURE_TYPE,INSTALLMENT,EVENT_INSTALLMENT,RESTRUCTURED,PROLONGED,ISO,AMOUNT,DISBURSE_AMOUNT,START_DATE,PERIOD,END_DATE,INTRATE,PENALTY_INTRATE,PREPAYMENT_INTRATE,PREPAYMENT_STEP,NOTUSED_INTRATE,ADMIN_INTRATE,ADMIN_FEE,RISK_TYPE,RISK_PERC_RATE_1,RISK_PERC_RATE_2,
				RISK_PERC_RATE_3,RISK_PERC_RATE_4,RISK_PERC_RATE_5,WRITEOFF_DATE,INTEREST_FLAGS,PENALTY_FLAGS,PREPAYMENT_FLAGS,PAYMENT_INTERVAL_TYPE,SCHEDULE_TYPE,PAYMENT_DAY,RESERVE_MAX_CATEGORY,INSTALLMENT_PERCENT,GRACE_STEPS,GRACE_TYPE,BASIS,RESPONSIBLE_USER_ID,CORESPONSIBLE_USER_ID,PURPOSE_TYPE,BAL_ACC,GROUP_ID,CLIENT_ACCOUNT,LINKED_CCY,INDEXED_RATE,INSURANCE_RATE,SERVICE_FEE_RATE,SERVICE_FEE,MAIN_COLLATERAL_LIST,PMT,GRACE_FINISH_DATE,CLOSE_DATE,GUARANTEE,INTERNAT_GUARANTEE,IMMEDIATE_FEEING)

SELECT LOAN_ID,@op_id,ROW_VERSION,BRANCH_ID,DEPT_NO,AUTHORIZE_LEVEL,STATE,CLIENT_NO,CREDIT_LINE_ID,PRODUCT_ID,AGREEMENT_NO,REG_DATE,LOAN_TYPE,DISBURSE_TYPE,ENSURE_TYPE,INSTALLMENT,EVENT_INSTALLMENT,RESTRUCTURED,PROLONGED,ISO,AMOUNT,DISBURSE_AMOUNT,START_DATE,PERIOD,END_DATE,INTRATE,PENALTY_INTRATE,PREPAYMENT_INTRATE,PREPAYMENT_STEP,NOTUSED_INTRATE,ADMIN_INTRATE,ADMIN_FEE,RISK_TYPE,RISK_PERC_RATE_1,RISK_PERC_RATE_2,
			RISK_PERC_RATE_3,RISK_PERC_RATE_4,RISK_PERC_RATE_5,WRITEOFF_DATE,INTEREST_FLAGS,PENALTY_FLAGS,PREPAYMENT_FLAGS,PAYMENT_INTERVAL_TYPE,SCHEDULE_TYPE,PAYMENT_DAY,RESERVE_MAX_CATEGORY,INSTALLMENT_PERCENT,GRACE_STEPS,GRACE_TYPE,BASIS,RESPONSIBLE_USER_ID,CORESPONSIBLE_USER_ID,PURPOSE_TYPE,BAL_ACC,GROUP_ID, CLIENT_ACCOUNT,LINKED_CCY,INDEXED_RATE,INSURANCE_RATE,SERVICE_FEE_RATE,SERVICE_FEE,MAIN_COLLATERAL_LIST,PMT,GRACE_FINISH_DATE,CLOSE_DATE,GUARANTEE,INTERNAT_GUARANTEE,IMMEDIATE_FEEING
FROM dbo.LOANS
WHERE LOAN_ID=@loan_id

  


SELECT @r = @@ROWCOUNT, @e = @@ERROR
IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
IF @r <> 1 BEGIN RAISERROR('RECORD NOT FOUND',16,1) RETURN(1) END

RETURN 0

GO
