SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[sys_generate_group_rights] (@group_id int)
AS

SET NOCOUNT ON;

BEGIN TRAN

UPDATE dbo.GROUPS
SET ACCESS_STRING = dbo.sys_get_group_rights_from_tasks (@group_id),
	ACCESS_STRING_2 = dbo.sys_get_group_rights2_from_tasks (@group_id)
WHERE GROUP_ID = @group_id


DELETE 
FROM dbo.CLI_SET_RIGHTS
WHERE GROUP_ID = @group_id

INSERT INTO dbo.CLI_SET_RIGHTS (GROUP_ID, SET_ID, RIGHT_NAME)
SELECT DISTINCT @group_id, SR.SET_ID, SR.RIGHT_NAME
FROM dbo.BANK_TASKS_CLI_SET_RIGHTS SR
	INNER JOIN dbo.BANK_TASKS BT ON BT.TASK_ID = SR.TASK_ID
	INNER JOIN dbo.GROUP_BANK_TASKS GBT ON GBT.TASK_ID = BT.TASK_ID
WHERE GBT.GROUP_ID = @group_id


DELETE 
FROM dbo.ACC_SET_RIGHTS
WHERE GROUP_ID = @group_id

INSERT INTO dbo.ACC_SET_RIGHTS (GROUP_ID, SET_ID, RIGHT_NAME)
SELECT DISTINCT @group_id, SR.SET_ID, SR.RIGHT_NAME
FROM dbo.BANK_TASKS_ACC_SET_RIGHTS SR
	INNER JOIN dbo.BANK_TASKS BT ON BT.TASK_ID = SR.TASK_ID
	INNER JOIN dbo.GROUP_BANK_TASKS GBT ON GBT.TASK_ID = BT.TASK_ID
WHERE GBT.GROUP_ID = @group_id


DELETE 
FROM dbo.OPS_SET_RIGHTS
WHERE GROUP_ID = @group_id

INSERT INTO dbo.OPS_SET_RIGHTS (GROUP_ID, SET_ID, RIGHT_NAME)
SELECT DISTINCT @group_id, SR.SET_ID, SR.RIGHT_NAME
FROM dbo.BANK_TASKS_OPS_SET_RIGHTS SR
	INNER JOIN dbo.BANK_TASKS BT ON BT.TASK_ID = SR.TASK_ID
	INNER JOIN dbo.GROUP_BANK_TASKS GBT ON GBT.TASK_ID = BT.TASK_ID
WHERE GBT.GROUP_ID = @group_id


DELETE 
FROM dbo.OPS_ARC_SET_RIGHTS
WHERE GROUP_ID = @group_id

INSERT INTO dbo.OPS_ARC_SET_RIGHTS (GROUP_ID, SET_ID, RIGHT_NAME)
SELECT DISTINCT @group_id, SR.SET_ID, SR.RIGHT_NAME
FROM dbo.BANK_TASKS_OPS_ARC_SET_RIGHTS SR
	INNER JOIN dbo.BANK_TASKS BT ON BT.TASK_ID = SR.TASK_ID
	INNER JOIN dbo.GROUP_BANK_TASKS GBT ON GBT.TASK_ID = BT.TASK_ID
WHERE GBT.GROUP_ID = @group_id


DELETE 
FROM dbo.LOAN_SET_RIGHTS
WHERE GROUP_ID = @group_id

INSERT INTO dbo.LOAN_SET_RIGHTS (GROUP_ID, SET_ID, RIGHT_NAME)
SELECT DISTINCT @group_id, SR.SET_ID, SR.RIGHT_NAME
FROM dbo.BANK_TASKS_LOAN_SET_RIGHTS SR
	INNER JOIN dbo.BANK_TASKS BT ON BT.TASK_ID = SR.TASK_ID
	INNER JOIN dbo.GROUP_BANK_TASKS GBT ON GBT.TASK_ID = BT.TASK_ID
WHERE GBT.GROUP_ID = @group_id


DELETE 
FROM dbo.DEPO_SET_RIGHTS
WHERE GROUP_ID = @group_id

INSERT INTO dbo.DEPO_SET_RIGHTS (GROUP_ID, SET_ID, RIGHT_NAME)
SELECT DISTINCT @group_id, SR.SET_ID, SR.RIGHT_NAME
FROM dbo.BANK_TASKS_DEPO_SET_RIGHTS SR
	INNER JOIN dbo.BANK_TASKS BT ON BT.TASK_ID = SR.TASK_ID
	INNER JOIN dbo.GROUP_BANK_TASKS GBT ON GBT.TASK_ID = BT.TASK_ID
WHERE GBT.GROUP_ID = @group_id

COMMIT
GO
