SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[PAYMENTS_CLOSE_DAY]
	@dt smalldatetime
AS

SET NOCOUNT ON

IF EXISTS(SELECT * FROM dbo.PENDING_PAYMENTS WHERE DT_TM <= @dt + 1 AND REC_STATE NOT IN (2, 3, 4))
BEGIN
	RAISERROR ('ÊÏÌÖÍÀËÖÒ ÂÀÃÀÓÀáÀÃÄÁÛÉ ÀÒÉÓ ÂÀÖÂÆÀÅÍÄËÉ ÓÀÁÖÈÄÁÉ!',16,1) 
	RETURN(3) 
END

INSERT INTO dbo.PENDING_PAYMENTS_ARC 
SELECT * 
FROM dbo.PENDING_PAYMENTS 
WHERE DT_TM <= @dt + 1 AND REC_STATE IN (2, 3, 4)
IF @@ERROR <> 0 RETURN 1

DELETE FROM dbo.PENDING_PAYMENTS 
WHERE DT_TM <= @dt + 1 AND REC_STATE IN (2, 3, 4)
RETURN @@ERROR
GO
