SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[CONV_INCOME_OUTCOME_DEL] AS
DECLARE 
	@dt smalldatetime

BEGIN TRAN

	EXEC GET_OPEN_BANK_DATE @dt OUTPUT

	DELETE FROM dbo.DOC_CHANGES
	WHERE DOC_REC_ID in (SELECT REC_ID FROM dbo.OPS_0000 WHERE DOC_DATE = @dt AND OP_CODE = 'CNVMZ')

	DELETE FROM dbo.DOC_DETAILS_CONV
	WHERE DOC_REC_ID in (SELECT REC_ID FROM dbo.OPS_0000 WHERE DOC_DATE = @dt AND OP_CODE = 'CNVMZ')

	DELETE FROM dbo.OPS_0000
	WHERE DOC_DATE = @dt AND OP_CODE = 'CNVMZ'

COMMIT
GO
