SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[LOAN_SP_GET_LOANS_FOR_PAYMENT]
	@date smalldatetime,
	@loan_id int = NULL
AS
SET NOCOUNT ON


DECLARE @T TABLE(LOAN_ID int PRIMARY KEY,
	OVERDUE_DELAY bit,
	BRANCH_NO int,
	DEPT_NO int,
	STATE tinyint,
	CLIENT_NO int,
	AGREEMENT_NO varchar(1000),
	ISO TISO	
)

SELECT * FROM @T
GO
