SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[ON_USER_GET_BANK_CODE_FROM_ACCOUNT] 
  @account TACCOUNT,
  @iso TISO = 'GEL',
  @is_val bit = 0,
  @bank_code TINTBANKCODE OUTPUT
AS
BEGIN
  RETURN 0
END
GO
