SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[LOAN_SP_DELETE_CREDIT_LINE]
	@credit_line_id int
AS
	IF (SELECT STATE FROM dbo.LOAN_CREDIT_LINES WHERE CREDIT_LINE_ID = @credit_line_id) > 0
	BEGIN
		RAISERROR ('ÃÀÀÅÔÏÒÉÆÉÒÄÁÖËÉ ÂÄÍÄÒÀËÖÒÉ áÄËÛÄÊÒÖËÄÁÉÓ ßÀÛËÀ ÛÄÖÞËÄÁÄËÉÀ !', 16, 1)
		RETURN (1)
	END

	IF EXISTS (SELECT * FROM dbo.LOANS WHERE (CREDIT_LINE_ID = @credit_line_id) AND ([STATE] < 255))
	BEGIN
		RAISERROR ('ÂÄÍÄÒÀËÖÒÉ áÄËÛÄÊÒÖËÄÁÉÓ ßÀÛËÀ ÛÄÖÞËÄÁÄËÉÀ, ÌÉÓ ØÅÄÛ ÌÏØÌÄÃÉ ÓÄÓáÉÓ/ÓÄÓáÄÁÉÓ ÀÒÓÄÁÏÁÉÓ ÂÀÌÏ!', 16, 1)
		RETURN (1)	
	END

	DELETE FROM dbo.LOAN_CREDIT_LINE_COLLATERALS_LINK 
	WHERE CREDIT_LINE_ID = @credit_line_id

	DELETE dbo.LOAN_COLLATERALS
	FROM dbo.LOAN_COLLATERALS A
		LEFT OUTER JOIN	dbo.LOAN_COLLATERALS_LINK B ON B.COLLATERAL_ID = A.COLLATERAL_ID
		LEFT OUTER JOIN	dbo.LOAN_CREDIT_LINE_COLLATERALS_LINK C ON C.COLLATERAL_ID = A.COLLATERAL_ID
	WHERE A.LOAN_ID IS NULL AND A.CREDIT_LINE_ID IS NULL AND B.LOAN_ID IS NULL AND C.CREDIT_LINE_ID IS NULL
	
	DELETE dbo.LOAN_COLLATERALS
	FROM dbo.LOAN_COLLATERALS A
		LEFT OUTER JOIN	dbo.LOAN_COLLATERALS_LINK B ON B.COLLATERAL_ID = A.COLLATERAL_ID
		LEFT OUTER JOIN	dbo.LOAN_CREDIT_LINE_COLLATERALS_LINK C ON C.COLLATERAL_ID = A.COLLATERAL_ID
	WHERE A.CREDIT_LINE_ID = @credit_line_id AND B.LOAN_ID IS NULL AND C.CREDIT_LINE_ID IS NULL

	UPDATE dbo.LOAN_COLLATERALS 
	SET CREDIT_LINE_ID = NULL
	WHERE CREDIT_LINE_ID = @credit_line_id

	DELETE FROM dbo.LOAN_CREDIT_LINES
	WHERE CREDIT_LINE_ID = @credit_line_id
RETURN

GO
