SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DX_SPX_DEPOSIT_OPS_DT_OID]
  @did int 
AS
  DECLARE @old_oid int
  SET NOCOUNT ON
  SELECT @old_oid = O.OID FROM dbo.DX_DEPOSIT_OPS O INNER JOIN dbo.DX_DEPOSIT_DATA D ON O.OID=D.OID WHERE O.DID=@did AND O.OWN_DATA=1 AND D.ST=0
  SET NOCOUNT OFF
  SELECT O.OID, ISNULL(O1.OID, @old_oid) AS OLD_OID, O.DT, O.OP_NO, O.OP_TYPE, D.DESCRIP AS OP_DESCRIP  
  FROM 
    dbo.DX_DEPOSIT_OPS O INNER JOIN
    dbo.DX_DEPOSIT_OPS_DESCRIP D ON D.OP_TYPE=O.OP_TYPE LEFT OUTER JOIN 
    dbo.DX_DEPOSIT_OPS O1 ON (O1.DID=O.DID) AND (O1.OID = (SELECT MAX(O2.OID) FROM dbo.DX_DEPOSIT_OPS O2 WHERE (O2.DID=@did) AND (O2.OID < O.OID)))
  WHERE (O.DID = @did) AND (O.COMMIT_STATE=0xFF) AND (O.OP_TYPE > 10) AND (O.OWN_DATA=1)



GO
