SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[GET_REPORT_KAS_INOUT]
	@acc_id int,
	@dt smalldatetime,
	@is_income bit,
	@shadow_level smallint = 1
AS

SET NOCOUNT ON

DECLARE 
	@rec_state tinyint

IF @shadow_level >= 0
	SET @rec_state = @shadow_level * 10

DECLARE @tbl TABLE (ACC_ID int, CLIENT_NAME varchar(150), DOC_NUM int, OP_CODE varchar(5), AMOUNT money, REC_ID int, IS_ARC bit)

IF @dt < dbo.bank_open_date()
	INSERT INTO @tbl
	SELECT CASE WHEN D.DOC_TYPE BETWEEN 120 AND 129 THEN D.CREDIT_ID ELSE D.DEBIT_ID END,
		ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,''),
		D.DOC_NUM, D.OP_CODE, D.AMOUNT, D.REC_ID, 1
	FROM dbo.OPS_ARC D
		INNER JOIN dbo.OPS_HELPER_ARC H (NOLOCK) ON H.REC_ID = D.REC_ID
		LEFT JOIN dbo.DOC_DETAILS_ARC_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_ID
	WHERE H.ACC_ID = @acc_id AND H.DT = @dt AND D.DOC_DATE = @dt AND
		((@is_income = 1 AND D.DOC_TYPE BETWEEN 120 AND 129) OR
		 (@is_income = 0 AND D.DOC_TYPE BETWEEN 130 AND 149)
		)
ELSE
IF @shadow_level >=0 
	INSERT INTO @tbl
	SELECT CASE WHEN D.DOC_TYPE BETWEEN 120 AND 129 THEN D.CREDIT_ID ELSE D.DEBIT_ID END,
		ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,''),
		D.DOC_NUM, D.OP_CODE, D.AMOUNT, D.REC_ID, 0
	FROM dbo.OPS_0000 D
		INNER JOIN dbo.OPS_HELPER_0000 H (NOLOCK) ON H.REC_ID = D.REC_ID
		LEFT JOIN dbo.DOC_DETAILS_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_ID
	WHERE H.ACC_ID = @acc_id AND H.DT = @dt AND D.DOC_DATE = @dt AND D.REC_STATE >= @rec_state AND 
		((@is_income = 1 AND D.DOC_TYPE BETWEEN 120 AND 129) OR
		 (@is_income = 0 AND D.DOC_TYPE BETWEEN 130 AND 149)
		)

SELECT A.ACCOUNT, T.CLIENT_NAME, T.DOC_NUM, T.OP_CODE, T.AMOUNT, CONVERT(tinyint, 0) AS FORSORT, T.REC_ID, T.IS_ARC
FROM @tbl T
	INNER JOIN dbo.ACCOUNTS A ON A.ACC_ID = T.ACC_ID
GO
