SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SYS_MOVE_ALL_ARC_DOCS_TO_CUR]
  @dt smalldatetime
AS

SET NOCOUNT ON

DECLARE 
	@year int,
	@sql nvarchar(4000),
	@e int,
	@r int

SET @year = YEAR(@dt)

SET @sql = N'
DECLARE @tbl TABLE (REC_ID int NOT NULL PRIMARY KEY CLUSTERED)

INSERT INTO @tbl (REC_ID) SELECT REC_ID FROM dbo.' + dbo.sys_get_arc_table_name('OPS',@year) + N' WITH (XLOCK) WHERE DOC_DATE = @dt

SET IDENTITY_INSERT dbo.OPS_0000 ON
INSERT INTO dbo.OPS_0000 (REC_ID, UID, DEBIT_ID, CREDIT_ID, DOC_DATE, DOC_DATE_IN_DOC, ISO, AMOUNT, AMOUNT_EQU, DOC_NUM, OP_CODE, REC_STATE, BNK_CLI_ID, DESCRIP, PARENT_REC_ID, OWNER, DOC_TYPE, ACCOUNT_EXTRA, PROD_ID, FOREIGN_ID, CHANNEL_ID, DEPT_NO, IS_SUSPICIOUS,CASHIER,CHK_SERIE,CASH_AMOUNT,TREASURY_CODE,TAX_CODE_OR_PID,RELATION_ID,FLAGS,BRANCH_ID)
SELECT DD.REC_ID, UID, DEBIT_ID, CREDIT_ID, DOC_DATE, DOC_DATE_IN_DOC, ISO, AMOUNT, AMOUNT_EQU, DOC_NUM, OP_CODE, REC_STATE, BNK_CLI_ID, DESCRIP, PARENT_REC_ID, OWNER, DOC_TYPE, ACCOUNT_EXTRA, PROD_ID, FOREIGN_ID, CHANNEL_ID, DEPT_NO, IS_SUSPICIOUS,CASHIER,CHK_SERIE,CASH_AMOUNT,TREASURY_CODE,TAX_CODE_OR_PID,RELATION_ID,FLAGS,BRANCH_ID
FROM dbo.' + dbo.sys_get_arc_table_name('OPS',@year) + N' DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERROR
SET IDENTITY_INSERT dbo.OPS_0000 OFF
IF @e<>0 RETURN

INSERT INTO dbo.DOC_DETAILS_PLAT
SELECT DD.* 
FROM dbo.DOC_DETAILS_ARC_PLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_DETAILS_VALPLAT
SELECT DD.* 
FROM dbo.DOC_DETAILS_ARC_VALPLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_DETAILS_CONV
SELECT DD.* 
FROM dbo.DOC_DETAILS_ARC_CONV DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_DETAILS_PASSPORTS
SELECT DD.* 
FROM dbo.DOC_DETAILS_ARC_PASSPORTS DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_DETAILS_PERC
SELECT DD.* 
FROM dbo.DOC_DETAILS_ARC_PERC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
INSERT INTO dbo.DOC_ATTRIBUTES
SELECT DD.* 
FROM dbo.DOC_ATTRIBUTES_ARC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
SET IDENTITY_INSERT dbo.DOC_CHANGES ON
INSERT INTO dbo.DOC_CHANGES (DOC_REC_ID, REC_ID, [USER_ID], DESCRIP, TIME_OF_CHANGE)
SELECT DD.DOC_REC_ID, DD.REC_ID, DD.[USER_ID], DD.DESCRIP, DD.TIME_OF_CHANGE 
FROM dbo.DOC_CHANGES_ARC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERROR
SET IDENTITY_INSERT dbo.DOC_CHANGES OFF
IF @e<>0 RETURN
DELETE FROM dbo.DOC_DETAILS_ARC_PLAT
FROM dbo.DOC_DETAILS_ARC_PLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
DELETE FROM dbo.DOC_DETAILS_ARC_VALPLAT
FROM dbo.DOC_DETAILS_ARC_VALPLAT DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
DELETE FROM dbo.DOC_DETAILS_ARC_CONV
FROM dbo.DOC_DETAILS_ARC_CONV DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
DELETE FROM dbo.DOC_DETAILS_ARC_PASSPORTS
FROM dbo.DOC_DETAILS_ARC_PASSPORTS DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURNDELETE FROM dbo.DOC_DETAILS_ARC_PERC
FROM dbo.DOC_DETAILS_ARC_PERC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
DELETE FROM dbo.DOC_ATTRIBUTES_ARC
FROM dbo.DOC_ATTRIBUTES_ARC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
DELETE FROM dbo.DOC_CHANGES_ARC
FROM dbo.DOC_CHANGES_ARC DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.DOC_REC_ID
SET @e=@@ERRORIF @e<>0 RETURN
DELETE FROM dbo.' + dbo.sys_get_arc_table_name('OPS',@year) + N'
FROM dbo.' + dbo.sys_get_arc_table_name('OPS',@year) + N' DD WITH (XLOCK)
  INNER JOIN @tbl B ON B.REC_ID = DD.REC_ID
SET @e=@@ERRORIF @e<>0 RETURN'EXEC @r = sp_executesql @sql, N'@dt smalldatetime, @e int OUTPUT', @dt, @e OUTPUT
IF @@ERROR <> 0 OR @r <> 0 OR @e <> 0 RETURN (99)

SET @sql = N'
DELETE FROM dbo.' + dbo.sys_get_arc_table_name('BAL',@year) + N'
FROM dbo.' + dbo.sys_get_arc_table_name('BAL',@year) + N' DD WITH (XLOCK)
WHERE DT = @dt
SET @e=@@ERRORIF @e<>0 RETURNINSERT INTO dbo.VAL_RATES_0000
SELECT *
FROM dbo.' + dbo.sys_get_arc_table_name('VAL_RATES',@year) + N' DD WITH (XLOCK)
WHERE DT = @dt
SET @e=@@ERROR
IF @e<>0 RETURNDELETE FROM dbo.' + dbo.sys_get_arc_table_name('VAL_RATES',@year) + N'
FROM dbo.' + dbo.sys_get_arc_table_name('VAL_RATES',@year) + N' DD WITH (XLOCK)
WHERE DT = @dt
SET @e=@@ERROR'
EXEC @r = sp_executesql @sql, N'@dt smalldatetime, @e int OUTPUT', @dt, @e OUTPUT
IF @@ERROR <> 0 OR @r <> 0 OR @e <> 0 RETURN (99)

RETURN (0)
GO
