SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_GET_OPS_INFO_DOCS]
	@doc_rec_id int,
	@op_date smalldatetime

AS
DECLARE @open_bank_day smalldatetime
EXEC dbo.GET_OPEN_BANK_DATE @open_bank_day OUTPUT
IF @op_date < @open_bank_day
	SELECT D.REC_ID, D.UID, D.PARENT_REC_ID, D.OP_NUM, D.DOC_DATE, D.OP_CODE, D.DEBIT_ID, D.DEBIT, D.CREDIT_ID, D.CREDIT, D.ISO, D.AMOUNT, D.DESCRIP, D.REC_STATE, D.DOC_TYPE, D.OWNER, D.ACCOUNT_EXTRA, D.CHANNEL_ID, D.FLAGS
	FROM dbo.DOCS_ARC_ALL D (NOLOCK)
	WHERE (D.OP_NUM=@doc_rec_id)
	ORDER BY D.REC_ID
	OPTION (RECOMPILE)
ELSE
	SELECT D.REC_ID, D.UID, D.PARENT_REC_ID, D.OP_NUM, D.DOC_DATE, D.OP_CODE, D.DEBIT_ID, D.DEBIT, D.CREDIT_ID, D.CREDIT, D.ISO, D.AMOUNT, D.DESCRIP, D.REC_STATE, D.DOC_TYPE, D.OWNER, D.ACCOUNT_EXTRA, D.CHANNEL_ID, D.FLAGS 
	FROM dbo.DOCS_ALL D (NOLOCK)
	WHERE (D.OP_NUM=@doc_rec_id)
	ORDER BY D.REC_ID
	OPTION (RECOMPILE)
GO
