SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[CLEARING_DEL]
	@dt smalldatetime
AS

SET NOCOUNT ON

DELETE FROM dbo.DOC_CHANGES
WHERE DOC_REC_ID IN (SELECT REC_ID FROM dbo.OPS_0000 WHERE DOC_DATE = @dt AND OP_CODE = '*CLR*' AND (DOC_TYPE = 97 OR DOC_TYPE = 200))

DELETE FROM OPS_0000 WHERE DOC_DATE = @dt AND OP_CODE='*CLR*'

RETURN 0
GO
