SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[GET_REPORT_OPER_KASSA]
  @start_date smalldatetime,
  @end_date smalldatetime,
  @user_id int,
  @min_doc_type tinyint,
  @shadow_level smallint = 1
AS

SET NOCOUNT ON

DECLARE 
	@rec_state tinyint

IF @shadow_level >= 0
	SET @rec_state = @shadow_level * 10

SELECT D.DOC_DATE, D.DOC_NUM, D.AMOUNT, D.ISO, A.ACCOUNT AS DEBIT, B.ACCOUNT AS CREDIT,
	ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,'') AS CLIENT_NAME,
	D.DESCRIP, D.REC_ID, 1 AS IS_ARC, D.OP_CODE
FROM dbo.OPS_ARC D (NOLOCK)	INNER JOIN ACCOUNTS A (NOLOCK) ON A.ACC_ID = D.DEBIT_ID
	INNER JOIN ACCOUNTS B (NOLOCK) ON B.ACC_ID = D.CREDIT_ID	INNER JOIN dbo.DOC_DETAILS_ARC_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_IDWHERE (D.DOC_DATE BETWEEN @start_date AND @end_date) AND (D.DOC_TYPE BETWEEN @min_doc_type AND (@min_doc_type + 9)) AND (D.OWNER = @user_id)

UNION ALL

SELECT D.DOC_DATE, D.DOC_NUM, D.AMOUNT, D.ISO, A.ACCOUNT AS DEBIT, B.ACCOUNT AS CREDIT,
	ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,'') AS CLIENT_NAME,
	D.DESCRIP, D.REC_ID, 0 AS IS_ARC, D.OP_CODE
FROM dbo.OPS_0000 D	INNER JOIN ACCOUNTS A (NOLOCK) ON A.ACC_ID = D.DEBIT_ID
	INNER JOIN ACCOUNTS B (NOLOCK) ON B.ACC_ID = D.CREDIT_ID	INNER JOIN dbo.DOC_DETAILS_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_IDWHERE (D.DOC_DATE BETWEEN @start_date AND @end_date) AND (D.DOC_TYPE BETWEEN @min_doc_type AND (@min_doc_type + 9)) AND (D.OWNER = @user_id) AND
      (@shadow_level >=0 ) AND (D.REC_STATE >= @rec_state)
GO
