SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[GET_PLASTIC_CARD_LIMIT_FOR_SEND]
AS

SELECT CARD_ID, SUM(AMOUNT) AS TOTAL_AMOUNT, ACCOUNT, ISO, MAX(REC_ID) AS MAX_REC_ID INTO #_TMP_PC_
FROM dbo.PLASTIC_CARD_LIMITS
GROUP BY CARD_ID, ACCOUNT, ISO

DELETE FROM #_TMP_PC_
WHERE TOTAL_AMOUNT = 0

SELECT * FROM #_TMP_PC_

DROP TABLE #_TMP_PC_

RETURN 0
GO
