SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-------------------------------4.09
CREATE PROCEDURE [dbo].[GET_REPORT_KASBOOK]
	@acc_id int,
	@dt smalldatetime,
	@shadow_level smallint = 1
AS

SET NOCOUNT ON

DECLARE 
	@rec_state tinyint

IF @shadow_level >= 0
	SET @rec_state = @shadow_level * 10

DECLARE @tbl TABLE (REC_ID int, DOC_NUM int, ISO char(3), ACC_ID int, DBO money, CRO money, DESCRIP varchar(150), IS_OUTCOME tinyint, IS_ARC bit, OWNER int, CASHIER int)

IF @dt < dbo.bank_open_date()
	INSERT INTO @tbl
	SELECT D.REC_ID, D.DOC_NUM, D.ISO,
		CASE WHEN D.DOC_TYPE BETWEEN 120 AND 129 THEN D.CREDIT_ID ELSE D.DEBIT_ID END,
		CASE @acc_id WHEN D.DEBIT_ID THEN D.AMOUNT ELSE NULL END,
		CASE @acc_id WHEN D.CREDIT_ID THEN D.AMOUNT ELSE NULL END,
		ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,''),
		CASE @acc_id WHEN D.CREDIT_ID THEN 1 ELSE 0 END, 1, D.OWNER, D.CASHIER
	FROM dbo.OPS_ARC D(NOLOCK)
		INNER JOIN dbo.OPS_HELPER_ARC H ON H.REC_ID = D.REC_ID
		LEFT JOIN dbo.DOC_DETAILS_ARC_PASSPORTS P(NOLOCK) ON P.DOC_REC_ID = D.REC_ID
	WHERE H.ACC_ID = @acc_id AND H.DT = @dt AND D.DOC_DATE = @dt AND D.DOC_TYPE BETWEEN 120 AND 159
ELSE
IF @shadow_level >=0 
	INSERT INTO @tbl
	SELECT D.REC_ID, D.DOC_NUM, D.ISO,
		CASE WHEN D.DOC_TYPE BETWEEN 120 AND 129 THEN D.CREDIT_ID ELSE D.DEBIT_ID END,
		CASE @acc_id WHEN D.DEBIT_ID THEN D.AMOUNT ELSE NULL END,
		CASE @acc_id WHEN D.CREDIT_ID THEN D.AMOUNT ELSE NULL END,
		ISNULL(P.FIRST_NAME,'') + ' ' + ISNULL(P.LAST_NAME,''),
		CASE @acc_id WHEN D.CREDIT_ID THEN 1 ELSE 0 END, 0, D.OWNER, D.CASHIER
	FROM dbo.OPS_0000 D
		INNER JOIN dbo.OPS_HELPER_0000 H (NOLOCK) ON H.REC_ID = D.REC_ID
		LEFT JOIN dbo.DOC_DETAILS_PASSPORTS P (NOLOCK) ON P.DOC_REC_ID = D.REC_ID
	WHERE H.ACC_ID = @acc_id AND H.DT = @dt AND D.DOC_DATE = @dt AND D.DOC_TYPE BETWEEN 120 AND 159 AND D.REC_STATE >= @rec_state

SELECT T.DOC_NUM, T.DESCRIP, A.ACCOUNT, T.DBO, T.CRO, T.IS_OUTCOME, T.REC_ID, T.IS_ARC, T.OWNER, T.CASHIER
FROM @tbl T
	INNER JOIN dbo.ACCOUNTS A ON A.ACC_ID = T.ACC_ID
ORDER BY T.IS_OUTCOME, T.DOC_NUM
GO
