SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[BCC_EXP_BC_ACCOUNTS]
	@bc_client_id int,
	@bc_login_id int
AS

SET NOCOUNT ON

DECLARE @dt smalldatetime
SET @dt = dbo.bank_open_date()

SELECT 
	A.ACC_ID, A.ACCOUNT, A.ISO, A.ACT_PAS, A.REC_STATE, A.DESCRIP, A.DESCRIP_LAT,
	AA.DATE_OPEN, AA.DATE_CLOSE, A.ACC_TYPE,
	A.ACC_FLAGS, AA.SALDO, dbo.get_equ(AA.SALDO, A.ISO, @dt) AS SALDO_EQU, AA.SHADOW_DBO, AA.SHADOW_CRO, AA.LAST_OP_DATE, AA.AMOUNT_KAS_DELTA,
	C.TAX_INSP_CODE, A.LOGIN_ACC_FLAGS, 
	'' AS CCARD_ID, 0 AS ACC_USAGE_TYPE, '' AS ACC_USAGE_DESCRIP, -- Obsolete
	AT.DESCRIP + ' ' + ISNULL(AST.DESCRIP,'') AS ACC_DESCRIP,
	AT.DESCRIP_LAT + ' ' + ISNULL(AST.DESCRIP_LAT,'') AS ACC_DESCRIP_LAT
FROM dbo.BC_LOGIN_ACC_VIEW A (NOLOCK)
	INNER JOIN dbo.ACC_VIEW AA (NOLOCK) ON AA.ACC_ID = A.ACC_ID
	LEFT JOIN dbo.CLIENTS C (NOLOCK) ON C.CLIENT_NO = A.CLIENT_NO
	LEFT JOIN dbo.ACC_TYPES AT (NOLOCK) ON AT.ACC_TYPE = A.ACC_TYPE
	LEFT JOIN dbo.ACC_SUBTYPES AST (NOLOCK) ON AST.ACC_TYPE = A.ACC_TYPE AND AST.ACC_SUBTYPE = A.ACC_SUBTYPE
WHERE A.BC_CLIENT_ID = @bc_client_id AND A.BC_LOGIN_ID = @bc_login_id
GO
