SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[tcd_sp_tcd_get_balance]
(	
	@tcd_serial_id varchar(50),
	@start_date smalldatetime = NULL,
	@end_date smalldatetime = NULL
)
AS
BEGIN
	DECLARE 
		@deliver_command_id int

	SELECT @deliver_command_id = COMMAND_ID 
	FROM TCD_COMMAND_TYPES
	WHERE DESCRIP = 'DELIVER'

	SELECT 
		U.USER_NAME, T.OP_DATE,		
		ISNULL(T.CASETTE_DEN_1, 0) AS CASETTE_DEN_1, ISNULL(T.CASETTE_CCY_1, '*') AS CASETTE_CCY_1, ISNULL(T.CASETTE_PREV_BALANCE_1, $0.00) AS CASETTE_PREV_BALANCE_1,		
		ISNULL(CASETTE_DEN_1, $0.00)*ISNULL(T.CASETTE_PREV_BALANCE_1,0) AS CASETTE_PREV_BALANCE_TOTAL_1,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_1,0) ELSE $0.00 END AS DELIVERED_1,
		ISNULL(CASETTE_DEN_1, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_1,0) ELSE $0.00 END AS DELIVERED_TOTAL_1,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_DISPENSED_NUM_1,0)-ISNULL(CASETTE_REQUESTED_NUM_1,0) ELSE ISNULL(CASETTE_DISPENSED_NUM_1,0) END AS REJECTED_1,
		ISNULL(CASETTE_DEN_1, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN (ISNULL(CASETTE_DISPENSED_NUM_1,0)-ISNULL(CASETTE_REQUESTED_NUM_1,0)) ELSE ISNULL(CASETTE_DISPENSED_NUM_1,0) END AS REJECTED_TOTAL_1,
		ISNULL(T.CASETTE_BALANCE_1, $0.00) AS CASETTE_BALANCE_1,
		ISNULL(CASETTE_DEN_1, $0.00)*ISNULL(CASETTE_BALANCE_1,0) AS CASETTE_BALANCE_TOTAL_1,

		ISNULL(T.CASETTE_DEN_2, 0) AS CASETTE_DEN_2, ISNULL(T.CASETTE_CCY_2, '*') AS CASETTE_CCY_2, ISNULL(T.CASETTE_PREV_BALANCE_2, $0.00) AS CASETTE_PREV_BALANCE_2,
		ISNULL(CASETTE_DEN_2, $0.00)*ISNULL(T.CASETTE_PREV_BALANCE_2,0) AS CASETTE_PREV_BALANCE_TOTAL_2,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_2,0) ELSE $0.00 END AS DELIVERED_2,
		ISNULL(CASETTE_DEN_2, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_2,0) ELSE $0.00 END AS DELIVERED_TOTAL_2,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_DISPENSED_NUM_2,0)-ISNULL(CASETTE_REQUESTED_NUM_2,0) ELSE ISNULL(CASETTE_DISPENSED_NUM_2,0) END AS REJECTED_2,
		ISNULL(CASETTE_DEN_2, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN (ISNULL(CASETTE_DISPENSED_NUM_2,0)-ISNULL(CASETTE_REQUESTED_NUM_2,0)) ELSE ISNULL(CASETTE_DISPENSED_NUM_2,0) END AS REJECTED_TOTAL_2,
		ISNULL(T.CASETTE_BALANCE_2, $0.00) AS CASETTE_BALANCE_2,
		ISNULL(CASETTE_DEN_2, $0.00)*ISNULL(CASETTE_BALANCE_2,0) AS CASETTE_BALANCE_TOTAL_2,

		ISNULL(T.CASETTE_DEN_3, 0) AS CASETTE_DEN_3, ISNULL(T.CASETTE_CCY_3, '*') AS CASETTE_CCY_3, ISNULL(T.CASETTE_PREV_BALANCE_3, $0.00) AS CASETTE_PREV_BALANCE_3,
		ISNULL(CASETTE_DEN_3, $0.00)*ISNULL(T.CASETTE_PREV_BALANCE_3,0) AS CASETTE_PREV_BALANCE_TOTAL_3,		
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_3,0) ELSE $0.00 END AS DELIVERED_3,
		ISNULL(CASETTE_DEN_3, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_3,0) ELSE $0.00 END AS DELIVERED_TOTAL_3,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_DISPENSED_NUM_3,0)-ISNULL(CASETTE_REQUESTED_NUM_3,0) ELSE ISNULL(CASETTE_DISPENSED_NUM_3,0) END AS REJECTED_3,
		ISNULL(CASETTE_DEN_3, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN (ISNULL(CASETTE_DISPENSED_NUM_3,0)-ISNULL(CASETTE_REQUESTED_NUM_3,0)) ELSE ISNULL(CASETTE_DISPENSED_NUM_3,0) END AS REJECTED_TOTAL_3,
		ISNULL(T.CASETTE_BALANCE_3, $0.00) AS CASETTE_BALANCE_3,
		ISNULL(CASETTE_DEN_3, $0.00)*ISNULL(CASETTE_BALANCE_3,0) AS CASETTE_BALANCE_TOTAL_3,

		ISNULL(T.CASETTE_DEN_4, 0) AS CASETTE_DEN_4, ISNULL(T.CASETTE_CCY_4, '*') AS CASETTE_CCY_4, ISNULL(T.CASETTE_PREV_BALANCE_4, $0.00) AS CASETTE_PREV_BALANCE_4,
		ISNULL(CASETTE_DEN_4, $0.00)*ISNULL(T.CASETTE_PREV_BALANCE_4,0) AS CASETTE_PREV_BALANCE_TOTAL_4,		
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_4,0) ELSE $0.00 END AS DELIVERED_4,
		ISNULL(CASETTE_DEN_4, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_4,0) ELSE $0.00 END AS DELIVERED_TOTAL_4,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_DISPENSED_NUM_4,0)-ISNULL(CASETTE_REQUESTED_NUM_4,0) ELSE ISNULL(CASETTE_DISPENSED_NUM_4,0) END AS REJECTED_4,
		ISNULL(CASETTE_DEN_4, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN (ISNULL(CASETTE_DISPENSED_NUM_4,0)-ISNULL(CASETTE_REQUESTED_NUM_4,0)) ELSE ISNULL(CASETTE_DISPENSED_NUM_4,0) END AS REJECTED_TOTAL_4,
		ISNULL(T.CASETTE_BALANCE_4, $0.00) AS CASETTE_BALANCE_4,
		ISNULL(CASETTE_DEN_4, $0.00)*ISNULL(CASETTE_BALANCE_4,0) AS CASETTE_BALANCE_TOTAL_4,

		ISNULL(T.CASETTE_DEN_5, 0) AS CASETTE_DEN_5, ISNULL(T.CASETTE_CCY_5, '*') AS CASETTE_CCY_5, ISNULL(T.CASETTE_PREV_BALANCE_5, $0.00) AS CASETTE_PREV_BALANCE_5,
		ISNULL(CASETTE_DEN_5, $0.00)*ISNULL(T.CASETTE_PREV_BALANCE_5,0) AS CASETTE_PREV_BALANCE_TOTAL_5,				
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_5,0) ELSE $0.00 END AS DELIVERED_5,
		ISNULL(CASETTE_DEN_5, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_5,0) ELSE $0.00 END AS DELIVERED_TOTAL_5,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_DISPENSED_NUM_5,0)-ISNULL(CASETTE_REQUESTED_NUM_5,0) ELSE ISNULL(CASETTE_DISPENSED_NUM_5,0) END AS REJECTED_5,
		ISNULL(CASETTE_DEN_5, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN (ISNULL(CASETTE_DISPENSED_NUM_5,0)-ISNULL(CASETTE_REQUESTED_NUM_5,0)) ELSE ISNULL(CASETTE_DISPENSED_NUM_5,0) END AS REJECTED_TOTAL_5,
		ISNULL(T.CASETTE_BALANCE_5, $0.00) AS CASETTE_BALANCE_5,
		ISNULL(CASETTE_DEN_5, $0.00)*ISNULL(CASETTE_BALANCE_5,0) AS CASETTE_BALANCE_TOTAL_5,

		ISNULL(T.CASETTE_DEN_6, 0) AS CASETTE_DEN_6, ISNULL(T.CASETTE_CCY_6, '*') AS CASETTE_CCY_6, ISNULL(T.CASETTE_PREV_BALANCE_6, $0.00) AS CASETTE_PREV_BALANCE_6,
		ISNULL(CASETTE_DEN_6, $0.00)*ISNULL(T.CASETTE_PREV_BALANCE_6,0) AS CASETTE_PREV_BALANCE_TOTAL_6,						
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_6,0) ELSE $0.00 END AS DELIVERED_6,
		ISNULL(CASETTE_DEN_6, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_REQUESTED_NUM_6,0) ELSE $0.00 END AS DELIVERED_TOTAL_6,
		CASE WHEN @deliver_command_id = COMMAND_ID THEN ISNULL(CASETTE_DISPENSED_NUM_6,0)-ISNULL(CASETTE_REQUESTED_NUM_6,0) ELSE ISNULL(CASETTE_DISPENSED_NUM_6,0) END AS REJECTED_6,
		ISNULL(CASETTE_DEN_5, $0.00)*CASE WHEN @deliver_command_id = COMMAND_ID THEN (ISNULL(CASETTE_DISPENSED_NUM_6,0)-ISNULL(CASETTE_REQUESTED_NUM_6,0)) ELSE ISNULL(CASETTE_DISPENSED_NUM_6,0) END AS REJECTED_TOTAL_6,
		ISNULL(T.CASETTE_BALANCE_6, $0.00) AS CASETTE_BALANCE_6,
		ISNULL(CASETTE_DEN_6, $0.00)*ISNULL(CASETTE_BALANCE_6,0) AS CASETTE_BALANCE_TOTAL_6

	FROM dbo.TCD_TRANSACTIONS T
		INNER JOIN dbo.USERS U (NOLOCK) ON U.[USER_ID] = T.[USER_ID]
	WHERE TCD_SERIAL_ID = @tcd_serial_id AND
	(@start_date IS NULL OR convert(smalldatetime,floor(convert(real, T.OP_DATE)))>=@start_date)AND(@end_date IS NULL OR convert(smalldatetime,floor(convert(real, T.OP_DATE)))<=@end_date)
	RETURN 0
END
GO
