SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_RESTORE_LOAN_DATA]
	@op_id int,
	@delete_backup bit = 1
AS
SET NOCOUNT ON

DECLARE
	@r int,
	@e int
	
UPDATE dbo.LOANS
SET
	BRANCH_ID				= H.BRANCH_ID
	,DEPT_NO				= H.DEPT_NO
	,AUTHORIZE_LEVEL		= H.AUTHORIZE_LEVEL
	,[STATE]				= H.STATE
	,CLIENT_NO				= H.CLIENT_NO
	,CREDIT_LINE_ID			= H.CREDIT_LINE_ID
	,PRODUCT_ID				= H.PRODUCT_ID
	,AGREEMENT_NO			= H.AGREEMENT_NO
	,REG_DATE				= H.REG_DATE
	,LOAN_TYPE				= H.LOAN_TYPE
	,DISBURSE_TYPE			= H.DISBURSE_TYPE
	,ENSURE_TYPE			= H.ENSURE_TYPE
	,INSTALLMENT			= H.INSTALLMENT
	,EVENT_INSTALLMENT		= H.EVENT_INSTALLMENT
	,RESTRUCTURED			= H.RESTRUCTURED
	,PROLONGED				= H.PROLONGED
	,ISO					= H.ISO
	,AMOUNT					= H.AMOUNT
	,DISBURSE_AMOUNT		= H.DISBURSE_AMOUNT
	,[START_DATE]			= H.START_DATE
	,PERIOD					= H.PERIOD
	,END_DATE				= H.END_DATE
	,INTRATE				= H.INTRATE
	,PENALTY_INTRATE		= H.PENALTY_INTRATE
	,PREPAYMENT_INTRATE		= H.PREPAYMENT_INTRATE
	,PREPAYMENT_STEP		= H.PREPAYMENT_STEP
	,NOTUSED_INTRATE		= H.NOTUSED_INTRATE
	,ADMIN_INTRATE			= H.ADMIN_INTRATE
	,ADMIN_FEE				= H.ADMIN_FEE
	,RISK_TYPE				= H.RISK_TYPE
	,RISK_PERC_RATE_1		= H.RISK_PERC_RATE_1
	,RISK_PERC_RATE_2		= H.RISK_PERC_RATE_2
	,RISK_PERC_RATE_3		= H.RISK_PERC_RATE_3
	,RISK_PERC_RATE_4		= H.RISK_PERC_RATE_4
	,RISK_PERC_RATE_5		= H.RISK_PERC_RATE_5
	,WRITEOFF_DATE			= H.WRITEOFF_DATE
	,INTEREST_FLAGS			= H.INTEREST_FLAGS
	,PENALTY_FLAGS			= H.PENALTY_FLAGS
	,PREPAYMENT_FLAGS		= H.PREPAYMENT_FLAGS
	,PAYMENT_INTERVAL_TYPE	= H.PAYMENT_INTERVAL_TYPE
	,SCHEDULE_TYPE			= H.SCHEDULE_TYPE
	,PAYMENT_DAY			= H.PAYMENT_DAY
	,RESERVE_MAX_CATEGORY	= H.RESERVE_MAX_CATEGORY
	,INSTALLMENT_PERCENT	= H.INSTALLMENT_PERCENT
	,GRACE_STEPS			= H.GRACE_STEPS
	,GRACE_TYPE				= H.GRACE_TYPE
	,BASIS					= H.BASIS
	,RESPONSIBLE_USER_ID	= H.RESPONSIBLE_USER_ID
	,CORESPONSIBLE_USER_ID	= H.CORESPONSIBLE_USER_ID
	,PURPOSE_TYPE			= H.PURPOSE_TYPE
	,BAL_ACC				= H.BAL_ACC
	,GROUP_ID				= H.GROUP_ID
	,CLIENT_ACCOUNT			= H.CLIENT_ACCOUNT	
	,LINKED_CCY				= H.LINKED_CCY
	,INDEXED_RATE			= H.INDEXED_RATE
	,INSURANCE_RATE			= H.INSURANCE_RATE
	,SERVICE_FEE_RATE		= H.SERVICE_FEE_RATE
	,SERVICE_FEE			= H.SERVICE_FEE
	,MAIN_COLLATERAL_LIST	= H.MAIN_COLLATERAL_LIST
	,PMT					= H.PMT
	,GRACE_FINISH_DATE		= H.GRACE_FINISH_DATE
	,CLOSE_DATE				= H.CLOSE_DATE
	,GUARANTEE				= H.GUARANTEE
	,INTERNAT_GUARANTEE		= H.INTERNAT_GUARANTEE
	,IMMEDIATE_FEEING		= H.IMMEDIATE_FEEING
FROM dbo.LOANS L (ROWLOCK)
	INNER JOIN dbo.LOANS_HISTORY H (ROWLOCK) ON L.LOAN_ID = H.LOAN_ID
WHERE H.OP_ID = @op_id

SELECT @r = @@ROWCOUNT, @e = @@ERROR
IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
IF @r <> 1 BEGIN RAISERROR('RECORD NOT FOUND',16,1) RETURN(1) END

IF @delete_backup = 1
BEGIN
	DELETE FROM dbo.LOANS_HISTORY WHERE OP_ID = @op_id 
	SELECT @r = @@ROWCOUNT, @e = @@ERROR
	IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
	IF @r <> 1 BEGIN RAISERROR('RECORD NOT FOUND',16,1) RETURN(1) END
END

RETURN 0

GO
