SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[ON_USER_SWIFT_SEND_IN_MODULE]
	@user_id int,
	@rec_id int,
	@op_num int OUTPUT,
	@date_add smalldatetime OUTPUT,
	@doc_date smalldatetime OUTPUT,
	@doc_date_in_doc smalldatetime OUTPUT,
	@iso TISO OUTPUT,
	@amount TAMOUNT OUTPUT,
	@amount_equ TAMOUNT OUTPUT,
	@doc_num int OUTPUT,
	@op_code TOPCODE OUTPUT,
	@debit TACCOUNT OUTPUT,
	@credit TACCOUNT OUTPUT,
	@rec_state tinyint OUTPUT,
	@bnk_cli_id int OUTPUT,
	@descrip varchar(150) OUTPUT,
	@parent_rec_id int OUTPUT,
	@owner int OUTPUT,
	@doc_type smallint OUTPUT,
	@account_extra TACCOUNT OUTPUT,
	@prog_id int OUTPUT,
	@foreign_id int OUTPUT,
	@channel_id int OUTPUT,
	@dept_no int OUTPUT,
	@is_suspicious bit OUTPUT,
	@sender_bank_code TINTBANKCODE OUTPUT,
	@sender_bank_name varchar(100) OUTPUT,
	@sender_acc TINTACCOUNT OUTPUT,
	@sender_acc_name varchar(100) OUTPUT,
	@receiver_bank_code TINTBANKCODE OUTPUT,
	@receiver_bank_name varchar(100) OUTPUT,
	@receiver_acc TINTACCOUNT OUTPUT,
	@receiver_acc_name varchar(100) OUTPUT,
	@intermed_bank_code TINTBANKCODE OUTPUT,
	@intermed_bank_name varchar(100) OUTPUT,
	@receiver_info varchar(255) OUTPUT,
	@receiver_info_1 varchar(35) OUTPUT,
	@receiver_info_2 varchar(35) OUTPUT,
	@receiver_info_3 varchar(35) OUTPUT,
	@receiver_info_4 varchar(35) OUTPUT,
	@sender_tax_code varchar(11) OUTPUT,
	@receiver_tax_code varchar(11) OUTPUT,
	@first_name varchar(50) OUTPUT,
	@last_name varchar(50) OUTPUT,
	@fathers_name varchar(50) OUTPUT,
	@birth_date smalldatetime OUTPUT,
	@birth_place varchar(100) OUTPUT,
	@address_jur varchar(100) OUTPUT,
	@address_fact varchar(100) OUTPUT,
	@country char(2) OUTPUT,
	@passport_type_id tinyint OUTPUT,
	@passport varchar(50) OUTPUT,
	@personal_id varchar(20) OUTPUT,
	@ref_num varchar(32) OUTPUT,
	@cor_bank_code TINTBANKCODE OUTPUT,
	@cor_account varchar(35) OUTPUT,
	@cor_bank_name varchar(100) OUTPUT,
	@address_lat varchar(100) OUTPUT,
	@swift_rec_state tinyint OUTPUT,
	@swift_add_date smalldatetime OUTPUT,
	@swift_rec_id varchar(100) OUTPUT,
	@receiver_institution TINTBANKCODE OUTPUT,
	@receiver_institution_name varchar(100) OUTPUT,
	@swift_op_code varchar(55) OUTPUT,
	@doc_date_str char(8) OUTPUT,
	@sender_acc_swift varchar(50) OUTPUT,
	@sender_descrip varchar(100) OUTPUT,
	@descrip_ext varchar(255) OUTPUT,
	@fin_date smalldatetime OUTPUT,
	@fin_account TACCOUNT OUTPUT,
	@fin_acc_name varchar(100) OUTPUT,
	@fin_amount TAMOUNT OUTPUT,
	@fin_iso TISO OUTPUT,
	@fin_doc_rec_id int OUTPUT,
	@det_of_charg char(3) OUTPUT
AS
SET NOCOUNT ON
--SET @swift_rec_state = 20

RETURN (0)
GO
