SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[LOAN_SP_GET_GEN_AGREE_OPS]
  @credit_line_id int,
  @eng_version bit = 0 
AS
	DECLARE
		@last_op_id int

	SET @last_op_id = dbo.LOAN_FN_GET_GEN_AGREE_LAST_OP_ID(@credit_line_id)

                    
	SELECT O.OP_ID, O.CREDIT_LINE_ID, O.OP_DATE, O.OP_TYPE,
		CASE WHEN @eng_version = 0 THEN T.DESCRIP ELSE T.DESCRIP_LAT END AS OP_DESCRIP,
		@last_op_id AS LAST_OP_ID, O.AMOUNT, O.OP_STATE, T.SELF_EXEC, 
		O.OP_NOTE, O.OWNER, O.AUTH_OWNER, O.DOC_REC_ID,
		RTRIM(U.USER_NAME) + '@' + DP_U.ALIAS AS U_OWNER_NAME,
		CASE WHEN US.USER_NAME IS NULL THEN US.USER_NAME ELSE RTRIM(US.USER_NAME) + '@' + DP_US.ALIAS END AS US_AUTH_OWNER_NAME
 	FROM dbo.LOAN_GEN_AGREE_OPS O (NOLOCK)
		INNER JOIN dbo.LOAN_GEN_AGREE_OP_TYPES T (NOLOCK) ON T.TYPE_ID = O.OP_TYPE
		INNER JOIN dbo.USERS U (NOLOCK) ON O.OWNER = U.USER_ID
		INNER JOIN dbo.DEPTS DP_U (NOLOCK) ON DP_U.DEPT_NO = U.DEPT_NO
        LEFT JOIN dbo.USERS US (NOLOCK) ON O.AUTH_OWNER = US.USER_ID
		LEFT JOIN dbo.DEPTS DP_US (NOLOCK) ON DP_US.DEPT_NO = US.DEPT_NO
	WHERE O.CREDIT_LINE_ID = @credit_line_id --AND ((L.AUTHORIZE_LEVEL >= L.STATE) OR (L.STATE > 20))
	ORDER BY O.OP_ID

	RETURN (0)
GO
