SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[LOAN_SP_BACKUP_LOAN_SCHEDULE]
	@op_id int,
	@loan_id int = NULL
AS
SET NOCOUNT ON

DECLARE
	@r int,
	@e int
	
IF @loan_id IS NULL
BEGIN
	SELECT @loan_id = LOAN_ID
	FROM dbo.LOAN_OPS (NOLOCK)
	WHERE OP_ID = @op_id

	SELECT @r = @@ROWCOUNT, @e = @@ERROR
	IF @e <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END
	IF @r <> 1 BEGIN RAISERROR('RECORD NOT FOUND',16,1) RETURN(1) END
END


INSERT INTO dbo.LOAN_SCHEDULE_HISTORY(LOAN_ID,OP_ID,SCHEDULE_DATE,INTEREST_DATE,AMOUNT,PRINCIPAL,INTEREST,NU_INTEREST,BALANCE,PAY_INTEREST,INTEREST_CORRECTION,NU_INTEREST_CORRECTION,ORIGINAL_AMOUNT,ORIGINAL_PRINCIPAL,ORIGINAL_INTEREST,ORIGINAL_NU_INTEREST,ORIGINAL_BALANCE,INSURANCE,SERVICE_FEE,ORIGINAL_INSURANCE,ORIGINAL_SERVICE_FEE, 	
										DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE, ORIGINAL_DEFERED_INTEREST, ORIGINAL_DEFERED_OVERDUE_INTEREST, ORIGINAL_DEFERED_PENALTY, ORIGINAL_DEFERED_FINE)
SELECT LOAN_ID,@op_id,SCHEDULE_DATE,INTEREST_DATE,AMOUNT,PRINCIPAL,INTEREST,NU_INTEREST,BALANCE,PAY_INTEREST,INTEREST_CORRECTION,NU_INTEREST_CORRECTION,ORIGINAL_AMOUNT,ORIGINAL_PRINCIPAL,ORIGINAL_INTEREST,ORIGINAL_NU_INTEREST,ORIGINAL_BALANCE,INSURANCE,SERVICE_FEE,ORIGINAL_INSURANCE,ORIGINAL_SERVICE_FEE,
										DEFERED_INTEREST, DEFERED_OVERDUE_INTEREST, DEFERED_PENALTY, DEFERED_FINE, ORIGINAL_DEFERED_INTEREST, ORIGINAL_DEFERED_OVERDUE_INTEREST, ORIGINAL_DEFERED_PENALTY, ORIGINAL_DEFERED_FINE
FROM dbo.LOAN_SCHEDULE
WHERE LOAN_ID=@loan_id

IF @@ERROR <> 0 BEGIN RAISERROR ('ÛÄÝÃÏÌÀ.',16,1) RETURN(1) END

RETURN 0
GO
