SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[depo_show_depo_ops]
	@did int = Null,
	@eng_version bit = 0 
AS

SET NOCOUNT ON;

DECLARE @last_op_id int

SELECT TOP 1 @last_op_id = OP_ID 
FROM dbo.DEPO_OPS (NOLOCK) 
WHERE DEPO_ID = @did
ORDER BY OP_ID DESC

SELECT O.OP_ID, O.DEPO_ID, O.DT, O.OP_NO, O.OP_TYPE, 
    CASE WHEN @eng_version = 0 THEN D.DESCRIP ELSE D.DESCRIP_LAT END AS OP_DESCRIP,
    O.OWN_DATA, O.AMOUNT, O.SELF_EXEC, O.COMMIT_STATE, O.DOC_REC_ID, O.OWNER, O.COMMITER_OWNER, 
    O.EXT_DATE, O.EXT_MONEY, O.EXT_INT, O.EXT_ACC_ID,
	@last_op_id AS LAST_OP_ID
FROM dbo.DEPO_OPS O (NOLOCK) 
	INNER JOIN dbo.DEPO_OPS_DESCRIP D (NOLOCK) ON D.OP_TYPE = O.OP_TYPE
WHERE O.DEPO_ID = @did
ORDER BY O.OP_ID

RETURN(0)
GO
