SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INCASSO_CLOSE_DAY]
	@dt smalldatetime
AS

SET NOCOUNT ON

DECLARE @tbl TABLE (INCASSO_ID int NOT NULL PRIMARY KEY)

INSERT INTO dbo.INCASSO_ARC 
OUTPUT inserted.REC_ID INTO @tbl
SELECT * 
FROM dbo.INCASSO
WHERE REC_STATE = 9 AND PENDING = 0
IF @@ERROR <> 0 RETURN 1

INSERT INTO dbo.INCASSO_ACCOUNTS_ARC 
SELECT IA.* 
FROM dbo.INCASSO_ACCOUNTS IA
	INNER JOIN @tbl A ON A.INCASSO_ID = IA.INCASSO_ID
IF @@ERROR <> 0 RETURN 2

INSERT INTO dbo.INCASSO_OPS_ARC 
SELECT IA.* 
FROM dbo.INCASSO_OPS IA
	INNER JOIN @tbl A ON A.INCASSO_ID = IA.INCASSO_ID
IF @@ERROR <> 0 RETURN 3

---

DELETE IA
FROM dbo.INCASSO_OPS IA
	INNER JOIN @tbl A ON A.INCASSO_ID = IA.INCASSO_ID
IF @@ERROR <> 0 RETURN 3

DELETE IA
FROM dbo.INCASSO_ACCOUNTS IA
	INNER JOIN @tbl A ON A.INCASSO_ID = IA.INCASSO_ID
IF @@ERROR <> 0 RETURN 3

DELETE IA
FROM dbo.INCASSO IA
	INNER JOIN @tbl A ON A.INCASSO_ID = IA.REC_ID
RETURN @@ERROR
GO
