SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[CHANGE_NAME]
 @OLD_NAME VARCHAR(100),
 @NEW_NAME VARCHAR(100)
AS

DECLARE @TMP_NAME VARCHAR(100)

--SET @TMP_NEW_NAME = 'LTD ONE'
SET @TMP_NAME = '%' + @OLD_NAME + '%'

-- ÀÍÂÀÒÉÛÄÁÉÓ ÃÀÓÀáÄËÄÁÄÁÉÓ ÛÄÝÅËÀ

EXEC SYS_DISABLE_CONSTRAINTS 'DOC_DETAILS_ARC_PLAT'
EXEC SYS_DISABLE_CONSTRAINTS 'DOC_DETAILS_ARC_KAS'
EXEC SYS_DISABLE_CONSTRAINTS 'DOCS_ARC'

UPDATE  ACCOUNTS SET
	DESCRIP = @NEW_NAME
WHERE	DESCRIP LIKE @TMP_NAME

-- ÀÒØÉÅÄÁÉÓ ÛÄÝÅËÀ

UPDATE	DOC_DETAILS_ARC_PLAT SET
	RECEIVER_ACC_NAME = @NEW_NAME
WHERE	RECEIVER_ACC_NAME LIKE @TMP_NAME

UPDATE	DOC_DETAILS_ARC_PLAT SET
	SENDER_ACC_NAME = @NEW_NAME
WHERE	SENDER_ACC_NAME LIKE @TMP_NAME

UPDATE	DOC_DETAILS_ARC_KAS SET
	CLIENT_NAME = @NEW_NAME
WHERE	CLIENT_NAME LIKE @TMP_NAME

UPDATE	DOC_DETAILS_ARC_KAS SET
	DOCUMENT = @NEW_NAME
WHERE	DOCUMENT LIKE @TMP_NAME

UPDATE	DOCS_ARC SET
	DESCRIP = @NEW_NAME
WHERE	DESCRIP LIKE @TMP_NAME

EXEC SYS_ENABLE_CONSTRAINTS 'DOC_DETAILS_ARC_PLAT'
EXEC SYS_ENABLE_CONSTRAINTS 'DOC_DETAILS_ARC_KAS'
EXEC SYS_ENABLE_CONSTRAINTS 'DOCS_ARC'

-- ÙÉÀ ÃÙÄÛÉ ÛÄÝÅËÀ

UPDATE	DOC_DETAILS_PLAT SET
	RECEIVER_ACC_NAME = @NEW_NAME
WHERE	RECEIVER_ACC_NAME LIKE @TMP_NAME

UPDATE	DOC_DETAILS_PLAT SET
	SENDER_ACC_NAME = @NEW_NAME
WHERE	SENDER_ACC_NAME LIKE @TMP_NAME

UPDATE	DOC_DETAILS_KAS SET
	CLIENT_NAME = @NEW_NAME
WHERE	CLIENT_NAME LIKE @TMP_NAME

UPDATE	DOC_DETAILS_KAS SET
	DOCUMENT = @NEW_NAME
WHERE	DOCUMENT LIKE @TMP_NAME

UPDATE	DOCS SET
	DESCRIP = @NEW_NAME
WHERE	DESCRIP LIKE @TMP_NAME


RETURN

GO
