SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[BCC_ADD_LOG]
  @action tinyint,
  @text varchar(255)
 AS

SET NOCOUNT ON;

INSERT INTO B2000_LOG ([USER_ID],ACTION_CODE,DESCRIP,APP_SRV_ID) 
VALUES (8, @action, @text, 2)
GO
