SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[BCBR_PLATS_FOR_SEND]
AS

SET NOCOUNT ON

DECLARE 
  @corr_account_na TACCOUNT,
  @corr_account_va TACCOUNT

EXEC GET_SETTING_ACC 'CORR_ACC_NA', @corr_account_na OUTPUT
EXEC GET_SETTING_ACC 'CORR_ACC_VA', @corr_account_va OUTPUT

SELECT REC_ID,DOC_DATE,DOC_DATE_IN_DOC,ISO,AMOUNT,DOC_NUM,OP_CODE,DEBIT,CREDIT,DESCRIP,DOC_TYPE,ACCOUNT_EXTRA,PROD_ID,FOREIGN_ID,IS_SUSPICIOUS,
  CONVERT(varchar(30),SENDER_BANK_CODE) AS SENDER_BANK_CODE,CONVERT(varchar(100),SENDER_BANK_NAME) AS SENDER_BANK_NAME,
  SENDER_ACC,CONVERT(varchar(100),SENDER_ACC_NAME) AS SENDER_ACC_NAME,
  CONVERT(varchar(30),RECEIVER_BANK_CODE) AS RECEIVER_BANK_CODE,CONVERT(varchar(100),RECEIVER_BANK_NAME) AS RECEIVER_BANK_NAME,
  RECEIVER_ACC,CONVERT(varchar(100),RECEIVER_ACC_NAME) AS RECEIVER_ACC_NAME,
  SENDER_TAX_CODE,RECEIVER_TAX_CODE,
  CONVERT(varchar(30),NULL) AS INTERMED_BANK_CODE,CONVERT(varchar(100),NULL) AS INTERMED_BANK_NAME,
  REC_DATE, SAXAZKOD, EXTRA_INFO, 
  CONVERT(varchar(50),NULL) AS FIRST_NAME,
  CONVERT(varchar(50),NULL) AS LAST_NAME,
  CONVERT(varchar(50),NULL) AS FATHERS_NAME,
  CONVERT(smalldatetime,NULL) AS BIRTH_DATE,
  CONVERT(varchar(100),NULL) AS BIRTH_PLACE,
  CONVERT(varchar(100),NULL) AS ADDRESS_JUR,
  CONVERT(varchar(100),NULL) AS ADDRESS_LAT,
  CONVERT(varchar(2),NULL) AS COUNTRY,
  CONVERT(tinyint,NULL) AS PASSPORT_TYPE_ID,
  CONVERT(varchar(50),NULL) AS PASSPORT,
  CONVERT(varchar(20),NULL) AS PERSONAL_ID,
  CONVERT(text,NULL) AS SWIFT_TEXT, REF_NUM
FROM dbo.DOCS_PLAT(NOLOCK)
WHERE (REC_STATE BETWEEN 10 AND 19) AND ((ISO='GEL' and CREDIT=@corr_account_na) OR (ISO<>'GEL' and CREDIT=@corr_account_va))

UNION ALL

SELECT A.REC_ID,A.DOC_DATE,A.DOC_DATE_IN_DOC,A.ISO,A.AMOUNT,A.DOC_NUM,A.OP_CODE,A.DEBIT,A.CREDIT,A.DESCRIP,A.DOC_TYPE,A.ACCOUNT_EXTRA,A.PROD_ID,A.FOREIGN_ID,A.IS_SUSPICIOUS,
  A.SENDER_BANK_CODE,A.SENDER_BANK_NAME,
  A.SENDER_ACC,A.SENDER_ACC_NAME,
  A.RECEIVER_BANK_CODE,A.RECEIVER_BANK_NAME,
  A.RECEIVER_ACC,A.RECEIVER_ACC_NAME,
  A.SENDER_TAX_CODE,A.RECEIVER_TAX_CODE,
  A.INTERMED_BANK_CODE,A.INTERMED_BANK_NAME,
  null, null, A.EXTRA_INFO, 
  B.FIRST_NAME, B.LAST_NAME, B.FATHERS_NAME, B.BIRTH_DATE, B.BIRTH_PLACE, B.ADDRESS_JUR, B.ADDRESS_LAT, B.COUNTRY, B.PASSPORT_TYPE_ID, B.PASSPORT, B.PERSONAL_ID, 
  A.SWIFT_TEXT, A.REF_NUM
FROM dbo.DOCS_VALPLAT A
	INNER JOIN dbo.DOC_DETAILS_PASSPORTS B ON B.DOC_REC_ID = A.REC_ID
WHERE (REC_STATE BETWEEN 10 AND 19) AND (CREDIT=@corr_account_va)
GO
