SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[SYS_BUILD_OPS_HELPER_0000_TABLE] AS

SET NOCOUNT ON

PRINT 'Rebuilding OPS_HELPER_0000'

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

ALTER TABLE dbo.OPS_HELPER_0000 NOCHECK CONSTRAINT ALL

DELETE FROM dbo.OPS_HELPER_0000

INSERT INTO dbo.OPS_HELPER_0000 (ACC_ID, DT, REC_ID)
SELECT DEBIT_ID, DOC_DATE, REC_ID FROM dbo.OPS_0000 (TABLOCK)
UNION ALL
SELECT CREDIT_ID, DOC_DATE, REC_ID FROM dbo.OPS_0000 (TABLOCK)

ALTER TABLE dbo.OPS_HELPER_0000 CHECK CONSTRAINT ALL

COMMIT
GO
