SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PLASTIC_CARD_MOVE_FROM_SEND]
	@rec_id int,
	@card_id varchar(19),
	@card_name varchar(24),
	@expiry smalldatetime
AS

SET NOCOUNT ON

DECLARE
	@card_id_old varchar(19)

SELECT	@card_id_old = CARD_ID_OLD 
FROM	dbo.PLASTIC_CARDS_FOR_SEND
WHERE	REC_ID = @rec_id

SET @card_id_old = ISNULL(@card_id_old,'')

DECLARE 
	@internal_transaction bit

SET @internal_transaction = 0
IF @@TRANCOUNT = 0
BEGIN
	BEGIN TRAN
	SET @internal_transaction = 1
END

INSERT INTO	dbo.PLASTIC_CARDS (CARD_ID,CLIENT_NO,BIN,CARD_TYPE,CARD_NAME,CARD_EXPIRY,CLIENT_ADDRESS,BASE_SUPP,PASSWORD,CONTRACT,ENROLLED,DEPT_NO,CONDITION_SET,CARD_ID_OLD,CLIENT_CATEGORY,PROD_CODE,AUTHORIZE_CODE,AGR_RISK_LEVEL)
	SELECT	@card_id,CLIENT_NO,BIN,CARD_TYPE,@card_name,@expiry,CLIENT_ADDRESS,BASE_SUPP,PASSWORD,[CONTRACT],ENROLLED,DEPT_NO,CONDITION_SET,CARD_ID_OLD,CLIENT_CATEGORY,PROD_CODE,AUTHORIZE_CODE,AGR_RISK_LEVEL
	FROM	dbo.PLASTIC_CARDS_FOR_SEND
	WHERE	REC_ID = @rec_id

INSERT INTO	dbo.PLASTIC_CARD_ACCOUNTS (CARD_ID,ACCOUNT,ISO,CREDIT_AMOUNT,MIN_AMOUNT,NON_REDUCE_AMOUNT,AUTH_BONUS,AUTH_BONUS_EXPIRITY,DEPOSIT_ACCOUNT,DEPOSIT_ISO,DEPOSIT_AMOUNT,DEPOSIT_DESCRIP,MESSAGE,TRANSIT_ACCOUNT,TRANSIT_ISO,CONDITION_SET,ACC_ID,ORDER_NO,CLIENT_NO,BILLING_GROUP)
	SELECT	@card_id,ACCOUNT,ISO,CREDIT_AMOUNT,MIN_AMOUNT,NON_REDUCE_AMOUNT,AUTH_BONUS,AUTH_BONUS_EXPIRITY,DEPOSIT_ACCOUNT,DEPOSIT_ISO,DEPOSIT_AMOUNT,DEPOSIT_DESCRIP,MESSAGE,TRANSIT_ACCOUNT,TRANSIT_ISO,CONDITION_SET,ACC_ID,ORDER_NO,CLIENT_NO,BILLING_GROUP
	FROM	dbo.PLASTIC_CARD_ACCOUNTS_FOR_SEND
	WHERE	REC_ID = @rec_id

DELETE
	FROM	dbo.PLASTIC_CARD_ACCOUNTS_FOR_SEND
	WHERE	REC_ID = @rec_id

DELETE
	FROM	dbo.PLASTIC_CARDS_FOR_SEND
	WHERE	REC_ID = @rec_id

IF @card_id_old <> ''
BEGIN
	UPDATE	dbo.PLASTIC_CARD_ACCOUNTS
	SET		CARD_ID = @card_id
	WHERE	CARD_ID = @card_id_old
END

IF @@ERROR <> 0 BEGIN IF @internal_transaction=1 AND @@TRANCOUNT>0 ROLLBACK RETURN 1 END

IF @internal_transaction=1 AND @@TRANCOUNT>0 
	COMMIT TRAN

RETURN 0
GO
