SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [easy].[effr_CreateEffectiveRate]
	@loan_id int,
	@op_id int,
	@date smalldatetime
AS
BEGIN
	CREATE TABLE #EFFECTIVE_RATE
		(
			RATE_TYPE int PRIMARY KEY,
			CODE varchar(50) COLLATE Latin1_General_BIN
								NOT NULL,
			DESCRIPTION nvarchar(512) COLLATE Latin1_General_BIN,
			RATE decimal(20, 8),
			CASH_FLOW xml NULL
		);
	
	INSERT INTO #EFFECTIVE_RATE
	EXEC easy.calculate_effective_rate @loan_id = @loan_id, @date = @date
	
	INSERT INTO easy.EffectiveRates (LOAN_ID, OP_ID, CODE, DESCRIPTION, RATE, CASH_FLOW)
	SELECT @loan_id, @op_id, CODE, DESCRIPTION, RATE, CASH_FLOW 
	FROM #EFFECTIVE_RATE
	
	DELETE FROM dbo.LOAN_ATTRIBUTES
	WHERE ATTRIB_CODE IN ('EFFECTIVE_RATE_SIMPLE', 'EFFECTIVE_RATE_DEVALUATION')

	INSERT INTO dbo.LOAN_ATTRIBUTES (LOAN_ID, ATTRIB_CODE, ATTRIB_VALUE)
	SELECT @loan_id, CASE CODE WHEN 'STD' THEN 'EFFECTIVE_RATE_SIMPLE' WHEN 'INFL' THEN 'EFFECTIVE_RATE_DEVALUATION' END, CAST(RATE AS money)
	FROM #EFFECTIVE_RATE
	WHERE CODE IN ('STD', 'INFL')
END
GO
