CREATE TABLE [af].[FUNCTIONS]
(
[FUNCTION_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[FUNCTION_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[COMMENT] [text] COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [af].[FUNCTIONS] ADD CONSTRAINT [PK_FUNCTIONS] PRIMARY KEY CLUSTERED  ([FUNCTION_ID]) ON [PRIMARY]
GO
