CREATE TABLE [af].[FUNCTION_PARAMS]
(
[FUNCTION_ID] [int] NOT NULL,
[PARAM_ID] [int] NOT NULL,
[PARAM_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[PARAM_TYPE] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [af].[FUNCTION_PARAMS] ADD CONSTRAINT [PK_FUNCTION_PARAMS] PRIMARY KEY CLUSTERED  ([FUNCTION_ID], [PARAM_ID]) ON [PRIMARY]
GO
ALTER TABLE [af].[FUNCTION_PARAMS] ADD CONSTRAINT [FK_FUNCTION_PARAMS_FUNCTIONS] FOREIGN KEY ([FUNCTION_ID]) REFERENCES [af].[FUNCTIONS] ([FUNCTION_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
