CREATE TABLE [auth].[SIGN_IN_RETURN_CODES]
(
[RC] [int] NOT NULL,
[DESCRIPTION] [nvarchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[MESSAGE_TEXT] [nvarchar] (150) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [auth].[SIGN_IN_RETURN_CODES] ADD CONSTRAINT [PK__SIGN_IN_RETURN_C__218F4751] PRIMARY KEY CLUSTERED  ([RC]) ON [PRIMARY]
GO
