CREATE TABLE [dbo].[PENDING_PAYMENTS]
(
[DOC_REC_ID] [int] NOT NULL,
[IS_ONLINE] [bit] NOT NULL,
[PROVIDER_ID] [int] NOT NULL,
[SERVICE_ALIAS] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[DOC_TYPE] [smallint] NOT NULL,
[OWNER] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[CHANNEL_ID] [int] NOT NULL,
[REC_STATE] [int] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_REC_STATE] DEFAULT ((0)),
[SORT_ORDER] [int] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_SORT_ORDER] DEFAULT ((0)),
[DT_TM] [smalldatetime] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_DT_TM] DEFAULT (getdate()),
[AMOUNT] [money] NOT NULL,
[ID_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ID2_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[CARD_ID] [varchar] (19) COLLATE Latin1_General_BIN NULL,
[CARD_TYPE] [smallint] NULL,
[INFO] [text] COLLATE Latin1_General_BIN NULL,
[RESPONSE] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[REF_NUM] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[INSERT_TIME] [datetime] NULL CONSTRAINT [DF_PENDING_PAYMENTS_INSERT_TIME] DEFAULT (getdate()),
[PAUSED] [bit] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_PAUSED] DEFAULT ((0)),
[LOCK_FLAG] [int] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_LOCK_FLAG] DEFAULT ((0)),
[WAITING_FLAG] [int] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_WAITING_FLAG] DEFAULT ((0)),
[DELETE_FLAG] [int] NOT NULL CONSTRAINT [DF_PENDING_PAYMENTS_DELETE_FLAG] DEFAULT ((0)),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PENDING_PAYMENTS] ADD CONSTRAINT [PK_PENDING_PAYMENTS] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [PRIMARY]
GO
