CREATE TABLE [dbo].[CROSS_RATES_KAS]
(
[ISO1] [dbo].[TISO] NOT NULL,
[ISO2] [dbo].[TISO] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT_BUY] [dbo].[TAMOUNT] NOT NULL,
[AMOUNT_SELL] [dbo].[TAMOUNT] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[CROSS_RATES_KAS_TRIGGER_ARC] ON [dbo].[CROSS_RATES_KAS] 
FOR UPDATE
AS

SET NOCOUNT ON

DECLARE @dt datetime
SET @dt = GETDATE()

INSERT INTO dbo.CROSS_RATES_KAS_ARC (ISO1,ISO2,ITEMS,AMOUNT_BUY,AMOUNT_SELL,DT_TM)
SELECT ISO1,ISO2,ITEMS,AMOUNT_BUY,AMOUNT_SELL,@dt
FROM DELETED

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[TRIGGER_CROSS_RATES_KAS] ON [dbo].[CROSS_RATES_KAS] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_CROSS_RATES_KAS'
 

GO
ALTER TABLE [dbo].[CROSS_RATES_KAS] ADD CONSTRAINT [PK_CROSS_RATES_KAS] PRIMARY KEY CLUSTERED  ([ISO1], [ISO2]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CROSS_RATES_KAS] WITH NOCHECK ADD CONSTRAINT [FK_CROSS_RATES_KAS_VAL_CODES] FOREIGN KEY ([ISO1]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
ALTER TABLE [dbo].[CROSS_RATES_KAS] WITH NOCHECK ADD CONSTRAINT [FK_CROSS_RATES_KAS_VAL_CODES1] FOREIGN KEY ([ISO2]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
