CREATE TABLE [dbo].[SWIFT_BIC_CODES]
(
[BIC] [varchar] (11) COLLATE Latin1_General_BIN NOT NULL,
[ISO] [dbo].[TISO] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_BIC_CODES] ADD CONSTRAINT [PK_SWIFT_BIC_CODES] PRIMARY KEY CLUSTERED  ([BIC], [ISO]) ON [PRIMARY]
GO
