CREATE TABLE [dbo].[SO_PRODUCTS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[AGREEMENT_TEMPLATE] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[REG_DATE] [smalldatetime] NOT NULL CONSTRAINT [DF_SO_PRODUCTS_REG_DATE] DEFAULT (getdate()),
[CHARGE_TYPE] [smallint] NOT NULL,
[ORDER_TYPES] [smallint] NOT NULL,
[DEBT_ACTIONS] [int] NOT NULL,
[PAYMENT_TYPE] [int] NOT NULL,
[PERIOD_TYPES] [int] NOT NULL,
[HOLIDAY_SHIFTING] [smallint] NOT NULL,
[MIN_PERIOD] [int] NOT NULL,
[MAX_PERIOD] [int] NOT NULL,
[FEE_RECV_PERCENT] [smallmoney] NOT NULL,
[FEE_MIN] [money] NOT NULL,
[PRIORITY] [smallint] NOT NULL,
[MAX_RETRY_COUNT_PER_PAYMENT] [smallint] NOT NULL,
[MIN_RETRY_COUNT_PER_PAYMENT] [smallint] NOT NULL,
[MIN_FAILURE_COUNT] [smallint] NOT NULL,
[MAX_FAILURE_COUNT] [smallint] NOT NULL,
[STATE] [tinyint] NOT NULL,
[VISIBLE] [bit] NOT NULL,
[FX_RATE_TYPE] [tinyint] NOT NULL,
[ACK_FIELDS] [int] NOT NULL,
[PRODUCT_OWNER] [tinyint] NOT NULL,
[REMOTE_REGISTRATION] [bit] NOT NULL,
[REMOTE_AUTHORIZATION] [bit] NOT NULL,
[REMOTE_SUSPEND] [bit] NOT NULL,
[REMOTE_DEACTIVATION] [bit] NOT NULL,
[END_DATE] [smalldatetime] NULL,
[EXECUTION_TIME] [smallint] NOT NULL,
[USE_TARIFF] [bit] NOT NULL,
[MIN_BAL_CONTROL] [bit] NOT NULL,
[CCYS] [varchar] (800) COLLATE Latin1_General_BIN NOT NULL,
[DEBIT_ACC_TYPES] [int] NOT NULL,
[CREDIT_ACC_TYPES] [int] NOT NULL,
[OP_CODE] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[DOC_STATE] [smallint] NOT NULL CONSTRAINT [DF_SO_PRODUCTS_DOC_SATE] DEFAULT ((0)),
[DOC_TYPE] [smallint] NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_TEMPLATE] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DESCRIP_TEMPLATE_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[RESPONSIBLE_USER_ID] [int] NOT NULL,
[CLIENT_TYPES] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [CK_SO_PRODUCTS_CHARGE_TYPE] CHECK (([CHARGE_TYPE]>(0)))
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [CK_SO_PRODUCTS_DEBT_ACTIONS] CHECK (([DEBT_ACTIONS]>(0)))
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [CK_SO_PRODUCTS_FX_RATE_TYPE] CHECK (([FX_RATE_TYPE]>(0)))
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [CK_SO_PRODUCTS_ORDER_TYPES] CHECK (([ORDER_TYPES]>(0)))
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [CK_SO_PRODUCTS_PERIOD_TYPES] CHECK (([PERIOD_TYPES]>(0)))
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [PK_SO_PRODUCTS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [IX_SO_PRODUCT_NAME] UNIQUE NONCLUSTERED  ([DESCRIP]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [IX_SO_PRODUCT_DESCRIP_LAT] UNIQUE NONCLUSTERED  ([DESCRIP_LAT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [FK_SO_PRODUCTS_ACC_VIEWS_CREDIT] FOREIGN KEY ([CREDIT_ACC_TYPES]) REFERENCES [dbo].[ACC_VIEWS] ([ID])
GO
ALTER TABLE [dbo].[SO_PRODUCTS] ADD CONSTRAINT [FK_SO_PRODUCTS_ACC_VIEWS_DEBIT] FOREIGN KEY ([DEBIT_ACC_TYPES]) REFERENCES [dbo].[ACC_VIEWS] ([ID])
GO
