CREATE TABLE [dbo].[DEL_DOCS]
(
[REC_ID] [int] NOT NULL,
[DOC_DATE] [smalldatetime] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [dbo].[TAMOUNT] NOT NULL,
[DEBIT] [dbo].[TACCOUNT] NOT NULL,
[CREDIT] [dbo].[TACCOUNT] NOT NULL,
[BRANCH_ID] [int] NULL,
[DEPT_NO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEL_DOCS] ADD CONSTRAINT [PK_DELETED_DOCS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
