CREATE TABLE [dbo].[SAXAZCODES9]
(
[SAXAZKOD] [varchar] (9) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[SAXAZCODES9_TRIGGER] ON [dbo].[SAXAZCODES9]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_SAXAZCODES9'
GO
ALTER TABLE [dbo].[SAXAZCODES9] ADD CONSTRAINT [PK_SAXAZCODES9] PRIMARY KEY CLUSTERED  ([SAXAZKOD]) ON [PRIMARY]
GO
