CREATE TABLE [dbo].[SWIFT_DOCS_IN_CHANGES]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_DOCS_IN_CHANGES] ADD CONSTRAINT [PK_SWIFT_DOCS_IN_CHANGES] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_DOCS_IN_CHANGES] ADD CONSTRAINT [FK_SWIFT_DOCS_IN_CHANGES_SWIFT_DOCS_IN] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [dbo].[SWIFT_DOCS_IN] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[SWIFT_DOCS_IN_CHANGES] ADD CONSTRAINT [FK_SWIFT_DOCS_IN_CHANGES_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
