CREATE TABLE [dbo].[LOAN_INSTALLMENT_CLIENT_OBJECTS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[CLIENT_NO] [int] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[ADDRESS] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[ADDRESS_LAT] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[IS_ACTIVE] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENT_CLIENT_OBJECTS] ADD CONSTRAINT [PK_LOAN_INSTALLMENT_CLIENT_OBJECTS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_INSTALLMENT_CLIENT_OBJECTS] ON [dbo].[LOAN_INSTALLMENT_CLIENT_OBJECTS] ([CLIENT_NO]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_LOAN_INSTALLMENT_CLIENT_OBJECTS_1] ON [dbo].[LOAN_INSTALLMENT_CLIENT_OBJECTS] ([CLIENT_NO], [DESCRIP], [ADDRESS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENT_CLIENT_OBJECTS] ADD CONSTRAINT [FK_LOAN_INSTALLMENT_CLIENT_OBJECTS_LOAN_INSTALLMENT_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[LOAN_INSTALLMENT_CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
