CREATE TABLE [dbo].[LOAN_CLIENT_BAL_ACCS]
(
[BAL_ACC] [dbo].[TBAL_ACC] NOT NULL,
[ACCOUNT_BAL_ACC] [dbo].[TBAL_ACC] NOT NULL,
[OPEN_ACCOUNT] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLIENT_BAL_ACCS] ADD CONSTRAINT [PK_LOAN_CLIENT_BAL_ACCS] PRIMARY KEY CLUSTERED  ([BAL_ACC], [ACCOUNT_BAL_ACC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLIENT_BAL_ACCS] ADD CONSTRAINT [FK_LOAN_CLIENT_BAL_ACCS_PLANLIST_ALT_1] FOREIGN KEY ([BAL_ACC]) REFERENCES [dbo].[PLANLIST_ALT] ([BAL_ACC]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_CLIENT_BAL_ACCS] ADD CONSTRAINT [FK_LOAN_CLIENT_BAL_ACCS_PLANLIST_ALT_2] FOREIGN KEY ([ACCOUNT_BAL_ACC]) REFERENCES [dbo].[PLANLIST_ALT] ([BAL_ACC])
GO
