CREATE TABLE [dbo].[DOC_CHANGES]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_DOC_CHANGE_TIME_OF_CH] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_CHANGES] ADD CONSTRAINT [PK_DOC_CHANGES] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_CHANGES] WITH NOCHECK ADD CONSTRAINT [FK_DOC_CHANGES_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[DOC_CHANGES] ADD CONSTRAINT [FK_DOC_CHANGES_DOC_REC_ID_IN_OPS] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [dbo].[OPS_0000] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
