CREATE TABLE [dbo].[ACC_BLOCK_PRODUCTS]
(
[PRODUCT_ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BLOCK_PRODUCTS] ADD CONSTRAINT [PK_ACC_BLOCK_PRODUCTS] PRIMARY KEY CLUSTERED  ([PRODUCT_ID]) ON [PRIMARY]
GO
