CREATE TABLE [dbo].[LOAN_RISK_ANALYSE]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[TYPE_ID] [int] NOT NULL,
[LEVEL_ID] [int] NOT NULL,
[LATE_DAY1] [smallint] NULL,
[LATE_DAY2] [smallint] NULL,
[OVERDUE_DAY1] [smallint] NULL,
[OVERDUE_DAY2] [smallint] NULL,
[IS_CALLOFFED] [bit] NOT NULL,
[CALLOFF_DAY1] [smallint] NULL,
[CALLOFF_DAY2] [smallint] NULL,
[COLLATERAL_TYPE] [smallint] NULL,
[IS_PROLONGED] [bit] NULL,
[IS_RESTRUCTURED] [bit] NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_RISK_ANALYSE] ADD CONSTRAINT [PK_LOAN_RISK_ANALYSE] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_RISK_ANALYSE_LEVEL_ID] ON [dbo].[LOAN_RISK_ANALYSE] ([LEVEL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_RISK_ANALYSE_TYPE_ID] ON [dbo].[LOAN_RISK_ANALYSE] ([TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_RISK_ANALYSE] ADD CONSTRAINT [FK_LOAN_RISK_ANALYSE_LOAN_RISK_LEVELS] FOREIGN KEY ([LEVEL_ID]) REFERENCES [dbo].[LOAN_RISK_LEVELS] ([LEVEL_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_RISK_ANALYSE] ADD CONSTRAINT [FK_LOAN_RISK_ANALYSE_LOAN_RISK_TYPES] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[LOAN_RISK_TYPES] ([TYPE_ID]) ON DELETE CASCADE
GO
