CREATE TABLE [dbo].[DEPO_CLASSIF]
(
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_CLASSIF] ADD CONSTRAINT [PK_DEPO_CLASSIF] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
