CREATE TABLE [dbo].[REPORTS]
(
[TAG] [smallint] NOT NULL,
[DESCRIP] [char] (50) COLLATE Latin1_General_BIN NOT NULL,
[REPORT_DATA] [image] NULL,
[REPORT_TYPE] [tinyint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[REPORTS_TRIGGER] ON [dbo].[REPORTS] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_REPORTS'


GO
ALTER TABLE [dbo].[REPORTS] ADD CONSTRAINT [PK_REPORTS] PRIMARY KEY CLUSTERED  ([TAG], [DESCRIP]) ON [PRIMARY]
GO
