CREATE TABLE [dbo].[DEPO_PRODUCT_PROPERTIES]
(
[PROD_ID] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT_MIN] [money] NULL,
[AMOUNT_MAX] [money] NULL,
[ACCRUE_AMOUNT_MIN] [money] NULL,
[ACCRUE_AMOUNT_MAX] [money] NULL,
[ACCUMULATE_MIN] [money] NULL,
[ACCUMULATE_MAX] [money] NULL,
[ACCUMULATE_AMOUNT] [money] NULL,
[ACCUMULATE_AMOUNT_LIMIT] [money] NULL,
[SPEND_MIN] [money] NULL,
[SPEND_MAX] [money] NULL,
[SPEND_INTRATE] [money] NULL,
[SPEND_TYPE] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PRODUCT_PROPERTIES] ADD CONSTRAINT [PK_DEPO_PRODUCT_PROPERTIES] PRIMARY KEY CLUSTERED  ([PROD_ID], [ISO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PRODUCT_PROPERTIES] ADD CONSTRAINT [FK_DEPO_PRODUCT_PROPERTIES_DEPO_PRODUCT] FOREIGN KEY ([PROD_ID]) REFERENCES [dbo].[DEPO_PRODUCT] ([PROD_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DEPO_PRODUCT_PROPERTIES] ADD CONSTRAINT [FK_DEPO_PRODUCT_PROPERTIES_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
