CREATE TABLE [dbo].[DEPO_PRODUCT_DEPO_ATTRIB_CODES]
(
[CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[PROD_ID] [int] NOT NULL,
[IS_REQUIRED] [tinyint] NOT NULL CONSTRAINT [DF_DEPO_PRODUCT_DEPO_ATTRIB_CODES_IS_REQUIRED] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PRODUCT_DEPO_ATTRIB_CODES] ADD CONSTRAINT [PK_DEPO_PRODUCT_DEPO_ATTRIB_CODES] PRIMARY KEY CLUSTERED  ([CODE], [PROD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PRODUCT_DEPO_ATTRIB_CODES] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_ATTRIB_CODES_DEPO_ATTRIB_CODES] FOREIGN KEY ([CODE]) REFERENCES [dbo].[DEPO_ATTRIB_CODES] ([CODE])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT_DEPO_ATTRIB_CODES] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_ATTRIB_CODES_DEPO_PRODUCT] FOREIGN KEY ([PROD_ID]) REFERENCES [dbo].[DEPO_PRODUCT] ([PROD_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
