CREATE TABLE [dbo].[ACCOUNTS_DETAILS]
(
[ACC_ID] [int] NOT NULL,
[SALDO] [money] NULL,
[SHADOW_DBO] [money] NULL,
[SHADOW_CRO] [money] NULL,
[SALDO_AVAILABLE] AS ((isnull([SALDO],($0.0000))+isnull([SHADOW_DBO],($0.0000)))-isnull([SHADOW_CRO],($0.0000))),
[LAST_OP_DATE] [smalldatetime] NULL,
[AMOUNT_KAS_DELTA] [money] NULL,
[UID2] [int] NOT NULL CONSTRAINT [DF_ACCOUNTS_DETAILS_UID2] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_DETAILS] ADD CONSTRAINT [PK_ACCOUNTS_DETAILS] PRIMARY KEY CLUSTERED  ([ACC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_DETAILS] ADD CONSTRAINT [FK_ACCOUNTS_DETAILS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
