CREATE TABLE [dbo].[CLIENT_DOCUMENT_REQUIREMENT]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[CLIENT_TYPE] [tinyint] NOT NULL,
[CLIENT_SUBTYPE] [tinyint] NULL,
[ORG_TYPE] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DOCUMENT_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[IS_MANDATORY] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_DOCUMENT_REQUIREMENT] ADD CONSTRAINT [PK_CLIENT_DOCUMENT_REQUIREMENT] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_DOCUMENT_REQUIREMENT] ADD CONSTRAINT [IX_CLIENT_DOCUMENT_REQUIREMENT_UQ] UNIQUE NONCLUSTERED  ([CLIENT_TYPE], [CLIENT_SUBTYPE], [ORG_TYPE], [DOCUMENT_NAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_DOCUMENT_REQUIREMENT] ADD CONSTRAINT [FK_CLIENT_DOCUMENT_REQUIREMENT_CLIENT_DOCUMENT_TYPES] FOREIGN KEY ([DOCUMENT_NAME]) REFERENCES [dbo].[CLIENT_DOCUMENT_TYPES] ([DOCUMENT_NAME]) ON DELETE CASCADE ON UPDATE CASCADE
GO
