CREATE TABLE [dbo].[USER_PASSWORD_HISTORY]
(
[USER_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[PSWHASH] [char] (32) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_PASSWORD_HISTORY] ADD CONSTRAINT [PK_USER_PASSWORD_HISTORY] PRIMARY KEY CLUSTERED  ([USER_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_PASSWORD_HISTORY] ADD CONSTRAINT [FK_USER_PASSWORD_HISTORY_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE
GO
