CREATE TABLE [dbo].[OPS_HELPER_0000]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[REC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OPS_HELPER_0000] ADD CONSTRAINT [CK_OPS_HELPER_0000] CHECK (([DT]>='20170901'))
GO
ALTER TABLE [dbo].[OPS_HELPER_0000] ADD CONSTRAINT [PK_OPS_HELPER_0000] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT], [REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_HELPER_0000] ON [dbo].[OPS_HELPER_0000] ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OPS_HELPER_0000] WITH NOCHECK ADD CONSTRAINT [FK_OPS_HELPER_0000_OPS_0000] FOREIGN KEY ([REC_ID]) REFERENCES [dbo].[OPS_0000] ([REC_ID]) ON DELETE CASCADE
GO
