CREATE TABLE [dbo].[LOAN_GEN_AGREE_NOTES]
(
[CREDIT_LINE_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DATE_TIME] [datetime] NOT NULL CONSTRAINT [DF_LOAN_GEN_AGREE_NOTES_DATE_TIME] DEFAULT (getdate()),
[OWNER] [int] NOT NULL,
[OP_TYPE] [smallint] NULL,
[NOTE] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_NOTES] ADD CONSTRAINT [PK_LOAN_GEN_AGREE_NOTES] PRIMARY KEY CLUSTERED  ([CREDIT_LINE_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_NOTES] ADD CONSTRAINT [FK_LOAN_GEN_AGREE_NOTES_LOAN_GEN_AGREE_OP_TYPES] FOREIGN KEY ([OP_TYPE]) REFERENCES [dbo].[LOAN_GEN_AGREE_OP_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_NOTES] ADD CONSTRAINT [FK_LOAN_GEN_AGREE_NOTES_USERS] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
