CREATE TABLE [dbo].[OPS_2011]
(
[REC_ID] [int] NOT NULL,
[UID] [int] NOT NULL,
[DOC_DATE] [smalldatetime] NOT NULL,
[DOC_DATE_IN_DOC] [smalldatetime] NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [money] NOT NULL,
[AMOUNT_EQU] [money] NOT NULL,
[DOC_NUM] [int] NULL,
[OP_CODE] [dbo].[TOPCODE] NULL,
[DEBIT_ID] [int] NOT NULL,
[CREDIT_ID] [int] NOT NULL,
[REC_STATE] [tinyint] NOT NULL,
[BNK_CLI_ID] [int] NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[PARENT_REC_ID] [int] NULL,
[OWNER] [int] NOT NULL,
[DOC_TYPE] [smallint] NOT NULL,
[ACCOUNT_EXTRA] [dbo].[TACCOUNT] NULL,
[PROD_ID] [int] NULL,
[FOREIGN_ID] [int] NULL,
[CHANNEL_ID] [int] NULL,
[DEPT_NO] [int] NULL,
[IS_SUSPICIOUS] [bit] NOT NULL,
[CASHIER] [int] NULL,
[CHK_SERIE] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[CASH_AMOUNT] [money] NULL,
[TREASURY_CODE] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[TAX_CODE_OR_PID] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[RELATION_ID] [int] NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF_OPS_2011_FLAGS] DEFAULT ((0)),
[BRANCH_ID] [int] NULL
) ON [ARCHIVE]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[ON_OPS_2011_DELETE]ON [dbo].[OPS_2011] AFTER DELETE ASSET NOCOUNT ONDECLARE @tbl TABLE (ACC_ID int NOT NULL PRIMARY KEY CLUSTERED, DBO money NULL, CRO money NULL)INSERT INTO @tbl (ACC_ID, DBO, CRO)SELECT H.ACC_ID, SUM(H.D), SUM(H.C)FROM (  SELECT DEBIT_ID AS ACC_ID, AMOUNT AS D, $0.0000 AS C FROM deleted  UNION ALL  SELECT CREDIT_ID, $0.0000, AMOUNT FROM deleted) HGROUP BY H.ACC_IDUPDATE dbo.ACCOUNTS_DETAILSSET UID2 = UID2 + 1, SALDO = ISNULL(A.SALDO, $0.00) - ISNULL(H.DBO, $.00) + ISNULL(H.CRO, $0.00)FROM dbo.ACCOUNTS_DETAILS A  INNER JOIN @tbl H ON A.ACC_ID = H.ACC_ID
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[ON_OPS_2011_INSERT]ON [dbo].[OPS_2011] AFTER INSERT ASSET NOCOUNT ONINSERT INTO dbo.OPS_HELPER_2011 (ACC_ID, DT, REC_ID)SELECT DEBIT_ID, DOC_DATE, REC_ID FROM insertedUNION ALLSELECT CREDIT_ID, DOC_DATE, REC_ID FROM insertedDECLARE @tbl TABLE (ACC_ID int NOT NULL PRIMARY KEY CLUSTERED, DBO money NULL, CRO money NULL)DECLARE @dt smalldatetimeSELECT TOP 1 @dt = DOC_DATE FROM insertedINSERT INTO @tbl (ACC_ID, DBO, CRO)SELECT H.ACC_ID, SUM(H.D), SUM(H.C)FROM (  SELECT DEBIT_ID AS ACC_ID, AMOUNT AS D, $0.0000 AS C FROM inserted  UNION ALL  SELECT CREDIT_ID, $0.0000, AMOUNT FROM inserted) HGROUP BY H.ACC_IDINSERT INTO dbo.SALDOS_2011(ACC_ID,DT,DBO,CRO,SALDO)SELECT H.ACC_ID, @dt, ISNULL(H.DBO, $0.00), ISNULL(H.CRO, $0.00), ISNULL(A.SALDO, $0.00) + ISNULL(H.DBO, $0.00) - ISNULL(H.CRO, $0.00)FROM @tbl H  INNER JOIN dbo.ACCOUNTS_DETAILS A ON A.ACC_ID = H.ACC_IDUPDATE dbo.ACCOUNTS_DETAILSSET UID2 = UID2 + 1, SALDO = ISNULL(A.SALDO, $0.00) + ISNULL(H.DBO, $.00) - ISNULL(H.CRO, $0.00), LAST_OP_DATE = @dtFROM dbo.ACCOUNTS_DETAILS A  INNER JOIN @tbl H ON A.ACC_ID = H.ACC_ID
GO
ALTER TABLE [dbo].[OPS_2011] ADD CONSTRAINT [CK_OPS_2011] CHECK (([DOC_DATE]>='20110101' AND [DOC_DATE]<'20120101'))
GO
ALTER TABLE [dbo].[OPS_2011] ADD CONSTRAINT [PK_OPS_2011] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_2011_ACC_EXTRA] ON [dbo].[OPS_2011] ([ACCOUNT_EXTRA]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_2011_DT] ON [dbo].[OPS_2011] ([DOC_DATE]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_2011_DOC_TYPE] ON [dbo].[OPS_2011] ([DOC_TYPE]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_2011_ISO] ON [dbo].[OPS_2011] ([ISO]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_2011_OWNER] ON [dbo].[OPS_2011] ([OWNER]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_OPS_2011_PARENT_REC_ID] ON [dbo].[OPS_2011] ([PARENT_REC_ID]) ON [ARCHIVE]
GO
