CREATE TABLE [dbo].[CLIENT_TYPES]
(
[CLIENT_TYPE] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_TYPES] ADD CONSTRAINT [CK_CLIENT_TYPES] CHECK (([CLIENT_TYPE]>=(1) AND [CLIENT_TYPE]<=(16)))
GO
ALTER TABLE [dbo].[CLIENT_TYPES] ADD CONSTRAINT [PK_CLIENT_TYPES] PRIMARY KEY CLUSTERED  ([CLIENT_TYPE]) ON [PRIMARY]
GO
