CREATE TABLE [dbo].[CLIENTS_CLASSIF]
(
[CLIENT_ID] [int] NOT NULL,
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTS_CLASSIF] ADD CONSTRAINT [PK_CLIENTS_CLASSIF] PRIMARY KEY CLUSTERED  ([CLIENT_ID], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CLIENTS_CLASSIF] ON [dbo].[CLIENTS_CLASSIF] ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTS_CLASSIF] ADD CONSTRAINT [FK_CLIENTS_CLASSIF_CLIENT_ID] FOREIGN KEY ([CLIENT_ID]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
