CREATE TABLE [dbo].[USERS]
(
[USER_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_NAME] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[USER_FULL_NAME] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[GROUP_ID] [int] NOT NULL,
[PSWHASH] [char] (32) COLLATE Latin1_General_BIN NOT NULL,
[LOCK_FLAG] [bit] NOT NULL CONSTRAINT [DF_USERS_LOCK_FLAG] DEFAULT ((0)),
[DEPT_NO] [int] NULL,
[COMMENT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[USER_PSW_NEVER_EXP] [bit] NOT NULL CONSTRAINT [DF_USERS_USER_PSW_NEVER_EXP] DEFAULT ((1)),
[USER_PSW_CHANGE] [bit] NOT NULL CONSTRAINT [DF_USERS_USER_PSW_CHANGE] DEFAULT ((0)),
[USER_PSW_CANT_CHANGE] [bit] NOT NULL CONSTRAINT [DF_USERS_USER_PSW_CANT_CHANGE] DEFAULT ((0)),
[USER_PSW_EXP_DATE] [smalldatetime] NULL,
[USER_DEL_FLAG] [bit] NOT NULL CONSTRAINT [DF_USERS_USER_DEL_FLAG] DEFAULT ((0)),
[USER_LAST_LOGIN] [smalldatetime] NOT NULL CONSTRAINT [DF_USERS_USER_LAST_LOGIN] DEFAULT (getdate()),
[USER_AUTO_LOCK_DATE] [smalldatetime] NULL,
[CLIENT_NO] [int] NULL,
[IS_CLIENT_MANAGER] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_CLIENT_MANAGER] DEFAULT ((0)),
[IS_OPERATOR_CASHIER] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_OPERATOR_CASHIER] DEFAULT ((0)),
[IS_ACC_MANAGER] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_ACC_MANAGER] DEFAULT ((0)),
[IS_CALL_CENTER_OPERATOR] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_CALL_CENTER_OPERATOR] DEFAULT ((0)),
[IS_LOAN_OFFICER] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_LOAN_OFFICER] DEFAULT ((0)),
[IS_DEPO_MANAGER] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_DEPO_OFFICER] DEFAULT ((0)),
[IS_CASHIER] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_CASHIER] DEFAULT ((0)),
[KAS_ACC] [dbo].[TACCOUNT] NULL,
[KAS_ACC_V] [dbo].[TACCOUNT] NULL,
[SAVED_GROUP_ID] [int] NULL,
[NIGHT_KAS_ACC] [dbo].[TACCOUNT] NULL,
[NIGHT_KAS_ACC_V] [dbo].[TACCOUNT] NULL,
[TRAV_CHEQUE_ACC2] [dbo].[TACCOUNT] NULL,
[NIGHT_TRAV_CHEQUE_ACC2] [dbo].[TACCOUNT] NULL,
[LAST_INVALID_PASSWORD_ATTEMPT] [smalldatetime] NULL,
[INVALID_PASSWORD_ATTEMPTS] [int] NULL,
[IS_TEMPORARY_LOCKED] [bit] NOT NULL CONSTRAINT [DF_USERS_IS_TEMPORARY_LOCKED] DEFAULT ((0)),
[TEMP_LOCK_EXPIRE_DATE] [smalldatetime] NULL,
[IS_AUTO_UNLOCKED] [bit] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[USERS_TRIGGER] ON [dbo].[USERS]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_USERS'
GO
ALTER TABLE [dbo].[USERS] ADD CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED  ([USER_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_USERS] ON [dbo].[USERS] ([USER_NAME], [DEPT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERS] WITH NOCHECK ADD CONSTRAINT [FK_USERS] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[GROUPS] ([GROUP_ID])
GO
ALTER TABLE [dbo].[USERS] ADD CONSTRAINT [FK_USERS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
ALTER TABLE [dbo].[USERS] ADD CONSTRAINT [FK_USERS_DEPTS] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
