CREATE TABLE [dbo].[ACCOUNTS_CRED_PERC]
(
[ACC_ID] [int] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NULL,
[MOVE_COUNT] [smallint] NULL,
[MOVE_COUNT_TYPE] [tinyint] NULL,
[CALC_TYPE] [tinyint] NOT NULL,
[FORMULA] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[CLIENT_ACCOUNT] [int] NULL,
[PERC_CLIENT_ACCOUNT] [int] NULL,
[PERC_BANK_ACCOUNT] [int] NOT NULL,
[DAYS_IN_YEAR] [smallint] NOT NULL,
[CALC_AMOUNT] [money] NULL,
[TOTAL_CALC_AMOUNT] [money] NULL,
[TOTAL_PAYED_AMOUNT] [money] NULL,
[LAST_CALC_DATE] [smalldatetime] NULL,
[LAST_MOVE_DATE] [smalldatetime] NULL,
[PERC_FLAGS] [int] NOT NULL CONSTRAINT [DF_ACCOUNTS_CRED_PERC_PERC_FLAGS] DEFAULT ((0)),
[PERC_TYPE] [tinyint] NOT NULL,
[TAX_RATE] [money] NULL,
[START_DATE_TYPE] [tinyint] NULL,
[START_DATE_DAYS] [int] NULL,
[DATE_TYPE] [tinyint] NULL CONSTRAINT [DF_ACCOUNTS_CRED_PERC_DATE_TYPE] DEFAULT ((0)),
[DEPO_ID] [int] NULL,
[RECALCULATE_TYPE] [tinyint] NULL,
[DEPO_REALIZE_ACC_ID] [int] NULL,
[INTEREST_REALIZE_ACC_ID] [int] NULL,
[DEPO_REALIZE_AMOUNT] [money] NULL,
[INTEREST_REALIZE_AMOUNT] [money] NULL,
[ADVANCE_ACC_ID] [money] NULL,
[ADVANCE_AMOUNT] [money] NULL,
[MIN_PROCESSING_DATE] [smalldatetime] NULL,
[MIN_PROCESSING_TOTAL_CALC_AMOUNT] [money] NULL,
[TOTAL_TAX_PAYED_AMOUNT] [money] NULL,
[TOTAL_TAX_PAYED_AMOUNT_EQU] [money] NULL,
[FUNCTION_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_CRED_PERC] ADD CONSTRAINT [CK_ACCOUNTS_CRED_PERC_CALC_TYPE] CHECK (([CALC_TYPE]>=(0) AND [CALC_TYPE]<=(99)))
GO
ALTER TABLE [dbo].[ACCOUNTS_CRED_PERC] ADD CONSTRAINT [CK_ACCOUNTS_CRED_PERC_PERC_TYPE] CHECK (([PERC_TYPE]=(4) OR [PERC_TYPE]=(3) OR [PERC_TYPE]=(2) OR [PERC_TYPE]=(1)))
GO
ALTER TABLE [dbo].[ACCOUNTS_CRED_PERC] ADD CONSTRAINT [PK_ACCOUNTS_CRED_PERC] PRIMARY KEY CLUSTERED  ([ACC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_CRED_PERC] ADD CONSTRAINT [FK_ACCOUNTS_CRED_PERC_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
