CREATE TABLE [dbo].[CROSS_RATES]
(
[ISO1] [dbo].[TISO] NOT NULL,
[ISO2] [dbo].[TISO] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT_BUY] [dbo].[TAMOUNT] NOT NULL,
[AMOUNT_SELL] [dbo].[TAMOUNT] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[CROSS_RATES_TRIGGER] ON [dbo].[CROSS_RATES] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_CROSS_RATES'
 

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[CROSS_RATES_TRIGGER_ARC] ON [dbo].[CROSS_RATES] 
FOR UPDATE
AS

SET NOCOUNT ON

DECLARE @dt datetime
SET @dt = GETDATE()

INSERT INTO dbo.CROSS_RATES_ARC (ISO1,ISO2,ITEMS,AMOUNT_BUY,AMOUNT_SELL,DT_TM)
SELECT ISO1,ISO2,ITEMS,AMOUNT_BUY,AMOUNT_SELL,@dt
FROM DELETED

GO
ALTER TABLE [dbo].[CROSS_RATES] ADD CONSTRAINT [PK_CROSS_RATES] PRIMARY KEY CLUSTERED  ([ISO1], [ISO2]) ON [PRIMARY]
GO
