CREATE TABLE [dbo].[TASK_RIGHTS]
(
[TASK_ID] [tinyint] NOT NULL,
[TASK_RIGHT_ID] [tinyint] NOT NULL,
[DESCRIP] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_RIGHTS] ADD CONSTRAINT [PK_TASK_RIGHTS] PRIMARY KEY CLUSTERED  ([TASK_ID], [TASK_RIGHT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_RIGHTS] WITH NOCHECK ADD CONSTRAINT [FK_TASK_RIGHTS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[TASKS] ([TASK_ID])
GO
