CREATE TABLE [dbo].[ACC_SUBTYPES]
(
[ACC_TYPE] [tinyint] NOT NULL,
[ACC_SUBTYPE] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SUBTYPES] ADD CONSTRAINT [PK_ACC_SUBTYPES] PRIMARY KEY CLUSTERED  ([ACC_TYPE], [ACC_SUBTYPE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SUBTYPE] ON [dbo].[ACC_SUBTYPES] ([ACC_SUBTYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SUBTYPES] ADD CONSTRAINT [FK_ACC_SUBTYPES_ACC_TYPES] FOREIGN KEY ([ACC_TYPE]) REFERENCES [dbo].[ACC_TYPES] ([ACC_TYPE]) ON DELETE CASCADE ON UPDATE CASCADE
GO
