CREATE TABLE [dbo].[BANKS]
(
[CODE9] [dbo].[TGEOBANKCODE] NOT NULL,
[CODE3] [dbo].[TUCHCODE] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[REC_STATE] [tinyint] NOT NULL CONSTRAINT [DF_BANKS_REC_STATE] DEFAULT ((0)),
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[HEAD_CODE9] [dbo].[TGEOBANKCODE] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[BANKS_TRIGGER] ON [dbo].[BANKS] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_BANKS'

GO
ALTER TABLE [dbo].[BANKS] WITH NOCHECK ADD CONSTRAINT [CK_BANKS_1] CHECK (([CODE9]>=(220000000) AND [CODE9]<=(220999999)))
GO
ALTER TABLE [dbo].[BANKS] ADD CONSTRAINT [PK_BANKS] PRIMARY KEY CLUSTERED  ([CODE9]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BANKS] ON [dbo].[BANKS] ([CODE3]) ON [PRIMARY]
GO
