CREATE TABLE [dbo].[DEPO_DATA_ANNULMENT_DETAILS]
(
[OP_ID] [int] NOT NULL,
[DAYS] [smallint] NOT NULL,
[PERC] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_DATA_ANNULMENT_DETAILS] ADD CONSTRAINT [PK_DEPO_DATA_ANNULMENT_DETAILS] PRIMARY KEY CLUSTERED  ([OP_ID], [DAYS], [PERC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_DATA_ANNULMENT_DETAILS] ADD CONSTRAINT [FK_DEPO_DATA_ANNULMENT_DETAILS_DX_DEPOSIT_DATA_ANNULMENT_DETAILS] FOREIGN KEY ([OP_ID]) REFERENCES [dbo].[DEPO_DATA] ([OP_ID]) ON DELETE CASCADE
GO
