CREATE TABLE [dbo].[TCD_OPS]
(
[OP_ID] [int] NOT NULL IDENTITY(1, 1),
[TCD_SERIAL_ID] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[COMMAND_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[OP_DATE] [smalldatetime] NOT NULL,
[REPLY_MSG_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCD_OPS] ADD CONSTRAINT [PK_TCD_OPS] PRIMARY KEY CLUSTERED  ([OP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCD_OPS] ADD CONSTRAINT [FK_TCD_OPS_TCD_COMMAND_TYPES] FOREIGN KEY ([COMMAND_ID]) REFERENCES [dbo].[TCD_COMMAND_TYPES] ([COMMAND_ID])
GO
ALTER TABLE [dbo].[TCD_OPS] ADD CONSTRAINT [FK_TCD_OPS_TCD_REPLY_MSG] FOREIGN KEY ([REPLY_MSG_ID]) REFERENCES [dbo].[TCD_REPLY_MSG] ([MSG_ID])
GO
