CREATE TABLE [dbo].[DOC_DETAILS_ARC_PLAT]
(
[DOC_REC_ID] [int] NOT NULL,
[SENDER_BANK_CODE] [dbo].[TGEOBANKCODE] NOT NULL,
[SENDER_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[SENDER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_CODE] [dbo].[TGEOBANKCODE] NOT NULL,
[RECEIVER_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[RECEIVER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[SENDER_BANK_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[SENDER_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[POR] [smallint] NULL,
[REC_DATE] [smalldatetime] NULL,
[SAXAZKOD] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO] [varchar] (250) COLLATE Latin1_General_BIN NULL,
[REF_NUM] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[TAX_PAYER_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[TAX_PAYER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[DOC_DETAILS_ARC_PLAT] ADD CONSTRAINT [PK_DOC_DETAILS_ARC_PLAT] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [ARCHIVE]
GO
