CREATE TABLE [dbo].[USER_LOG]
(
[EVENT_ID] [int] NOT NULL IDENTITY(1, 1),
[SEVERITY] [tinyint] NOT NULL,
[TIMESTAMP] [datetime] NOT NULL,
[REMOTE_ADDRESS] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[APP_URI] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[USER_NAME] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIPTION] [nvarchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_LOG] ADD CONSTRAINT [PK_USER_LOG] PRIMARY KEY CLUSTERED  ([EVENT_ID]) ON [PRIMARY]
GO
