CREATE TABLE [dbo].[TCD_COLLECTORS]
(
[COLLECTOR_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCD_COLLECTORS] ADD CONSTRAINT [PK_TCD_COLLECTORS] PRIMARY KEY CLUSTERED  ([COLLECTOR_ID]) ON [PRIMARY]
GO
