CREATE TABLE [dbo].[FAST_PAYMENT_SYSTEM_CURRENCIES]
(
[FP_SYS_ID] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAST_PAYMENT_SYSTEM_CURRENCIES] ADD CONSTRAINT [PK_FAST_PAYMENT_SYSTEM_CURRENCIES] PRIMARY KEY CLUSTERED  ([FP_SYS_ID], [ISO]) ON [PRIMARY]
GO
