CREATE TABLE [dbo].[LOAN_OP_REPORTS]
(
[OP_TYPE] [smallint] NOT NULL,
[TAG] [smallint] NOT NULL,
[DESCRIP] [char] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OP_REPORTS] ADD CONSTRAINT [PK_LOAN_OP_REPORTS] PRIMARY KEY CLUSTERED  ([OP_TYPE], [TAG], [DESCRIP]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OP_REPORTS] ADD CONSTRAINT [FK_LOAN_OP_REPORTS_LOAN_OP_TYPES] FOREIGN KEY ([OP_TYPE]) REFERENCES [dbo].[LOAN_OP_TYPES] ([TYPE_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_OP_REPORTS] ADD CONSTRAINT [FK_LOAN_OP_REPORTS_REPORTS] FOREIGN KEY ([TAG], [DESCRIP]) REFERENCES [dbo].[REPORTS] ([TAG], [DESCRIP])
GO
