CREATE TABLE [dbo].[SWIFT_CHANGES]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_SWIFT_CHANGES_TIME_OF_CH] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_CHANGES] ADD CONSTRAINT [PK_SWIFT_CHANGES] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_CHANGES] ADD CONSTRAINT [FK_SWIFT_CHANGES_1] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [dbo].[SWIFT_DOCS] ([OP_NUM]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SWIFT_CHANGES] ADD CONSTRAINT [FK_SWIFT_CHANGES_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
