CREATE TABLE [dbo].[LOAN_INSTALLMENTS]
(
[LOAN_ID] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL,
[CLIENT_OBJECT] [int] NOT NULL,
[INVOCE] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[START_PAYMENT] [money] NOT NULL,
[EVENT_INSTALLMENT] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENTS] ADD CONSTRAINT [PK_LOAN_INSTALLMENTS] PRIMARY KEY CLUSTERED  ([LOAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_INSTALLMENTS] ON [dbo].[LOAN_INSTALLMENTS] ([CLIENT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENTS] ADD CONSTRAINT [FK_LOAN_INSTALLMENTS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENTS] ADD CONSTRAINT [FK_LOAN_INSTALLMENTS_LOAN_INSTALLMENT_CLIENT_OBJECTS] FOREIGN KEY ([CLIENT_OBJECT]) REFERENCES [dbo].[LOAN_INSTALLMENT_CLIENT_OBJECTS] ([REC_ID])
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENTS] ADD CONSTRAINT [FK_LOAN_INSTALLMENTS_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
