CREATE TABLE [dbo].[BONUS_PRODUCTS]
(
[REC_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BONUS_PRODUCTS] ADD CONSTRAINT [PK_BONUS_PRODUCTS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
