CREATE TABLE [dbo].[OTHER_CLIENT_CHANGES]
(
[PERSONAL_ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_OTHER_CLIENT_CHANGES_TIME_OF_CH] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OTHER_CLIENT_CHANGES] ADD CONSTRAINT [PK_OTHER_CLIENT_CHANGES] PRIMARY KEY CLUSTERED  ([PERSONAL_ID], [REC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_OTHER_CLIENT_CHANGES] ON [dbo].[OTHER_CLIENT_CHANGES] ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OTHER_CLIENT_CHANGES] ADD CONSTRAINT [FK_OTHER_CLIENT_CHANGES_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
