CREATE TABLE [dbo].[JOBS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[SP_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JOBS] ADD CONSTRAINT [PK_JOBS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JOBS] ADD CONSTRAINT [IX_JOBS] UNIQUE NONCLUSTERED  ([DESCRIP]) ON [PRIMARY]
GO
