CREATE TABLE [dbo].[LOAN_PRODUCT_DEPTS]
(
[PRODUCT_ID] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_DEPTS] ADD CONSTRAINT [PK_LOAN_PRODUCT_DEPTS] PRIMARY KEY CLUSTERED  ([PRODUCT_ID], [DEPT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_DEPTS] ADD CONSTRAINT [FK_LOAN_PRODUCT_DEPTS_DEPTS] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_DEPTS] ADD CONSTRAINT [FK_LOAN_PRODUCT_DEPTS_LOAN_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([PRODUCT_ID]) ON DELETE CASCADE
GO
