CREATE TABLE [dbo].[LOAN_GROUPS]
(
[GROUP_ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (15) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF_LOAN_GROUPS_IS_ACTIVE] DEFAULT ((1)),
[LOAN_LIMIT_AMOUNT] [money] NULL,
[LOAN_LIMIT_ISO] [dbo].[TISO] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GROUPS] ADD CONSTRAINT [PK_LOAN_GROUPS] PRIMARY KEY CLUSTERED  ([GROUP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GROUPS] ADD CONSTRAINT [FK_LOAN_GROUPS_VAL_CODES] FOREIGN KEY ([LOAN_LIMIT_ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
