CREATE TABLE [dbo].[BC_CLIENTS]
(
[BC_CLIENT_ID] [int] NOT NULL IDENTITY(1, 1),
[CLIENT_TYPE] [tinyint] NOT NULL,
[BRANCH_ID] [int] NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF_BC_CLIENTS_FLAGS] DEFAULT ((0)),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[BNK_CLI_OPER_ID] [int] NOT NULL,
[MANAGER_PC_NAMES] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[BC_BID] [uniqueidentifier] NULL CONSTRAINT [DF_BC_CLIENTS_BC_BID] DEFAULT (newid()),
[COMMENT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[REG_DATE] [smalldatetime] NULL,
[FINISH_DATE] [smalldatetime] NULL,
[MAIN_CLIENT_ID] [int] NULL,
[REGISTERED_IN_DEPT_NO] [int] NULL,
[ADMIN_COMMENT] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[START_DATE] [smalldatetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[ON_BC_CLIENTS_CHANGE] ON [dbo].[BC_CLIENTS]
AFTER INSERT,DELETE,UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@bc_client_id int, 
		@client_no int,
		@flags int
	
	-- Delete
	
	SELECT @bc_client_id = null, @client_no = null
		
	SELECT @bc_client_id = BC_CLIENT_ID, @client_no = MAIN_CLIENT_ID
	FROM deleted
	
	IF (@bc_client_id IS NOT NULL) AND (@client_no IS NOT NULL) AND 
			NOT EXISTS (SELECT * FROM dbo.BC_CLIENTS WHERE MAIN_CLIENT_ID = @client_no AND FLAGS & 1 <> 0)
		DELETE FROM dbo.CLIENT_BANKING_PRODUCTS
		WHERE CLIENT_NO = @client_no AND BANKING_PRODUCT_ID = 2 -- BC
	
	
	-- Insert
	
	SELECT @bc_client_id = null, @client_no = null
		
	SELECT @bc_client_id = BC_CLIENT_ID, @client_no = MAIN_CLIENT_ID, @flags = FLAGS & 0x01
	FROM inserted
	
	IF (@bc_client_id IS NOT NULL) AND (@client_no IS NOT NULL) AND (@flags <> 0) AND 
			NOT EXISTS (SELECT * FROM dbo.CLIENT_BANKING_PRODUCTS WHERE CLIENT_NO = @client_no AND BANKING_PRODUCT_ID = 2)
		INSERT INTO dbo.CLIENT_BANKING_PRODUCTS (CLIENT_NO, BANKING_PRODUCT_ID)
		VALUES (@client_no, 2) -- BC
END
GO
ALTER TABLE [dbo].[BC_CLIENTS] ADD CONSTRAINT [CK_BC_CLIENTS_1] CHECK (([CLIENT_TYPE]=(2) OR [CLIENT_TYPE]=(1) OR [CLIENT_TYPE]=(0)))
GO
ALTER TABLE [dbo].[BC_CLIENTS] ADD CONSTRAINT [PK_BC_CLIENTS] PRIMARY KEY CLUSTERED  ([BC_CLIENT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BC_CLIENTS_MAIN_CLIENT_NO] ON [dbo].[BC_CLIENTS] ([MAIN_CLIENT_ID]) INCLUDE ([FLAGS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_CLIENTS] ADD CONSTRAINT [FK_BC_CLIENTS_DEPTS] FOREIGN KEY ([BRANCH_ID]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
