CREATE TABLE [dbo].[DEPO_INTRATE_ADVANCE_SCHEMA]
(
[SCHEMA_ID] [int] NOT NULL IDENTITY(1, 1),
[IS_ACTIVE] [bit] NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[PRODUCT_LIST] [varchar] (1000) COLLATE Latin1_General_BIN NULL,
[ACTION_NOTE] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[FORMULA] [varchar] (512) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_INTRATE_ADVANCE_SCHEMA] ADD CONSTRAINT [PK_DEPO_INTRATE_ADVANCE_SCHEMA] PRIMARY KEY CLUSTERED  ([SCHEMA_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_INTRATE_ADVANCE_SCHEMA] ADD CONSTRAINT [FK_DEPO_INTRATE_ADVANCE_SCHEMA_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
