CREATE TABLE [dbo].[DEPO_SET_RIGHT_NAMES2]
(
[RIGHT_NAME] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[CATEGORY] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_SET_RIGHT_NAMES2] ADD CONSTRAINT [PK_DEPO_SET_RIGHT_NAMES2] PRIMARY KEY CLUSTERED  ([RIGHT_NAME]) ON [PRIMARY]
GO
