CREATE TABLE [dbo].[DEPO_SET_RIGHTS2]
(
[GROUP_ID] [int] NOT NULL,
[SET_ID] [smallint] NOT NULL,
[RIGHT_NAME] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_SET_RIGHTS2] ADD CONSTRAINT [PK_DEPO_SET_RIGHTS2] PRIMARY KEY CLUSTERED  ([GROUP_ID], [SET_ID], [RIGHT_NAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_SET_RIGHTS2] ADD CONSTRAINT [FK_DEPO_SET_RIGHTS2_DEPO_SET_RIGHT_NAMES] FOREIGN KEY ([RIGHT_NAME]) REFERENCES [dbo].[DEPO_SET_RIGHT_NAMES2] ([RIGHT_NAME]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DEPO_SET_RIGHTS2] ADD CONSTRAINT [FK_DEPO_SET_RIGHTS2_GROUPS] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[GROUPS] ([GROUP_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DEPO_SET_RIGHTS2] ADD CONSTRAINT [FK_DEPO_SET_RIGHTS2_SETS] FOREIGN KEY ([SET_ID]) REFERENCES [dbo].[DEPO_SETS2] ([SET_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
