CREATE TABLE [dbo].[ACCOUNTS_BLOB]
(
[ACC_ID] [int] NOT NULL,
[COMMENTS] [text] COLLATE Latin1_General_BIN NULL,
[BLOB_DATA] [image] NULL
) ON [BLOBS] TEXTIMAGE_ON [BLOBS]
GO
ALTER TABLE [dbo].[ACCOUNTS_BLOB] ADD CONSTRAINT [PK_ACCOUNTS_BLOB] PRIMARY KEY CLUSTERED  ([ACC_ID]) ON [BLOBS]
GO
ALTER TABLE [dbo].[ACCOUNTS_BLOB] ADD CONSTRAINT [FK_AACCOUNTS_BLOB_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
