CREATE TABLE [dbo].[LOAN_GEN_AGREE_OPS]
(
[OP_ID] [int] NOT NULL IDENTITY(1, 1),
[CREDIT_LINE_ID] [int] NOT NULL,
[OP_DATE] [smalldatetime] NOT NULL,
[OP_TYPE] [smallint] NOT NULL,
[OP_STATE] [tinyint] NOT NULL CONSTRAINT [DF_GEN_AGREE_OPS_OP_STATE] DEFAULT ((0)),
[OP_TIME] [datetime] NOT NULL CONSTRAINT [DF_GEN_AGREE_OPS_OP_TIME] DEFAULT (getdate()),
[PARENT_OP_ID] [int] NULL,
[AMOUNT] [money] NULL,
[OP_DATA] [xml] NULL,
[OP_NOTE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OWNER] [int] NOT NULL,
[DOC_REC_ID] [int] NULL,
[NOTE_REC_ID] [int] NULL,
[AUTH_OWNER] [int] NULL,
[OP_EXT_XML] [xml] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_OPS] ADD CONSTRAINT [PK_GEN_AGREE_OPS] PRIMARY KEY CLUSTERED  ([OP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_OPS] ADD CONSTRAINT [FK_LOAN_GEN_AGREE_OPS_LOAN_CREDIT_LINES] FOREIGN KEY ([CREDIT_LINE_ID]) REFERENCES [dbo].[LOAN_CREDIT_LINES] ([CREDIT_LINE_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_OPS] ADD CONSTRAINT [FK_LOAN_GEN_AGREE_OPS_LOAN_GEN_AGREE_OP_TYPES] FOREIGN KEY ([OP_TYPE]) REFERENCES [dbo].[LOAN_GEN_AGREE_OP_TYPES] ([TYPE_ID])
GO
