CREATE TABLE [dbo].[BAL_OPS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[CHART_NO] [int] NOT NULL,
[DOC_DATE] [smalldatetime] NOT NULL,
[BAL_ACC_DEBIT] [dbo].[TBAL_ACC] NOT NULL,
[BAL_ACC_CREDIT] [dbo].[TBAL_ACC] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [money] NOT NULL,
[AMOUNT_EQU] [money] NULL,
[USER_ID] [int] NOT NULL,
[OP_CODE] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[ON_BAL_OPS_UPDATE] ON [dbo].[BAL_OPS]
AFTER INSERT,UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.BAL_OPS
	SET AMOUNT_EQU = dbo.get_equ(i.AMOUNT, i.ISO, i.DOC_DATE)
	FROM dbo.BAL_OPS O
		INNER JOIN inserted i ON i.REC_ID = O.REC_ID
END
GO
ALTER TABLE [dbo].[BAL_OPS] ADD CONSTRAINT [PK_BAL_OPS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
