CREATE TABLE [dbo].[PLASTIC_CARD_CHIP_CARDS]
(
[CARD_CHIP] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[REC_STATE] [bit] NOT NULL CONSTRAINT [DF_PLASTIC_CARD_CHIP_CARDS_REC_STATE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLASTIC_CARD_CHIP_CARDS] ADD CONSTRAINT [PK_PLASTIC_CARD_CHIP_CARDS] PRIMARY KEY CLUSTERED  ([CARD_CHIP]) ON [PRIMARY]
GO
