CREATE TABLE [dbo].[LOAN_CLIENT_SUBTYPES2]
(
[CLIENT_SUBTYPE2] [int] NOT NULL IDENTITY(1, 1),
[CLIENT_TYPE] [tinyint] NOT NULL,
[CLIENT_SUBTYPE] [tinyint] NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLIENT_SUBTYPES2] ADD CONSTRAINT [PK_LOAN_CLIENT_SUBTYPES2] PRIMARY KEY CLUSTERED  ([CLIENT_SUBTYPE2]) ON [PRIMARY]
GO
