CREATE TABLE [dbo].[APPLICATIONS]
(
[URI] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[NAME] [nvarchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[IS_LOCKED] [bit] NOT NULL,
[LOCK_REASON] [nvarchar] (30) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APPLICATIONS] ADD CONSTRAINT [PK__APPLICATIONS__350C3019] PRIMARY KEY CLUSTERED  ([URI]) ON [PRIMARY]
GO
