CREATE TABLE [dbo].[SO_SCHEDULES]
(
[TASK_ID] [int] NOT NULL,
[DATE] [smalldatetime] NOT NULL,
[FAIL_COUNTER] [int] NULL,
[STATE] [int] NOT NULL CONSTRAINT [DF_SO_SCHEDULES_STATE] DEFAULT ((10)),
[FAULT_MESSAGE] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[FAULT_CODE] [int] NULL,
[SUSPENDED_BY_BANK] [bit] NULL,
[DOC_REC_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULES] ADD CONSTRAINT [PK_SO_SCHEDULES] PRIMARY KEY CLUSTERED  ([TASK_ID], [DATE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULES] ADD CONSTRAINT [FK_SO_SCHEDULES_SO_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[SO_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
