CREATE TABLE [dbo].[PAYMENT_SCHEDUER_ERROR_LOG]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[PROVIDER_ID] [int] NOT NULL,
[SERVICE_ALIAS] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ID_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ID2_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ACC_ID] [int] NOT NULL,
[AMOUNT] [money] NOT NULL,
[REC_STATE] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENT_SCHEDUER_ERROR_LOG_REC_STATE] DEFAULT ((0)),
[REC_DATE] [smalldatetime] NOT NULL CONSTRAINT [DF_PAYMENT_SCHEDUER_ERROR_LOG_REC_DATE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENT_SCHEDUER_ERROR_LOG] ADD CONSTRAINT [PK_PAYMENT_SCHEDUER_ERROR_LOG] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
