CREATE TABLE [dbo].[RATE_POLITICS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (60) COLLATE Latin1_General_BIN NOT NULL,
[FORMULA] [text] COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RATE_POLITICS] ADD CONSTRAINT [PK_RATE_POLITICS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
