CREATE TABLE [dbo].[LOAN_ACCOUNT_BALANCE]
(
[LOAN_ID] [int] NOT NULL,
[ACC_0301_DATE] [smalldatetime] NULL,
[ACC_0301_BALANCE] [money] NULL,
[PRINCIPAL_BALANCE] [money] NULL,
[OVERDUE_PRINCIPAL_BALANCE] [money] NULL,
[WRITEOFF_PRINCIPAL_BALANCE] [money] NULL,
[ADMIN_FEE_DATE] [smalldatetime] NULL,
[ADMIN_FEE_BALANCE] [money] NULL,
[INTEREST_DATE] [smalldatetime] NULL,
[INTEREST_BALANCE] [money] NULL,
[OVERDUE_INTEREST_DATE] [smalldatetime] NULL,
[OVERDUE_INTEREST_BALANCE] [money] NULL,
[OVERDUE_INTEREST30_DATE] [smalldatetime] NULL,
[OVERDUE_INTEREST30_BALANCE] [money] NULL,
[PENALTY_DATE] [smalldatetime] NULL,
[PENALTY_BALANCE] [money] NULL,
[WRITEOFF_DATE] [smalldatetime] NULL,
[WRITEOFF_BALANCE] [money] NULL,
[RISK_CATEGORY_DATE] [smalldatetime] NULL,
[RISK_CATEGORY_BALANCE] [money] NULL,
[RISK_CATEGORY_1_BALANCE] [money] NULL,
[RISK_CATEGORY_2_BALANCE] [money] NULL,
[RISK_CATEGORY_3_BALANCE] [money] NULL,
[RISK_CATEGORY_4_BALANCE] [money] NULL,
[RISK_CATEGORY_5_BALANCE] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCOUNT_BALANCE] ADD CONSTRAINT [PK_LOAN_ACCOUNT_BALANCE] PRIMARY KEY CLUSTERED  ([LOAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCOUNT_BALANCE] ADD CONSTRAINT [FK_LOAN_ACCOUNT_BALANCE_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
