CREATE TABLE [dbo].[LOAN_ACCOUNTS]
(
[LOAN_ID] [int] NOT NULL,
[ACCOUNT_TYPE] [int] NOT NULL,
[ACC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCOUNTS] ADD CONSTRAINT [PK_LOAN_ACCOUNTS] PRIMARY KEY CLUSTERED  ([LOAN_ID], [ACCOUNT_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCOUNTS] ADD CONSTRAINT [FK_LOAN_ACCOUNTS_LOAN_ACCOUNT_TYPES] FOREIGN KEY ([ACCOUNT_TYPE]) REFERENCES [dbo].[LOAN_ACCOUNT_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_ACCOUNTS] ADD CONSTRAINT [FK_LOAN_ACCOUNTS_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
