CREATE TABLE [dbo].[DEPO_OPS_DESCRIP]
(
[OP_TYPE] [int] NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (150) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_OPS_DESCRIP] ADD CONSTRAINT [PK_DEPO_OPS_DESCRIP] PRIMARY KEY CLUSTERED  ([OP_TYPE]) ON [PRIMARY]
GO
