CREATE TABLE [dbo].[DEPO_ANNULMENT_METHODS]
(
[METHOD_ID] [int] NOT NULL IDENTITY(1, 1),
[METHOD_DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[START_DATE_TYPE] [tinyint] NOT NULL,
[START_DATE_DAYS] [int] NULL,
[DATE_TYPE] [tinyint] NOT NULL CONSTRAINT [DF_DP_ANNULMENT_METHODS_DATE_TYPE] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_ANNULMENT_METHODS] ADD CONSTRAINT [PK_DEPO_ANNULMENT_METHODS] PRIMARY KEY CLUSTERED  ([METHOD_ID]) ON [PRIMARY]
GO
