CREATE TABLE [dbo].[DEPO_INI]
(
[IDS] [char] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_INI] ADD CONSTRAINT [PK_DEPO_INI] PRIMARY KEY CLUSTERED  ([IDS]) ON [PRIMARY]
GO
