CREATE TABLE [dbo].[DOC_DETAILS_PERC]
(
[DOC_REC_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[ID] [int] NULL,
[ACCR_DATE] [smalldatetime] NOT NULL,
[PREV_DATE] [smalldatetime] NULL,
[AMOUNT4] [money] NOT NULL,
[PREV_MIN_PROCESSING_DATE] [smalldatetime] NULL,
[PREV_MIN_PROCESSING_TOTAL_CALC_AMOUNT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_DETAILS_PERC] ADD CONSTRAINT [PK_DOC_DETAILS_PERC] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [PRIMARY]
GO
