CREATE TABLE [dbo].[ACCOUNTS_DEB_PERC]
(
[ACC_ID] [int] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NULL,
[MOVE_COUNT] [smallint] NULL,
[MOVE_COUNT_TYPE] [tinyint] NOT NULL,
[CALC_TYPE] [tinyint] NOT NULL,
[FORMULA] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[CLIENT_ACCOUNT] [int] NULL,
[PERC_CLIENT_ACCOUNT] [int] NULL,
[PERC_BANK_ACCOUNT] [int] NOT NULL,
[DAYS_IN_YEAR] [smallint] NOT NULL,
[CALC_AMOUNT] [money] NULL,
[TOTAL_CALC_AMOUNT] [money] NULL,
[TOTAL_PAYED_AMOUNT] [money] NULL,
[LAST_CALC_DATE] [smalldatetime] NULL,
[LAST_MOVE_DATE] [smalldatetime] NULL,
[PERC_FLAGS] [int] NOT NULL CONSTRAINT [DF_ACCOUNTS_DEB_PERC_PERC_FLAGS] DEFAULT ((0)),
[PERC_TYPE] [tinyint] NOT NULL,
[FUNCTION_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_DEB_PERC] ADD CONSTRAINT [CK_ACCOUNTS_DEB_PERC_CALC_TYPE] CHECK (([CALC_TYPE]>=(0) AND [CALC_TYPE]<=(99)))
GO
ALTER TABLE [dbo].[ACCOUNTS_DEB_PERC] ADD CONSTRAINT [CK_ACCOUNTS_DEB_PERC_PERC_TYPE] CHECK (([PERC_TYPE]=(2) OR [PERC_TYPE]=(1)))
GO
ALTER TABLE [dbo].[ACCOUNTS_DEB_PERC] ADD CONSTRAINT [PK_ACCOUNTS_DEB_PERC] PRIMARY KEY CLUSTERED  ([ACC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_DEB_PERC] ADD CONSTRAINT [FK_ACCOUNTS_DEB_PERC_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
