CREATE TABLE [dbo].[LOAN_PRINT_PARAMS]
(
[DEPT_NO] [int] NOT NULL,
[BRANCH_ID] [int] NOT NULL,
[CITY] [dbo].[TDESCRIP] NOT NULL,
[CITY_LAT] [dbo].[TDESCRIP] NOT NULL,
[BANK_DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[BANK_DESCRIP_LAT] [dbo].[TDESCRIP] NOT NULL,
[ADDRESS] [dbo].[TDESCRIP] NOT NULL,
[ADDRESS_LAT] [dbo].[TDESCRIP] NOT NULL,
[PHONES] [dbo].[TDESCRIP] NULL,
[FAXES] [dbo].[TDESCRIP] NULL,
[EMAIL] [dbo].[TDESCRIP] NULL,
[WEB_PAGE] [dbo].[TDESCRIP] NULL,
[SIGNATORY_POSITION] [dbo].[TDESCRIP] NOT NULL,
[SIGNATORY_POSITION_LAT] [dbo].[TDESCRIP] NOT NULL,
[SIGNATURE] [dbo].[TDESCRIP] NOT NULL,
[SIGNATURE_LAT] [dbo].[TDESCRIP] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRINT_PARAMS] ADD CONSTRAINT [PK_LOAN_PRINT_PARAMS] PRIMARY KEY CLUSTERED  ([DEPT_NO], [BRANCH_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRINT_PARAMS] ADD CONSTRAINT [FK_LOAN_PRINT_PARAMS_DEPTS_BRANCH_ID] FOREIGN KEY ([BRANCH_ID]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[LOAN_PRINT_PARAMS] ADD CONSTRAINT [FK_LOAN_PRINT_PARAMS_DEPTS_DEPT_NO] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
