CREATE TABLE [dbo].[LOAN_CLASSIFS]
(
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLASSIFS] ADD CONSTRAINT [PK_LOAN_CLASSIFS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
