CREATE TABLE [dbo].[ACCOUNTS_ARC]
(
[REC_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[BRANCH_ID] [int] NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[DEPT_NO] [int] NULL,
[BAL_ACC_ALT] [dbo].[TBAL_ACC] NOT NULL,
[ACT_PAS] [tinyint] NOT NULL,
[IS_OFFBALANCE] [bit] NOT NULL,
[REC_STATE] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ACC_TYPE] [tinyint] NOT NULL,
[ACC_SUBTYPE] [int] NULL,
[CLIENT_NO] [int] NULL,
[DATE_OPEN] [smalldatetime] NOT NULL,
[PERIOD] [smalldatetime] NULL,
[DATE_CLOSE] [smalldatetime] NULL,
[TARIFF] [smallint] NULL,
[PRODUCT_NO] [int] NULL,
[MIN_AMOUNT] [money] NULL,
[MIN_AMOUNT_NEW] [money] NULL,
[MIN_AMOUNT_CHECK_DATE] [smalldatetime] NULL,
[BLOCKED_AMOUNT] [money] NULL,
[BLOCK_CHECK_DATE] [smalldatetime] NULL,
[PROF_LOSS_ACC] [dbo].[TACCOUNT] NULL,
[FLAGS] [int] NOT NULL,
[REMARK] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[CODE_PHRASE] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[RESPONSIBLE_USER_ID] [int] NULL,
[BAL_ACC_OLD] [dbo].[TBAL_ACC] NULL,
[IS_CONTROL] [bit] NULL,
[IS_INCASSO] [bit] NULL,
[UID] [int] NULL,
[USER_DEF_TYPE] [int] NULL,
[BAL_ACC2] [dbo].[TBAL_ACC] NULL,
[BAL_ACC3] [dbo].[TBAL_ACC] NULL,
[MIN_AMOUNT_CHECK_DATE_NEW] [smalldatetime] NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[ACCOUNTS_ARC] ADD CONSTRAINT [PK_ACCOUNTS_ARC] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [ARCHIVE]
GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_ARC_ACC_ID] ON [dbo].[ACCOUNTS_ARC] ([ACC_ID]) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[ACCOUNTS_ARC] ADD CONSTRAINT [FK_ACCOUNTS_ARC_ACC_CHANGES] FOREIGN KEY ([REC_ID]) REFERENCES [dbo].[ACC_CHANGES] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
