CREATE TABLE [dbo].[SALDOS_2010]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[DBO] [money] NOT NULL,
[CRO] [money] NOT NULL,
[SALDO] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[SALDOS_2010] ADD CONSTRAINT [CK_SALDOS_2010] CHECK (([DT]>='20100101' AND [DT]<'20110101'))
GO
ALTER TABLE [dbo].[SALDOS_2010] ADD CONSTRAINT [PK_SALDOS_2010] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT]) ON [ARCHIVE]
GO
