CREATE TABLE [dbo].[LOAN_GEN_AGREE_OP_TYPES]
(
[TYPE_ID] [smallint] NOT NULL,
[SELF_EXEC] [bit] NOT NULL CONSTRAINT [DF_LOAN_GEN_AGREE_OP_TYPES_SELF_EXEC] DEFAULT ((0)),
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[CONST_FUNCTION] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[DOC_REC_STATE] [int] NOT NULL CONSTRAINT [DF_LOAN_GEN_AGREE_OP_TYPES_DOC_REC_STATE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_OP_TYPES] ADD CONSTRAINT [PK_LOAN_GEN_AGREE_OP_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
