CREATE TABLE [dbo].[SALDOS_2009]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[DBO] [money] NOT NULL,
[CRO] [money] NOT NULL,
[SALDO] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[SALDOS_2009] ADD CONSTRAINT [CK_SALDOS_2009] CHECK (([DT]>='20090101' AND [DT]<'20100101'))
GO
ALTER TABLE [dbo].[SALDOS_2009] ADD CONSTRAINT [PK_SALDOS_2009] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT]) ON [ARCHIVE]
GO
