CREATE TABLE [dbo].[LOAN_PRODUCT_ACCOUNT_TEMPLATES]
(
[PRODUCT_ID] [int] NOT NULL,
[ACC_TYPE_ID] [int] NOT NULL,
[PARENT_ACC_TYPE_ID] [int] NULL,
[TEMPLATE] [varchar] (150) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCOUNT_TEMPLATES] ADD CONSTRAINT [CK_LOAN_PRODUCT_ACCOUNT_TEMPLATES] CHECK (([TEMPLATE] IS NULL AND [PARENT_ACC_TYPE_ID] IS NOT NULL OR [TEMPLATE] IS NOT NULL AND [PARENT_ACC_TYPE_ID] IS NULL OR [TEMPLATE] IS NULL AND [PARENT_ACC_TYPE_ID] IS NULL AND ([ACC_TYPE_ID]=(8000) OR [ACC_TYPE_ID]=(8010) OR [ACC_TYPE_ID]=(8020) OR [ACC_TYPE_ID]=(8030) OR [ACC_TYPE_ID]=(8040) OR [ACC_TYPE_ID]=(8050) OR [ACC_TYPE_ID]=(9000) OR [ACC_TYPE_ID]=(9010) OR [ACC_TYPE_ID]=(9020) OR [ACC_TYPE_ID]=(9030) OR [ACC_TYPE_ID]=(9040) OR [ACC_TYPE_ID]=(9050))))
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCOUNT_TEMPLATES] ADD CONSTRAINT [PK_LOAN_PRODUCT_ACCOUNT_TEMPLATES] PRIMARY KEY CLUSTERED  ([PRODUCT_ID], [ACC_TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCOUNT_TEMPLATES] ADD CONSTRAINT [FK_LOAN_PRODUCT_ACCOUNT_TEMPLATES_LOAN_ACCOUNT_TYPES] FOREIGN KEY ([ACC_TYPE_ID]) REFERENCES [dbo].[LOAN_ACCOUNT_TYPES] ([TYPE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCOUNT_TEMPLATES] ADD CONSTRAINT [FK_LOAN_PRODUCT_ACCOUNT_TEMPLATES_LOAN_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([PRODUCT_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
