CREATE TABLE [dbo].[DOC_ATTRIB_CODES]
(
[CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[IS_REQUIRED] [bit] NOT NULL CONSTRAINT [DF_DOC_ATTRIB_CODES_IS_REQUIRED] DEFAULT ((0)),
[ONLY_ONE_VALUE] [bit] NOT NULL CONSTRAINT [DF_DOC_ATTRIB_CODES_ONLY_ONE_VALUE] DEFAULT ((0)),
[USAGE_TYPE] [int] NOT NULL CONSTRAINT [DF_DOC_ATTRIB_CODES_USAGE_TYPE] DEFAULT ((((((((1)+(2))+(4))+(8))+(16))+(32))+(64))+(128)),
[TYPE] [tinyint] NOT NULL CONSTRAINT [DF_DOC_ATTRIB_CODES_TYPE] DEFAULT ((0)),
[VALUES] [varchar] (4000) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_ATTRIB_CODES] ADD CONSTRAINT [PK_DOC_ATTRIB_CODES] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
