CREATE TABLE [dbo].[CLIENT_EXTENSIONS_RATINGS_HISTORY]
(
[CLIENT_NO] [int] NOT NULL,
[DATE] [datetime] NOT NULL,
[RAITING] [varchar] (3) COLLATE Latin1_General_BIN NOT NULL,
[USER_ID] [int] NOT NULL,
[COMMENT] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_EXTENSIONS_RATINGS_HISTORY] ADD CONSTRAINT [PK_CLIENT_EXTENSIONS_RATINGS_HISTORY] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [DATE]) ON [PRIMARY]
GO
