CREATE TABLE [dbo].[OTHER_ACCOUNTS]
(
[BANK_CODE] [dbo].[TINTBANKCODE] NOT NULL,
[ACCOUNT] [dbo].[TINTACCOUNT] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[REC_STATE] [tinyint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OTHER_ACCOUNTS] ADD CONSTRAINT [PK_OTHER_ACCOUNTS] PRIMARY KEY CLUSTERED  ([BANK_CODE], [ACCOUNT]) ON [PRIMARY]
GO
