CREATE TABLE [dbo].[PASSPORT_TYPES]
(
[PASSPORT_TYPE_ID] [tinyint] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[PASSPORT_EDIT_MASK] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PERS_ID_EDIT_MASK] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PASSPORT_FLAGS] [int] NOT NULL CONSTRAINT [DF_PASSPORT_TYPES_PASSPORT_FLAGS] DEFAULT ((63)),
[CHECK_DUP_PERSONAL_ID] [bit] NOT NULL CONSTRAINT [DF_PASSPORT_TYPES_CHECK_DUP_PERSONAL_ID] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[PASSPORT_TYPES_TRIGGER] ON [dbo].[PASSPORT_TYPES]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_PASSPORT_TYPES'
GO
ALTER TABLE [dbo].[PASSPORT_TYPES] ADD CONSTRAINT [PK_PASSPORT_TYPES] PRIMARY KEY CLUSTERED  ([PASSPORT_TYPE_ID]) ON [PRIMARY]
GO
