CREATE TABLE [dbo].[LOAN_OP_PAYMENT_DETAILS]
(
[OP_ID] [int] NOT NULL,
[PAYMENT_TYPE] [smallint] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OP_PAYMENT_DETAILS] ADD CONSTRAINT [PK_LOAN_OP_PAYMENT_DETAILS] PRIMARY KEY CLUSTERED  ([OP_ID], [PAYMENT_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OP_PAYMENT_DETAILS] ADD CONSTRAINT [FK_LOAN_OP_PAYMENT_DETAILS_LOAN_OPS] FOREIGN KEY ([OP_ID]) REFERENCES [dbo].[LOAN_OPS] ([OP_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_OP_PAYMENT_DETAILS] ADD CONSTRAINT [FK_LOAN_OP_PAYMENT_DETAILS_LOAN_PAYMENT_TYPES] FOREIGN KEY ([PAYMENT_TYPE]) REFERENCES [dbo].[LOAN_PAYMENT_TYPES] ([TYPE_ID])
GO
