CREATE TABLE [dbo].[INCASSO_ARC]
(
[REC_ID] [int] NOT NULL,
[BRANCH_ID] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL,
[INCASSO_NUM] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ISSUE_DATE] [smalldatetime] NOT NULL,
[REC_DATE_TIME] [datetime] NOT NULL,
[ACTIVATION_DATE_TIME] [smalldatetime] NOT NULL,
[REC_STATE] [tinyint] NOT NULL,
[ACC_ID] [int] NOT NULL,
[ACC_ID_OFB] [int] NULL,
[INCASSO_AMOUNT] [money] NOT NULL,
[BALANCE] [money] NOT NULL,
[PAYED_AMOUNT] [money] NOT NULL,
[SUSPENDED_AMOUNT] [money] NULL,
[PAYED_COUNT] [smallint] NOT NULL,
[RECEIVER_BANK_CODE] [dbo].[TINTBANKCODE] NOT NULL,
[RECEIVER_BANK_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_ACC] [varchar] (34) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_ACC_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NOT NULL,
[SAXAZKOD] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[INCASSO_ISSUER] [tinyint] NOT NULL,
[USER_ID] [int] NOT NULL,
[PENDING] [bit] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL CONSTRAINT [DF_INCASSO_ARC_ISO] DEFAULT ('GEL')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_ARC] ADD CONSTRAINT [PK_INCASSO_ARC] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
