CREATE TABLE [dbo].[LOAN_GEN_AGREE_OP_COLLATERALS]
(
[OP_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[ROW_VERSION] [int] NULL,
[LOAN_ID] [int] NULL,
[CREDIT_LINE_ID] [int] NULL,
[CLIENT_NO] [int] NULL,
[OWNER] [int] NULL,
[ISO] [dbo].[TISO] NULL,
[COLLATERAL_TYPE] [int] NULL,
[AMOUNT] [money] NULL,
[DESCRIP] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[MARKET_AMOUNT] [money] NULL,
[COLLATERAL_DETAILS] [xml] NULL,
[IS_ENSURED] [bit] NULL,
[ENSURANCE_PAYMENT_AMOUNT] [money] NULL,
[ENSUR_PAYMENT_INTERVAL_TYPE] [int] NULL,
[ENSURANCE_COMPANY_ID] [int] NULL,
[IS_LINKED] [bit] NULL,
[MAIN] [bit] NULL,
[XML_STR] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[COLLATERAL_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_OP_COLLATERALS] ADD CONSTRAINT [PK_LOAN_GEN_AGREE_OP_COLLATERALS] PRIMARY KEY CLUSTERED  ([OP_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_GEN_AGREE_OP_COLLATERALS] ADD CONSTRAINT [FK_LOAN_GEN_AGREE_OP_COLLATERALS_LOAN_GEN_AGREE_OPS] FOREIGN KEY ([OP_ID]) REFERENCES [dbo].[LOAN_GEN_AGREE_OPS] ([OP_ID]) ON DELETE CASCADE
GO
