CREATE TABLE [dbo].[GROUP_APPLICATIONS]
(
[GROUP_ID] [int] NOT NULL,
[APP_URI] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[SESSION_LIMIT] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_APPLICATIONS] ADD CONSTRAINT [PK__GROUP_APPLICATIO__3CAD51E1] PRIMARY KEY CLUSTERED  ([GROUP_ID], [APP_URI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_APPLICATIONS] ADD CONSTRAINT [FK_GROUP_APPLICATIONS_APPLICATIONS] FOREIGN KEY ([APP_URI]) REFERENCES [dbo].[APPLICATIONS] ([URI]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GROUP_APPLICATIONS] ADD CONSTRAINT [FK_GROUP_APPLICATIONS_GROUPS] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[GROUPS] ([GROUP_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
