CREATE TABLE [dbo].[CLIENTS_FACSIMILE_ARC]
(
[CLI_CHANGE_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[FACS_TYPE] [int] NULL,
[IS_AUTHORIZED] [bit] NOT NULL,
[IS_ACTIVE] [bit] NOT NULL,
[START_DATE] [smalldatetime] NULL,
[END_DATE] [smalldatetime] NULL,
[BLOB_DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTS_FACSIMILE_ARC] ADD CONSTRAINT [PK_CLIENTS_FACSIMILE_ARC] PRIMARY KEY CLUSTERED  ([CLI_CHANGE_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTS_FACSIMILE_ARC] WITH NOCHECK ADD CONSTRAINT [FK_CLIENTS_FACSIMILE_ARC_CLI_CHANGES] FOREIGN KEY ([CLI_CHANGE_ID]) REFERENCES [dbo].[CLI_CHANGES] ([REC_ID])
GO
ALTER TABLE [dbo].[CLIENTS_FACSIMILE_ARC] ADD CONSTRAINT [FK_CLIENTS_FACSIMILE_ARC_FACSIMILE_TYPES] FOREIGN KEY ([FACS_TYPE]) REFERENCES [dbo].[FACSIMILE_TYPES] ([TYPE_ID])
GO
