CREATE TABLE [dbo].[LOAN_RISK_LEVELS]
(
[LEVEL_ID] [int] NOT NULL,
[CODE] [varchar] (15) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_RISK_LEVELS] ADD CONSTRAINT [PK_LOAN_RISK_LEVELS] PRIMARY KEY CLUSTERED  ([LEVEL_ID]) ON [PRIMARY]
GO
