CREATE TABLE [dbo].[SWIFT_DOCS]
(
[OP_NUM] [int] NOT NULL IDENTITY(1, 1),
[REC_ID] [int] NOT NULL,
[DOC_DATE] [smalldatetime] NOT NULL,
[DOC_DATE_IN_DOC] [smalldatetime] NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [dbo].[TAMOUNT] NOT NULL,
[AMOUNT_EQU] [dbo].[TAMOUNT] NULL,
[DOC_NUM] [int] NULL,
[OP_CODE] [dbo].[TOPCODE] NULL,
[DEBIT] [dbo].[TACCOUNT] NOT NULL,
[CREDIT] [dbo].[TACCOUNT] NOT NULL,
[REC_STATE] [tinyint] NOT NULL,
[BNK_CLI_ID] [int] NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[PARENT_REC_ID] [int] NULL,
[OWNER] [int] NOT NULL,
[DOC_TYPE] [smallint] NOT NULL,
[ACCOUNT_EXTRA] [dbo].[TACCOUNT] NULL,
[PROD_ID] [int] NULL,
[FOREIGN_ID] [int] NULL,
[CHANNEL_ID] [int] NULL,
[DEPT_NO] [int] NULL,
[SENDER_BANK_CODE] [dbo].[TINTBANKCODE] NOT NULL,
[SENDER_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[RECEIVER_BANK_CODE] [dbo].[TINTBANKCODE] NOT NULL,
[RECEIVER_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[SENDER_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[SENDER_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_CODE] [dbo].[TINTBANKCODE] NULL,
[INTERMED_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SWIFT_TEXT] [text] COLLATE Latin1_General_BIN NULL,
[REF_NUM] [varchar] (32) COLLATE Latin1_General_BIN NULL,
[AUT_STATUS] [tinyint] NOT NULL CONSTRAINT [DF_SWIFT_DOCS_AUT_STATUS] DEFAULT ((0)),
[DAV_STATUS] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ASAXVA_STATUS] [bit] NULL,
[RECEIVER_ACC_NAME_REAL] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ERROR_REASON] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ADDRESS_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[COR_BANK_CODE] [dbo].[TINTACCOUNT] NULL,
[COR_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[COR_COUNTRY] [char] (2) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_DOCS] ADD CONSTRAINT [PK_SWIFT_DOCS] PRIMARY KEY CLUSTERED  ([OP_NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SWIFT_DOCS_DOC_DATE] ON [dbo].[SWIFT_DOCS] ([DOC_DATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SWIFT_DOCS_REF_NUM] ON [dbo].[SWIFT_DOCS] ([REF_NUM]) ON [PRIMARY]
GO
