CREATE TABLE [dbo].[SO_SCHEDULE_CHANGES]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[TASK_ID] [int] NOT NULL,
[DATE] [smalldatetime] NOT NULL,
[USER_ID] [int] NOT NULL,
[FIELD] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[OLD_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[NEW_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[OLD_DISPLAY_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[NEW_DISPLAY_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [datetime] NULL CONSTRAINT [DF_SO_SCHEDULE_CHANGES_TIME_OF_CHANGE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULE_CHANGES] ADD CONSTRAINT [PK_SO_SCHEDULE_CHANGES_1] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULE_CHANGES] ADD CONSTRAINT [FK_SO_SCHEDULE_CHANGES_SO_SCHEDULES] FOREIGN KEY ([TASK_ID], [DATE]) REFERENCES [dbo].[SO_SCHEDULES] ([TASK_ID], [DATE]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[SO_SCHEDULE_CHANGES] ADD CONSTRAINT [FK_SO_SCHEDULE_CHANGES_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
