CREATE TABLE [dbo].[PAYMENT_PROVIDER_SERVICES]
(
[PROVIDER_ID] [int] NOT NULL,
[SERVICE_ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICE_ALIAS] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ONLINE_CAN_GET_DEBT] [bit] NOT NULL,
[ONLINE_CAN_PAY] [bit] NOT NULL,
[ONLINE_CAN_CHECK] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_ONLINE_CAN_CHECK] DEFAULT ((0)),
[CAN_CHECK_ID_IN_PROVIDER] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_CAN_CHECK_ID_IN_PROVIDER] DEFAULT ((0)),
[CAN_DELETE] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_CAN_DELETE] DEFAULT ((0)),
[FIXED_ID] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_FIXED_ID] DEFAULT ((0)),
[SERVICE_NAME] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[SERVICE_NAME_LAT] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_TEMPLATE] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_PROVIDER_SERVICES_DESCRIP_TEMPLATE] DEFAULT ('%s'),
[DESCRIP_TEMPLATE_LAT] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_PROVIDER_SERVICES_DESCRIP_TEMPLATE_LAT] DEFAULT ('%s'),
[RECV_BANK_CODE] [dbo].[TGEOBANKCODE] NOT NULL,
[RECV_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[RECV_ACC_ONLINE] [dbo].[TINTACCOUNT] NOT NULL,
[RECV_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[RECV_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[TRANSIT_ACCOUNT] [int] NULL,
[MONYBACK_TRANSIT_ACCOUNT] [int] NULL,
[TERM_ID] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[TARIFF_PERCENT] [dbo].[TPERCENT] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_TARIFF_PERCENT] DEFAULT ((0.0000)),
[TARIFF_MIN_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_TARIFF_MIN_AMOUNT] DEFAULT ((0.0000)),
[PROVIDER_MONEYBACK_PERCENT] [dbo].[TPERCENT] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_PROVIDER_MONEYBACK_PERCENT] DEFAULT ((0.0000)),
[PROVIDER_MONEYBACK_TARIFF] [money] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_PROVIDER_MONEYBACK_TARIFF] DEFAULT ((0.0000)),
[PROVIDER_MONEYBACK_ACCOUNT] [int] NULL,
[CRITICAL_AMOUNT] [money] NULL,
[MAX_AMOUNT] [money] NULL,
[CHARGE_TYPE] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_PROVIDER_SERVICES_CHARGE_TYPE] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[PAYMENT_PROVIDER_SERVICES_TRIGGER] ON [dbo].[PAYMENT_PROVIDER_SERVICES] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC dbo._UPDATE_VERSION 'VER_PMT_PROV_SERV'
EXEC dbo._UPDATE_VERSION 'VER_BC_CHARGER_CHARGES'
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[PAYMENT_PROVIDERS_TRIGGER] ON [dbo].[PAYMENT_PROVIDER_SERVICES] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC dbo._UPDATE_VERSION 'VER_PMT_PROVIDERS'
EXEC dbo._UPDATE_VERSION 'VER_BC_CHARGERS'
GO
ALTER TABLE [dbo].[PAYMENT_PROVIDER_SERVICES] ADD CONSTRAINT [PK_PAYMENT_PROVIDER_SERVICES] PRIMARY KEY CLUSTERED  ([PROVIDER_ID], [SERVICE_ALIAS]) ON [PRIMARY]
GO
