CREATE TABLE [dbo].[LOAN_INSTALLMENT_ITEMS]
(
[LOAN_ID] [int] NOT NULL,
[ITEM_ID] [int] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[ITEM_PRICE] [money] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_INSTALLMENT_ITEMS_ITEM_ID] ON [dbo].[LOAN_INSTALLMENT_ITEMS] ([ITEM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_INSTALLMENT_ITEMS_LOAN_ID] ON [dbo].[LOAN_INSTALLMENT_ITEMS] ([LOAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENT_ITEMS] ADD CONSTRAINT [FK_LOAN_INSTALLMENT_ITEMS_LOAN_COLLATERAL_ITEMS] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[LOAN_COLLATERAL_ITEMS] ([ITEM_ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENT_ITEMS] ADD CONSTRAINT [FK_LOAN_INSTALLMENT_ITEMS_LOAN_INSTALLMENTS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOAN_INSTALLMENTS] ([LOAN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
