CREATE TABLE [dbo].[DEPO_DEPOSIT_CHANGES]
(
[DEPO_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [text] COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_DEPO_DEPOSIT_CHANGES_TIME_OF_CHANGE] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_DEPOSIT_CHANGES] ADD CONSTRAINT [PK_DEPO_DEPOSIT_CHANGES] PRIMARY KEY CLUSTERED  ([DEPO_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_DEPOSIT_CHANGES] ADD CONSTRAINT [FK_DEPO_DEPOSIT_CHANGES_DEPO_DEPOSITS] FOREIGN KEY ([DEPO_ID]) REFERENCES [dbo].[DEPO_DEPOSITS] ([DEPO_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DEPO_DEPOSIT_CHANGES] ADD CONSTRAINT [FK_DEPO_DEPOSIT_CHANGES_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
