CREATE TABLE [dbo].[VAL_RATES_2014]
(
[ISO] [dbo].[TISO] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[VAL_RATES_2014] ADD CONSTRAINT [CK_VAL_RATES_2014] CHECK (([DT]>='20140101' AND [DT]<'20150101'))
GO
ALTER TABLE [dbo].[VAL_RATES_2014] ADD CONSTRAINT [PK_VAL_RATES_2014] PRIMARY KEY CLUSTERED  ([ISO], [DT]) ON [ARCHIVE]
GO
