CREATE TABLE [dbo].[FACSIMILE_TYPES]
(
[TYPE_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[NEEDS_AUTHORIZATION] [bit] NOT NULL CONSTRAINT [DF_FACSIMILE_TYPES_AUTHORIZE] DEFAULT ((0)),
[NEEDS_ACTIVATE] [bit] NOT NULL CONSTRAINT [DF_FACSIMILE_TYPES_ACTIVATE] DEFAULT ((0)),
[NEEDS_DATES] [bit] NOT NULL CONSTRAINT [DF_FACSIMILE_TYPES_NEEDS_DATES] DEFAULT ((0)),
[FOR_CLIENTS] [bit] NOT NULL CONSTRAINT [DF_FACSIMILE_TYPES_FOR_CLIENTS] DEFAULT ((1)),
[FOR_ACCOUNTS] [bit] NOT NULL CONSTRAINT [DF_FACSIMILE_TYPES_FOR_ACCOUNTS] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACSIMILE_TYPES] ADD CONSTRAINT [PK_FACSIMILE_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
