CREATE TABLE [dbo].[PAYMENT_SERVICE_CHANNELS]
(
[SERVICE_ID] [int] NOT NULL,
[CHANNEL_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENT_SERVICE_CHANNELS] ADD CONSTRAINT [PK_PAYMENT_SERVICE_CHANELS] PRIMARY KEY CLUSTERED  ([SERVICE_ID], [CHANNEL_ID]) ON [PRIMARY]
GO
