CREATE TABLE [dbo].[PLANLIST]
(
[BAL_ACC] [dbo].[TBAL_ACC] NOT NULL,
[ACT_PAS] [tinyint] NOT NULL,
[CLASS_TYPE] [tinyint] NOT NULL,
[VAL_TYPE] [tinyint] NOT NULL,
[REC_STATE] [tinyint] NULL CONSTRAINT [DF_PLANLIST_REC_STATE] DEFAULT ((0)),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ACC_TYPE] [tinyint] NOT NULL CONSTRAINT [DF_PLANLIST_ACC_TYPE] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[PLANLIST_TRIGGER] ON [dbo].[PLANLIST]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_PLANLIST'

GO
ALTER TABLE [dbo].[PLANLIST] ADD CONSTRAINT [CK_PLANLIST_4] CHECK (([ACC_TYPE]=(2) OR [ACC_TYPE]=(1) OR [ACC_TYPE]=(0)))
GO
ALTER TABLE [dbo].[PLANLIST] WITH NOCHECK ADD CONSTRAINT [CK_PLANLIST_1] CHECK (([ACT_PAS]>=(0) AND [ACT_PAS]<=(3)))
GO
ALTER TABLE [dbo].[PLANLIST] WITH NOCHECK ADD CONSTRAINT [CK_PLANLIST_2] CHECK (([CLASS_TYPE]=(64) OR [CLASS_TYPE]=(32) OR [CLASS_TYPE]=(16) OR [CLASS_TYPE]=(8) OR [CLASS_TYPE]=(4) OR [CLASS_TYPE]=(2) OR [CLASS_TYPE]=(1)))
GO
ALTER TABLE [dbo].[PLANLIST] WITH NOCHECK ADD CONSTRAINT [CK_PLANLIST_3] CHECK (([VAL_TYPE]=(4) OR [VAL_TYPE]=(2) OR [VAL_TYPE]=(1)))
GO
ALTER TABLE [dbo].[PLANLIST] ADD CONSTRAINT [PK_PLANLIST] PRIMARY KEY CLUSTERED  ([BAL_ACC]) ON [PRIMARY]
GO
