CREATE TABLE [dbo].[DAY_RETURNS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DT] [smalldatetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DAY_RETURNS] ADD CONSTRAINT [PK_DAY_RETURNS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
