CREATE TABLE [dbo].[LOAN_COLLATERALS_MERGE]
(
[COLLATERAL_ID] [int] NOT NULL,
[ROW_VERSION] [int] NOT NULL,
[LOAN_ID] [int] NULL,
[CREDIT_LINE_ID] [int] NULL,
[CLIENT_NO] [int] NOT NULL,
[OWNER] [int] NOT NULL,
[ISO] [char] (3) COLLATE Latin1_General_BIN NOT NULL,
[COLLATERAL_TYPE] [int] NOT NULL,
[AMOUNT] [money] NOT NULL,
[DESCRIP] [varchar] (400) COLLATE Latin1_General_BIN NULL,
[MARKET_AMOUNT] [money] NOT NULL,
[COLLATERAL_DETAILS] [xml] NULL,
[IS_ENSURED] [bit] NULL,
[ENSURANCE_PAYMENT_AMOUNT] [money] NULL,
[ENSUR_PAYMENT_INTERVAL_TYPE] [int] NULL,
[ENSURANCE_COMPANY_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
