CREATE TABLE [dbo].[ACCOUNTS_FACSIMILE_ARC]
(
[ACC_CHANGE_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[FACS_TYPE] [int] NOT NULL,
[IS_AUTHORIZED] [bit] NOT NULL,
[IS_ACTIVE] [bit] NOT NULL,
[START_DATE] [smalldatetime] NULL,
[END_DATE] [smalldatetime] NULL,
[BLOB_DATA] [image] NULL
) ON [ARCHIVE] TEXTIMAGE_ON [ARCHIVE]
GO
ALTER TABLE [dbo].[ACCOUNTS_FACSIMILE_ARC] ADD CONSTRAINT [PK_ACCOUNTS_FACSIMILE_ARC] PRIMARY KEY CLUSTERED  ([ACC_CHANGE_ID], [REC_ID]) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[ACCOUNTS_FACSIMILE_ARC] ADD CONSTRAINT [FK_ACCOUNTS_FACSIMILE_ARC_ACC_CHANGES] FOREIGN KEY ([ACC_CHANGE_ID]) REFERENCES [dbo].[ACC_CHANGES] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS_FACSIMILE_ARC] ADD CONSTRAINT [FK_ACCOUNTS_FACSIMILE_ARC_FACSIMILE_TYPES] FOREIGN KEY ([FACS_TYPE]) REFERENCES [dbo].[FACSIMILE_TYPES] ([TYPE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
