CREATE TABLE [dbo].[LOAN_COLLATERALS_LINK]
(
[LOAN_ID] [int] NOT NULL,
[COLLATERAL_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COLLATERALS_LINK] ADD CONSTRAINT [PK_LOAN_COLLATERALS_LINK] PRIMARY KEY CLUSTERED  ([LOAN_ID], [COLLATERAL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_COLLAT_LINK_COLLATERAL_ID] ON [dbo].[LOAN_COLLATERALS_LINK] ([COLLATERAL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COLLATERALS_LINK] WITH NOCHECK ADD CONSTRAINT [FK_LOAN_COLLATERALS_LINK_LOAN_COLLATERALS] FOREIGN KEY ([COLLATERAL_ID]) REFERENCES [dbo].[LOAN_COLLATERALS] ([COLLATERAL_ID])
GO
ALTER TABLE [dbo].[LOAN_COLLATERALS_LINK] WITH NOCHECK ADD CONSTRAINT [FK_LOAN_COLLATERALS_LINK_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
