CREATE TABLE [dbo].[CLIENT_DOCUMENT_TYPES]
(
[DOCUMENT_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[START_DATE] [smalldatetime] NULL,
[END_DATE] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_DOCUMENT_TYPES] ADD CONSTRAINT [PK_CLIENT_DOCUMENT_TYPES] PRIMARY KEY CLUSTERED  ([DOCUMENT_NAME]) ON [PRIMARY]
GO
