CREATE TABLE [dbo].[DEPO_CLASSIF_LNK]
(
[DEPO_ID] [int] NOT NULL,
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_CLASSIF_LNK] ADD CONSTRAINT [PK_DEPO_CLASSIF_LNK] PRIMARY KEY CLUSTERED  ([DEPO_ID], [ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_CLASSIF_LNK] ADD CONSTRAINT [FK_DEPO_CLASSIF_LNK_DEPO_CLASSIF] FOREIGN KEY ([ID]) REFERENCES [dbo].[DEPO_CLASSIF] ([ID])
GO
ALTER TABLE [dbo].[DEPO_CLASSIF_LNK] WITH NOCHECK ADD CONSTRAINT [FK_DEPO_CLASSIF_LNK_DEPOS] FOREIGN KEY ([DEPO_ID]) REFERENCES [dbo].[DEPOS] ([DEPO_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
