CREATE TABLE [dbo].[DEL_DOC_CHANGES]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_DEL_DOC_CHANGE_TIME_OF_CH] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEL_DOC_CHANGES] ADD CONSTRAINT [PK_DEL_DOC_CHANGES] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEL_DOC_CHANGES] WITH NOCHECK ADD CONSTRAINT [FK_DELETED_DOC_CHANGES_1] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [dbo].[DEL_DOCS] ([REC_ID])
GO
ALTER TABLE [dbo].[DEL_DOC_CHANGES] WITH NOCHECK ADD CONSTRAINT [FK_DELETED_DOC_CHANGES_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
