CREATE TABLE [dbo].[CLIENT_SEGMENTS]
(
[REC_ID] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[IS_JURIDICAL] [bit] NOT NULL CONSTRAINT [DF_CLIENT_SEGMENTS_IS_JURIDICAL] DEFAULT ((1))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[CLIENT_SEGMENTS_TRIGGER] ON [dbo].[CLIENT_SEGMENTS]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_CLIENT_SEGMENTS'
GO
ALTER TABLE [dbo].[CLIENT_SEGMENTS] ADD CONSTRAINT [PK_CLIENT_SEGMENTS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
