CREATE TABLE [dbo].[LOAN_ATTACHMENTS]
(
[LOAN_ID] [int] NOT NULL,
[FILE_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[IS_FOLDER] [bit] NOT NULL CONSTRAINT [DF_LOAN_ATTACHMENTS_IS_FOLDER] DEFAULT ((0)),
[FILE_DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [BLOBS]
GO
ALTER TABLE [dbo].[LOAN_ATTACHMENTS] ADD CONSTRAINT [PK_LOAN_ATTACHMENTS] PRIMARY KEY CLUSTERED  ([LOAN_ID], [FILE_NAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ATTACHMENTS] ADD CONSTRAINT [FK_LOAN_ATTACHMENTS_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
