CREATE TABLE [dbo].[ACC_PRODUCTS]
(
[PRODUCT_NO] [int] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[EXTRA_PARAM1] [int] NULL,
[EXTRA_PARAM2] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[ACC_PRODUCTS_TRIGGER] ON [dbo].[ACC_PRODUCTS]
FOR INSERT, UPDATE, DELETE 
AS

EXEC _UPDATE_VERSION 'VER_ACC_PRODUCTS'
GO
ALTER TABLE [dbo].[ACC_PRODUCTS] ADD CONSTRAINT [PK_ACC_PRODUCTS] PRIMARY KEY CLUSTERED  ([PRODUCT_NO]) ON [PRIMARY]
GO
