CREATE TABLE [dbo].[OPS_HELPER_2013]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[REC_ID] [int] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[OPS_HELPER_2013] ADD CONSTRAINT [CK_OPS_HELPER_2013] CHECK (([DT]>='20130101' AND [DT]<'20140101'))
GO
ALTER TABLE [dbo].[OPS_HELPER_2013] ADD CONSTRAINT [PK_OPS_HELPER_2013] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT], [REC_ID]) ON [ARCHIVE]
GO
