CREATE TABLE [dbo].[BC_DOC_DETAILS_VALPLAT]
(
[DOC_REC_ID] [int] NOT NULL,
[SENDER_BANK_CODE] [dbo].[TINTBANKCODE] NOT NULL,
[SENDER_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[RECEIVER_BANK_CODE] [dbo].[TINTBANKCODE] NOT NULL,
[RECEIVER_ACC] [dbo].[TINTACCOUNT] NOT NULL,
[SENDER_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[SENDER_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ACC_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_CODE] [dbo].[TINTBANKCODE] NULL,
[INTERMED_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SENDER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[RECEIVER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[SWIFT_TEXT] [text] COLLATE Latin1_General_BIN NULL,
[REF_NUM] [varchar] (32) COLLATE Latin1_General_BIN NULL,
[COR_BANK_CODE] [dbo].[TINTACCOUNT] NULL,
[COR_BANK_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_DOC_DETAILS_VALPLAT] ADD CONSTRAINT [PK_BC_DOC_DETAILS_VALPLAT] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [PRIMARY]
GO
