CREATE TABLE [dbo].[SAXAZCODES_1]
(
[ID] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[SAXAZCODES_1_TRIGGER] ON [dbo].[SAXAZCODES_1]
FOR INSERT, UPDATE, DELETE 
AS

EXEC dbo._UPDATE_VERSION 'VER_SAXAZCODES_1'
GO
ALTER TABLE [dbo].[SAXAZCODES_1] ADD CONSTRAINT [PK_SAXAZCODES_1] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
