CREATE TABLE [dbo].[VAL_RATES_2017]
(
[ISO] [dbo].[TISO] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[VAL_RATES_2017] ADD CONSTRAINT [CK_VAL_RATES_2017] CHECK (([DT]>='20170101' AND [DT]<'20170901'))
GO
ALTER TABLE [dbo].[VAL_RATES_2017] ADD CONSTRAINT [PK_VAL_RATES_2017] PRIMARY KEY CLUSTERED  ([ISO], [DT]) ON [ARCHIVE]
GO
