CREATE TABLE [dbo].[LOAN_DETAIL_OVERDUE]
(
[LOAN_ID] [int] NOT NULL,
[OVERDUE_DATE] [smalldatetime] NOT NULL,
[LATE_OP_ID] [int] NULL,
[OVERDUE_OP_ID] [int] NOT NULL,
[OVERDUE_PRINCIPAL] [money] NULL,
[OVERDUE_PERCENT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DETAIL_OVERDUE] ADD CONSTRAINT [PK_LOAN_DETAIL_OVERDUE] PRIMARY KEY CLUSTERED  ([LOAN_ID], [OVERDUE_DATE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_LOAN_DETAIL_OVERDUE] ON [dbo].[LOAN_DETAIL_OVERDUE] ([OVERDUE_OP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DETAIL_OVERDUE] ADD CONSTRAINT [FK_LOAN_DETAIL_OVERDUE_LOAN_OPS_LATE_OP_ID] FOREIGN KEY ([LATE_OP_ID]) REFERENCES [dbo].[LOAN_OPS] ([OP_ID])
GO
ALTER TABLE [dbo].[LOAN_DETAIL_OVERDUE] ADD CONSTRAINT [FK_LOAN_DETAIL_OVERDUE_LOAN_OPS_OVERDUE_OP_ID] FOREIGN KEY ([OVERDUE_OP_ID]) REFERENCES [dbo].[LOAN_OPS] ([OP_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_DETAIL_OVERDUE] ADD CONSTRAINT [FK_LOAN_DETAIL_OVERDUE_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID])
GO
