CREATE TABLE [dbo].[INCASSO_OPS_ID]
(
[INCASSO_OP_ID] [int] NOT NULL,
[DOC_REC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_OPS_ID] ADD CONSTRAINT [PK_INCASSO_OPS_ID] PRIMARY KEY CLUSTERED  ([INCASSO_OP_ID], [DOC_REC_ID]) ON [PRIMARY]
GO
