CREATE TABLE [dbo].[CLIENTS_USR]
(
[USER_ID] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTS_USR] ADD CONSTRAINT [PK_CLIENTS_USR] PRIMARY KEY CLUSTERED  ([USER_ID], [CLIENT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTS_USR] ADD CONSTRAINT [FK_CLIENTS_USR_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
ALTER TABLE [dbo].[CLIENTS_USR] WITH NOCHECK ADD CONSTRAINT [FK_CLIENTS_USR_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
