CREATE TABLE [dbo].[DEPOSIT_ATTRIBUTES]
(
[REC_ID] [int] NOT NULL,
[ATTRIB_CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ATTRIB_VALUE] [varchar] (1000) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPOSIT_ATTRIBUTES] ADD CONSTRAINT [PK_DEPOSIT_ATTRIBUTES] PRIMARY KEY CLUSTERED  ([REC_ID], [ATTRIB_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPOSIT_ATTRIBUTES] ADD CONSTRAINT [FK_DEPOSIT_ATTRIBUTES_DEPOSIT_ATTRIB_CODES] FOREIGN KEY ([ATTRIB_CODE]) REFERENCES [dbo].[DEPOSIT_ATTRIB_CODES] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
GO
