CREATE TABLE [dbo].[SO_TASK_CHANGES]
(
[TASK_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[FIELD] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[OLD_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[NEW_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[OLD_DISPLAY_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[NEW_DISPLAY_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [datetime] NULL CONSTRAINT [DF_SO_TASK_CHANGES_TIME_OF_CHANGE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_TASK_CHANGES] ADD CONSTRAINT [PK_SO_TASK_CHANGES] PRIMARY KEY CLUSTERED  ([TASK_ID], [REC_ID]) WITH (ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_TASK_CHANGES] ADD CONSTRAINT [FK_SO_TASK_CHANGES_SO_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[SO_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[SO_TASK_CHANGES] ADD CONSTRAINT [FK_SO_TASK_CHANGES_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
