CREATE TABLE [dbo].[LOAN_PRODUCT_USERS]
(
[PRODUCT_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_USERS] ADD CONSTRAINT [PK_LOAN_PRODUCT_USERS] PRIMARY KEY CLUSTERED  ([PRODUCT_ID], [USER_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_USERS] ADD CONSTRAINT [FK_LOAN_PRODUCT_USERS_LOAN_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([PRODUCT_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_USERS] ADD CONSTRAINT [FK_LOAN_PRODUCT_USERS_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
