CREATE TABLE [dbo].[PLASTIC_CARD_LIMITS]
(
[CARD_ID] [varchar] (19) COLLATE Latin1_General_BIN NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[AMOUNT] [money] NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLASTIC_CARD_LIMITS] ADD CONSTRAINT [PK_PLASTIC_CARD_LIMITS] PRIMARY KEY CLUSTERED  ([CARD_ID], [REC_ID]) ON [PRIMARY]
GO
