CREATE TABLE [dbo].[BANKING_PRODUCTS]
(
[PRODUCT_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF_BANKING_PRODUCTS_IS_ACTIVE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANKING_PRODUCTS] ADD CONSTRAINT [PK_BANKING_PRODUCTS] PRIMARY KEY CLUSTERED  ([PRODUCT_ID]) ON [PRIMARY]
GO
