CREATE TABLE [dbo].[OPS_HELPER_2015]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[REC_ID] [int] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[OPS_HELPER_2015] ADD CONSTRAINT [CK_OPS_HELPER_2015] CHECK (([DT]>='20150101' AND [DT]<'20160101'))
GO
ALTER TABLE [dbo].[OPS_HELPER_2015] ADD CONSTRAINT [PK_OPS_HELPER_2015] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT], [REC_ID]) ON [ARCHIVE]
GO
