CREATE TABLE [dbo].[LOAN_PURPOSE_MONITORING_ATTACHMENTS]
(
[MONITORING_ID] [int] NOT NULL,
[FILE_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[IS_FOLDER] [bit] NOT NULL,
[FILE_DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PURPOSE_MONITORING_ATTACHMENTS] ADD CONSTRAINT [PK_LOAN_PURPOSE_MONITORING_ATTACHMENTS] PRIMARY KEY CLUSTERED  ([MONITORING_ID], [FILE_NAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PURPOSE_MONITORING_ATTACHMENTS] ADD CONSTRAINT [FK_LOAN_PURPOSE_MONITORING_ATTACHMENTS_LOAN_PURPOSE_MONITORING] FOREIGN KEY ([MONITORING_ID]) REFERENCES [dbo].[LOAN_PURPOSE_MONITORING] ([REC_ID]) ON DELETE CASCADE
GO
