CREATE TABLE [dbo].[SALDOS_2013]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[DBO] [money] NOT NULL,
[CRO] [money] NOT NULL,
[SALDO] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[SALDOS_2013] ADD CONSTRAINT [CK_SALDOS_2013] CHECK (([DT]>='20130101' AND [DT]<'20140101'))
GO
ALTER TABLE [dbo].[SALDOS_2013] ADD CONSTRAINT [PK_SALDOS_2013] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT]) ON [ARCHIVE]
GO
