CREATE TABLE [dbo].[LOAN_CHANGES]
(
[LOAN_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [text] COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_LOAN_CHANGES_TIME_OF_CHANGE] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CHANGES] ADD CONSTRAINT [PK_LOAN_CHANGES] PRIMARY KEY CLUSTERED  ([LOAN_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CHANGES] ADD CONSTRAINT [FK_LOAN_CHANGES_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOAN_CHANGES] ADD CONSTRAINT [FK_LOAN_CHANGES_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
