CREATE TABLE [dbo].[LOAN_OP_TYPES]
(
[TYPE_ID] [smallint] NOT NULL,
[SELF_EXEC] [bit] NOT NULL CONSTRAINT [DF_LOAN_OP_TYPES_SELF_EXEC] DEFAULT ((0)),
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[CONST_FUNCTION] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DOC_REC_STATE] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OP_TYPES] ADD CONSTRAINT [CK_LOAN_OP_TYPES_DOC_REC_STATE] CHECK (([DOC_REC_STATE]=(20) OR [DOC_REC_STATE]=(10) OR [DOC_REC_STATE]=(0)))
GO
ALTER TABLE [dbo].[LOAN_OP_TYPES] ADD CONSTRAINT [PK_LOAN_OP_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
