CREATE TABLE [dbo].[ACCOUNTS_JOBS]
(
[ACC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[JOB_ID] [int] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NULL,
[FREQ_TYPE] [tinyint] NOT NULL,
[PARAM_STR] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[JOB_FLAGS] [tinyint] NOT NULL CONSTRAINT [DF_ACCOUNTS_JOBS_JOB_FLAGS] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_JOBS] ADD CONSTRAINT [PK_ACCOUNTS_JOBS] PRIMARY KEY CLUSTERED  ([ACC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_JOBS] ADD CONSTRAINT [FK_ACCOUNTS_JOBS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS_JOBS] ADD CONSTRAINT [FK_ACCOUNTS_JOBS_JOBS] FOREIGN KEY ([JOB_ID]) REFERENCES [dbo].[JOBS] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
