CREATE TABLE [dbo].[DEPO_PRODUCT]
(
[PROD_ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [dbo].[TCODE] NOT NULL,
[PROD_NO] [int] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[IS_ACTIVE] [bit] NOT NULL,
[REMOTE_USE] [bit] NOT NULL,
[AGR_NO_TEMPLATE] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[DEPO_TYPE] [tinyint] NOT NULL,
[DEPO_ACC_SUBTYPE] [int] NOT NULL,
[DEPO_ACCOUNT_STATE] [tinyint] NOT NULL,
[CLIENT_TYPES] [int] NOT NULL,
[CLIENT_PROPERTIES] [int] NOT NULL,
[DATE_TYPE] [tinyint] NOT NULL,
[PERC_FLAGS] [int] NOT NULL,
[DAYS_IN_YEAR] [smallint] NOT NULL,
[MIN_PERIOD] [int] NULL,
[MAX_PERIOD] [int] NULL,
[INTRATE_SCHEMA] [int] NOT NULL,
[INTEREST_CORRECTION] [money] NOT NULL,
[ACCRUE_TYPE] [tinyint] NOT NULL,
[RECALCULATE_TYPE] [tinyint] NOT NULL,
[REALIZE_SCHEMA] [int] NOT NULL,
[DEPO_REALIZE_SCHEMA] [tinyint] NOT NULL,
[CONVERTIBLE] [tinyint] NOT NULL,
[PROLONGABLE] [tinyint] NOT NULL,
[RENEWABLE] [tinyint] NOT NULL,
[RENEW_CAPITALIZED] [tinyint] NOT NULL,
[RENEW_MAX] [int] NULL,
[RENEW_LAST_PROD_ID] [int] NULL,
[SHAREABLE] [tinyint] NOT NULL,
[SHARED_CONTROL] [tinyint] NULL,
[CHILD_DEPOSIT] [bit] NOT NULL,
[ACCUMULATIVE] [tinyint] NOT NULL,
[SPEND] [tinyint] NOT NULL,
[REVISION_SCHEMA] [int] NOT NULL,
[REVISION_GRACE_ITEMS] [int] NULL,
[REVISION_GRACE_DATE_TYPE] [tinyint] NULL,
[ANNULMENTED] [bit] NOT NULL,
[ANNULMENT_REALIZE] [bit] NOT NULL,
[ANNULMENT_SCHEMA] [int] NULL,
[ANNULMENT_SCHEMA_ADVANCE] [int] NULL,
[BONUS_SCHEMA] [int] NULL,
[ANALYZE_SCHEMA] [int] NULL,
[ANALYZE_SCHEMA_ANNUL] [bit] NULL,
[ACCUMULATE_SCHEMA_INTRATE] [tinyint] NULL,
[INTEREST_ADV_REALIZE] [tinyint] NOT NULL,
[DEPO_ACC_TEMPL] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[LOSS_ACC_TEMPL] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[ACCRUAL_ACC_TEMPL] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DEPO_REALIZE_TYPE] [tinyint] NOT NULL,
[CREDITCARD_BALANCE_CHECK] [bit] NOT NULL,
[INTEREST_REALIZE_TYPE] [tinyint] NOT NULL,
[INTEREST_ADV_REALIZE_ACC_TEMPL] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[DEPO_FILL_ACCOUNTS] [tinyint] NOT NULL,
[FUNCTION_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [PK_DEPO_PRODUCT] PRIMARY KEY CLUSTERED  ([PROD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_ACC_SUBTYPES] FOREIGN KEY ([DEPO_ACC_SUBTYPE]) REFERENCES [dbo].[ACC_SUBTYPES] ([ACC_SUBTYPE])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_ANALYZE_SCHEMA] FOREIGN KEY ([ANALYZE_SCHEMA]) REFERENCES [dbo].[DEPO_PRODUCT_ANALYZE_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_ANNULMENT_SCHEMA] FOREIGN KEY ([ANNULMENT_SCHEMA]) REFERENCES [dbo].[DEPO_PRODUCT_ANNULMENT_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_ANNULMENT_SCHEMA_ADVANCE] FOREIGN KEY ([ANNULMENT_SCHEMA_ADVANCE]) REFERENCES [dbo].[DEPO_PRODUCT_ANNULMENT_SCHEMA_ADVANCE] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_BONUS_SCHEMA] FOREIGN KEY ([BONUS_SCHEMA]) REFERENCES [dbo].[DEPO_PRODUCT_BONUS_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_INTRATE_SCHEMA] FOREIGN KEY ([INTRATE_SCHEMA]) REFERENCES [dbo].[DEPO_PRODUCT_INTRATE_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_REALIZE_SCHEMA] FOREIGN KEY ([REALIZE_SCHEMA]) REFERENCES [dbo].[DEPO_PRODUCT_REALIZE_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_DEPO_PRODUCT_REVISION_SCHEMA] FOREIGN KEY ([REVISION_SCHEMA]) REFERENCES [dbo].[DEPO_PRODUCT_REVISION_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[DEPO_PRODUCT] ADD CONSTRAINT [FK_DEPO_PRODUCT_FUNCTIONS] FOREIGN KEY ([FUNCTION_ID]) REFERENCES [af].[FUNCTIONS] ([FUNCTION_ID])
GO
