CREATE TABLE [dbo].[INCASSO_ACCOUNTS]
(
[INCASSO_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[AMOUNT] [money] NOT NULL CONSTRAINT [DF_INCASSO_ACCOUNTS_AMOUNT] DEFAULT (($0.0000))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_ACCOUNTS] ADD CONSTRAINT [PK_INCASSO_ACCOUNTS_1] PRIMARY KEY CLUSTERED  ([INCASSO_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_ACCOUNTS] ADD CONSTRAINT [IX_INCASSO_ACCOUNTS] UNIQUE NONCLUSTERED  ([INCASSO_ID], [ACC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_ACCOUNTS] ADD CONSTRAINT [FK_INCASSO_ACCOUNTS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID])
GO
ALTER TABLE [dbo].[INCASSO_ACCOUNTS] ADD CONSTRAINT [FK_INCASSO_ACCOUNTS_INCASSO] FOREIGN KEY ([INCASSO_ID]) REFERENCES [dbo].[INCASSO] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
