CREATE TABLE [dbo].[SAXAZCODES_3]
(
[ID] [smallint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[SAXAZCODES_3_TRIGGER] ON [dbo].[SAXAZCODES_3]
FOR INSERT, UPDATE, DELETE 
AS

EXEC dbo._UPDATE_VERSION 'VER_SAXAZCODES_3'
GO
ALTER TABLE [dbo].[SAXAZCODES_3] ADD CONSTRAINT [PK_SAXAZCODES_3] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
