CREATE TABLE [dbo].[CALL_CENTER_CODES]
(
[ENVELOPE_NO] [int] NOT NULL,
[PHONE_CODE] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[DT_TM] [smalldatetime] NOT NULL,
[USER_ID] [int] NOT NULL,
[USER2_ID] [int] NULL,
[USER3_ID] [int] NULL,
[CLIENT_NO] [int] NULL,
[STATUS] [tinyint] NULL,
[IS_BLOCKED] [bit] NULL,
[LAST_UPDATE_DT_TM] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CALL_CENTER_CODES] ADD CONSTRAINT [PK_CALL_CENTER_CODES] PRIMARY KEY CLUSTERED  ([ENVELOPE_NO], [PHONE_CODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CALL_CENTER_CODES_CLIENT_NO_STATUS] ON [dbo].[CALL_CENTER_CODES] ([CLIENT_NO], [STATUS]) INCLUDE ([ENVELOPE_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CALL_CENTER_CODES_PHONE_CODE] ON [dbo].[CALL_CENTER_CODES] ([PHONE_CODE]) ON [PRIMARY]
GO
