CREATE TABLE [dbo].[LOAN_CREDIT_LINE_COLLATERALS_LINK]
(
[CREDIT_LINE_ID] [int] NOT NULL,
[COLLATERAL_ID] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CREDIT_LINE_COLLAT_LINK_COLLAT_ID] ON [dbo].[LOAN_CREDIT_LINE_COLLATERALS_LINK] ([COLLATERAL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINE_COLLATERALS_LINK] WITH NOCHECK ADD CONSTRAINT [FK_LOAN_CREDIT_LINE_COLLATERALS_LINK_LOAN_COLLATERALS] FOREIGN KEY ([COLLATERAL_ID]) REFERENCES [dbo].[LOAN_COLLATERALS] ([COLLATERAL_ID])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINE_COLLATERALS_LINK] WITH NOCHECK ADD CONSTRAINT [FK_LOAN_CREDIT_LINE_COLLATERALS_LINK_LOAN_CREDIT_LINES] FOREIGN KEY ([CREDIT_LINE_ID]) REFERENCES [dbo].[LOAN_CREDIT_LINES] ([CREDIT_LINE_ID])
GO
