CREATE TABLE [dbo].[BC_LOGIN_ACC]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[BC_LOGIN_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF_BC_LOGIN_ACC_FLAGS] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_LOGIN_ACC] ADD CONSTRAINT [PK_BC_LOGIN_ACC] PRIMARY KEY CLUSTERED  ([BC_LOGIN_ID], [ACC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_BC_LOGIN_ACC] ON [dbo].[BC_LOGIN_ACC] ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_LOGIN_ACC] ADD CONSTRAINT [FK_BC_LOGIN_ACC_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BC_LOGIN_ACC] ADD CONSTRAINT [FK_BC_LOGIN_ACC_BC_LOGIN_ID] FOREIGN KEY ([BC_LOGIN_ID]) REFERENCES [dbo].[BC_LOGINS] ([BC_LOGIN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
