CREATE TABLE [dbo].[LOAN_ACCOUNT_TYPES]
(
[TYPE_ID] [int] NOT NULL,
[CODE] [varchar] (15) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[HEAD_BRANCH] [bit] NOT NULL CONSTRAINT [DF_LOAN_ACCOUNT_TYPES_HEAD_BRANCH] DEFAULT ((0)),
[GUARANTEE_HEAD_BRANCH] [bit] NOT NULL CONSTRAINT [DF_LOAN_ACCOUNT_TYPES_GUARANTEE_HEAD_BRANCH] DEFAULT ((0)),
[ACC_SHOW_FLAG] [int] NOT NULL CONSTRAINT [DF_LOAN_ACCOUNT_TYPES_ACC_SHOW_FLAG] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCOUNT_TYPES] ADD CONSTRAINT [PK_LOAN_ACCOUNT_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
