CREATE TABLE [dbo].[CLIENT_SUBTYPES]
(
[CLIENT_TYPE] [tinyint] NOT NULL,
[CLIENT_SUBTYPE] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_SUBTYPES] ADD CONSTRAINT [PK_CLIENT_SUBTYPES] PRIMARY KEY CLUSTERED  ([CLIENT_TYPE], [CLIENT_SUBTYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_SUBTYPES] ADD CONSTRAINT [FK_CLIENT_SUBTYPES_TYPES] FOREIGN KEY ([CLIENT_TYPE]) REFERENCES [dbo].[CLIENT_TYPES] ([CLIENT_TYPE]) ON DELETE CASCADE ON UPDATE CASCADE
GO
