CREATE TABLE [dbo].[ACCOUNTS_BLOCKS]
(
[ACC_ID] [int] NOT NULL,
[BLOCK_ID] [int] NOT NULL IDENTITY(1, 1),
[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF_ACCOUNTS_BLOCKS_IS_ACTIVE] DEFAULT ((1)),
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [money] NOT NULL,
[FEE] [money] NOT NULL CONSTRAINT [DF_ACCOUNTS_BLOCKS_FEE] DEFAULT ((0)),
[BLOCKED_BY_PRODUCT] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[BLOCKED_BY_USER] [int] NULL,
[BLOCK_DATE_TIME] [datetime] NOT NULL CONSTRAINT [DF_ACCOUNTS_BLOCKS_DATE_TIME] DEFAULT (getdate()),
[AUTO_UNBLOCK_DATE] [smalldatetime] NULL,
[UNBLOCKED_BY_USER] [int] NULL,
[UNBLOCK_DATE_TIME] [datetime] NULL,
[USER_DATA] [sql_variant] NULL,
[DOC_REC_ID] [int] NULL,
[COMMENT] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_BLOCKS] ADD CONSTRAINT [FK_ACCOUNTS_BLOCKS_ACC_BLOCK_PRODUCTS] FOREIGN KEY ([BLOCKED_BY_PRODUCT]) REFERENCES [dbo].[ACC_BLOCK_PRODUCTS] ([PRODUCT_ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS_BLOCKS] ADD CONSTRAINT [FK_ACCOUNTS_BLOCKS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID])
GO
