CREATE TABLE [dbo].[COUNTRIES]
(
[COUNTRY] [char] (2) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[ZONE_TYPE] [tinyint] NOT NULL CONSTRAINT [DF_COUNTRIES_ZONE_TYPE] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[COUNTRIES_TRIGGER] ON [dbo].[COUNTRIES]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_COUNTRIES'

GO
ALTER TABLE [dbo].[COUNTRIES] ADD CONSTRAINT [CK_COUNTRIES] CHECK (([ZONE_TYPE]=(2) OR [ZONE_TYPE]=(1) OR [ZONE_TYPE]=(0)))
GO
ALTER TABLE [dbo].[COUNTRIES] ADD CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED  ([COUNTRY]) ON [PRIMARY]
GO
