CREATE TABLE [dbo].[GROUP_BANK_TASKS]
(
[GROUP_ID] [int] NOT NULL,
[TASK_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_BANK_TASKS] ADD CONSTRAINT [PK_GROUP_BANK_TASKS] PRIMARY KEY CLUSTERED  ([GROUP_ID], [TASK_ID]) ON [PRIMARY]
GO
