CREATE TABLE [dbo].[VAL_RATES_2010]
(
[ISO] [dbo].[TISO] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[VAL_RATES_2010] ADD CONSTRAINT [CK_VAL_RATES_2010] CHECK (([DT]>='20100101' AND [DT]<'20110101'))
GO
ALTER TABLE [dbo].[VAL_RATES_2010] ADD CONSTRAINT [PK_VAL_RATES_2010] PRIMARY KEY CLUSTERED  ([ISO], [DT]) ON [ARCHIVE]
GO
