CREATE TABLE [dbo].[LOAN_RISK_TYPES]
(
[TYPE_ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (15) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NOT NULL,
[PERC_RATE_1] [smallmoney] NOT NULL,
[PERC_RATE_2] [smallmoney] NOT NULL,
[PERC_RATE_3] [smallmoney] NOT NULL,
[PERC_RATE_4] [smallmoney] NOT NULL,
[PERC_RATE_5] [smallmoney] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_RISK_TYPES] ADD CONSTRAINT [PK_LOAN_RISK_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
