CREATE TABLE [dbo].[DEPTS]
(
[DEPT_NO] [int] NOT NULL,
[BRANCH_ID] [int] NOT NULL,
[IS_DEPT] [bit] NOT NULL CONSTRAINT [DF_DEPTS_IS_DEPT] DEFAULT ((0)),
[ALIAS] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[DATABASE_ID] [int] NULL,
[CODE9] [dbo].[TGEOBANKCODE] NULL,
[BIC] [char] (11) COLLATE Latin1_General_BIN NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[ADDRESS] [varchar] (80) COLLATE Latin1_General_BIN NULL,
[PHONE] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[FAX] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[WORK_TYPE] [tinyint] NULL,
[KAS_ACC] [dbo].[TACCOUNT] NULL,
[KAS_ACC_V] [dbo].[TACCOUNT] NULL,
[CONV_ACC_19_1A] [dbo].[TACCOUNT] NULL,
[CONV_ACC_19_1P] [dbo].[TACCOUNT] NULL,
[CONV_ACC_64X1] [dbo].[TACCOUNT] NULL,
[CONV_ACC_64X1_V] [dbo].[TACCOUNT] NULL,
[CONV_ACC_84X1] [dbo].[TACCOUNT] NULL,
[CONV_ACC_84X1_V] [dbo].[TACCOUNT] NULL,
[UP_PROFIT_ACC] [dbo].[TACCOUNT] NULL,
[PROV_MONEYBACK_ACC] [dbo].[TACCOUNT] NULL,
[SIGN1] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SIGN2] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[ADDRESS_LAT] [varchar] (80) COLLATE Latin1_General_BIN NULL,
[E_MAIL] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[KAS_TRANSIT_ACC] [dbo].[TACCOUNT] NULL,
[KAS_TRANSIT_ACC_V] [dbo].[TACCOUNT] NULL,
[CITY] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[CITY_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[BANK_NAME] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[BANK_NAME_LAT] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[BANK_REPRESENTATIVE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[BANK_REPRESENTATIVE_LAT] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[POSITION] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[POSITION_LAT] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SIGN1_LAT] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SIGN2_LAT] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TRAV_CHEQUE_ACC1] [dbo].[TACCOUNT] NULL,
[TRAV_CHEQUE_ACC2] [dbo].[TACCOUNT] NULL,
[TCD_CASETTE_ACCOUNT] [dbo].[TACCOUNT] NULL,
[TCD_CASETTE_ACCOUNT_V] [dbo].[TACCOUNT] NULL,
[OFF_BAL_DEBIT_DEPT] [tinyint] NULL,
[OFF_BAL_DEBIT_ACC] [dbo].[TACCOUNT] NULL,
[OFF_BAL_DEBIT_ACC_V] [dbo].[TACCOUNT] NULL,
[OFF_BAL_CREDIT_DEPT] [tinyint] NULL,
[OFF_BAL_CREDIT_ACC] [dbo].[TACCOUNT] NULL,
[OFF_BAL_CREDIT_ACC_V] [dbo].[TACCOUNT] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[DEPTS_TRIGGER] ON [dbo].[DEPTS]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_DEPTS'
GO
ALTER TABLE [dbo].[DEPTS] ADD CONSTRAINT [PK_DEPTS] PRIMARY KEY CLUSTERED  ([DEPT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPTS] WITH NOCHECK ADD CONSTRAINT [FK_DEPTS] FOREIGN KEY ([CODE9]) REFERENCES [dbo].[BANKS] ([CODE9])
GO
