CREATE TABLE [dbo].[WBC_LOG]
(
[BC_LOGIN_ID] [int] NULL,
[ACTION_CODE] [tinyint] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[DATE_AND_TIME] [smalldatetime] NOT NULL CONSTRAINT [DF_WBC_LOG_DATE_AND_TIME] DEFAULT (getdate()),
[REC_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WBC_LOG] ADD CONSTRAINT [PK_WBC_LOG] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
