CREATE TABLE [dbo].[BC_UPDATE_INFO]
(
[BC_UPDATE_DATA] [text] COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[BC_UPDATE_INFO_TRIGGER] ON [dbo].[BC_UPDATE_INFO] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_BC_UPDATE_INFO'
GO
