CREATE TABLE [dbo].[CLASSIF_CLI]
(
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[CLASSIF_CLI_TRIGGER] ON [dbo].[CLASSIF_CLI]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_CLASSIF_CLI'

GO
ALTER TABLE [dbo].[CLASSIF_CLI] ADD CONSTRAINT [PK_CLASSIF_CLI] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLASSIF_CLI] WITH NOCHECK ADD CONSTRAINT [FK_CLASSIF_CLI_CLASSIF_CLI] FOREIGN KEY ([ID]) REFERENCES [dbo].[CLASSIF_CLI] ([ID])
GO
