CREATE TABLE [dbo].[PLASTIC_CARD_ACCOUNTS_ARC]
(
[CARD_ID] [varchar] (19) COLLATE Latin1_General_BIN NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[CREDIT_AMOUNT] [dbo].[TAMOUNT] NOT NULL,
[MIN_AMOUNT] [dbo].[TAMOUNT] NOT NULL,
[NON_REDUCE_AMOUNT] [dbo].[TAMOUNT] NOT NULL,
[AUTH_BONUS] [dbo].[TAMOUNT] NULL,
[AUTH_BONUS_EXPIRITY] [smalldatetime] NULL,
[DEPOSIT_ACCOUNT] [dbo].[TACCOUNT] NULL,
[DEPOSIT_ISO] [dbo].[TISO] NULL,
[DEPOSIT_AMOUNT] [dbo].[TAMOUNT] NULL,
[DEPOSIT_DESCRIP] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[MESSAGE] [varchar] (99) COLLATE Latin1_General_BIN NULL,
[TRANSIT_ACCOUNT] [dbo].[TACCOUNT] NULL,
[TRANSIT_ISO] [dbo].[TISO] NULL,
[CONDITION_SET] [varchar] (3) COLLATE Latin1_General_BIN NOT NULL,
[USER_ID] [smallint] NULL,
[BILLING_GROUP] [varchar] (10) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_PLASTIC_CARD_ACCOUNTS_ARC_BILLING_GROUP] DEFAULT ('')
) ON [PRIMARY]
GO
