CREATE TABLE [dbo].[TCD_COMMAND_TYPES]
(
[COMMAND_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[WAIT_TIME] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCD_COMMAND_TYPES] ADD CONSTRAINT [PK_TCD_COMMAND_TYPES] PRIMARY KEY CLUSTERED  ([COMMAND_ID]) ON [PRIMARY]
GO
