CREATE TABLE [dbo].[USER_RELATIONS]
(
[USER_ID] [int] NOT NULL,
[USER_ID_2] [int] NOT NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF_USER_RELATIONS_FLAGS] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_RELATIONS] ADD CONSTRAINT [PK_USER_RELATIONS] PRIMARY KEY CLUSTERED  ([USER_ID], [USER_ID_2]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_USER_RELATIONS_USER_ID] ON [dbo].[USER_RELATIONS] ([USER_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_USER_RELATIONS_USER_ID2] ON [dbo].[USER_RELATIONS] ([USER_ID_2]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_USER_RELATIONS_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[USER_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_USER_RELATIONS_USERS1] FOREIGN KEY ([USER_ID_2]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
