CREATE TABLE [dbo].[PAYMENTS_SCHEDULER_TMP]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[PROVIDER_ID] [int] NOT NULL,
[SERVICE_ALIAS] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ACC_ID] [int] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_TMP_ACC_ID] DEFAULT ((0)),
[ID_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ID2_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[AMOUNT] [money] NOT NULL,
[PAY_PART] [bit] NOT NULL,
[PRIORITY_ORDER] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[CCY] [char] (3) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_TMP_CCY] DEFAULT ('GEL')
) ON [PRIMARY]
GO
