CREATE TABLE [dbo].[LOAN_SRV_FILTERS]
(
[TAG] [int] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[FILTER_DATA] [varchar] (max) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_SRV_FILTERS] ADD CONSTRAINT [PK_LOAN_SRV_FILTERS] PRIMARY KEY CLUSTERED  ([TAG], [DESCRIP]) ON [PRIMARY]
GO
