CREATE TABLE [dbo].[SO_SCHEDULE_ANULLS]
(
[TASK_ID] [int] NOT NULL,
[DATE] [smalldatetime] NOT NULL,
[VERSION] [int] NOT NULL,
[FAIL_COUNTER] [int] NULL,
[STATE] [int] NOT NULL CONSTRAINT [DF_SO_SCHEDULE_ANULL_STATE] DEFAULT ((10)),
[FAULT_MESSAGE] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[FAULT_CODE] [int] NULL,
[SUSPENDED_BY_BANK] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULE_ANULLS] ADD CONSTRAINT [PK_SO_SCHEDULE_ANULLS_1] PRIMARY KEY CLUSTERED  ([TASK_ID], [DATE], [VERSION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULE_ANULLS] ADD CONSTRAINT [FK_SO_SCHEDULE_ANULLS_SO_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[SO_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
