CREATE TABLE [dbo].[CLASSIF]
(
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[CLASSIF_TRIGGER] ON [dbo].[CLASSIF]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_CLASSIF'

GO
ALTER TABLE [dbo].[CLASSIF] ADD CONSTRAINT [PK_CLASSIF] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
