CREATE TABLE [dbo].[BCBR_VERSIONS]
(
[TABLENAME] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[VERSION] [int] NOT NULL CONSTRAINT [DF_BCBR_VERSIONS_VERSION] DEFAULT ((0)),
[DATE_VERSION] [int] NULL CONSTRAINT [DF_BCBR_VERSIONS_DATE_VERSION] DEFAULT ((0)),
[HASH] [varchar] (34) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCBR_VERSIONS] ADD CONSTRAINT [PK_BCBR_VERSIONS] PRIMARY KEY CLUSTERED  ([TABLENAME]) ON [PRIMARY]
GO
