CREATE TABLE [dbo].[INCASSO_ACCOUNTS_ARC]
(
[INCASSO_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[AMOUNT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_ACCOUNTS_ARC] ADD CONSTRAINT [PK_INCASSO_ACCOUNTS_ARC] PRIMARY KEY CLUSTERED  ([INCASSO_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_ACCOUNTS_ARC] ADD CONSTRAINT [FK_INCASSO_ACCOUNTS_INCASSO_ARC] FOREIGN KEY ([INCASSO_ID]) REFERENCES [dbo].[INCASSO_ARC] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
