CREATE TABLE [dbo].[DEPOS]
(
[DEPO_ID] [int] NOT NULL IDENTITY(1, 1),
[BRANCH_ID] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[OP_ID] [int] NULL,
[CLIENT_NO] [int] NOT NULL,
[DEPO_NO] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DEPO_TYPE_ID] [int] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[ACC_ID] [int] NOT NULL,
[PROD_ID] [int] NULL,
[PROLONGATION] [bit] NOT NULL CONSTRAINT [DF_DEPOS_PROLONGATION] DEFAULT ((0)),
[REALIZE_ADVANCE] [bit] NULL,
[REALIZE_ADV_ACC_ID] [int] NULL,
[CONVERTED_DEPOSIT] [bit] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[ON_DEPOS_DELETE_TRIGGER] ON [dbo].[DEPOS]
FOR DELETE AS

SET NOCOUNT ON

DECLARE	@r int
  
DECLARE
  @depo_id int,
  @rec_state int

DECLARE cc CURSOR FOR 
SELECT DEPO_ID FROM deleted

OPEN cc
IF @@ERROR <> 0 GOTO ROLLBACK_DEL_TRAN

FETCH NEXT FROM cc INTO @depo_id
IF @@ERROR <> 0 GOTO ROLLBACK_DEL_TRAN

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT @rec_state = D.REC_STATE
	FROM dbo.DEPO_OPS O
		INNER JOIN dbo.DEPO_DATA D ON D.OP_ID = O.OP_ID
	WHERE O.DEPO_ID = @depo_id
  
	IF @rec_state <> 0
	BEGIN
		RAISERROR ('CANNOT DELETE THIS DEPOSIT',16,1) 
		GOTO ROLLBACK_DEL_TRAN
	END

	FETCH NEXT FROM cc INTO @depo_id
	IF @@ERROR <> 0 GOTO ROLLBACK_DEL_TRAN
END

IF @@FETCH_STATUS <> -1
BEGIN
  RAISERROR ('FETCH STATUS ERROR',16,1)
  GOTO ROLLBACK_DEL_TRAN
END

CLOSE cc
DEALLOCATE cc
RETURN

ROLLBACK_DEL_TRAN:
ROLLBACK
CLOSE cc
DEALLOCATE cc

RETURN
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [PK_DEPOS] PRIMARY KEY CLUSTERED  ([DEPO_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [IX_DEPOS] UNIQUE NONCLUSTERED  ([DEPO_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [FK_DEPOS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID])
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [FK_DEPOS_DEPOSIT_TYPES] FOREIGN KEY ([DEPO_TYPE_ID]) REFERENCES [dbo].[DEPO_TYPES] ([DEPO_TYPE_ID])
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [FK_DEPOS_DEPTS_BRANCH_ID] FOREIGN KEY ([BRANCH_ID]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [FK_DEPOS_DEPTS_DEPT_NO] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [FK_DEPOS_PRODUCTS_PROD_ID] FOREIGN KEY ([PROD_ID]) REFERENCES [dbo].[DEPO_PRODUCTS] ([PROD_ID])
GO
ALTER TABLE [dbo].[DEPOS] ADD CONSTRAINT [FK_DEPOS_VAL_CODES_ISO] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
