CREATE TABLE [dbo].[GROUP_LIMITS]
(
[GROUP_ID] [int] NOT NULL,
[DOC_TYPE] [int] NOT NULL,
[OP_TYPE] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL CONSTRAINT [DF_GROUP_LIMITS_ISO] DEFAULT (''),
[LIMIT_MAX_VALUE] [money] NULL,
[LIMIT_YELLOW_VALUE] [money] NULL,
[LIMIT_GREEN_VALUE] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_LIMITS] ADD CONSTRAINT [PK_GROUP_LIMITS] PRIMARY KEY CLUSTERED  ([GROUP_ID], [DOC_TYPE], [OP_TYPE], [ISO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_LIMITS] ADD CONSTRAINT [FK_GROUP_LIMITS_GROUPS] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[GROUPS] ([GROUP_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
