CREATE TABLE [dbo].[BC_BANK_KEYS2]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DEPT_NO] [int] NOT NULL,
[DT_FROM] [smalldatetime] NOT NULL,
[DT_TO] [smalldatetime] NOT NULL,
[PUB_KEY] [text] COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[BC_BANK_KEYS2_TRIGGER] ON [dbo].[BC_BANK_KEYS2]
FOR INSERT, UPDATE, DELETE 
AS

EXEC _UPDATE_VERSION 'VER_BC_BANK_KEYS2'
GO
ALTER TABLE [dbo].[BC_BANK_KEYS2] ADD CONSTRAINT [PK_BC_BANK_KEYS2] PRIMARY KEY NONCLUSTERED  ([DEPT_NO], [REC_ID]) ON [PRIMARY]
GO
