CREATE TABLE [dbo].[TASKS]
(
[TASK_ID] [tinyint] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[CATEGORY] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[CATEGORY_LAT] [varchar] (20) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [PK_TASKS] PRIMARY KEY CLUSTERED  ([TASK_ID]) ON [PRIMARY]
GO
