CREATE TABLE [dbo].[SWIFT_STATEMENTS_LIST]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[UID] [int] NOT NULL CONSTRAINT [DF_SWIFT_STATEMENTS_LIST_UID] DEFAULT ((0)),
[STATE] [int] NOT NULL CONSTRAINT [DF_SWIFT_STATEMENTS_LIST_STATE] DEFAULT ((0)),
[STATEMENT_NO] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[CREATE_DT] [smalldatetime] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NOT NULL,
[STATEMENT_COMMITTED] [bit] NOT NULL CONSTRAINT [DF_SWIFT_STATEMENTS_LIST_STATEMENT_COMMITTED] DEFAULT ((0)),
[OWNER] [int] NOT NULL,
[SWIFT_TEXT] [text] COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_STATEMENTS_LIST] ADD CONSTRAINT [PK_SWIFT_STATEMENTS_LIST] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_STATEMENTS_LIST] ADD CONSTRAINT [FK_SWIFT_STATEMENTS_LIST_USERS] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
