CREATE TABLE [dbo].[FAST_PAYMENT_SYSTEMS]
(
[FP_SYS_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[USE_HEAD_BRANCH_ACCOUNTS] [bit] NOT NULL,
[TRANSIT_ACC_SEND] [dbo].[TACCOUNT] NOT NULL,
[PROFIT_ACC_SEND] [dbo].[TACCOUNT] NULL,
[TRANSIT_ACC_WITHDRAW] [dbo].[TACCOUNT] NOT NULL,
[PROFIT_ACC_WITHDRAW] [dbo].[TACCOUNT] NULL,
[ALIAS] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAST_PAYMENT_SYSTEMS] ADD CONSTRAINT [PK_FAST_PAYMENT_SYSTEMS] PRIMARY KEY CLUSTERED  ([FP_SYS_ID]) ON [PRIMARY]
GO
