CREATE TABLE [dbo].[GROUPS]
(
[GROUP_ID] [int] NOT NULL IDENTITY(1, 1),
[ACCESS_STRING] [dbo].[TACCESS] NOT NULL,
[ACCESS_STRING_2] [dbo].[TACCESS2] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[GROUPS_TRIGGER] ON [dbo].[GROUPS]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_GROUPS'

GO
ALTER TABLE [dbo].[GROUPS] ADD CONSTRAINT [PK_GROUPS] PRIMARY KEY CLUSTERED  ([GROUP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUPS] ADD CONSTRAINT [IX_GROUPS] UNIQUE NONCLUSTERED  ([DESCRIP]) ON [PRIMARY]
GO
