CREATE TABLE [dbo].[CLIENT_ATTRIBUTES]
(
[CLIENT_NO] [int] NOT NULL,
[ATTRIB_CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ATTRIB_VALUE] [varchar] (1000) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_ATTRIBUTES] ADD CONSTRAINT [PK_CLIENT_ATTRIBUTES] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [ATTRIB_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_ATTRIBUTES] ADD CONSTRAINT [FK_CLIENT_ATTRIBUTES_CLIENT_ATTRIB_CODES] FOREIGN KEY ([ATTRIB_CODE]) REFERENCES [dbo].[CLIENT_ATTRIB_CODES] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CLIENT_ATTRIBUTES] ADD CONSTRAINT [FK_CLIENT_ATTRIBUTES_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
