CREATE TABLE [dbo].[BC_BNK_LIMITS]
(
[BC_CLIENT_ID] [int] NOT NULL,
[LIMIT_TYPE] [tinyint] NOT NULL,
[LIMIT_PERIOD] [tinyint] NOT NULL,
[LIMIT_VALUE] [dbo].[TAMOUNT] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_BNK_LIMITS] WITH NOCHECK ADD CONSTRAINT [CK_BC_BNK_LIMITS_2] CHECK (([LIMIT_PERIOD]>=(0) AND [LIMIT_PERIOD]<=(6)))
GO
ALTER TABLE [dbo].[BC_BNK_LIMITS] WITH NOCHECK ADD CONSTRAINT [CK_BC_BNK_LIMITS_1] CHECK (([LIMIT_TYPE]=(3) OR [LIMIT_TYPE]=(2) OR [LIMIT_TYPE]=(1)))
GO
CREATE CLUSTERED INDEX [IX_BC_BNK_LIMITS] ON [dbo].[BC_BNK_LIMITS] ([BC_CLIENT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_BNK_LIMITS] ADD CONSTRAINT [FK_BC_BNK_LIMITS_BC_CLIENTS] FOREIGN KEY ([BC_CLIENT_ID]) REFERENCES [dbo].[BC_CLIENTS] ([BC_CLIENT_ID])
GO
