CREATE TABLE [dbo].[LOAN_STATES]
(
[STATE] [tinyint] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[CONST_FUNCTION] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_STATES] ADD CONSTRAINT [PK_LOAN_STATES] PRIMARY KEY CLUSTERED  ([STATE]) ON [PRIMARY]
GO
