CREATE TABLE [dbo].[ACC_USER_DEF_TYPES]
(
[USER_DEF_TYPE] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ICON] [image] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_USER_DEF_TYPES] ADD CONSTRAINT [PK_ACC_USER_DEF_TYPES] PRIMARY KEY CLUSTERED  ([USER_DEF_TYPE]) ON [PRIMARY]
GO
