CREATE TABLE [dbo].[SWIFT_CLIENT_REG]
(
[CLIENT_NO] [int] NOT NULL,
[STATE] [smallint] NOT NULL CONSTRAINT [DF_SWIFT_CLIENT_REG_STATE] DEFAULT ((0)),
[RECEIVER_INSTITUTION] [dbo].[TINTBANKCODE] NOT NULL,
[RECEIVER_INSTITUTION_NAME] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_CLIENT_REG] ADD CONSTRAINT [PK_SWIFT_CLIENT_REG] PRIMARY KEY CLUSTERED  ([CLIENT_NO]) ON [PRIMARY]
GO
