CREATE TABLE [dbo].[LOAN_COBORROWERS]
(
[LOAN_ID] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COBORROWERS] ADD CONSTRAINT [PK_LOAN_COBORROWERS] PRIMARY KEY CLUSTERED  ([LOAN_ID], [CLIENT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COBORROWERS] ADD CONSTRAINT [FK_LOAN_COBORROWERS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOAN_COBORROWERS] ADD CONSTRAINT [FK_LOAN_COBORROWERS_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
