CREATE TABLE [dbo].[CHK_BOOK_DET_CHANGES]
(
[CHK_ID] [int] NOT NULL,
[CHK_NUM] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DOC_REC_ID] [int] NULL,
[DT_TM] [smalldatetime] NOT NULL CONSTRAINT [DF_CHK_BOOK_DET_CHANGES_DT_TM] DEFAULT (getdate()),
[COMMENT] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHK_BOOK_DET_CHANGES] ADD CONSTRAINT [PK_CHK_BOOK_DET_CHANGES] PRIMARY KEY CLUSTERED  ([CHK_ID], [CHK_NUM], [REC_ID]) ON [PRIMARY]
GO
