CREATE TABLE [dbo].[USER_SESSIONS]
(
[SESSION_ID] [uniqueidentifier] NOT NULL,
[USER_ID] [int] NOT NULL,
[APP_URI] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[REMOTE_ADDRESS] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[EXPIRE_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_SESSIONS] ADD CONSTRAINT [PK__USER_SESSIONS__38DCC0FD] PRIMARY KEY CLUSTERED  ([SESSION_ID]) ON [PRIMARY]
GO
