CREATE TABLE [dbo].[LOAN_PRODUCT_ACCRUE]
(
[PRODUCT_ID] [int] NOT NULL,
[ACCRUE_TYPE] [tinyint] NOT NULL,
[ACCRUE] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCRUE] ADD CONSTRAINT [PK_LOAN_PRODUCT_ACCRUE] PRIMARY KEY CLUSTERED  ([PRODUCT_ID], [ACCRUE_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCRUE] ADD CONSTRAINT [FK_LOAN_PRODUCT_ACCRUE_LOAN_ACCRUE_TYPES] FOREIGN KEY ([ACCRUE_TYPE]) REFERENCES [dbo].[LOAN_ACCRUE_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_ACCRUE] ADD CONSTRAINT [FK_LOAN_PRODUCT_ACCRUE_LOAN_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([PRODUCT_ID]) ON DELETE CASCADE
GO
