CREATE TABLE [dbo].[CROSS_RATES_KAS_ARC]
(
[DT_TM] [datetime] NOT NULL CONSTRAINT [DF__CROSS_RATES_KAS_DT_TM] DEFAULT (getdate()),
[ISO1] [dbo].[TISO] NOT NULL,
[ISO2] [dbo].[TISO] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT_BUY] [dbo].[TAMOUNT] NOT NULL,
[AMOUNT_SELL] [dbo].[TAMOUNT] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CROSS_RATES_KAS_ARC] ADD CONSTRAINT [PK_CROSS_RATES_KAS_ARC] PRIMARY KEY CLUSTERED  ([DT_TM], [ISO1], [ISO2]) ON [PRIMARY]
GO
