CREATE TABLE [dbo].[PROCASH_USERS]
(
[USER_ID] [int] NOT NULL,
[SAFE_NR] [varchar] (8) COLLATE Latin1_General_BIN NOT NULL,
[DESK_CODE] [int] NOT NULL CONSTRAINT [DF_PROCASH_USERS_DESK_CODE] DEFAULT ((0)),
[P_RIGHT] [char] (1) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_PROCASH_USERS_P_RIGHT] DEFAULT ('1')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCASH_USERS] ADD CONSTRAINT [IX_PROCASH_USERS] UNIQUE NONCLUSTERED  ([USER_ID], [SAFE_NR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCASH_USERS] ADD CONSTRAINT [FK_PROCASH_USERS_PROCASH] FOREIGN KEY ([SAFE_NR]) REFERENCES [dbo].[PROCASH] ([SAFE_NR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PROCASH_USERS] ADD CONSTRAINT [FK_PROCASH_USERS_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
