CREATE TABLE [dbo].[LOAN_ACCRUE]
(
[LOAN_ID] [int] NOT NULL,
[ACCRUE_TYPE] [tinyint] NOT NULL,
[ACCRUE] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCRUE] ADD CONSTRAINT [PK_LOAN_ACCRUE] PRIMARY KEY CLUSTERED  ([LOAN_ID], [ACCRUE_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ACCRUE] ADD CONSTRAINT [FK_LOAN_ACCRUE_LOAN_ACCRUE_TYPES] FOREIGN KEY ([ACCRUE_TYPE]) REFERENCES [dbo].[LOAN_ACCRUE_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_ACCRUE] ADD CONSTRAINT [FK_LOAN_ACCRUE_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
