CREATE TABLE [dbo].[CLIENT_NOTES]
(
[CLIENT_NO] [int] NOT NULL,
[DATE] [smalldatetime] NOT NULL,
[NOTE_TYPE] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[COMMENT] [varchar] (250) COLLATE Latin1_General_BIN NOT NULL,
[REC_STATE] [tinyint] NOT NULL CONSTRAINT [DF_CLIENT_NOTES_REC_STATE] DEFAULT ((0)),
[USER_ID2] [int] NULL,
[COMMENT2] [varchar] (250) COLLATE Latin1_General_BIN NULL,
[DATE2] [smalldatetime] NULL,
[PROD_ID] [int] NULL,
[FOREIGN_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_NOTES] ADD CONSTRAINT [CK_CLIENT_NOTES] CHECK (([NOTE_TYPE]>=(0) AND [NOTE_TYPE]<=(4)))
GO
ALTER TABLE [dbo].[CLIENT_NOTES] ADD CONSTRAINT [PK_CLIENT_NOTES] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [DATE], [NOTE_TYPE], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_NOTES] ADD CONSTRAINT [FK_CLIENT_NOTES_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
