CREATE TABLE [dbo].[STD_OP_CODES]
(
[OP_CODE] [varchar] (5) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF_STD_OP_CODES_FLAGS] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE TRIGGER [dbo].[STD_OP_CODES_TRIGGER] ON [dbo].[STD_OP_CODES]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_OP_CODES'

GO
ALTER TABLE [dbo].[STD_OP_CODES] ADD CONSTRAINT [PK_STD_OP_CODES] PRIMARY KEY CLUSTERED  ([DESCRIP]) ON [PRIMARY]
GO
