CREATE TABLE [dbo].[INCASSO_OPS_ARC]
(
[INCASSO_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[OP_TYPE] [int] NULL,
[DATE_TIME] [smalldatetime] NOT NULL,
[USER_ID] [int] NULL,
[REC_STATE] [tinyint] NOT NULL,
[AMOUNT] [money] NULL,
[DOC_NUM] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DOC_DATE] [smalldatetime] NULL,
[EXTRA_DATE] [smalldatetime] NULL,
[EXTRA_REC_ID] [int] NULL,
[OLD_REC_STATE] [tinyint] NOT NULL CONSTRAINT [DF_INCASSO_OPS_ARC_OLD_REC_STATE] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCASSO_OPS_ARC] ADD CONSTRAINT [PK_INCASSO_OPS_ARC] PRIMARY KEY CLUSTERED  ([INCASSO_ID], [REC_ID]) ON [PRIMARY]
GO
