CREATE TABLE [dbo].[WBC_UFC_ERRORS]
(
[ERROR_CODE] [char] (3) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WBC_UFC_ERRORS] ADD CONSTRAINT [PK_WBC_UFC_ERRORS] PRIMARY KEY CLUSTERED  ([ERROR_CODE]) ON [PRIMARY]
GO
