CREATE TABLE [dbo].[LOAN_DATA]
(
[LOAN_ID] [int] NOT NULL,
[DESCRIP] [varchar] (8000) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DATA] ADD CONSTRAINT [PK_LOAN_DATA] PRIMARY KEY CLUSTERED  ([LOAN_ID]) ON [PRIMARY]
GO
