CREATE TABLE [dbo].[VAL_RATES_2016]
(
[ISO] [dbo].[TISO] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[VAL_RATES_2016] ADD CONSTRAINT [CK_VAL_RATES_2016] CHECK (([DT]>='20160101' AND [DT]<'20170101'))
GO
ALTER TABLE [dbo].[VAL_RATES_2016] ADD CONSTRAINT [PK_VAL_RATES_2016] PRIMARY KEY CLUSTERED  ([ISO], [DT]) ON [ARCHIVE]
GO
