CREATE TABLE [dbo].[CLIENT_EXTENSIONS2]
(
[CLIENT_NO] [int] NOT NULL,
[TARIFF_PLAN_ID] [int] NOT NULL,
[ACC_ID] [int] NULL,
[IS_STANDART] [bit] NOT NULL,
[AUTO_OVERDRAFT] [bit] NOT NULL CONSTRAINT [DF_CLIENT_EXTENSIONS2_AUTO_OVERDRAFT] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_EXTENSIONS2] ADD CONSTRAINT [PK_CLIENT_EXTENSIONS2] PRIMARY KEY CLUSTERED  ([CLIENT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_EXTENSIONS2] ADD CONSTRAINT [FK_CLIENT_EXTENSIONS2_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE
GO
