CREATE TABLE [dbo].[PLANLIST_ALT]
(
[BAL_ACC] [dbo].[TBAL_ACC] NOT NULL,
[ACT_PAS] [tinyint] NOT NULL,
[CLASS_TYPE] [tinyint] NOT NULL,
[VAL_TYPE] [tinyint] NOT NULL,
[REC_STATE] [tinyint] NULL CONSTRAINT [DF_PLANLIST_ALT_REC_STATE] DEFAULT ((0)),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ACC_TYPE] [tinyint] NOT NULL CONSTRAINT [DF_PLANLIST_ALT_ACC_TYPE] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[PLANLIST_ALT_TRIGGER] ON [dbo].[PLANLIST_ALT]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_PLANLIST_ALT'

GO
ALTER TABLE [dbo].[PLANLIST_ALT] ADD CONSTRAINT [CK_PLANLIST_ALT_4] CHECK (([ACC_TYPE]=(2) OR [ACC_TYPE]=(1) OR [ACC_TYPE]=(0)))
GO
ALTER TABLE [dbo].[PLANLIST_ALT] WITH NOCHECK ADD CONSTRAINT [CK_PLANLIST_ALT_1] CHECK (([ACT_PAS]>=(0) AND [ACT_PAS]<=(3)))
GO
ALTER TABLE [dbo].[PLANLIST_ALT] WITH NOCHECK ADD CONSTRAINT [CK_PLANLIST_ALT_3] CHECK (([VAL_TYPE]=(4) OR [VAL_TYPE]=(2) OR [VAL_TYPE]=(1)))
GO
ALTER TABLE [dbo].[PLANLIST_ALT] ADD CONSTRAINT [PK_PLANLIST_ALT] PRIMARY KEY CLUSTERED  ([BAL_ACC]) ON [PRIMARY]
GO
