CREATE TABLE [dbo].[PAYMENT_CHANNELS]
(
[CHANNEL_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[OP_CODE] [varchar] (5) COLLATE Latin1_General_BIN NOT NULL,
[OP_CODE_TARIFF] [varchar] (5) COLLATE Latin1_General_BIN NOT NULL,
[CHANNEL_PERCENT] [int] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_CHANEL_PERCENT] DEFAULT ((0)),
[IS_CASH] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_IS_CASH] DEFAULT ((0)),
[REC_STATE] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_REC_STATE] DEFAULT ((0)),
[PLAT_INNER] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_PLAT_INNER] DEFAULT ((0)),
[PLAT_OUTER] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_PLAT_OUTER] DEFAULT ((0)),
[PLAT_OUTER_BRANCH] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_PLAT_OUTER_BRANCH] DEFAULT ((0)),
[TRANSIT] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENT_CHANELS_TRANSIT] DEFAULT ((0)),
[BLOCK_IN_PROCESSING_CENTER] [bit] NOT NULL CONSTRAINT [DF_PAYMENT_CHANNELS_BLOCK_IN_PROCESSING_CENTER] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENT_CHANNELS] ADD CONSTRAINT [PK_PAYMENT_CHANELS] PRIMARY KEY CLUSTERED  ([CHANNEL_ID]) ON [PRIMARY]
GO
