CREATE TABLE [dbo].[ACCOUNTS_CLASSIF]
(
[ACC_ID] [int] NOT NULL,
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_CLASSIF] ADD CONSTRAINT [PK_ACCOUNTS_CLASSIF] PRIMARY KEY CLUSTERED  ([ACC_ID], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_CLASSIF] ON [dbo].[ACCOUNTS_CLASSIF] ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_CLASSIF] ADD CONSTRAINT [FK_ACCOUNTS_CLASSIF_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS_CLASSIF] ADD CONSTRAINT [FK_ACCOUNTS_CLASSIF_CLASIF] FOREIGN KEY ([ID]) REFERENCES [dbo].[CLASSIF] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
