CREATE TABLE [dbo].[B2000_LOG]
(
[USER_ID] [int] NOT NULL,
[ACTION_CODE] [tinyint] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[APP_SRV_ID] [smallint] NOT NULL,
[DATE_AND_TIME] [smalldatetime] NOT NULL CONSTRAINT [DF_BANK2000_LOG_WHEN] DEFAULT (getdate()),
[REC_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[B2000_LOG] ADD CONSTRAINT [PK_B2000_LOG] PRIMARY KEY NONCLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
