CREATE TABLE [dbo].[DOC_DETAILS_CONV]
(
[DOC_REC_ID] [int] NOT NULL,
[RATE_ITEMS] [int] NOT NULL CONSTRAINT [DF_DOC_DETAILS_CONV_RATE_ITEMS] DEFAULT ((1)),
[RATE_AMOUNT] [dbo].[TAMOUNT] NOT NULL,
[RATE_REVERSE] [bit] NOT NULL CONSTRAINT [DF_DOC_DETAILS_CONV_RATE_REVERSE] DEFAULT ((0)),
[RATE_FLAGS] [int] NOT NULL CONSTRAINT [DF_DOC_DETAILS_CONV_RATE_FLAGS] DEFAULT ((0)),
[LAT_DESCRIP] [bit] NOT NULL CONSTRAINT [DF_DOC_DETAILS_CONV_LAT_DESCRIP] DEFAULT ((0)),
[TARIFF_KIND] [bit] NOT NULL CONSTRAINT [DF_DOC_DETAILS_CONV_TARIFF_KIND] DEFAULT ((0)),
[CLIENT_NO] [int] NULL,
[RATE_CLIENT_NO] [int] NULL,
[AMOUNT3] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_DETAILS_CONV] ADD CONSTRAINT [PK_DOC_DETAILS_CONV] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_DETAILS_CONV] ADD CONSTRAINT [FK_DOC_DETAILS_CONV_REC_ID_IN_OPS] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [dbo].[OPS_0000] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
