CREATE TABLE [dbo].[CLIENT_RELATIONS]
(
[CLIENT_NO] [int] NOT NULL,
[REL_CLIENT_NO] [int] NOT NULL,
[CLIENT_RELATION_TYPE_ID] [smallint] NOT NULL,
[INT_VALUE] [int] NULL,
[STR_VALUE] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[MONEY_VALUE] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_RELATIONS] ADD CONSTRAINT [PK_CLIENT_RELATIONS] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [REL_CLIENT_NO], [CLIENT_RELATION_TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_CLIENT_RELATIONS_CLIENT_RELATION_TYPES] FOREIGN KEY ([CLIENT_RELATION_TYPE_ID]) REFERENCES [dbo].[CLIENT_RELATION_TYPES] ([CLIENT_RELATION_TYPE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CLIENT_RELATIONS] ADD CONSTRAINT [FK_CLIENT_RELATIONS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
ALTER TABLE [dbo].[CLIENT_RELATIONS] ADD CONSTRAINT [FK_CLIENT_RELATIONS_CLIENTS_REL] FOREIGN KEY ([REL_CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
