CREATE TABLE [dbo].[PAYMENTS_SCHEDULER]
(
[CLIENT_ID] [int] NOT NULL,
[PROVIDER_ID] [int] NOT NULL,
[SERVICE_ALIAS] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ID_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ACC_ID] [int] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_ACC_ID] DEFAULT ((0)),
[ID2_IN_PROVIDER] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[REC_STATE] [smallint] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_REC_STATE] DEFAULT ((0)),
[SUBSCRIBE_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_SUBSCRIBE_AMOUNT] DEFAULT ((0)),
[MAX_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_MAX_AMOUNT] DEFAULT ((0)),
[FILL_AMOUNT] [money] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_FILL_AMOUNT] DEFAULT ((0)),
[PAY_MAX_AMOUNT] [bit] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_PAY_MAX_AMOUNT] DEFAULT ((0)),
[PAY_DAY] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_PAY_DAY] DEFAULT ((255)),
[PAY_PART] [bit] NULL,
[PRIORITY_ORDER] [tinyint] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_PRIORITY_ORDER] DEFAULT ((1)),
[START_DATE] [smalldatetime] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_START_DATE] DEFAULT (CONVERT([smalldatetime],floor(CONVERT([real],getdate(),(0))-(1)),(0))),
[END_DATE] [smalldatetime] NULL,
[LAST_PAY_DATE] [smalldatetime] NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_LAST_PAY_DAY] DEFAULT (CONVERT([smalldatetime],floor(CONVERT([real],getdate(),(0))-(1)),(0))),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[CCY] [char] (3) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_PAYMENTS_SCHEDULER_CCY] DEFAULT ('GEL')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENTS_SCHEDULER] ADD CONSTRAINT [PK_PAYMENTS_SCHEDULER] PRIMARY KEY CLUSTERED  ([CLIENT_ID], [PROVIDER_ID], [SERVICE_ALIAS], [ID_IN_PROVIDER]) ON [PRIMARY]
GO
