CREATE TABLE [dbo].[LOAN_CLASSIFED]
(
[LOAN_ID] [int] NOT NULL,
[ID] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLASSIFED] ADD CONSTRAINT [PK_LOAN_CLASSIFED] PRIMARY KEY CLUSTERED  ([LOAN_ID], [ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLASSIFED] ADD CONSTRAINT [FK_LOAN_CLASSIFED_LOAN_CLASSIFS] FOREIGN KEY ([ID]) REFERENCES [dbo].[LOAN_CLASSIFS] ([ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOAN_CLASSIFED] ADD CONSTRAINT [FK_LOAN_CLASSIFED_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
