CREATE TABLE [dbo].[LOAN_INSURANCE_COMPANIES]
(
[COMPANY_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (400) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (400) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSURANCE_COMPANIES] ADD CONSTRAINT [PK_LOAN_INSURANCE_COMPANIES] PRIMARY KEY CLUSTERED  ([COMPANY_ID]) ON [PRIMARY]
GO
