CREATE TABLE [dbo].[CLI_CHANGES]
(
[CLIENT_NO] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL CONSTRAINT [DF_CLI_CHANGES_TIME_OF_CH] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLI_CHANGES] ADD CONSTRAINT [PK_CLI_CHANGES] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [REC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CLI_CHANGES] ON [dbo].[CLI_CHANGES] ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLI_CHANGES] WITH NOCHECK ADD CONSTRAINT [FK_CLI_CHANGES_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[CLI_CHANGES] ADD CONSTRAINT [FK_CLI_CHANGES_CLIENT_NO] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
