CREATE TABLE [dbo].[DEPO_ANNULMENT_METHOD_DETAILS]
(
[METHOD_ID] [int] NOT NULL,
[DAYS] [smallint] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[PERC] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_ANNULMENT_METHOD_DETAILS] ADD CONSTRAINT [PK_DEPO_ANNULMENT_METHOD_DETAILS] PRIMARY KEY CLUSTERED  ([METHOD_ID], [DAYS], [ISO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_ANNULMENT_METHOD_DETAILS] ADD CONSTRAINT [FK_DEPO_ANNULMENT_METHOD_DETAILS_DEPO_ANNULMENT_METHODS] FOREIGN KEY ([METHOD_ID]) REFERENCES [dbo].[DEPO_ANNULMENT_METHODS] ([METHOD_ID]) ON DELETE CASCADE
GO
