CREATE TABLE [dbo].[LOAN_INSTALLMENT_EVENTS]
(
[ITEM_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INSTALLMENT_EVENTS] ADD CONSTRAINT [PK_LOAN_INSTALLMENT_EVENTS] PRIMARY KEY CLUSTERED  ([ITEM_ID]) ON [PRIMARY]
GO
