CREATE TABLE [dbo].[NBG_ACC_TRANSLATOR]
(
[ACCOUNT_EXT] [dbo].[TACCOUNT] NOT NULL,
[ACCOUNT_INT] [dbo].[TACCOUNT] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NBG_ACC_TRANSLATOR] ADD CONSTRAINT [PK_NBG_ACC_TRANSLATOR] PRIMARY KEY CLUSTERED  ([ACCOUNT_EXT]) ON [PRIMARY]
GO
