CREATE TABLE [dbo].[SALDOS_2016]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[DBO] [money] NOT NULL,
[CRO] [money] NOT NULL,
[SALDO] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[SALDOS_2016] ADD CONSTRAINT [CK_SALDOS_2016] CHECK (([DT]>='20160101' AND [DT]<'20170101'))
GO
ALTER TABLE [dbo].[SALDOS_2016] ADD CONSTRAINT [PK_SALDOS_2016] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT]) ON [ARCHIVE]
GO
