CREATE TABLE [dbo].[SO_TASK_DEBIT_ACCOUNTS]
(
[TASK_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[PRIORITY] [int] NULL CONSTRAINT [DF_SO_TASK_DEBIT_ACCOUNTS_PRIORITY] DEFAULT ((0)),
[AMOUNT] [money] NULL,
[IS_PERCENT] [bit] NULL,
[EQU_ISO] [char] (3) COLLATE Latin1_General_BIN NULL,
[IS_MASTER_ACC] [bit] NULL,
[IS_HELPER_ACC] [bit] NOT NULL CONSTRAINT [DF_SO_TASK_DEBIT_ACCOUNTS_IS_HELPER_ACC] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_TASK_DEBIT_ACCOUNTS] ADD CONSTRAINT [FK_SO_TASK_DEBIT_ACCOUNTS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID])
GO
ALTER TABLE [dbo].[SO_TASK_DEBIT_ACCOUNTS] ADD CONSTRAINT [FK_SO_TASK_DEBIT_ACCOUNTS_SO_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[SO_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
