CREATE TABLE [dbo].[ACCOUNTS_DEB_PERC_ARC]
(
[REC_ID] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NULL,
[MOVE_COUNT] [smallint] NULL,
[MOVE_COUNT_TYPE] [tinyint] NOT NULL,
[CALC_TYPE] [tinyint] NOT NULL,
[FORMULA] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[CLIENT_ACCOUNT] [int] NULL,
[PERC_CLIENT_ACCOUNT] [int] NULL,
[PERC_BANK_ACCOUNT] [int] NOT NULL,
[DAYS_IN_YEAR] [smallint] NOT NULL,
[CALC_AMOUNT] [money] NULL,
[TOTAL_CALC_AMOUNT] [money] NULL,
[TOTAL_PAYED_AMOUNT] [money] NULL,
[LAST_CALC_DATE] [smalldatetime] NULL,
[LAST_MOVE_DATE] [smalldatetime] NULL,
[PERC_FLAGS] [int] NOT NULL,
[PERC_TYPE] [tinyint] NOT NULL,
[FUNCTION_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_DEB_PERC_ARC] ADD CONSTRAINT [PK_ACCOUNTS_DEB_PERC_ARC] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_DEB_PERC_ARC] ADD CONSTRAINT [FK_ACCOUNTS_DEB_PERC_ARC_ACC_CHANGES] FOREIGN KEY ([REC_ID]) REFERENCES [dbo].[ACC_CHANGES] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
