CREATE TABLE [dbo].[LOAN_CREDIT_LINE_OP_TYPES]
(
[TYPE_ID] [smallint] NOT NULL,
[SELF_EXEC] [bit] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[CONST_FUNCTION] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINE_OP_TYPES] ADD CONSTRAINT [PK_LOAN_CREDIT_LINE_OP_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
