CREATE TABLE [dbo].[LOAN_COLLATERAL_ITEMS]
(
[ITEM_ID] [int] NOT NULL IDENTITY(1, 1),
[COLLATERAL_TYPE] [int] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[INSTALLMENT] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COLLATERAL_ITEMS] ADD CONSTRAINT [PK_LOAN_COLLATERAL_ITEMS] PRIMARY KEY CLUSTERED  ([ITEM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_COLLATERAL_ITEMS] ON [dbo].[LOAN_COLLATERAL_ITEMS] ([COLLATERAL_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COLLATERAL_ITEMS] ADD CONSTRAINT [FK_LOAN_COLLATERAL_ITEMS_LOAN_COLLATERAL_TYPES] FOREIGN KEY ([COLLATERAL_TYPE]) REFERENCES [dbo].[LOAN_COLLATERAL_TYPES] ([TYPE_ID]) ON UPDATE CASCADE
GO
