CREATE TABLE [dbo].[TCD_CASETTES]
(
[CASETTE_SERIAL_ID] [int] NOT NULL,
[BRANCH_ID] [int] NULL,
[TCD_SERIAL_ID] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[CASETTE_CCY] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[CASETTE_DEN] [int] NULL,
[IS_REJECT] [bit] NOT NULL,
[PENDING] [bit] NOT NULL CONSTRAINT [DF_TCD_CASETTES_PENDING] DEFAULT ((0)),
[STATE] [tinyint] NOT NULL CONSTRAINT [DF_TCD_CASETTES_IS_ACTIVE] DEFAULT ((0)),
[CURRENT_TCD_SERIAL_ID] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[CURRENT_CCY] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[CURRENT_DEN] [nchar] (10) COLLATE Latin1_General_BIN NULL,
[CURRENT_COUNT] [int] NULL,
[COLLECTOR_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCD_CASETTES] ADD CONSTRAINT [PK_TCD_CASETTES] PRIMARY KEY CLUSTERED  ([CASETTE_SERIAL_ID]) ON [PRIMARY]
GO
