CREATE TABLE [dbo].[ACCOUNTS]
(
[ACC_ID] [int] NOT NULL IDENTITY(1, 1),
[BRANCH_ID] [int] NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[DEPT_NO] [int] NULL,
[BAL_ACC_ALT] [dbo].[TBAL_ACC] NOT NULL,
[ACT_PAS] [tinyint] NOT NULL,
[IS_OFFBALANCE] AS (CONVERT([bit],case  when [BAL_ACC_ALT]<(1000) then (1) else (0) end,(0))),
[REC_STATE] [tinyint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ACC_TYPE] [tinyint] NOT NULL,
[ACC_SUBTYPE] [int] NULL,
[CLIENT_NO] [int] NULL,
[DATE_OPEN] [smalldatetime] NOT NULL,
[PERIOD] [smalldatetime] NULL,
[DATE_CLOSE] [smalldatetime] NULL,
[TARIFF] [smallint] NULL,
[PRODUCT_NO] [int] NULL,
[MIN_AMOUNT] [money] NULL,
[MIN_AMOUNT_NEW] [money] NULL,
[MIN_AMOUNT_CHECK_DATE] [smalldatetime] NULL,
[BLOCKED_AMOUNT] [money] NULL,
[BLOCK_CHECK_DATE] [smalldatetime] NULL,
[PROF_LOSS_ACC] [dbo].[TACCOUNT] NULL,
[FLAGS] [int] NOT NULL CONSTRAINT [DF_ACCOUNTS_FLAGS] DEFAULT ((0)),
[REMARK] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[CODE_PHRASE] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[RESPONSIBLE_USER_ID] [int] NULL,
[BAL_ACC_OLD] [dbo].[TBAL_ACC] NULL,
[IS_CONTROL] [bit] NOT NULL CONSTRAINT [DF_ACCOUNTS_IS_CONTROL] DEFAULT ((0)),
[IS_INCASSO] [bit] NOT NULL CONSTRAINT [DF_ACCOUNTS_IS_INCASSO] DEFAULT ((0)),
[UID] [int] NOT NULL CONSTRAINT [DF_ACCOUNTS_UID] DEFAULT ((0)),
[USER_DEF_TYPE] [int] NULL,
[BAL_ACC2] [dbo].[TBAL_ACC] NULL,
[BAL_ACC3] [dbo].[TBAL_ACC] NULL,
[MIN_AMOUNT_CHECK_DATE_NEW] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [CK_ACCOUNTS_ACTPAS] CHECK (([ACT_PAS]>=(0) AND [ACT_PAS]<=(2)))
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [CK_ACCOUNTS_REC_STATE] CHECK (([REC_STATE]=(128) OR [REC_STATE]=(64) OR [REC_STATE]=(32) OR [REC_STATE]=(16) OR [REC_STATE]=(8) OR [REC_STATE]=(4) OR [REC_STATE]=(2) OR [REC_STATE]=(1)))
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [PK_ACCOUNTS] PRIMARY KEY CLUSTERED  ([ACC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ACCOUNTS_ACC_ISO_BRANCH] ON [dbo].[ACCOUNTS] ([ACCOUNT], [ISO], [BRANCH_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ACCOUNTS_ACC_ISO_DEPT] ON [dbo].[ACCOUNTS] ([ACCOUNT], [ISO], [DEPT_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_BAL_ACC] ON [dbo].[ACCOUNTS] ([BAL_ACC_ALT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_BRANCH_ID] ON [dbo].[ACCOUNTS] ([BRANCH_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_CLIID] ON [dbo].[ACCOUNTS] ([CLIENT_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_DEPT_NO] ON [dbo].[ACCOUNTS] ([DEPT_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_ACC_PRODUCTS] FOREIGN KEY ([PRODUCT_NO]) REFERENCES [dbo].[ACC_PRODUCTS] ([PRODUCT_NO]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_ACC_TYPES] FOREIGN KEY ([ACC_TYPE]) REFERENCES [dbo].[ACC_TYPES] ([ACC_TYPE]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_BAL_ACC] FOREIGN KEY ([BAL_ACC_ALT]) REFERENCES [dbo].[PLANLIST_ALT] ([BAL_ACC])
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_DEPTS_BRANCH_ID] FOREIGN KEY ([BRANCH_ID]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_DEPTS_DEPT_NO] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_TARIFF] FOREIGN KEY ([TARIFF]) REFERENCES [dbo].[TARIFF] ([TARIFF]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_USERS] FOREIGN KEY ([RESPONSIBLE_USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO]) ON UPDATE CASCADE
GO
