CREATE TABLE [dbo].[PLUGINS]
(
[TASK_ID] [smallint] NOT NULL,
[MENUNAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[UNIT] [text] COLLATE Latin1_General_BIN NOT NULL,
[MENU] [smallint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[PLUGINS_TRIGGER] ON [dbo].[PLUGINS]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_PLUGINS'


GO
ALTER TABLE [dbo].[PLUGINS] ADD CONSTRAINT [PK_PLUGINS] PRIMARY KEY CLUSTERED  ([TASK_ID], [MENUNAME]) ON [PRIMARY]
GO
