CREATE TABLE [dbo].[TCD_REPLY_MSG]
(
[MSG_ID] [int] NOT NULL,
[CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[RECOMENDED_ACTION] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[TYPE] [varchar] (1) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCD_REPLY_MSG] ADD CONSTRAINT [PK_TCD_REPLY_MSG] PRIMARY KEY CLUSTERED  ([MSG_ID]) ON [PRIMARY]
GO
