CREATE TABLE [dbo].[TARIFF]
(
[TARIFF] [smallint] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[FORMULA] [text] COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TARIFF] ADD CONSTRAINT [PK_TARIFF] PRIMARY KEY CLUSTERED  ([TARIFF]) ON [PRIMARY]
GO
