CREATE TABLE [dbo].[BAL_0000]
(
[DT] [smalldatetime] NOT NULL,
[BRANCH_ID] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[BAL_ACC] [dbo].[TBAL_ACC] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[DBO] [money] NOT NULL,
[DBO_EQU] [money] NOT NULL,
[CRO] [money] NOT NULL,
[CRO_EQU] [money] NOT NULL,
[DBS] [money] NOT NULL,
[DBS_EQU] [money] NOT NULL,
[CRS] [money] NOT NULL,
[CRS_EQU] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAL_0000] ADD CONSTRAINT [CK_BAL_0000] CHECK (([DT]>='20071121'))
GO
ALTER TABLE [dbo].[BAL_0000] ADD CONSTRAINT [PK_BAL_0000] PRIMARY KEY CLUSTERED  ([DT], [BRANCH_ID], [DEPT_NO], [BAL_ACC], [ISO]) ON [PRIMARY]
GO
