CREATE TABLE [dbo].[LOAN_CREDIT_LINE_ACCOUNTS]
(
[CREDIT_LINE_ID] [int] NOT NULL,
[ACCOUNT_TYPE] [int] NOT NULL,
[ACC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINE_ACCOUNTS] ADD CONSTRAINT [PK_LOAN_CREDIT_LINE_ACCOUNTS] PRIMARY KEY CLUSTERED  ([CREDIT_LINE_ID], [ACCOUNT_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINE_ACCOUNTS] ADD CONSTRAINT [FK_LOAN_CREDIT_LINE_ACCOUNTS_LOAN_ACCOUNT_TYPES] FOREIGN KEY ([ACCOUNT_TYPE]) REFERENCES [dbo].[LOAN_ACCOUNT_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINE_ACCOUNTS] ADD CONSTRAINT [FK_LOAN_CREDIT_LINE_ACCOUNTS_LOAN_CREDIT_LINES] FOREIGN KEY ([CREDIT_LINE_ID]) REFERENCES [dbo].[LOAN_CREDIT_LINES] ([CREDIT_LINE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
