CREATE TABLE [dbo].[CASHING_LIMIT]
(
[ISO] [dbo].[TISO] NOT NULL,
[ISO_EQU] [dbo].[TISO] NULL,
[AMOUNT] [dbo].[TAMOUNT] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHING_LIMIT] ADD CONSTRAINT [PK_CASHING_LIMIT] PRIMARY KEY CLUSTERED  ([ISO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASHING_LIMIT] ADD CONSTRAINT [FK_CASHING_LIMIT_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
ALTER TABLE [dbo].[CASHING_LIMIT] ADD CONSTRAINT [FK_CASHING_LIMIT_VAL_CODES1] FOREIGN KEY ([ISO_EQU]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
