CREATE TABLE [dbo].[LOANS]
(
[LOAN_ID] [int] NOT NULL IDENTITY(1, 1),
[ROW_VERSION] [int] NOT NULL CONSTRAINT [DF_LOANS_ROW_VERSION] DEFAULT ((1)),
[BRANCH_ID] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[AUTHORIZE_LEVEL] [tinyint] NOT NULL,
[STATE] [tinyint] NOT NULL,
[CLIENT_NO] [int] NOT NULL,
[CLIENT_SUBTYPE2] [int] NULL,
[CREDIT_LINE_ID] [int] NULL,
[PRODUCT_ID] [int] NOT NULL,
[AGREEMENT_NO] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[REG_DATE] [smalldatetime] NOT NULL,
[LOAN_TYPE] [int] NOT NULL,
[DISBURSE_TYPE] [int] NOT NULL,
[ENSURE_TYPE] [int] NOT NULL,
[INSTALLMENT] [bit] NOT NULL,
[EVENT_INSTALLMENT] [bit] NULL,
[RESTRUCTURED] [int] NOT NULL CONSTRAINT [DF_LOANS_RESTRUCTURED] DEFAULT ((0)),
[PROLONGED] [int] NOT NULL CONSTRAINT [DF_LOANS_PROLONGED] DEFAULT ((0)),
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [money] NOT NULL,
[DISBURSE_AMOUNT] [money] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[PERIOD] [int] NOT NULL,
[END_DATE] [smalldatetime] NOT NULL,
[INTRATE] [money] NOT NULL,
[PENALTY_INTRATE] [dbo].[TPERCENT] NOT NULL,
[PREPAYMENT_INTRATE] [dbo].[TPERCENT] NOT NULL,
[PREPAYMENT_STEP] [int] NOT NULL,
[NOTUSED_INTRATE] [dbo].[TPERCENT] NOT NULL,
[ADMIN_INTRATE] [dbo].[TPERCENT] NOT NULL,
[ADMIN_FEE] [money] NOT NULL,
[RISK_TYPE] [int] NOT NULL,
[RISK_PERC_RATE_1] [money] NOT NULL,
[RISK_PERC_RATE_2] [money] NOT NULL,
[RISK_PERC_RATE_3] [money] NOT NULL,
[RISK_PERC_RATE_4] [money] NOT NULL,
[RISK_PERC_RATE_5] [money] NOT NULL,
[WRITEOFF_DATE] [smalldatetime] NULL,
[CALLOFF_DATE] [smalldatetime] NULL,
[INTEREST_FLAGS] [int] NOT NULL,
[PENALTY_FLAGS] [int] NOT NULL,
[PREPAYMENT_FLAGS] [int] NOT NULL,
[PAYMENT_INTERVAL_TYPE] [int] NOT NULL,
[SCHEDULE_TYPE] [int] NOT NULL,
[PAYMENT_DAY] [tinyint] NOT NULL,
[RESERVE_MAX_CATEGORY] [bit] NOT NULL,
[INSTALLMENT_PERCENT] [money] NULL,
[GRACE_STEPS] [tinyint] NULL,
[GRACE_TYPE] [bit] NULL,
[BASIS] [int] NOT NULL,
[RESPONSIBLE_USER_ID] [int] NOT NULL,
[CORESPONSIBLE_USER_ID] [int] NOT NULL,
[PURPOSE_TYPE] [int] NOT NULL,
[BAL_ACC] [dbo].[TBAL_ACC] NOT NULL,
[GROUP_ID] [int] NULL,
[CLIENT_ACCOUNT] [int] NULL,
[LINKED_CCY] [dbo].[TISO] NULL,
[INDEXED_RATE] [money] NULL,
[INSURANCE_RATE] [money] NULL,
[SERVICE_FEE_RATE] [money] NULL,
[SERVICE_FEE] [money] NULL,
[MAIN_COLLATERAL_LIST] [varchar] (1000) COLLATE Latin1_General_BIN NULL,
[PMT] [money] NULL,
[GRACE_FINISH_DATE] [smalldatetime] NULL,
[CLOSE_DATE] [smalldatetime] NULL,
[GUARANTEE] [bit] NOT NULL CONSTRAINT [DF_LOANS_GUARANTEE] DEFAULT ((0)),
[INTERNAT_GUARANTEE] [bit] NOT NULL CONSTRAINT [DF_LOANS_INTERNAT_GUARANTEE] DEFAULT ((0)),
[IMMEDIATE_FEEING] [bit] NOT NULL CONSTRAINT [DF_LOANS_IMMEDIATE_FEEING] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [CK_LOANS_AUTHORIZE_LEVEL] CHECK (([AUTHORIZE_LEVEL]=(20) OR [AUTHORIZE_LEVEL]=(10) OR [AUTHORIZE_LEVEL]=(0)))
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [CK_LOANS_DISBURSE_AMOUNT] CHECK (([DISBURSE_AMOUNT]<=[AMOUNT]))
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [CK_LOANS_INSTALLMENT] CHECK (([INSTALLMENT]=(0) AND [EVENT_INSTALLMENT] IS NULL OR [INSTALLMENT]=(1) AND [EVENT_INSTALLMENT] IS NOT NULL))
GO
ALTER TABLE [dbo].[LOANS] ADD CONSTRAINT [PK_LOANS] PRIMARY KEY CLUSTERED  ([LOAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_AGREEMENT_NO] ON [dbo].[LOANS] ([AGREEMENT_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_BRANCH_NO] ON [dbo].[LOANS] ([BRANCH_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_CLIENT_NO] ON [dbo].[LOANS] ([CLIENT_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_DEPT_NO] ON [dbo].[LOANS] ([DEPT_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_ISO] ON [dbo].[LOANS] ([ISO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_PRODUCT_ID] ON [dbo].[LOANS] ([PRODUCT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANS_RISK_TYPE] ON [dbo].[LOANS] ([RISK_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_DEPTS_BRANCH_ID] FOREIGN KEY ([BRANCH_ID]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_DEPTS_DEPT_NO] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_CLIENT_SUBTYPES2] FOREIGN KEY ([CLIENT_SUBTYPE2]) REFERENCES [dbo].[LOAN_CLIENT_SUBTYPES2] ([CLIENT_SUBTYPE2])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_DISBURSE_TYPES] FOREIGN KEY ([DISBURSE_TYPE]) REFERENCES [dbo].[LOAN_DISBURSE_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_PAYMENT_INTERVALS] FOREIGN KEY ([PAYMENT_INTERVAL_TYPE]) REFERENCES [dbo].[LOAN_PAYMENT_INTERVALS] ([TYPE_ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([PRODUCT_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_PURPOSE_TYPES] FOREIGN KEY ([PURPOSE_TYPE]) REFERENCES [dbo].[LOAN_PURPOSE_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_RISK_TYPES] FOREIGN KEY ([RISK_TYPE]) REFERENCES [dbo].[LOAN_RISK_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_SCHEDULE_TYPES] FOREIGN KEY ([SCHEDULE_TYPE]) REFERENCES [dbo].[LOAN_SCHEDULE_TYPES] ([SCHEDULE_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_STATES] FOREIGN KEY ([STATE]) REFERENCES [dbo].[LOAN_STATES] ([STATE])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_LOAN_TYPES] FOREIGN KEY ([LOAN_TYPE]) REFERENCES [dbo].[LOAN_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_PLANLIST_ALT] FOREIGN KEY ([BAL_ACC]) REFERENCES [dbo].[PLANLIST_ALT] ([BAL_ACC])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_USERS_CORESPONSIBLE_USER_ID] FOREIGN KEY ([CORESPONSIBLE_USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[LOANS] WITH NOCHECK ADD CONSTRAINT [FK_LOANS_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
