CREATE TABLE [dbo].[TASKS2]
(
[TASK_ID] [tinyint] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASKS2] ADD CONSTRAINT [PK_TASKS2] PRIMARY KEY CLUSTERED  ([TASK_ID]) ON [PRIMARY]
GO
