CREATE TABLE [dbo].[LOAN_DETAIL_LATE]
(
[LOAN_ID] [int] NOT NULL,
[LATE_DATE] [smalldatetime] NOT NULL,
[LATE_OP_ID] [int] NOT NULL,
[LATE_PRINCIPAL] [money] NULL,
[LATE_PERCENT] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DETAIL_LATE] ADD CONSTRAINT [PK_LOAN_DETAIL_LATE] PRIMARY KEY CLUSTERED  ([LOAN_ID], [LATE_DATE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_LOAN_DETAIL_LATE] ON [dbo].[LOAN_DETAIL_LATE] ([LATE_OP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DETAIL_LATE] ADD CONSTRAINT [FK_LOAN_DETAIL_LATE_LOAN_OPS] FOREIGN KEY ([LATE_OP_ID]) REFERENCES [dbo].[LOAN_OPS] ([OP_ID]) ON DELETE CASCADE
GO
