CREATE TABLE [dbo].[CLIENT_BONUSES]
(
[CLIENT_NO] [int] NOT NULL,
[ID] [int] NOT NULL,
[BONUS_ID] [int] NOT NULL,
[EXECUTED] [bit] NOT NULL CONSTRAINT [DF_CLIENT_BONUSES_EXECUTED] DEFAULT ((0)),
[ADDED_BY] [int] NOT NULL,
[ADDED_AT] [smalldatetime] NOT NULL,
[EXECUTED_BY] [int] NULL,
[EXECUTED_AT] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_BONUSES] ADD CONSTRAINT [PK_CLIENT_BONUSES] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [ID], [BONUS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_BONUSES] ADD CONSTRAINT [FK_CLIENT_BONUSES_BONUSES] FOREIGN KEY ([BONUS_ID]) REFERENCES [dbo].[BONUSES] ([REC_ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CLIENT_BONUSES] ADD CONSTRAINT [FK_CLIENT_BONUSES_USERS] FOREIGN KEY ([ADDED_BY]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[CLIENT_BONUSES] ADD CONSTRAINT [FK_CLIENT_BONUSES_USERS2] FOREIGN KEY ([EXECUTED_BY]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
