CREATE TABLE [dbo].[LOAN_COLLATERAL_ACCOUNTS]
(
[COLLATERAL_ID] [int] NOT NULL,
[COLLATERAL_TYPE] [int] NOT NULL,
[ACC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COLLATERAL_ACCOUNTS] ADD CONSTRAINT [PK_LOAN_COLLATERAL_ACCOUNTS] PRIMARY KEY CLUSTERED  ([COLLATERAL_ID], [COLLATERAL_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COLLATERAL_ACCOUNTS] ADD CONSTRAINT [FK_LOAN_COLLATERAL_ACCOUNTS_LOAN_COLLATERAL_TYPES] FOREIGN KEY ([COLLATERAL_TYPE]) REFERENCES [dbo].[LOAN_COLLATERAL_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_COLLATERAL_ACCOUNTS] ADD CONSTRAINT [FK_LOAN_COLLATERAL_ACCOUNTS_LOAN_COLLATERALS] FOREIGN KEY ([COLLATERAL_ID]) REFERENCES [dbo].[LOAN_COLLATERALS] ([COLLATERAL_ID]) ON DELETE CASCADE
GO
