CREATE TABLE [dbo].[EASY_PENALTIES_2011_OCT]
(
[AGREEMENT_NO] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[SALDO_DEB] [money] NULL,
[SALDO_CRED] [money] NULL,
[LOAN_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EASY_PENALTIES_2011_OCT] ADD CONSTRAINT [PK__EASY_PENALTIES_2__6A865D33] PRIMARY KEY CLUSTERED  ([AGREEMENT_NO]) ON [PRIMARY]
GO
