CREATE TABLE [dbo].[LOAN_STATES_LOG]
(
[LOAN_ID] [int] NOT NULL,
[DATE] [smalldatetime] NOT NULL,
[STATE] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_STATES_LOG] ADD CONSTRAINT [PK_LOAN_STATES_LOG] PRIMARY KEY CLUSTERED  ([LOAN_ID], [DATE]) ON [PRIMARY]
GO
