CREATE TABLE [dbo].[LOAN_PURPOSE_TYPES]
(
[TYPE_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[CODE] [varchar] (15) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PURPOSE_TYPES] ADD CONSTRAINT [PK_LOAN_PURPOSE_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
