CREATE TABLE [dbo].[BC_LIMIT_TEMPLATES]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_LIMIT_TEMPLATES] ADD CONSTRAINT [PK_BC_LIMIT_TEMPLATES] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_LIMIT_TEMPLATES] ADD CONSTRAINT [IX_BC_LIMIT_TEMPLATES] UNIQUE NONCLUSTERED  ([DESCRIP]) ON [PRIMARY]
GO
