CREATE TABLE [dbo].[ACCOUNTS_CRED_PERC_DETAILS]
(
[ACC_ID] [int] NOT NULL,
[DAYS] [smallint] NOT NULL,
[PERC] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_CRED_PERC_DETAILS] ADD CONSTRAINT [PK_ACCOUNTS_CRED_PERC_DETAILS] PRIMARY KEY CLUSTERED  ([ACC_ID], [DAYS], [PERC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_CRED_PERC_DETAILS] ADD CONSTRAINT [FK_ACCOUNTS_CRED_PERC_DETAILS_ACCOUNTS_CRED_PERC] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS_CRED_PERC] ([ACC_ID]) ON DELETE CASCADE
GO
