CREATE TABLE [dbo].[SO_TASKS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ROW_VERSION] [timestamp] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[REG_DATE] [smalldatetime] NOT NULL CONSTRAINT [DF_SO_ORDER_REG_DATE] DEFAULT (getdate()),
[AGREEMENT_NO] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[RESPONSIBLE_USER_ID] [int] NULL,
[PRODUCT_ID] [int] NOT NULL,
[CLIENT_NO] [int] NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NOT NULL,
[HOLIDAY_SHIFTING] [smallint] NOT NULL,
[PERIOD_TYPE] [int] NOT NULL,
[DAYS_ARRAY] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[RETRY_COUNT_PER_PAY] [int] NOT NULL,
[MAX_FAILURE_COUNT] [int] NOT NULL,
[DEBT_ACTION] [int] NOT NULL,
[SWEEP_IO_AMOUNT] [money] NULL,
[SWEEP_IO_MIN_BALANCE] [money] NULL,
[PRIORITY] [int] NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[FX_RATE_TYPE] [tinyint] NOT NULL,
[STATE] [tinyint] NOT NULL CONSTRAINT [DF_SO_TASKS_STATE] DEFAULT ((10)),
[SUSPENDED_BY_BANK] [bit] NULL,
[ORDER_DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[ORDER_DESCRIP_LAT] [varchar] (150) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_TASKS] ADD CONSTRAINT [PK_SO_ORDER] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_TASKS] ADD CONSTRAINT [FK_SO_TASKS_SO_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[SO_PRODUCTS] ([ID])
GO
