CREATE TABLE [dbo].[OPS_HELPER_2017]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[REC_ID] [int] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[OPS_HELPER_2017] ADD CONSTRAINT [CK_OPS_HELPER_2017] CHECK (([DT]>='20170101' AND [DT]<'20170901'))
GO
ALTER TABLE [dbo].[OPS_HELPER_2017] ADD CONSTRAINT [PK_OPS_HELPER_2017] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT], [REC_ID]) ON [ARCHIVE]
GO
