CREATE TABLE [dbo].[SO_TASK_CREDIT_ACCOUNTS]
(
[TASK_ID] [int] NOT NULL,
[PRIORITY] [int] NOT NULL CONSTRAINT [DF_SO_TASK_CREDIT_ACCOUNTS_PRIORITY] DEFAULT ((0)),
[AMOUNT] [money] NULL,
[ISO] [char] (3) COLLATE Latin1_General_BIN NULL,
[ACC_ID] [int] NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[SAXAZKOD] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[TAX_PAYER_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[TAX_PAYER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ACC] [dbo].[TINTACCOUNT] NULL,
[RECEIVER_ACC_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ADDRESS_LAT] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_CODE] [dbo].[TINTBANKCODE] NULL,
[INTERMED_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO_DESCRIP] [bit] NULL,
[EXTRA_INFO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[DET_OF_CHARG] [char] (3) COLLATE Latin1_General_BIN NULL,
[COR_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NULL,
[COR_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[IS_PERCENT] [bit] NULL,
[EQU_ISO] [char] (3) COLLATE Latin1_General_BIN NULL,
[SENDER_ADDRESS_LAT] [varchar] (105) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_TASK_CREDIT_ACCOUNTS] ADD CONSTRAINT [FK_SO_TASK_CREDIT_ACCOUNTS_SO_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[SO_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
