CREATE TABLE [dbo].[BC_HANDBOOKS]
(
[TABLE_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[MENU_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[MENU_NAME_LAT] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[BC_HANDBOOKS_TRIGGER] ON [dbo].[BC_HANDBOOKS] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_BC_HANDBOOKS'
GO
ALTER TABLE [dbo].[BC_HANDBOOKS] ADD CONSTRAINT [PK_BC_HANDBOOKS] PRIMARY KEY CLUSTERED  ([TABLE_NAME]) ON [PRIMARY]
GO
