CREATE TABLE [dbo].[SAVED_SQL_FILTERS]
(
[CLASS_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[USER_ID] [int] NOT NULL CONSTRAINT [DF_SAVED_SQL_FILTERS_USER_ID] DEFAULT ((0)),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[FILTER_DATA] [text] COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SAVED_SQL_FILTERS] ADD CONSTRAINT [PK_SAVED_SQL_FILTERS] PRIMARY KEY CLUSTERED  ([CLASS_NAME], [USER_ID], [DESCRIP]) ON [PRIMARY]
GO
