CREATE TABLE [dbo].[SWIFT_CHANGES_ARC]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_CHANGES_ARC] ADD CONSTRAINT [PK_SWIFT_CHANGES_ARC] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_CHANGES_ARC] ADD CONSTRAINT [FK_SWIFT_CHANGES_ARC_1] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [dbo].[SWIFT_DOCS_ARC] ([OP_NUM]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SWIFT_CHANGES_ARC] ADD CONSTRAINT [FK_SWIFT_CHANGES_ARC_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
