CREATE TABLE [dbo].[DOC_CHANGES_ARC]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [smalldatetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_CHANGES_ARC] ADD CONSTRAINT [PK_DOC_CHANGES_ARC] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_CHANGES_ARC] WITH NOCHECK ADD CONSTRAINT [FK_DOC_CHANGES_ARC_2] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
