CREATE TABLE [dbo].[LOAN_CLIENT_TYPES]
(
[TYPE_ID] [tinyint] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CLIENT_TYPES] ADD CONSTRAINT [PK_LOAN_CLIENT_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
