CREATE TABLE [dbo].[BC_REPORTS]
(
[TAG] [smallint] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[REPORT_DATA] [image] NULL,
[REPORT_TYPE] [tinyint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[BC_REPORTS_TRIGGER] ON [dbo].[BC_REPORTS] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_BC_REPORTS'


GO
ALTER TABLE [dbo].[BC_REPORTS] ADD CONSTRAINT [PK_BC_REPORTS] PRIMARY KEY CLUSTERED  ([TAG], [DESCRIP]) ON [PRIMARY]
GO
