CREATE TABLE [dbo].[LOAN_OPS]
(
[OP_ID] [int] NOT NULL IDENTITY(1, 1),
[LOAN_ID] [int] NOT NULL,
[OP_DATE] [smalldatetime] NOT NULL,
[OP_TYPE] [smallint] NOT NULL,
[OP_STATE] [tinyint] NOT NULL CONSTRAINT [DF_LOAN_OPS_OP_STATE] DEFAULT ((0)),
[OP_TIME] [datetime] NOT NULL CONSTRAINT [DF_LOAN_OPS_OP_TIME] DEFAULT (getdate()),
[PARENT_OP_ID] [int] NULL,
[AMOUNT] [money] NULL,
[BY_PROCESSING] [bit] NOT NULL CONSTRAINT [DF_LOAN_OPS_BY_PROCESSING] DEFAULT ((0)),
[OP_DATA] [xml] NULL,
[OP_DETAILS] [xml] NULL,
[OP_EXT_XML_1] [xml] NULL,
[OP_EXT_XML_2] [xml] NULL,
[OP_LOAN_DETAILS] [xml] NULL,
[OP_NOTE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OWNER] [int] NOT NULL,
[DOC_REC_ID] [int] NULL,
[NOTE_REC_ID] [int] NULL,
[UPDATE_DATA] [bit] NOT NULL,
[UPDATE_SCHEDULE] [bit] NOT NULL,
[AUTH_OWNER] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OPS] ADD CONSTRAINT [PK_LOAN_OPS] PRIMARY KEY CLUSTERED  ([OP_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_OPS_LOAN_ID] ON [dbo].[LOAN_OPS] ([LOAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_OPS_LOAN_ID_OP_TYPE_OP_DATE] ON [dbo].[LOAN_OPS] ([LOAN_ID], [OP_TYPE], [OP_DATE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_OPS] ADD CONSTRAINT [FK_LOAN_OPS_LOAN_NOTES] FOREIGN KEY ([NOTE_REC_ID]) REFERENCES [dbo].[LOAN_NOTES] ([REC_ID])
GO
ALTER TABLE [dbo].[LOAN_OPS] ADD CONSTRAINT [FK_LOAN_OPS_LOAN_OP_TYPES] FOREIGN KEY ([OP_TYPE]) REFERENCES [dbo].[LOAN_OP_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_OPS] ADD CONSTRAINT [FK_LOAN_OPS_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_OPS] ADD CONSTRAINT [FK_LOAN_OPS_USERS_AUTHORIZE_OWNER] FOREIGN KEY ([AUTH_OWNER]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[LOAN_OPS] ADD CONSTRAINT [FK_LOAN_OPS_USERS_OWNER] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
