CREATE TABLE [dbo].[CORRESPONDENT_BANKS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[BIC] [char] (11) COLLATE Latin1_General_BIN NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[NOSTRO_ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[LORO_ACCOUNT] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORRESPONDENT_BANKS] ADD CONSTRAINT [PK_CORRESPONDENT_BANKS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORRESPONDENT_BANKS] ADD CONSTRAINT [IX_CORRESPONDENT_BANKS] UNIQUE NONCLUSTERED  ([BIC], [ISO]) ON [PRIMARY]
GO
