CREATE TABLE [dbo].[OPS_HELPER_2014]
(
[ACC_ID] [int] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[REC_ID] [int] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[OPS_HELPER_2014] ADD CONSTRAINT [CK_OPS_HELPER_2014] CHECK (([DT]>='20140101' AND [DT]<'20150101'))
GO
ALTER TABLE [dbo].[OPS_HELPER_2014] ADD CONSTRAINT [PK_OPS_HELPER_2014] PRIMARY KEY CLUSTERED  ([ACC_ID], [DT], [REC_ID]) ON [ARCHIVE]
GO
