CREATE TABLE [dbo].[LOAN_ATTRIBUTES]
(
[LOAN_ID] [int] NOT NULL,
[ATTRIB_CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ATTRIB_VALUE] [varchar] (1000) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ATTRIBUTES] ADD CONSTRAINT [PK_LOAN_ATTRIBUTES] PRIMARY KEY CLUSTERED  ([LOAN_ID], [ATTRIB_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_ATTRIBUTES] ADD CONSTRAINT [FK_LOAN_ATTRIBUTES_LOAN_ATTRIB_CODES] FOREIGN KEY ([ATTRIB_CODE]) REFERENCES [dbo].[LOAN_ATTRIB_CODES] ([CODE])
GO
ALTER TABLE [dbo].[LOAN_ATTRIBUTES] ADD CONSTRAINT [FK_LOAN_ATTRIBUTES_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
