CREATE TABLE [dbo].[BC_BANK_MSGS2]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[BC_LOGIN_ID] [int] NULL,
[DT_TM] [smalldatetime] NOT NULL CONSTRAINT [DF_BC_BANK_MSGS2_DT_TM] DEFAULT (getdate()),
[USER_ID] [int] NULL,
[MSG_TEXT] [text] COLLATE Latin1_General_BIN NOT NULL,
[MSG_DATA] [image] NULL,
[FILENAME] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[BC_BANK_MSGS2_TRIGGER] ON [dbo].[BC_BANK_MSGS2]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_BC_BANK_MSGS2'
GO
ALTER TABLE [dbo].[BC_BANK_MSGS2] ADD CONSTRAINT [PK_BC_BANK_MSGS2] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BC_BANK_MSGS2_DT] ON [dbo].[BC_BANK_MSGS2] ([DT_TM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_BANK_MSGS2] WITH NOCHECK ADD CONSTRAINT [FK_BC_BANK_MSGS2_BC_LOGINS] FOREIGN KEY ([BC_LOGIN_ID]) REFERENCES [dbo].[BC_LOGINS] ([BC_LOGIN_ID])
GO
ALTER TABLE [dbo].[BC_BANK_MSGS2] ADD CONSTRAINT [FK_BC_BANK_MSGS2_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE
GO
