CREATE TABLE [dbo].[VAL_RATES_2013]
(
[ISO] [dbo].[TISO] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[VAL_RATES_2013] ADD CONSTRAINT [CK_VAL_RATES_2013] CHECK (([DT]>='20130101' AND [DT]<'20140101'))
GO
ALTER TABLE [dbo].[VAL_RATES_2013] ADD CONSTRAINT [PK_VAL_RATES_2013] PRIMARY KEY CLUSTERED  ([ISO], [DT]) ON [ARCHIVE]
GO
