CREATE TABLE [dbo].[CCENTER_PAGES]
(
[PAGE_ID] [int] NOT NULL IDENTITY(1, 1),
[PAGE_NAME] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[PAGE_NAME_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[SP_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[EXTRA_PARAM_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[EXTRA_PARAM_FIELD] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[FIELD_DEFS] [text] COLLATE Latin1_General_BIN NULL,
[SET_RIGHT_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCENTER_PAGES] ADD CONSTRAINT [PK_CCENTER_PAGES] PRIMARY KEY CLUSTERED  ([PAGE_ID]) ON [PRIMARY]
GO
