CREATE TABLE [dbo].[LOAN_NOTES]
(
[LOAN_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DATE_TIME] [datetime] NOT NULL CONSTRAINT [DF_LOAN_NOTES_DATE_TIME] DEFAULT (getdate()),
[OWNER] [int] NOT NULL,
[OP_TYPE] [smallint] NULL,
[NOTE] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_NOTES] ADD CONSTRAINT [PK_LOAN_NOTES] PRIMARY KEY CLUSTERED  ([LOAN_ID], [REC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_LOAN_NOTES] ON [dbo].[LOAN_NOTES] ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_NOTES] ADD CONSTRAINT [FK_LOAN_NOTES_LOAN_OP_TYPES] FOREIGN KEY ([OP_TYPE]) REFERENCES [dbo].[LOAN_OP_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_NOTES] ADD CONSTRAINT [FK_LOAN_NOTES_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_NOTES] ADD CONSTRAINT [FK_LOAN_NOTES_USERS] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
