CREATE TABLE [dbo].[CCENTER_PAGES_BUTTONS]
(
[PAGE_ID] [int] NOT NULL,
[BUTTON_ID] [int] NOT NULL CONSTRAINT [DF_CCENTER_PAGES_GRIDS_GRID_ID] DEFAULT ((0)),
[BUTTON_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[BUTTON_NAME_LAT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[INFO_TYPE] [int] NOT NULL CONSTRAINT [DF_CCENTER_PAGES_BUTTONS_BUTTON_TYPE] DEFAULT ((0)),
[SP_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[EXTRA_PARAM_NAMES] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[EXTRA_PARAM_FIELDS] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CONFIRMATION_TEXT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[SET_RIGHT_NAME] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCENTER_PAGES_BUTTONS] ADD CONSTRAINT [PK_CCENTER_PAGES_BUTTONS] PRIMARY KEY CLUSTERED  ([PAGE_ID], [BUTTON_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCENTER_PAGES_BUTTONS] ADD CONSTRAINT [FK_CCENTER_PAGES_GRIDS_CCENTER_PAGES] FOREIGN KEY ([PAGE_ID]) REFERENCES [dbo].[CCENTER_PAGES] ([PAGE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
