CREATE TABLE [dbo].[VAL_RATES_0000]
(
[ISO] [dbo].[TISO] NOT NULL,
[DT] [smalldatetime] NOT NULL,
[ITEMS] [int] NOT NULL,
[AMOUNT] [money] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[NBG_RATES_RECALC_TRIGGER] ON [dbo].[VAL_RATES_0000] 
FOR DELETE, UPDATE, INSERT
AS

IF @@ROWCOUNT <> 1 RETURN

SET NOCOUNT ON

DECLARE
  @iso TISO,
  @dt_rate smalldatetime

IF ((SELECT COUNT(*) FROM INSERTED) = 1) AND ((SELECT COUNT(*) FROM DELETED) = 1)
BEGIN
  SELECT @iso = ISO, @dt_rate = DT FROM INSERTED
  IF UPDATE (ISO) OR UPDATE(DT)
    RAISERROR ('UPDATE OF FIELD "ISO" OR "DT" IS NOT ALLOWED',16,1 )
END
ELSE
IF (SELECT COUNT(*) FROM DELETED) = 1
BEGIN
  SELECT @iso = ISO, @dt_rate = DT FROM DELETED
END
ELSE
  SELECT @iso = ISO, @dt_rate = DT FROM INSERTED

DECLARE cc CURSOR LOCAL FORWARD_ONLY SCROLL_LOCKS
FOR
SELECT DOC_DATE, AMOUNT, AMOUNT_EQU
FROM dbo.OPS_0000 (UPDLOCK)
WHERE DOC_DATE >= @dt_rate AND DOC_TYPE >= 0 AND ISO = @iso AND AMOUNT > $0.00
FOR UPDATE OF AMOUNT_EQU

OPEN cc

DECLARE
  @dt smalldatetime,
  @amount TAMOUNT,
  @amount_equ TAMOUNT,
  @amount_equ_old TAMOUNT

FETCH NEXT FROM cc INTO @dt, @amount, @amount_equ_old

WHILE @@FETCH_STATUS = 0
BEGIN
  SET @amount_equ = dbo.get_equ (@amount,@iso,@dt)

  IF @amount_equ_old <> @amount_equ
  BEGIN
    UPDATE dbo.OPS_0000
    SET AMOUNT_EQU = @amount_equ
    WHERE CURRENT OF cc
  END
  
  FETCH NEXT FROM cc INTO @dt, @amount, @amount_equ_old
END

CLOSE cc
DEALLOCATE cc
RETURN
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[VAL_RATES_TRIGGER] ON [dbo].[VAL_RATES_0000]
FOR INSERT, UPDATE, DELETE 
AS
 
EXEC dbo._UPDATE_VERSION 'VER_VAL_RATES'
GO
ALTER TABLE [dbo].[VAL_RATES_0000] ADD CONSTRAINT [CK_VAL_RATES_0000] CHECK (([DT]>='20170901'))
GO
ALTER TABLE [dbo].[VAL_RATES_0000] ADD CONSTRAINT [PK_VAL_RATES_0000] PRIMARY KEY CLUSTERED  ([ISO], [DT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VAL_RATES_0000] ADD CONSTRAINT [FK_VAL_RATES_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
