CREATE TABLE [dbo].[ACCOUNTS_FACSIMILE]
(
[ACC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[FACS_TYPE] [int] NULL,
[IS_AUTHORIZED] [bit] NOT NULL CONSTRAINT [DF_ACCOUNTS_FACSIMILE_IS_AUTHORIZED] DEFAULT ((0)),
[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF_ACCOUNTS_FACSIMILE_IS_ACTIVE] DEFAULT ((1)),
[START_DATE] [smalldatetime] NULL,
[END_DATE] [smalldatetime] NULL,
[BLOB_DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [BLOBS]
GO
ALTER TABLE [dbo].[ACCOUNTS_FACSIMILE] ADD CONSTRAINT [PK_ACCOUNTS_FACSIMILE] PRIMARY KEY CLUSTERED  ([ACC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNTS_FACSIMILE] ADD CONSTRAINT [FK_ACCOUNTS_FACSIMILE_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNTS_FACSIMILE] ADD CONSTRAINT [FK_ACCOUNTS_FACSIMILE_FACSIMILE_TYPES] FOREIGN KEY ([FACS_TYPE]) REFERENCES [dbo].[FACSIMILE_TYPES] ([TYPE_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
