CREATE TABLE [dbo].[CHK_BOOK_CHANGES]
(
[CHK_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_ID] [int] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[DT_TM] [smalldatetime] NOT NULL CONSTRAINT [DF_CHK_BOOK_CHANGES_DT_TM] DEFAULT (getdate()),
[COMMENT] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHK_BOOK_CHANGES] ADD CONSTRAINT [PK_CHK_BOOK_CHANGES] PRIMARY KEY CLUSTERED  ([CHK_ID], [REC_ID]) ON [PRIMARY]
GO
