CREATE TABLE [dbo].[DOC_NUMBERING]
(
[DOC_NUM_TYPE] [tinyint] NOT NULL,
[LAST_USED_NUM] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_NUMBERING] ADD CONSTRAINT [PK_DOC_NUMBERING] PRIMARY KEY CLUSTERED  ([DOC_NUM_TYPE]) ON [PRIMARY]
GO
