CREATE TABLE [dbo].[DOC_DETAILS_ARC_VALPLAT]
(
[DOC_REC_ID] [int] NOT NULL,
[SENDER_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[SENDER_ACC] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_ACC] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[SENDER_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[SENDER_ACC_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ACC_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SENDER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[RECEIVER_TAX_CODE] [varchar] (11) COLLATE Latin1_General_BIN NULL,
[REF_NUM] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[COR_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NULL,
[COR_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[SWIFT_TEXT] [text] COLLATE Latin1_General_BIN NULL,
[DET_OF_CHARG] [char] (3) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO_DESCRIP] [bit] NULL,
[SENDER_ADDRESS_LAT] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ADDRESS_LAT] [varchar] (105) COLLATE Latin1_General_BIN NULL
) ON [ARCHIVE] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOC_DETAILS_ARC_VALPLAT] ADD CONSTRAINT [PK_DOC_DETAILS_ARC_VALPLAT] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [ARCHIVE]
GO
