CREATE TABLE [dbo].[LOAN_DISBURSE_TYPES]
(
[TYPE_ID] [int] NOT NULL,
[CODE] [varchar] (15) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DISBURSE_TYPES] ADD CONSTRAINT [PK_LOAN_DISBURSE_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
