CREATE TABLE [dbo].[LOAN_CREDIT_LINES]
(
[CREDIT_LINE_ID] [int] NOT NULL IDENTITY(1, 1),
[ROW_VERSION] [int] NOT NULL,
[BRANCH_NO] [int] NOT NULL,
[DEPT_NO] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL,
[AGREEMENT_NO] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[STATE] [tinyint] NOT NULL,
[REG_DATE] [smalldatetime] NOT NULL,
[RESPONSIBLE_USER_ID] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [money] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[PERIOD] [int] NOT NULL,
[END_DATE] AS (dateadd(year,[PERIOD],[START_DATE])),
[ENSURE_TYPE] [int] NOT NULL CONSTRAINT [DF_LOAN_CREDIT_LINES_ENSURE_TYPE] DEFAULT ((1)),
[RESTRUCTURED] [int] NOT NULL CONSTRAINT [DF_LOAN_CREDIT_LINES_RESTRUCTURED] DEFAULT ((0)),
[MAIN_COLLATERAL_LIST] [varchar] (1000) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [PK_LOAN_CREDIT_LINES] PRIMARY KEY CLUSTERED  ([CREDIT_LINE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [FK_LOAN_CREDIT_LINES_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [FK_LOAN_CREDIT_LINES_DEPTS] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [FK_LOAN_CREDIT_LINES_DEPTS_BRANCH] FOREIGN KEY ([BRANCH_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [FK_LOAN_CREDIT_LINES_LOAN_CREDIT_LINE_STATES] FOREIGN KEY ([STATE]) REFERENCES [dbo].[LOAN_CREDIT_LINE_STATES] ([STATE])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [FK_LOAN_CREDIT_LINES_USERS] FOREIGN KEY ([RESPONSIBLE_USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
ALTER TABLE [dbo].[LOAN_CREDIT_LINES] ADD CONSTRAINT [FK_LOAN_CREDIT_LINES_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
