CREATE TABLE [dbo].[LOAN_PRODUCT_PROPERTIES]
(
[PRODUCT_ID] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[MIN_DAYS] [int] NOT NULL,
[MAX_DAYS] [int] NOT NULL,
[MIN_AMOUNT] [money] NOT NULL,
[MAX_AMOUNT] [money] NOT NULL,
[MIN_INTRATE] [dbo].[TPERCENT] NOT NULL,
[MAX_INTRATE] [dbo].[TPERCENT] NOT NULL,
[PENALTY_INTRATE] [dbo].[TPERCENT] NOT NULL,
[NOTUSED_INTRATE] [dbo].[TPERCENT] NOT NULL,
[ADMIN_INTRATE] [dbo].[TPERCENT] NOT NULL,
[PENALTY_INTRATE_TO] [dbo].[TPERCENT] NOT NULL,
[NOTUSED_INTRATE_TO] [dbo].[TPERCENT] NOT NULL,
[ADMIN_INTRATE_TO] [dbo].[TPERCENT] NOT NULL,
[ADMIN_MIN_AMOUNT] [money] NOT NULL,
[INSURANCE_INTRATE_FROM] [dbo].[TPERCENT] NOT NULL CONSTRAINT [DF_LOAN_PRODUCT_INSURANCE_INTRATE_FROM] DEFAULT ((0)),
[INSURANCE_INTRATE_TO] [dbo].[TPERCENT] NOT NULL CONSTRAINT [DF_LOAN_PRODUCT_INSURANCE_INTRATE_TO] DEFAULT ((0)),
[SERVICE_FEE_RATE_FROM] [dbo].[TPERCENT] NOT NULL CONSTRAINT [DF_LOAN_PRODUCT_PROPERTIES_SERVICE_FEE_RATE_FROM] DEFAULT ((0)),
[SERVICE_FEE_RATE_TO] [dbo].[TPERCENT] NOT NULL CONSTRAINT [DF_LOAN_PRODUCT_PROPERTIES_SERVICE_FEE_RATE_TO] DEFAULT ((0)),
[SERVICE_FEE_MIN] [money] NOT NULL CONSTRAINT [SERVICE_FEE_MIN] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_PROPERTIES] ADD CONSTRAINT [CK_LOAN_PRODUCT_PROPERTIES_AMOUNTS] CHECK (([MIN_AMOUNT]<=[MAX_AMOUNT]))
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_PROPERTIES] ADD CONSTRAINT [CK_LOAN_PRODUCT_PROPERTIES_DAYS] CHECK (([MIN_DAYS]<=[MAX_DAYS]))
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_PROPERTIES] ADD CONSTRAINT [CK_LOAN_PRODUCT_PROPERTIES_INTRATE] CHECK (([MIN_INTRATE]<=[MAX_INTRATE] AND [PENALTY_INTRATE]<=[PENALTY_INTRATE_TO] AND [NOTUSED_INTRATE]<=[NOTUSED_INTRATE_TO] AND [ADMIN_INTRATE]<=[ADMIN_INTRATE_TO]))
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_PROPERTIES] ADD CONSTRAINT [PK_LOAN_PRODUCT_PROPERTIES] PRIMARY KEY CLUSTERED  ([PRODUCT_ID], [ISO], [MIN_DAYS], [MIN_AMOUNT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_PROPERTIES] ADD CONSTRAINT [FK_LOAN_PRODUCT_PROPERTIES_LOAN_PRODUCTS] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([PRODUCT_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_PRODUCT_PROPERTIES] ADD CONSTRAINT [FK_LOAN_PRODUCT_PROPERTIES_VAL_CODES] FOREIGN KEY ([ISO]) REFERENCES [dbo].[VAL_CODES] ([ISO])
GO
