CREATE TABLE [dbo].[BC_MSGS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[DOC_DATE] [smalldatetime] NOT NULL,
[DESCRIP] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[TEXT] [text] COLLATE Latin1_General_BIN NULL,
[DATA] [image] NULL,
[BC_LOGIN_ID] [int] NULL,
[REC_STATE] [tinyint] NOT NULL,
[MSG_TYPE] [int] NOT NULL CONSTRAINT [DF_BC_MSGS_MSG_TYPE] DEFAULT ((0)),
[FILENAME] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_MSGS] ADD CONSTRAINT [PK_BC_MSGS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BC_MSGS_LOGIN_ID] ON [dbo].[BC_MSGS] ([BC_LOGIN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BC_MSGS_DT] ON [dbo].[BC_MSGS] ([DOC_DATE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BC_MSGS] WITH NOCHECK ADD CONSTRAINT [FK_BC_MSGS_BC_LOGINS] FOREIGN KEY ([BC_LOGIN_ID]) REFERENCES [dbo].[BC_LOGINS] ([BC_LOGIN_ID])
GO
