CREATE TABLE [dbo].[BC_SETTINGS]
(
[BRANCH_ID] [int] NOT NULL,
[BC_SERVER1_IP] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[BC_SERVER1_PORT] [int] NULL,
[BC_SERVER2_IP] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[BC_SERVER2_PORT] [int] NULL,
[BC_SERVER3_IP] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[BC_SERVER3_PORT] [int] NULL,
[BCBR_SERVER1_IP] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[BCBR_SERVER1_PORT] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[BCBR_SERVER2_IP] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[BCBR_SERVER2_PORT] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[BC_SERVER_START_HM] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[BC_SERVER_END_HM] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[BC_SERVER_PHONES] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[BC_INFO_PHONES] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[BC_HTML] [image] NULL,
[BC_FEATURES_FLAGS] [int] NOT NULL CONSTRAINT [DF_BC_SETTINGS_BC_FEATURES_FLAGS] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[BC_SETTINGS_TRIGGER] ON [dbo].[BC_SETTINGS] 
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_BC_SETTINGS'
GO
ALTER TABLE [dbo].[BC_SETTINGS] ADD CONSTRAINT [PK_BC_SETTINGS] PRIMARY KEY CLUSTERED  ([BRANCH_ID]) ON [PRIMARY]
GO
