CREATE TABLE [dbo].[ACC_ATTRIBUTES]
(
[ACC_ID] [int] NOT NULL,
[ATTRIB_CODE] [varchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[ATTRIB_VALUE] [varchar] (1000) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ATTRIBUTES] ADD CONSTRAINT [PK_ACC_ATTRIBUTES] PRIMARY KEY CLUSTERED  ([ACC_ID], [ATTRIB_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ATTRIBUTES] ADD CONSTRAINT [FK_ACC_ATTRIBUTES_ACC_ATTRIB_CODES] FOREIGN KEY ([ATTRIB_CODE]) REFERENCES [dbo].[ACC_ATTRIB_CODES] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ACC_ATTRIBUTES] ADD CONSTRAINT [FK_ACC_ATTRIBUTES_ACCS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
