CREATE TABLE [dbo].[LOAN_INI]
(
[IDS] [char] (20) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_INI] ADD CONSTRAINT [PK_LOAN_INI] PRIMARY KEY CLUSTERED  ([IDS]) ON [PRIMARY]
GO
