CREATE TABLE [dbo].[LOAN_PRODUCTS]
(
[PRODUCT_ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [dbo].[TCODE] NOT NULL,
[CODE3] [int] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL,
[DESCRIP_LAT] [dbo].[TDESCRIP] NULL,
[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_IS_ACTIVE] DEFAULT ((1)),
[AGR_NO_TEMPLATE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AUTHORIZE_LEVEL] [tinyint] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_AUTHORIZE_LEVEL] DEFAULT ((20)),
[CLIENT_TYPES] [int] NOT NULL,
[CLIENT_SUBTYPES] [int] NULL,
[CLIENT_PROPERTIES] [int] NOT NULL,
[SCHEDULE_TYPES] [int] NOT NULL,
[INSTALLMENT] [bit] NOT NULL,
[EVENT_INSTALLMENT] [bit] NULL,
[CREDIT_LINE] [bit] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_CREDIT_LINE] DEFAULT ((0)),
[LOAN_TYPE_ID] [int] NOT NULL,
[DISBURSE_TYPE] [int] NOT NULL,
[ENSURE_TYPE] [tinyint] NOT NULL,
[RISK_TYPE] [int] NOT NULL,
[AUTO_RISK_MANAGEMENT] [bit] NOT NULL,
[RESERVE_MAX_CATEGORY] [bit] NOT NULL,
[GRACE_DAYS] [int] NOT NULL,
[PREPAYMENT_STEP] [tinyint] NULL,
[PREPAYMENT_INTRATE] [dbo].[TPERCENT] NOT NULL,
[PREPAYMENT_INTRATE_TO] [dbo].[TPERCENT] NOT NULL,
[INTEREST_FLAGS] [int] NOT NULL,
[PENALTY_FLAGS] [int] NOT NULL,
[PERCENT_INCOME_FLAGS] [int] NOT NULL,
[PREPAYMENT_FLAGS] [int] NOT NULL,
[ROUND_NAT_TYPE] [tinyint] NOT NULL,
[ROUND_FOREIGN_TYPE] [tinyint] NOT NULL,
[PAYM_INTERVALS] [tinyint] NOT NULL,
[BASIS] [int] NOT NULL,
[LOAN_PURPOSE_TYPE] [varchar] (1000) COLLATE Latin1_General_BIN NULL,
[BAL_ACC_SUB] [tinyint] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_BAL_ACC_SUB] DEFAULT ((0)),
[INDEXABLE] [tinyint] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_INDEXABLE] DEFAULT ((3)),
[INSURE_LOAN] [tinyint] NOT NULL CONSTRAINT [DF__LOAN_PROD__INSUR__465455A7] DEFAULT ((3)),
[GUARANTEE] [bit] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_GUARANTEE] DEFAULT ((0)),
[INTERNAT_GUARANTEE] [bit] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_INTERNAT_GUARANTEE] DEFAULT ((0)),
[USE_KAS_AMOUNT] [bit] NOT NULL CONSTRAINT [DF_LOAN_PRODUCTS_USE_KAS_AMOUNT] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [CK_LOAN_PRODUCTS_AUTHORIZE_LEVEL] CHECK (([AUTHORIZE_LEVEL]=(20) OR [AUTHORIZE_LEVEL]=(10) OR [AUTHORIZE_LEVEL]=(0)))
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [CK_LOAN_PRODUCTS_BAL_ACC_SUB] CHECK (([BAL_ACC_SUB]>=(0) AND [BAL_ACC_SUB]<=(99)))
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [CK_LOAN_PRODUCTS_INSTALLMENT] CHECK (([INSTALLMENT]=(0) AND [EVENT_INSTALLMENT] IS NULL OR [INSTALLMENT]=(1) AND [EVENT_INSTALLMENT] IS NOT NULL))
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [CK_LOAN_PRODUCTS_PREPAYMENT_INTRATE] CHECK (([PREPAYMENT_INTRATE]<=[PREPAYMENT_INTRATE_TO]))
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [CK_LOAN_PRODUCTS_ROUND_FOREIGN_TYPE] CHECK (([ROUND_FOREIGN_TYPE]=(3) OR [ROUND_FOREIGN_TYPE]=(2) OR [ROUND_FOREIGN_TYPE]=(1) OR [ROUND_FOREIGN_TYPE]=(0)))
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [CK_LOAN_PRODUCTS_ROUND_NAT_TYPE] CHECK (([ROUND_NAT_TYPE]=(3) OR [ROUND_NAT_TYPE]=(2) OR [ROUND_NAT_TYPE]=(1) OR [ROUND_NAT_TYPE]=(0)))
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [PK_LOAN_PRODUCTS] PRIMARY KEY CLUSTERED  ([PRODUCT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [FK_LOAN_PRODUCTS_LOAN_RISK_TYPES] FOREIGN KEY ([RISK_TYPE]) REFERENCES [dbo].[LOAN_RISK_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[LOAN_PRODUCTS] ADD CONSTRAINT [FK_LOAN_PRODUCTS_LOAN_TYPES] FOREIGN KEY ([LOAN_TYPE_ID]) REFERENCES [dbo].[LOAN_TYPES] ([TYPE_ID]) ON UPDATE CASCADE
GO
