CREATE TABLE [dbo].[DEPO_PROD_RANGE_AMOUNTS]
(
[PROD_ID] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[MIN_AMOUNT] [money] NOT NULL,
[MAX_AMOUNT] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PROD_RANGE_AMOUNTS] ADD CONSTRAINT [PK_DEPO_PROD_RANGE_AMOUNTS] PRIMARY KEY CLUSTERED  ([PROD_ID], [ISO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_PROD_RANGE_AMOUNTS] ADD CONSTRAINT [FK_DEPO_PROD_RANGE_AMOUNTS_DEPO_PRODUCTS] FOREIGN KEY ([PROD_ID]) REFERENCES [dbo].[DEPO_PRODUCTS] ([PROD_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
