CREATE TABLE [dbo].[DEPO_OP_TYPES]
(
[TYPE_ID] [smallint] NOT NULL,
[GROUP_ID] [smallint] NOT NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[CONST_FUNCTION] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[SELF_EXEC] [bit] NOT NULL,
[ADD_WITH_ACCOUNTING] [bit] NOT NULL,
[ADD_DOC_REC_STATE] [tinyint] NOT NULL,
[ADD_DOC_REC_STATE_CASH] [tinyint] NOT NULL,
[EXEC_DOC_REC_STATE] [tinyint] NOT NULL,
[EXEC_DOC_REC_STATE_CASH] [tinyint] NOT NULL,
[DOC_REC_STATE] [tinyint] NOT NULL,
[DOC_REC_STATE_CASH] [tinyint] NOT NULL,
[ACCRUE_BEFORE_ADD] [bit] NOT NULL,
[ACCRUE_BEFORE_EXEC] [bit] NOT NULL,
[REALIZE_BEFORE_ADD] [bit] NOT NULL,
[REALIZE_BEFORE_EXEC] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_OP_TYPES] ADD CONSTRAINT [PK_DEPO_OP_TYPES] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
