CREATE TABLE [dbo].[RESERVED_ACCOUNTS]
(
[ACCOUNT] [dbo].[TACCOUNT] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[USER_ID] [int] NOT NULL,
[DT_TM] [smalldatetime] NOT NULL CONSTRAINT [DF_RESERVED_ACCOUNTS_DT_TM] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVED_ACCOUNTS] ADD CONSTRAINT [PK_RESERVED_ACCOUNTS] PRIMARY KEY CLUSTERED  ([ACCOUNT], [ISO]) ON [PRIMARY]
GO
