CREATE TABLE [dbo].[INI_INT]
(
[IDS] [char] (20) COLLATE Latin1_General_BIN NOT NULL,
[VALS] [decimal] (18, 0) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INI_INT] ADD CONSTRAINT [PK_INI_INT] PRIMARY KEY CLUSTERED  ([IDS]) ON [PRIMARY]
GO
