CREATE TABLE [dbo].[DOC_DETAILS_ARC_PASSPORTS]
(
[DOC_REC_ID] [int] NOT NULL,
[FIRST_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[LAST_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[FATHERS_NAME] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[BIRTH_DATE] [smalldatetime] NULL,
[BIRTH_PLACE] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ADDRESS_JUR] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[ADDRESS_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[COUNTRY] [char] (2) COLLATE Latin1_General_BIN NULL,
[PASSPORT_TYPE_ID] [tinyint] NOT NULL,
[PASSPORT] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PERSONAL_ID] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[REG_ORGAN] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PASSPORT_ISSUE_DT] [smalldatetime] NULL,
[PASSPORT_END_DATE] [smalldatetime] NULL
) ON [ARCHIVE]
GO
ALTER TABLE [dbo].[DOC_DETAILS_ARC_PASSPORTS] ADD CONSTRAINT [PK_DOC_DETAILS_ARC_PASSPORTS] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [ARCHIVE]
GO
