CREATE TABLE [dbo].[SWIFT_STATEMENT_DETAILS]
(
[SW_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[DOC_TYPE] [smallint] NULL,
[DT] [smalldatetime] NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NULL,
[ACC_ID] [int] NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[DOC_NUM] [int] NULL,
[OP_CODE] [dbo].[TOPCODE] NULL,
[REC_STATE] [tinyint] NULL,
[PARENT_REC_ID] [int] NULL,
[ACCOUNT_EXTRA] [dbo].[TACCOUNT] NULL,
[DOC_DATE_IN_DOC] [smalldatetime] NULL,
[IS_ARC] [bit] NULL,
[DBO] [money] NULL,
[CRO] [money] NULL,
[SALDO] [money] NULL,
[SORT_ID] [money] NULL,
[SW_CODE] [char] (3) COLLATE Latin1_General_BIN NULL,
[SW_CODE_DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SWIFT_STATEMENT_DETAILS] ADD CONSTRAINT [FK_SWIFT_STATEMENT_DETAILS_SWIFT_STATEMENTS_LIST] FOREIGN KEY ([SW_REC_ID]) REFERENCES [dbo].[SWIFT_STATEMENTS_LIST] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
