CREATE TABLE [dbo].[DEPO_TYPES]
(
[DEPO_TYPE_ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[DESCRIP_LAT] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPO_TYPES] ADD CONSTRAINT [PK_DX_DEPOSIT_TYPES] PRIMARY KEY CLUSTERED  ([DEPO_TYPE_ID]) ON [PRIMARY]
GO
