CREATE TABLE [dbo].[LOAN_PURPOSE_MONITORING]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[LOAN_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[MONITORING_DATE] [smalldatetime] NOT NULL,
[MONITORING_PROGRESS] [tinyint] NOT NULL,
[MONITORING_SUBJECT] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL,
[MONITORING_MEMO] [varchar] (max) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PURPOSE_MONITORING] ADD CONSTRAINT [PK_LOAN_PURPOSE_MONITORING] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOAN_PURPOSE_MONITORING] ON [dbo].[LOAN_PURPOSE_MONITORING] ([LOAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_PURPOSE_MONITORING] ADD CONSTRAINT [FK_LOAN_PURPOSE_MONITORING_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LOAN_PURPOSE_MONITORING] ADD CONSTRAINT [FK_LOAN_PURPOSE_MONITORING_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
