CREATE TABLE [dbo].[LICENSES]
(
[DEPT_NO] [int] NOT NULL,
[PROD_NAME] [varchar] (16) COLLATE Latin1_General_BIN NOT NULL,
[ISSUE_DT] [smalldatetime] NOT NULL,
[LICENSE] [char] (32) COLLATE Latin1_General_BIN NULL,
[LIC_EXP_DATE] [smalldatetime] NULL,
[LIC_COUNT] [int] NOT NULL,
[MAX_VERSION] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE TRIGGER [dbo].[LICENSES_TRIGGER] ON [dbo].[LICENSES]
FOR INSERT, UPDATE, DELETE 
AS
EXEC _UPDATE_VERSION 'VER_LICENSES'

GO
ALTER TABLE [dbo].[LICENSES] ADD CONSTRAINT [PK_LICENSES] PRIMARY KEY CLUSTERED  ([DEPT_NO], [PROD_NAME], [ISSUE_DT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LICENSES] ADD CONSTRAINT [FK_LICENSES_DEPTS] FOREIGN KEY ([DEPT_NO]) REFERENCES [dbo].[DEPTS] ([DEPT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
