CREATE TABLE [dbo].[SO_SCHEDULE_ANULL_CHANGES]
(
[TASK_ID] [int] NOT NULL,
[DATE] [smalldatetime] NOT NULL,
[VERSION] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[FIELD] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[OLD_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[NEW_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[OLD_DISPLAY_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[NEW_DISPLAY_VALUE] [varchar] (4000) COLLATE Latin1_General_BIN NULL,
[TIME_OF_CHANGE] [datetime] NULL CONSTRAINT [DF_SO_SCHEDULE_ANULL_CHANGES_TIME_OF_CHANGE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SCHEDULE_ANULL_CHANGES] ADD CONSTRAINT [PK_SO_SCHEDULE_ANULL_CHANGES_1] PRIMARY KEY CLUSTERED  ([TASK_ID], [DATE], [VERSION]) ON [PRIMARY]
GO
