CREATE TABLE [dbo].[LOAN_DOC_OPCODES]
(
[OP_CODE] [dbo].[TOPCODE] NOT NULL,
[DESCRIP] [dbo].[TDESCRIP] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_DOC_OPCODES] ADD CONSTRAINT [PK_LOAN_DOC_OPCODES] PRIMARY KEY CLUSTERED  ([OP_CODE]) ON [PRIMARY]
GO
