CREATE TABLE [dbo].[CLIENT_ATTACHMENTS]
(
[CLIENT_NO] [int] NOT NULL,
[FILE_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[IS_FOLDER] [bit] NOT NULL CONSTRAINT [DF_CLIENT_ATTACHMENTS_IS_FOLDER] DEFAULT ((0)),
[FILE_DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [BLOBS]
GO
ALTER TABLE [dbo].[CLIENT_ATTACHMENTS] ADD CONSTRAINT [PK_CLIENT_ATTACHMENTS] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [FILE_NAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENT_ATTACHMENTS] ADD CONSTRAINT [FK_CLIENT_ATTACHMENTS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
GO
