CREATE TABLE [easy].[LOANS_riskinfo_20160801]
(
[LOAN_ID] [int] NOT NULL IDENTITY(1, 1),
[RISK_TYPE] [int] NOT NULL,
[RESERVE_MAX_CATEGORY] [bit] NOT NULL,
[RISK_PERC_RATE_1] [money] NOT NULL,
[RISK_PERC_RATE_2] [money] NOT NULL,
[RISK_PERC_RATE_3] [money] NOT NULL,
[RISK_PERC_RATE_4] [money] NOT NULL,
[RISK_PERC_RATE_5] [money] NOT NULL
) ON [PRIMARY]
GO
