CREATE TABLE [export].[LOAN_STATE]
(
[LOAN_ID] [int] NOT NULL,
[SEND_STATE] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [export].[LOAN_STATE] ADD CONSTRAINT [PK_LOAN_STATE] PRIMARY KEY CLUSTERED  ([LOAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [export].[LOAN_STATE] ADD CONSTRAINT [FK_LOAN_STATE_LOANS] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([LOAN_ID]) ON DELETE CASCADE
GO
