CREATE TABLE [impexp].[PORTIONS_OUT_SWIFT_ARC]
(
[PORTION_DATE] [smalldatetime] NOT NULL,
[PORTION] [int] NOT NULL,
[STATE] [int] NOT NULL,
[AMOUNT] [money] NOT NULL,
[COUNT] [int] NOT NULL,
[CREATION_TIME] [smalldatetime] NULL,
[CLOSE_TIME] [smalldatetime] NULL,
[EXPORT_TIME] [smalldatetime] NULL,
[FINISH_TIME] [smalldatetime] NULL,
[DOC_REC_ID] [int] NULL,
[PROCESSED_AMOUNT] [money] NOT NULL,
[PROCESSED_COUNT] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[PORTIONS_OUT_SWIFT_ARC] ADD CONSTRAINT [PK_PORTIONS_OUT_SWIFT_ARC] PRIMARY KEY CLUSTERED  ([PORTION_DATE], [PORTION]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[PORTIONS_OUT_SWIFT_ARC] ADD CONSTRAINT [FK_PORTIONS_OUT_SWIFT_ARC_PORTION_STATES] FOREIGN KEY ([STATE]) REFERENCES [impexp].[PORTION_STATES] ([STATE]) ON UPDATE CASCADE
GO
