CREATE TABLE [impexp].[DOCS_OUT_SWIFT_ARC]
(
[DOC_REC_ID] [int] NOT NULL,
[UID] [int] NOT NULL,
[DOC_DATE] [smalldatetime] NOT NULL,
[PORTION_DATE] [smalldatetime] NOT NULL,
[PORTION] [int] NOT NULL,
[OLD_FLAGS] [int] NOT NULL,
[ISO] [dbo].[TISO] NOT NULL,
[AMOUNT] [money] NOT NULL,
[AMOUNT_EQU] [money] NOT NULL,
[DOC_CREDIT_ID] [int] NOT NULL,
[REF_NUM] [varchar] (32) COLLATE Latin1_General_BIN NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[SENDER_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[SENDER_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[SENDER_ACC] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[SENDER_ACC_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[SENDER_ADDRESS_LAT] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ACC] [varchar] (37) COLLATE Latin1_General_BIN NOT NULL,
[RECEIVER_ACC_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_CODE] [varchar] (37) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_NAME] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_CODE2] [varchar] (37) COLLATE Latin1_General_BIN NULL,
[INTERMED_BANK_NAME2] [varchar] (105) COLLATE Latin1_General_BIN NULL,
[CORRESPONDENT_BANK_ID] [int] NULL,
[EXTRA_INFO] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO_DESCRIP] [bit] NULL,
[DET_OF_CHARG] [char] (3) COLLATE Latin1_General_BIN NULL,
[CLOSE_TIME] [smalldatetime] NULL,
[EXPORT_TIME] [smalldatetime] NULL,
[FINISH_TIME] [smalldatetime] NULL,
[FINALYZE_DATE] [smalldatetime] NULL,
[FINALYZE_BANK_ID] [int] NULL,
[FINALYZE_ACC_ID] [int] NULL,
[FINALYZE_AMOUNT] [money] NULL,
[FINALYZE_ISO] [dbo].[TISO] NULL,
[FINALYZE_DOC_REC_ID] [int] NULL,
[SWIFT_TEXT] [text] COLLATE Latin1_General_BIN NULL,
[SWIFT_FILENAME] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[STATE] [int] NOT NULL,
[SWIFT_FLAGS_1] [int] NOT NULL,
[SWIFT_FLAGS_2] [int] NOT NULL,
[OP_CODE] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[RECEIVER_ADDRESS_LAT] [varchar] (105) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC] ADD CONSTRAINT [PK_DOCS_OUT_SWIFT_ARC] PRIMARY KEY CLUSTERED  ([DOC_REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC] ADD CONSTRAINT [FK_DOCS_OUT_SWIFT_ARC_CORRESPONDENT_BANKS] FOREIGN KEY ([CORRESPONDENT_BANK_ID]) REFERENCES [dbo].[CORRESPONDENT_BANKS] ([REC_ID])
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC] ADD CONSTRAINT [FK_DOCS_OUT_SWIFT_ARC_CORRESPONDENT_BANKS_FINALYZE_BANK] FOREIGN KEY ([FINALYZE_BANK_ID]) REFERENCES [dbo].[CORRESPONDENT_BANKS] ([REC_ID])
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC] ADD CONSTRAINT [FK_DOCS_OUT_SWIFT_ARC_PORTIONS_OUT_SWIFT_ARC] FOREIGN KEY ([PORTION_DATE], [PORTION]) REFERENCES [impexp].[PORTIONS_OUT_SWIFT_ARC] ([PORTION_DATE], [PORTION])
GO
