CREATE TABLE [impexp].[STATEMENT_CODE_DESCRIPS]
(
[CODE_DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_CODE_DESCRIPS] ADD CONSTRAINT [PK_STATEMENT_CODE_DESCRIPS] PRIMARY KEY CLUSTERED  ([CODE_DESCRIP]) ON [PRIMARY]
GO
