CREATE TABLE [impexp].[SWIFT_MSG_COUNT]
(
[DOC_DATE] [smalldatetime] NOT NULL,
[MSG_TYPE] [varchar] (10) COLLATE Latin1_General_BIN NOT NULL,
[MSG_COUNT] [int] NOT NULL CONSTRAINT [DF_SWIFT_MSG_COUNT_MSG_COUNT] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[SWIFT_MSG_COUNT] ADD CONSTRAINT [PK_SWIFT_MSG_COUNT] PRIMARY KEY CLUSTERED  ([DOC_DATE], [MSG_TYPE]) ON [PRIMARY]
GO
