CREATE TABLE [impexp].[DOCS_OUT_SWIFT_ARC_CHANGES]
(
[DOC_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[DATE_TIME] [datetime] NOT NULL CONSTRAINT [DF_DOCS_OUT_SWIFT_ARC_CHANGES_DATE_TIME] DEFAULT (getdate()),
[CHANGE_TYPE] [int] NOT NULL,
[DESCRIP] [varchar] (255) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC_CHANGES] ADD CONSTRAINT [PK_DOCS_OUT_SWIFT_ARC_CHANGES] PRIMARY KEY CLUSTERED  ([DOC_REC_ID], [REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC_CHANGES] ADD CONSTRAINT [FK_DOCS_OUT_SWIFT_ARC_CHANGES_DOCS_OUT_SWIFT_ARC] FOREIGN KEY ([DOC_REC_ID]) REFERENCES [impexp].[DOCS_OUT_SWIFT_ARC] ([DOC_REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [impexp].[DOCS_OUT_SWIFT_ARC_CHANGES] ADD CONSTRAINT [FK_DOCS_OUT_SWIFT_ARC_CHANGES_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
