CREATE TABLE [impexp].[STATEMENT_SWIFTS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[STATEMENT_ID] [int] NOT NULL,
[RECEIVER_INSTITUTION] [dbo].[TINTBANKCODE] NOT NULL,
[STATEMENT_NO] [int] NOT NULL,
[REF_NUM] [varchar] (32) COLLATE Latin1_General_BIN NOT NULL,
[SWIFT_FILE_NAME] [varchar] (128) COLLATE Latin1_General_BIN NOT NULL,
[OWNER] [int] NOT NULL,
[SWIFT_TEXT] [text] COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_SWIFTS] ADD CONSTRAINT [PK_STATEMENT_SWIFTS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_SWIFTS] ADD CONSTRAINT [IX_STATEMENT_SWIFTS] UNIQUE NONCLUSTERED  ([STATEMENT_ID], [RECEIVER_INSTITUTION]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_SWIFTS] ADD CONSTRAINT [FK_STATEMENT_SWIFTS_STATEMENTS] FOREIGN KEY ([STATEMENT_ID]) REFERENCES [impexp].[STATEMENTS] ([REC_ID])
GO
ALTER TABLE [impexp].[STATEMENT_SWIFTS] ADD CONSTRAINT [FK_STATEMENT_SWIFTS_USERS] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[USERS] ([USER_ID])
GO
