CREATE TABLE [impexp].[STATEMENT_CODES]
(
[CODE] [char] (3) COLLATE Latin1_General_BIN NOT NULL,
[CODE_DESCRIP] [varchar] (250) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_CODES] ADD CONSTRAINT [PK_STATEMENT_CODES] PRIMARY KEY CLUSTERED  ([CODE]) ON [PRIMARY]
GO
