CREATE TABLE [impexp].[PORTION_STATES]
(
[STATE] [int] NOT NULL,
[NAME_GEO] [nvarchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[NAME_LAT] [nvarchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[PORTION_STATES] ADD CONSTRAINT [PK_PORTION_STATES] PRIMARY KEY CLUSTERED  ([STATE]) ON [PRIMARY]
GO
