CREATE TABLE [impexp].[STATEMENT_CLIENTS]
(
[CLIENT_NO] [int] NOT NULL,
[CLIENT_CODE] [char] (2) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_CLIENTS] ADD CONSTRAINT [PK_STATEMENT_CLIENTS_1] PRIMARY KEY CLUSTERED  ([CLIENT_NO]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_CLIENTS] ADD CONSTRAINT [FK_STATEMENT_CLIENTS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON UPDATE CASCADE
GO
