CREATE TABLE [impexp].[PORTIONS_OUT_SWIFT_INFO]
(
[PORTION] [int] NOT NULL,
[PORTION_ALIAS] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[PORTIONS_OUT_SWIFT_INFO] ADD CONSTRAINT [PK_PORTIONS_OUT_SWIFT_INFO] PRIMARY KEY CLUSTERED  ([PORTION]) ON [PRIMARY]
GO
