CREATE TABLE [impexp].[STATEMENTS]
(
[REC_ID] [int] NOT NULL IDENTITY(1, 1),
[UID] [int] NOT NULL,
[STATE] [int] NOT NULL,
[CLIENT_NO] [int] NOT NULL,
[ACC_ID] [int] NOT NULL,
[CREATE_DT] [smalldatetime] NOT NULL,
[START_DATE] [smalldatetime] NOT NULL,
[END_DATE] [smalldatetime] NOT NULL,
[SWIFT_START_DATE] [smalldatetime] NOT NULL,
[OWNER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENTS] ADD CONSTRAINT [PK_STATEMENTS] PRIMARY KEY CLUSTERED  ([REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENTS] ADD CONSTRAINT [FK_STATEMENTS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) ON DELETE CASCADE
GO
ALTER TABLE [impexp].[STATEMENTS] ADD CONSTRAINT [FK_STATEMENTS_CLIENTS] FOREIGN KEY ([CLIENT_NO]) REFERENCES [dbo].[CLIENTS] ([CLIENT_NO]) ON DELETE CASCADE
GO
ALTER TABLE [impexp].[STATEMENTS] ADD CONSTRAINT [FK_STATEMENTS_USERS] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[USERS] ([USER_ID]) ON DELETE CASCADE
GO
