CREATE TABLE [impexp].[STATEMENT_NUMBERING]
(
[CLIENT_NO] [int] NOT NULL,
[RECEIVER_INSTITUTION] [dbo].[TINTBANKCODE] NOT NULL,
[ACC_ID] [int] NOT NULL,
[STATEMENT_NO] [int] NOT NULL CONSTRAINT [DF_STATEMENT_NUMBERING_STATEMENT_NO] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_NUMBERING] ADD CONSTRAINT [PK_STATEMENT_NUMBERING] PRIMARY KEY CLUSTERED  ([CLIENT_NO], [RECEIVER_INSTITUTION], [ACC_ID]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_NUMBERING] ADD CONSTRAINT [FK_STATEMENT_NUMBERING_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID])
GO
ALTER TABLE [impexp].[STATEMENT_NUMBERING] ADD CONSTRAINT [FK_STATEMENT_NUMBERING_STATEMENT_CLIENTS_INSTITUTIONS] FOREIGN KEY ([CLIENT_NO], [RECEIVER_INSTITUTION]) REFERENCES [impexp].[STATEMENT_CLIENTS_INSTITUTIONS] ([CLIENT_NO], [RECEIVER_INSTITUTION]) ON DELETE CASCADE ON UPDATE CASCADE
GO
