CREATE TABLE [impexp].[STATEMENT_DETAILS]
(
[SW_REC_ID] [int] NOT NULL,
[REC_ID] [int] NOT NULL,
[DOC_TYPE] [smallint] NULL,
[DT] [smalldatetime] NOT NULL,
[ACCOUNT] [dbo].[TACCOUNT] NULL,
[ACC_ID] [int] NULL,
[DESCRIP] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[EXTRA_INFO] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[DOC_NUM] [int] NULL,
[OP_CODE] [dbo].[TOPCODE] NULL,
[REC_STATE] [tinyint] NULL,
[PARENT_REC_ID] [int] NULL,
[ACCOUNT_EXTRA] [dbo].[TACCOUNT] NULL,
[DOC_DATE_IN_DOC] [smalldatetime] NULL,
[IS_ARC] [bit] NULL,
[DBO] [money] NULL,
[DBO_EQU] [money] NULL,
[CRO] [money] NULL,
[CRO_EQU] [money] NULL,
[SALDO] [money] NULL,
[SALDO_EQU] [money] NULL,
[SORT_ID] [money] NULL,
[SW_CODE] [char] (3) COLLATE Latin1_General_BIN NULL,
[SW_CODE_DESCRIP] [varchar] (100) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_STATEMENT_DETAILS] ON [impexp].[STATEMENT_DETAILS] ([DT], [REC_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_STATEMENT_DETAILS_SW_REC_ID] ON [impexp].[STATEMENT_DETAILS] ([SW_REC_ID]) ON [PRIMARY]
GO
ALTER TABLE [impexp].[STATEMENT_DETAILS] ADD CONSTRAINT [FK_STATEMENT_DETAILS_STATEMENT_CODES] FOREIGN KEY ([SW_CODE]) REFERENCES [impexp].[STATEMENT_CODES] ([CODE]) ON UPDATE CASCADE
GO
ALTER TABLE [impexp].[STATEMENT_DETAILS] ADD CONSTRAINT [FK_STATEMENT_DETAILS_STATEMENTS] FOREIGN KEY ([SW_REC_ID]) REFERENCES [impexp].[STATEMENTS] ([REC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
